# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdvanceOption.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdvanceOption(object):
    def setupUi(self, AdvanceOption):
        AdvanceOption.setObjectName("AdvanceOption")
        AdvanceOption.resize(381, 497)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AdvanceOption.sizePolicy().hasHeightForWidth())
        AdvanceOption.setSizePolicy(sizePolicy)
        AdvanceOption.setMinimumSize(QtCore.QSize(230, 480))
        self.gridLayout_7 = QtWidgets.QGridLayout(AdvanceOption)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_Seq_AdvOption = QtWidgets.QGroupBox(AdvanceOption)
        self.groupBox_Seq_AdvOption.setCheckable(True)
        self.groupBox_Seq_AdvOption.setChecked(False)
        self.groupBox_Seq_AdvOption.setObjectName("groupBox_Seq_AdvOption")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_Seq_AdvOption)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_Seq = QtWidgets.QLabel(self.groupBox_Seq_AdvOption)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Seq.sizePolicy().hasHeightForWidth())
        self.label_Seq.setSizePolicy(sizePolicy)
        self.label_Seq.setMinimumSize(QtCore.QSize(0, 25))
        self.label_Seq.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_Seq.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_Seq.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_Seq.setText("")
        self.label_Seq.setObjectName("label_Seq")
        self.gridLayout_8.addWidget(self.label_Seq, 0, 0, 1, 1)
        self.pushButton_SeqEditor = QtWidgets.QPushButton(self.groupBox_Seq_AdvOption)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SeqEditor.sizePolicy().hasHeightForWidth())
        self.pushButton_SeqEditor.setSizePolicy(sizePolicy)
        self.pushButton_SeqEditor.setMinimumSize(QtCore.QSize(110, 0))
        self.pushButton_SeqEditor.setObjectName("pushButton_SeqEditor")
        self.gridLayout_8.addWidget(self.pushButton_SeqEditor, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_Seq_AdvOption, 4, 2, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(AdvanceOption)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget = QtWidgets.QWidget(self.groupBox_4)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.radioButton_BiasON_AdvOption = QtWidgets.QRadioButton(self.widget)
        self.radioButton_BiasON_AdvOption.setChecked(True)
        self.radioButton_BiasON_AdvOption.setObjectName("radioButton_BiasON_AdvOption")
        self.horizontalLayout.addWidget(self.radioButton_BiasON_AdvOption)
        self.radioButton_BiasOFF_AdvOption = QtWidgets.QRadioButton(self.widget)
        self.radioButton_BiasOFF_AdvOption.setObjectName("radioButton_BiasOFF_AdvOption")
        self.horizontalLayout.addWidget(self.radioButton_BiasOFF_AdvOption)
        self.gridLayout_5.addWidget(self.widget, 1, 2, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.groupBox_4)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.radioButton_ZON_AdvOption = QtWidgets.QRadioButton(self.widget_2)
        self.radioButton_ZON_AdvOption.setObjectName("radioButton_ZON_AdvOption")
        self.horizontalLayout_2.addWidget(self.radioButton_ZON_AdvOption)
        self.radioButton_ZOFF_AdvOption = QtWidgets.QRadioButton(self.widget_2)
        self.radioButton_ZOFF_AdvOption.setChecked(True)
        self.radioButton_ZOFF_AdvOption.setObjectName("radioButton_ZOFF_AdvOption")
        self.horizontalLayout_2.addWidget(self.radioButton_ZOFF_AdvOption)
        self.gridLayout_5.addWidget(self.widget_2, 2, 2, 2, 1)
        self.gridLayout_7.addWidget(self.groupBox_4, 1, 2, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(AdvanceOption)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.radioButton_Forward_Dir = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_Forward_Dir.setObjectName("radioButton_Forward_Dir")
        self.gridLayout_3.addWidget(self.radioButton_Forward_Dir, 0, 0, 1, 1)
        self.radioButton_AvgBoth_Dir = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_AvgBoth_Dir.setObjectName("radioButton_AvgBoth_Dir")
        self.gridLayout_3.addWidget(self.radioButton_AvgBoth_Dir, 2, 0, 1, 1)
        self.radioButton_Bacward_Dir = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_Bacward_Dir.setObjectName("radioButton_Bacward_Dir")
        self.gridLayout_3.addWidget(self.radioButton_Bacward_Dir, 1, 0, 1, 1)
        self.radioButton_Both_Dir = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_Both_Dir.setChecked(True)
        self.radioButton_Both_Dir.setObjectName("radioButton_Both_Dir")
        self.gridLayout_3.addWidget(self.radioButton_Both_Dir, 3, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_3, 3, 2, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(AdvanceOption)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.radioButton_FeedbackON = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_FeedbackON.setObjectName("radioButton_FeedbackON")
        self.gridLayout_9.addWidget(self.radioButton_FeedbackON, 0, 0, 1, 1)
        self.radioButton_FeedbackOFF = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_FeedbackOFF.setChecked(True)
        self.radioButton_FeedbackOFF.setObjectName("radioButton_FeedbackOFF")
        self.gridLayout_9.addWidget(self.radioButton_FeedbackOFF, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_5, 0, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(AdvanceOption)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.spinBox_Avg_Measure = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_Avg_Measure.setMinimum(1)
        self.spinBox_Avg_Measure.setMaximum(65535)
        self.spinBox_Avg_Measure.setSingleStep(1)
        self.spinBox_Avg_Measure.setProperty("value", 5000)
        self.spinBox_Avg_Measure.setObjectName("spinBox_Avg_Measure")
        self.gridLayout_2.addWidget(self.spinBox_Avg_Measure, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.checkBox_Ch3_Measure = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Ch3_Measure.sizePolicy().hasHeightForWidth())
        self.checkBox_Ch3_Measure.setSizePolicy(sizePolicy)
        self.checkBox_Ch3_Measure.setChecked(True)
        self.checkBox_Ch3_Measure.setObjectName("checkBox_Ch3_Measure")
        self.gridLayout_2.addWidget(self.checkBox_Ch3_Measure, 3, 0, 1, 2)
        self.radioButton_Z_Measure = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_Z_Measure.setObjectName("radioButton_Z_Measure")
        self.gridLayout_2.addWidget(self.radioButton_Z_Measure, 1, 0, 1, 2)
        self.radioButton_I_Measure = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_I_Measure.setChecked(True)
        self.radioButton_I_Measure.setObjectName("radioButton_I_Measure")
        self.gridLayout_2.addWidget(self.radioButton_I_Measure, 0, 0, 1, 2)
        self.checkBox_Ch2_Measure = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Ch2_Measure.sizePolicy().hasHeightForWidth())
        self.checkBox_Ch2_Measure.setSizePolicy(sizePolicy)
        self.checkBox_Ch2_Measure.setChecked(True)
        self.checkBox_Ch2_Measure.setObjectName("checkBox_Ch2_Measure")
        self.gridLayout_2.addWidget(self.checkBox_Ch2_Measure, 2, 0, 1, 2)
        self.gridLayout_7.addWidget(self.groupBox_2, 3, 0, 1, 1)
        self.groupBox_AutoSave_AdvOption = QtWidgets.QGroupBox(AdvanceOption)
        self.groupBox_AutoSave_AdvOption.setCheckable(True)
        self.groupBox_AutoSave_AdvOption.setObjectName("groupBox_AutoSave_AdvOption")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_AutoSave_AdvOption)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.checkBox_SaveEveryPasses_Autosave = QtWidgets.QCheckBox(self.groupBox_AutoSave_AdvOption)
        self.checkBox_SaveEveryPasses_Autosave.setObjectName("checkBox_SaveEveryPasses_Autosave")
        self.gridLayout_6.addWidget(self.checkBox_SaveEveryPasses_Autosave, 0, 0, 1, 1)
        self.checkBox_AskFileName_Autosave = QtWidgets.QCheckBox(self.groupBox_AutoSave_AdvOption)
        self.checkBox_AskFileName_Autosave.setObjectName("checkBox_AskFileName_Autosave")
        self.gridLayout_6.addWidget(self.checkBox_AskFileName_Autosave, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_AutoSave_AdvOption, 4, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(AdvanceOption)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.spinBox_MeasureDelay_Dealy = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_MeasureDelay_Dealy.sizePolicy().hasHeightForWidth())
        self.spinBox_MeasureDelay_Dealy.setSizePolicy(sizePolicy)
        self.spinBox_MeasureDelay_Dealy.setMinimumSize(QtCore.QSize(60, 20))
        self.spinBox_MeasureDelay_Dealy.setMaximum(65535)
        self.spinBox_MeasureDelay_Dealy.setProperty("value", 100)
        self.spinBox_MeasureDelay_Dealy.setObjectName("spinBox_MeasureDelay_Dealy")
        self.gridLayout.addWidget(self.spinBox_MeasureDelay_Dealy, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 2, 1, 1)
        self.spinBox_MoveDelay_Dealy = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_MoveDelay_Dealy.sizePolicy().hasHeightForWidth())
        self.spinBox_MoveDelay_Dealy.setSizePolicy(sizePolicy)
        self.spinBox_MoveDelay_Dealy.setMinimumSize(QtCore.QSize(60, 20))
        self.spinBox_MoveDelay_Dealy.setMinimum(1)
        self.spinBox_MoveDelay_Dealy.setMaximum(65535)
        self.spinBox_MoveDelay_Dealy.setObjectName("spinBox_MoveDelay_Dealy")
        self.gridLayout.addWidget(self.spinBox_MoveDelay_Dealy, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.spinBox_Wait_Delay = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_Wait_Delay.setMaximum(100000)
        self.spinBox_Wait_Delay.setProperty("value", 300)
        self.spinBox_Wait_Delay.setObjectName("spinBox_Wait_Delay")
        self.gridLayout.addWidget(self.spinBox_Wait_Delay, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 2, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox, 0, 0, 2, 1)

        self.retranslateUi(AdvanceOption)
        QtCore.QMetaObject.connectSlotsByName(AdvanceOption)

    def retranslateUi(self, AdvanceOption):
        _translate = QtCore.QCoreApplication.translate
        AdvanceOption.setWindowTitle(_translate("AdvanceOption", "Advance Option"))
        self.groupBox_Seq_AdvOption.setTitle(_translate("AdvanceOption", "Sequence"))
        self.pushButton_SeqEditor.setText(_translate("AdvanceOption", "Sequence Editor"))
        self.groupBox_4.setTitle(_translate("AdvanceOption", "Dither"))
        self.label_4.setText(_translate("AdvanceOption", "Bias"))
        self.radioButton_BiasON_AdvOption.setText(_translate("AdvanceOption", "ON"))
        self.radioButton_BiasOFF_AdvOption.setText(_translate("AdvanceOption", "OFF"))
        self.label_5.setText(_translate("AdvanceOption", "Z"))
        self.radioButton_ZON_AdvOption.setText(_translate("AdvanceOption", "ON"))
        self.radioButton_ZOFF_AdvOption.setText(_translate("AdvanceOption", "OFF"))
        self.groupBox_3.setTitle(_translate("AdvanceOption", "Scan Direction"))
        self.radioButton_Forward_Dir.setText(_translate("AdvanceOption", "Forward only"))
        self.radioButton_AvgBoth_Dir.setText(_translate("AdvanceOption", "Average both"))
        self.radioButton_Bacward_Dir.setText(_translate("AdvanceOption", "Backward only"))
        self.radioButton_Both_Dir.setText(_translate("AdvanceOption", "Both"))
        self.groupBox_5.setTitle(_translate("AdvanceOption", "Feedback"))
        self.radioButton_FeedbackON.setText(_translate("AdvanceOption", "ON"))
        self.radioButton_FeedbackOFF.setText(_translate("AdvanceOption", "OFF"))
        self.groupBox_2.setTitle(_translate("AdvanceOption", "Measure"))
        self.label_3.setText(_translate("AdvanceOption", "Average"))
        self.checkBox_Ch3_Measure.setText(_translate("AdvanceOption", "Ch3"))
        self.radioButton_Z_Measure.setText(_translate("AdvanceOption", "Z"))
        self.radioButton_I_Measure.setText(_translate("AdvanceOption", "I"))
        self.checkBox_Ch2_Measure.setText(_translate("AdvanceOption", "Ch2"))
        self.groupBox_AutoSave_AdvOption.setTitle(_translate("AdvanceOption", "Auto Save"))
        self.checkBox_SaveEveryPasses_Autosave.setText(_translate("AdvanceOption", "Save every passes"))
        self.checkBox_AskFileName_Autosave.setText(_translate("AdvanceOption", "Ask file name before scan"))
        self.groupBox.setTitle(_translate("AdvanceOption", "Delay"))
        self.label_2.setText(_translate("AdvanceOption", "Measure Delay"))
        self.label_7.setText(_translate("AdvanceOption", "us"))
        self.label.setText(_translate("AdvanceOption", "Move Delay"))
        self.label_6.setText(_translate("AdvanceOption", "us"))
        self.label_8.setText(_translate("AdvanceOption", "Wait"))
        self.label_9.setText(_translate("AdvanceOption", "ms"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AdvanceOption = QtWidgets.QWidget()
    ui = Ui_AdvanceOption()
    ui.setupUi(AdvanceOption)
    AdvanceOption.show()
    sys.exit(app.exec_())
