# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdvanceOption.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdvanceOption(object):
    def setupUi(self, AdvanceOption):
        AdvanceOption.setObjectName("AdvanceOption")
        AdvanceOption.resize(240, 565)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AdvanceOption.sizePolicy().hasHeightForWidth())
        AdvanceOption.setSizePolicy(sizePolicy)
        AdvanceOption.setMinimumSize(QtCore.QSize(230, 480))
        self.gridLayout_7 = QtWidgets.QGridLayout(AdvanceOption)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox = QtWidgets.QGroupBox(AdvanceOption)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox_MoveDelay_AdvOption = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_MoveDelay_AdvOption.sizePolicy().hasHeightForWidth())
        self.spinBox_MoveDelay_AdvOption.setSizePolicy(sizePolicy)
        self.spinBox_MoveDelay_AdvOption.setMinimumSize(QtCore.QSize(60, 20))
        self.spinBox_MoveDelay_AdvOption.setObjectName("spinBox_MoveDelay_AdvOption")
        self.gridLayout.addWidget(self.spinBox_MoveDelay_AdvOption, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.spinBox_MeasureDelay_AdvOption = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_MeasureDelay_AdvOption.sizePolicy().hasHeightForWidth())
        self.spinBox_MeasureDelay_AdvOption.setSizePolicy(sizePolicy)
        self.spinBox_MeasureDelay_AdvOption.setMinimumSize(QtCore.QSize(60, 20))
        self.spinBox_MeasureDelay_AdvOption.setObjectName("spinBox_MeasureDelay_AdvOption")
        self.gridLayout.addWidget(self.spinBox_MeasureDelay_AdvOption, 1, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox, 0, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(AdvanceOption)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_MeasureI_AdvOption = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_MeasureI_AdvOption.sizePolicy().hasHeightForWidth())
        self.checkBox_MeasureI_AdvOption.setSizePolicy(sizePolicy)
        self.checkBox_MeasureI_AdvOption.setObjectName("checkBox_MeasureI_AdvOption")
        self.gridLayout_2.addWidget(self.checkBox_MeasureI_AdvOption, 0, 0, 1, 1)
        self.checkBox_MeasureZ_AdvOption = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_MeasureZ_AdvOption.sizePolicy().hasHeightForWidth())
        self.checkBox_MeasureZ_AdvOption.setSizePolicy(sizePolicy)
        self.checkBox_MeasureZ_AdvOption.setObjectName("checkBox_MeasureZ_AdvOption")
        self.gridLayout_2.addWidget(self.checkBox_MeasureZ_AdvOption, 1, 0, 1, 1)
        self.checkBox_MeasureCh2_AdvOption = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_MeasureCh2_AdvOption.sizePolicy().hasHeightForWidth())
        self.checkBox_MeasureCh2_AdvOption.setSizePolicy(sizePolicy)
        self.checkBox_MeasureCh2_AdvOption.setObjectName("checkBox_MeasureCh2_AdvOption")
        self.gridLayout_2.addWidget(self.checkBox_MeasureCh2_AdvOption, 2, 0, 1, 1)
        self.checkBox_MeasureCh3_AdvOption = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_MeasureCh3_AdvOption.sizePolicy().hasHeightForWidth())
        self.checkBox_MeasureCh3_AdvOption.setSizePolicy(sizePolicy)
        self.checkBox_MeasureCh3_AdvOption.setObjectName("checkBox_MeasureCh3_AdvOption")
        self.gridLayout_2.addWidget(self.checkBox_MeasureCh3_AdvOption, 3, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(AdvanceOption)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_ScanForward_AdvOption = QtWidgets.QCheckBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_ScanForward_AdvOption.sizePolicy().hasHeightForWidth())
        self.checkBox_ScanForward_AdvOption.setSizePolicy(sizePolicy)
        self.checkBox_ScanForward_AdvOption.setObjectName("checkBox_ScanForward_AdvOption")
        self.gridLayout_3.addWidget(self.checkBox_ScanForward_AdvOption, 0, 0, 1, 1)
        self.checkBox_ScanBackward_AdvOption = QtWidgets.QCheckBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_ScanBackward_AdvOption.sizePolicy().hasHeightForWidth())
        self.checkBox_ScanBackward_AdvOption.setSizePolicy(sizePolicy)
        self.checkBox_ScanBackward_AdvOption.setObjectName("checkBox_ScanBackward_AdvOption")
        self.gridLayout_3.addWidget(self.checkBox_ScanBackward_AdvOption, 1, 0, 1, 1)
        self.checkBox_ScanAvg_AdvOption = QtWidgets.QCheckBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_ScanAvg_AdvOption.sizePolicy().hasHeightForWidth())
        self.checkBox_ScanAvg_AdvOption.setSizePolicy(sizePolicy)
        self.checkBox_ScanAvg_AdvOption.setObjectName("checkBox_ScanAvg_AdvOption")
        self.gridLayout_3.addWidget(self.checkBox_ScanAvg_AdvOption, 2, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_3, 1, 1, 1, 1)
        self.frame = QtWidgets.QFrame(AdvanceOption)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.spinBox_NumofSamples_AdvOption = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_NumofSamples_AdvOption.sizePolicy().hasHeightForWidth())
        self.spinBox_NumofSamples_AdvOption.setSizePolicy(sizePolicy)
        self.spinBox_NumofSamples_AdvOption.setMinimumSize(QtCore.QSize(60, 20))
        self.spinBox_NumofSamples_AdvOption.setMaximum(4095)
        self.spinBox_NumofSamples_AdvOption.setObjectName("spinBox_NumofSamples_AdvOption")
        self.gridLayout_4.addWidget(self.spinBox_NumofSamples_AdvOption, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.frame, 2, 0, 1, 2)
        self.groupBox_4 = QtWidgets.QGroupBox(AdvanceOption)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1)
        self.radioButton_BiasON_AdvOption = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_BiasON_AdvOption.setObjectName("radioButton_BiasON_AdvOption")
        self.gridLayout_5.addWidget(self.radioButton_BiasON_AdvOption, 0, 1, 1, 1)
        self.radioButton_BiasOFF_AdvOption = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_BiasOFF_AdvOption.setObjectName("radioButton_BiasOFF_AdvOption")
        self.gridLayout_5.addWidget(self.radioButton_BiasOFF_AdvOption, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 1, 0, 1, 1)
        self.radioButton_ZON_AdvOption = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_ZON_AdvOption.setObjectName("radioButton_ZON_AdvOption")
        self.gridLayout_5.addWidget(self.radioButton_ZON_AdvOption, 1, 1, 1, 1)
        self.radioButton_ZOFF_AdvOption = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_ZOFF_AdvOption.setObjectName("radioButton_ZOFF_AdvOption")
        self.gridLayout_5.addWidget(self.radioButton_ZOFF_AdvOption, 1, 2, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_4, 3, 0, 1, 2)
        self.groupBox_Seq_AdvOption = QtWidgets.QGroupBox(AdvanceOption)
        self.groupBox_Seq_AdvOption.setCheckable(True)
        self.groupBox_Seq_AdvOption.setObjectName("groupBox_Seq_AdvOption")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_Seq_AdvOption)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_Seq_AdvOption = QtWidgets.QLabel(self.groupBox_Seq_AdvOption)
        self.label_Seq_AdvOption.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_Seq_AdvOption.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_Seq_AdvOption.setText("")
        self.label_Seq_AdvOption.setObjectName("label_Seq_AdvOption")
        self.gridLayout_8.addWidget(self.label_Seq_AdvOption, 0, 0, 1, 1)
        self.pushButton_SeqEditor_AdvOption = QtWidgets.QPushButton(self.groupBox_Seq_AdvOption)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SeqEditor_AdvOption.sizePolicy().hasHeightForWidth())
        self.pushButton_SeqEditor_AdvOption.setSizePolicy(sizePolicy)
        self.pushButton_SeqEditor_AdvOption.setMinimumSize(QtCore.QSize(110, 0))
        self.pushButton_SeqEditor_AdvOption.setObjectName("pushButton_SeqEditor_AdvOption")
        self.gridLayout_8.addWidget(self.pushButton_SeqEditor_AdvOption, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_Seq_AdvOption, 4, 0, 1, 2)
        self.groupBox_AutoSave_AdvOption = QtWidgets.QGroupBox(AdvanceOption)
        self.groupBox_AutoSave_AdvOption.setCheckable(True)
        self.groupBox_AutoSave_AdvOption.setObjectName("groupBox_AutoSave_AdvOption")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_AutoSave_AdvOption)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.checkBox_SaveEveryPasses_AdvOption = QtWidgets.QCheckBox(self.groupBox_AutoSave_AdvOption)
        self.checkBox_SaveEveryPasses_AdvOption.setObjectName("checkBox_SaveEveryPasses_AdvOption")
        self.gridLayout_6.addWidget(self.checkBox_SaveEveryPasses_AdvOption, 0, 0, 1, 1)
        self.checkBox_AskFileName_AdvOption = QtWidgets.QCheckBox(self.groupBox_AutoSave_AdvOption)
        self.checkBox_AskFileName_AdvOption.setObjectName("checkBox_AskFileName_AdvOption")
        self.gridLayout_6.addWidget(self.checkBox_AskFileName_AdvOption, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_AutoSave_AdvOption, 5, 0, 1, 2)

        self.retranslateUi(AdvanceOption)
        QtCore.QMetaObject.connectSlotsByName(AdvanceOption)

    def retranslateUi(self, AdvanceOption):
        _translate = QtCore.QCoreApplication.translate
        AdvanceOption.setWindowTitle(_translate("AdvanceOption", "Advance Option"))
        self.groupBox.setTitle(_translate("AdvanceOption", "Delay"))
        self.label.setText(_translate("AdvanceOption", "Move Delay"))
        self.label_2.setText(_translate("AdvanceOption", "Measure Delay"))
        self.groupBox_2.setTitle(_translate("AdvanceOption", "Measure"))
        self.checkBox_MeasureI_AdvOption.setText(_translate("AdvanceOption", "I"))
        self.checkBox_MeasureZ_AdvOption.setText(_translate("AdvanceOption", "Z"))
        self.checkBox_MeasureCh2_AdvOption.setText(_translate("AdvanceOption", "Ch2"))
        self.checkBox_MeasureCh3_AdvOption.setText(_translate("AdvanceOption", "Ch3"))
        self.groupBox_3.setTitle(_translate("AdvanceOption", "Scan Direction"))
        self.checkBox_ScanForward_AdvOption.setText(_translate("AdvanceOption", "Forward"))
        self.checkBox_ScanBackward_AdvOption.setText(_translate("AdvanceOption", "Backward"))
        self.checkBox_ScanAvg_AdvOption.setText(_translate("AdvanceOption", "Average Both"))
        self.label_3.setText(_translate("AdvanceOption", "Number of samples"))
        self.groupBox_4.setTitle(_translate("AdvanceOption", "Dither"))
        self.label_4.setText(_translate("AdvanceOption", "Bias"))
        self.radioButton_BiasON_AdvOption.setText(_translate("AdvanceOption", "ON"))
        self.radioButton_BiasOFF_AdvOption.setText(_translate("AdvanceOption", "OFF"))
        self.label_5.setText(_translate("AdvanceOption", "Z"))
        self.radioButton_ZON_AdvOption.setText(_translate("AdvanceOption", "ON"))
        self.radioButton_ZOFF_AdvOption.setText(_translate("AdvanceOption", "OFF"))
        self.groupBox_Seq_AdvOption.setTitle(_translate("AdvanceOption", "Sequence"))
        self.pushButton_SeqEditor_AdvOption.setText(_translate("AdvanceOption", "Sequence Editor"))
        self.groupBox_AutoSave_AdvOption.setTitle(_translate("AdvanceOption", "Auto Save"))
        self.checkBox_SaveEveryPasses_AdvOption.setText(_translate("AdvanceOption", "Save every passes"))
        self.checkBox_AskFileName_AdvOption.setText(_translate("AdvanceOption", "Ask file name before scan"))
