# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Correction.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Correction(object):
    def setupUi(self, Correction):
        Correction.setObjectName("Correction")
        Correction.resize(320, 359)
        self.gridLayout_4 = QtWidgets.QGridLayout(Correction)
        self.gridLayout_4.setHorizontalSpacing(9)
        self.gridLayout_4.setVerticalSpacing(14)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_XYDrift_BetPasses = QtWidgets.QGroupBox(Correction)
        self.groupBox_XYDrift_BetPasses.setCheckable(True)
        self.groupBox_XYDrift_BetPasses.setObjectName("groupBox_XYDrift_BetPasses")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_XYDrift_BetPasses)
        self.gridLayout_3.setSpacing(9)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_XYDrift_BetPasses)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 2)
        self.spinBox_DoXYDrift_XYDrift = QtWidgets.QSpinBox(self.groupBox_XYDrift_BetPasses)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_DoXYDrift_XYDrift.sizePolicy().hasHeightForWidth())
        self.spinBox_DoXYDrift_XYDrift.setSizePolicy(sizePolicy)
        self.spinBox_DoXYDrift_XYDrift.setMinimumSize(QtCore.QSize(60, 20))
        self.spinBox_DoXYDrift_XYDrift.setMinimum(1)
        self.spinBox_DoXYDrift_XYDrift.setObjectName("spinBox_DoXYDrift_XYDrift")
        self.gridLayout_3.addWidget(self.spinBox_DoXYDrift_XYDrift, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_XYDrift_BetPasses)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 3, 1, 1)
        self.checkBox_Scan_XYDrift = QtWidgets.QCheckBox(self.groupBox_XYDrift_BetPasses)
        self.checkBox_Scan_XYDrift.setObjectName("checkBox_Scan_XYDrift")
        self.gridLayout_3.addWidget(self.checkBox_Scan_XYDrift, 1, 0, 1, 1)
        self.checkBox_Tracking_XYDrift = QtWidgets.QCheckBox(self.groupBox_XYDrift_BetPasses)
        self.checkBox_Tracking_XYDrift.setMinimumSize(QtCore.QSize(65, 0))
        self.checkBox_Tracking_XYDrift.setChecked(True)
        self.checkBox_Tracking_XYDrift.setObjectName("checkBox_Tracking_XYDrift")
        self.gridLayout_3.addWidget(self.checkBox_Tracking_XYDrift, 2, 0, 1, 1)
        self.pushButton_Pattern_XYDrift = QtWidgets.QPushButton(self.groupBox_XYDrift_BetPasses)
        self.pushButton_Pattern_XYDrift.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_Pattern_XYDrift.setObjectName("pushButton_Pattern_XYDrift")
        self.gridLayout_3.addWidget(self.pushButton_Pattern_XYDrift, 1, 1, 1, 3)
        self.gridLayout_4.addWidget(self.groupBox_XYDrift_BetPasses, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Correction)
        self.groupBox_3.setCheckable(True)
        self.groupBox_3.setChecked(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_SelectPoint = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_SelectPoint.setObjectName("pushButton_SelectPoint")
        self.verticalLayout_2.addWidget(self.pushButton_SelectPoint)
        self.gridLayout_4.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.groupBox_ZDrift_BetPasses = QtWidgets.QGroupBox(Correction)
        self.groupBox_ZDrift_BetPasses.setCheckable(True)
        self.groupBox_ZDrift_BetPasses.setObjectName("groupBox_ZDrift_BetPasses")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_ZDrift_BetPasses)
        self.gridLayout.setSpacing(9)
        self.gridLayout.setObjectName("gridLayout")
        self.spinBox_DoZCorrection_ZDrift = QtWidgets.QSpinBox(self.groupBox_ZDrift_BetPasses)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_DoZCorrection_ZDrift.sizePolicy().hasHeightForWidth())
        self.spinBox_DoZCorrection_ZDrift.setSizePolicy(sizePolicy)
        self.spinBox_DoZCorrection_ZDrift.setMinimumSize(QtCore.QSize(60, 20))
        self.spinBox_DoZCorrection_ZDrift.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_DoZCorrection_ZDrift.setMinimum(1)
        self.spinBox_DoZCorrection_ZDrift.setObjectName("spinBox_DoZCorrection_ZDrift")
        self.gridLayout.addWidget(self.spinBox_DoZCorrection_ZDrift, 0, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.groupBox_ZDrift_BetPasses)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.checkBox_MatchCurr_ZDrift = QtWidgets.QCheckBox(self.groupBox_ZDrift_BetPasses)
        self.checkBox_MatchCurr_ZDrift.setObjectName("checkBox_MatchCurr_ZDrift")
        self.gridLayout.addWidget(self.checkBox_MatchCurr_ZDrift, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_ZDrift_BetPasses)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setIndent(-1)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_ZDrift_BetPasses)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.spinBox_Delay1_ZDrift = QtWidgets.QSpinBox(self.groupBox_ZDrift_BetPasses)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_Delay1_ZDrift.sizePolicy().hasHeightForWidth())
        self.spinBox_Delay1_ZDrift.setSizePolicy(sizePolicy)
        self.spinBox_Delay1_ZDrift.setMinimumSize(QtCore.QSize(60, 20))
        self.spinBox_Delay1_ZDrift.setMinimum(1)
        self.spinBox_Delay1_ZDrift.setMaximum(1000)
        self.spinBox_Delay1_ZDrift.setObjectName("spinBox_Delay1_ZDrift")
        self.gridLayout.addWidget(self.spinBox_Delay1_ZDrift, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_ZDrift_BetPasses)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_ZDrift_BetPasses, 0, 0, 1, 1)

        self.retranslateUi(Correction)
        QtCore.QMetaObject.connectSlotsByName(Correction)

    def retranslateUi(self, Correction):
        _translate = QtCore.QCoreApplication.translate
        Correction.setWindowTitle(_translate("Correction", "Correction"))
        self.groupBox_XYDrift_BetPasses.setTitle(_translate("Correction", "XY Drift correction"))
        self.label_5.setText(_translate("Correction", "Do XY drift correction every"))
        self.label_6.setText(_translate("Correction", "passes"))
        self.checkBox_Scan_XYDrift.setText(_translate("Correction", "Scan"))
        self.checkBox_Tracking_XYDrift.setText(_translate("Correction", "Tracking"))
        self.pushButton_Pattern_XYDrift.setText(_translate("Correction", "Select Pattern"))
        self.groupBox_3.setTitle(_translate("Correction", "Customize correction point"))
        self.pushButton_SelectPoint.setText(_translate("Correction", "Select correction points"))
        self.groupBox_ZDrift_BetPasses.setTitle(_translate("Correction", "Z Drift correction"))
        self.label.setText(_translate("Correction", "Do Z correction every"))
        self.checkBox_MatchCurr_ZDrift.setText(_translate("Correction", "Match Curent"))
        self.label_2.setText(_translate("Correction", "passes"))
        self.label_3.setText(_translate("Correction", "Feedback on delay"))
        self.label_4.setText(_translate("Correction", "ms"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Correction = QtWidgets.QWidget()
    ui = Ui_Correction()
    ui.setupUi(Correction)
    Correction.show()
    sys.exit(app.exec_())
