# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DataWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DataWindow(object):
    def setupUi(self, DataWindow):
        DataWindow.setObjectName("DataWindow")
        DataWindow.resize(823, 556)
        self.gridLayout_3 = QtWidgets.QGridLayout(DataWindow)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(DataWindow)
        self.groupBox.setMinimumSize(QtCore.QSize(260, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(260, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(DataWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setContentsMargins(-1, 6, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_yScale = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_yScale.sizePolicy().hasHeightForWidth())
        self.pushButton_yScale.setSizePolicy(sizePolicy)
        self.pushButton_yScale.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/toolbar/data/up_down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_yScale.setIcon(icon)
        self.pushButton_yScale.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_yScale.setFlat(True)
        self.pushButton_yScale.setObjectName("pushButton_yScale")
        self.gridLayout.addWidget(self.pushButton_yScale, 0, 2, 1, 1)
        self.pushButton_xScale = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_xScale.sizePolicy().hasHeightForWidth())
        self.pushButton_xScale.setSizePolicy(sizePolicy)
        self.pushButton_xScale.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/toolbar/data/left_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_xScale.setIcon(icon1)
        self.pushButton_xScale.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_xScale.setFlat(True)
        self.pushButton_xScale.setObjectName("pushButton_xScale")
        self.gridLayout.addWidget(self.pushButton_xScale, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_2, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(DataWindow)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.graphicsView = GraphicsLayoutWidget(self.widget)
        self.graphicsView.setMinimumSize(QtCore.QSize(512, 512))
        self.graphicsView.setMaximumSize(QtCore.QSize(512, 512))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_2.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 0, 1, 2, 1)

        self.retranslateUi(DataWindow)
        QtCore.QMetaObject.connectSlotsByName(DataWindow)

    def retranslateUi(self, DataWindow):
        _translate = QtCore.QCoreApplication.translate
        DataWindow.setWindowTitle(_translate("DataWindow", "Data Window"))
        self.groupBox.setTitle(_translate("DataWindow", "Plot list"))
        self.label.setText(_translate("DataWindow", "Auto scale"))
from pyqtgraph import GraphicsLayoutWidget
import logo_rc
