# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DepositionInfo.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DepositionInfo(object):
    def setupUi(self, DepositionInfo):
        DepositionInfo.setObjectName("DepositionInfo")
        DepositionInfo.setWindowModality(QtCore.Qt.ApplicationModal)
        DepositionInfo.resize(760, 414)
        self.gridLayout = QtWidgets.QGridLayout(DepositionInfo)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(DepositionInfo)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_41 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        self.label_41.setMinimumSize(QtCore.QSize(0, 25))
        self.label_41.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_41.setObjectName("label_41")
        self.gridLayout_5.addWidget(self.label_41, 5, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_52.sizePolicy().hasHeightForWidth())
        self.label_52.setSizePolicy(sizePolicy)
        self.label_52.setMinimumSize(QtCore.QSize(0, 25))
        self.label_52.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_52.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_52.setObjectName("label_52")
        self.gridLayout_5.addWidget(self.label_52, 0, 3, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setMinimumSize(QtCore.QSize(0, 25))
        self.label_29.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(0, 25))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 5, 2, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setMinimumSize(QtCore.QSize(0, 25))
        self.label_37.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_37.setObjectName("label_37")
        self.gridLayout_5.addWidget(self.label_37, 8, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMinimumSize(QtCore.QSize(0, 25))
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 8, 2, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_51.sizePolicy().hasHeightForWidth())
        self.label_51.setSizePolicy(sizePolicy)
        self.label_51.setMinimumSize(QtCore.QSize(0, 25))
        self.label_51.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_51.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_51.setObjectName("label_51")
        self.gridLayout_5.addWidget(self.label_51, 1, 3, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        self.label_44.setMinimumSize(QtCore.QSize(0, 25))
        self.label_44.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_44.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_44.setObjectName("label_44")
        self.gridLayout_5.addWidget(self.label_44, 0, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setMinimumSize(QtCore.QSize(0, 25))
        self.label_28.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 0, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMinimumSize(QtCore.QSize(0, 25))
        self.label_27.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 9, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMinimumSize(QtCore.QSize(0, 25))
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 7, 2, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_49.sizePolicy().hasHeightForWidth())
        self.label_49.setSizePolicy(sizePolicy)
        self.label_49.setMinimumSize(QtCore.QSize(0, 25))
        self.label_49.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_49.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_49.setObjectName("label_49")
        self.gridLayout_5.addWidget(self.label_49, 5, 3, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_50.sizePolicy().hasHeightForWidth())
        self.label_50.setSizePolicy(sizePolicy)
        self.label_50.setMinimumSize(QtCore.QSize(0, 25))
        self.label_50.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_50.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_50.setObjectName("label_50")
        self.gridLayout_5.addWidget(self.label_50, 3, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(0, 25))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 1, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(0, 25))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(0, 25))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 8, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(0, 25))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setMinimumSize(QtCore.QSize(0, 25))
        self.label_36.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_36.setObjectName("label_36")
        self.gridLayout_5.addWidget(self.label_36, 9, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_48.sizePolicy().hasHeightForWidth())
        self.label_48.setSizePolicy(sizePolicy)
        self.label_48.setMinimumSize(QtCore.QSize(0, 25))
        self.label_48.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_48.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_48.setObjectName("label_48")
        self.gridLayout_5.addWidget(self.label_48, 6, 3, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_45.sizePolicy().hasHeightForWidth())
        self.label_45.setSizePolicy(sizePolicy)
        self.label_45.setMinimumSize(QtCore.QSize(0, 25))
        self.label_45.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_45.setObjectName("label_45")
        self.gridLayout_5.addWidget(self.label_45, 9, 3, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setMinimumSize(QtCore.QSize(0, 25))
        self.label_30.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 10, 0, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.groupBox_4)
        self.label_54.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_54.setObjectName("label_54")
        self.gridLayout_5.addWidget(self.label_54, 10, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(0, 25))
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 3, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QtCore.QSize(0, 25))
        self.label_26.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 9, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_42.sizePolicy().hasHeightForWidth())
        self.label_42.setSizePolicy(sizePolicy)
        self.label_42.setMinimumSize(QtCore.QSize(0, 25))
        self.label_42.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_42.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_42.setObjectName("label_42")
        self.gridLayout_5.addWidget(self.label_42, 3, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(0, 25))
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 7, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        self.label_43.setMinimumSize(QtCore.QSize(0, 25))
        self.label_43.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_43.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_43.setObjectName("label_43")
        self.gridLayout_5.addWidget(self.label_43, 1, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_46.sizePolicy().hasHeightForWidth())
        self.label_46.setSizePolicy(sizePolicy)
        self.label_46.setMinimumSize(QtCore.QSize(0, 25))
        self.label_46.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_46.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_46.setObjectName("label_46")
        self.gridLayout_5.addWidget(self.label_46, 8, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(0, 25))
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 3, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_39.sizePolicy().hasHeightForWidth())
        self.label_39.setSizePolicy(sizePolicy)
        self.label_39.setMinimumSize(QtCore.QSize(0, 25))
        self.label_39.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_39.setObjectName("label_39")
        self.gridLayout_5.addWidget(self.label_39, 7, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.groupBox_4)
        self.label_53.setObjectName("label_53")
        self.gridLayout_5.addWidget(self.label_53, 10, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(0, 25))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 6, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMinimumSize(QtCore.QSize(0, 25))
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 6, 2, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_47.sizePolicy().hasHeightForWidth())
        self.label_47.setSizePolicy(sizePolicy)
        self.label_47.setMinimumSize(QtCore.QSize(0, 25))
        self.label_47.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_47.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_47.setObjectName("label_47")
        self.gridLayout_5.addWidget(self.label_47, 7, 3, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_40.sizePolicy().hasHeightForWidth())
        self.label_40.setSizePolicy(sizePolicy)
        self.label_40.setMinimumSize(QtCore.QSize(0, 25))
        self.label_40.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_40.setObjectName("label_40")
        self.gridLayout_5.addWidget(self.label_40, 6, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setMinimumSize(QtCore.QSize(0, 25))
        self.label_38.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_38.setObjectName("label_38")
        self.gridLayout_5.addWidget(self.label_38, 10, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 1, 0, 5, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(DepositionInfo)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 25))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(0, 25))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(DepositionInfo)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.listWidget_2 = QtWidgets.QListWidget(self.groupBox_6)
        self.listWidget_2.setObjectName("listWidget_2")
        self.gridLayout_7.addWidget(self.listWidget_2, 3, 0, 1, 4)
        self.label_56 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_56.sizePolicy().hasHeightForWidth())
        self.label_56.setSizePolicy(sizePolicy)
        self.label_56.setMinimumSize(QtCore.QSize(0, 25))
        self.label_56.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_56.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_56.setObjectName("label_56")
        self.gridLayout_7.addWidget(self.label_56, 1, 1, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_55.sizePolicy().hasHeightForWidth())
        self.label_55.setSizePolicy(sizePolicy)
        self.label_55.setMinimumSize(QtCore.QSize(0, 25))
        self.label_55.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_55.setObjectName("label_55")
        self.gridLayout_7.addWidget(self.label_55, 1, 0, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_58.sizePolicy().hasHeightForWidth())
        self.label_58.setSizePolicy(sizePolicy)
        self.label_58.setMinimumSize(QtCore.QSize(0, 25))
        self.label_58.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_58.setObjectName("label_58")
        self.gridLayout_7.addWidget(self.label_58, 1, 2, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_59.sizePolicy().hasHeightForWidth())
        self.label_59.setSizePolicy(sizePolicy)
        self.label_59.setMinimumSize(QtCore.QSize(0, 25))
        self.label_59.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_59.setObjectName("label_59")
        self.gridLayout_7.addWidget(self.label_59, 0, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setMinimumSize(QtCore.QSize(0, 25))
        self.label_31.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_31.setObjectName("label_31")
        self.gridLayout_7.addWidget(self.label_31, 0, 1, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_60.sizePolicy().hasHeightForWidth())
        self.label_60.setSizePolicy(sizePolicy)
        self.label_60.setMinimumSize(QtCore.QSize(0, 25))
        self.label_60.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_60.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_60.setObjectName("label_60")
        self.gridLayout_7.addWidget(self.label_60, 0, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(0, 25))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_57.sizePolicy().hasHeightForWidth())
        self.label_57.setSizePolicy(sizePolicy)
        self.label_57.setMinimumSize(QtCore.QSize(0, 25))
        self.label_57.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_57.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_57.setObjectName("label_57")
        self.gridLayout_7.addWidget(self.label_57, 1, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox_6, 0, 1, 4, 1)
        self.groupBox = QtWidgets.QGroupBox(DepositionInfo)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 25))
        self.label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 25))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(0, 25))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 2, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox)
        self.label_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_33.setObjectName("label_33")
        self.gridLayout_2.addWidget(self.label_33, 2, 4, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(0, 25))
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 0, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox)
        self.label_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_32.setObjectName("label_32")
        self.gridLayout_2.addWidget(self.label_32, 0, 4, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 25))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 3, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(0, 25))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 3, 1, 1, 4)
        self.gridLayout.addWidget(self.groupBox, 4, 1, 2, 1)

        self.retranslateUi(DepositionInfo)
        QtCore.QMetaObject.connectSlotsByName(DepositionInfo)

    def retranslateUi(self, DepositionInfo):
        _translate = QtCore.QCoreApplication.translate
        DepositionInfo.setWindowTitle(_translate("DepositionInfo", "Deposition Data Info"))
        self.groupBox_4.setTitle(_translate("DepositionInfo", "Status"))
        self.label_41.setText(_translate("DepositionInfo", "TextLabel"))
        self.label_52.setText(_translate("DepositionInfo", "TextLabel"))
        self.label_29.setText(_translate("DepositionInfo", "Pream gain"))
        self.label_8.setText(_translate("DepositionInfo", "Yoffset (bits)"))
        self.label_37.setText(_translate("DepositionInfo", "TextLabel"))
        self.label_25.setText(_translate("DepositionInfo", "Y gain"))
        self.label_51.setText(_translate("DepositionInfo", "TextLabel"))
        self.label_44.setText(_translate("DepositionInfo", "TextLabel"))
        self.label_28.setText(_translate("DepositionInfo", "Bias DAC"))
        self.label_27.setText(_translate("DepositionInfo", "Z gain2"))
        self.label_23.setText(_translate("DepositionInfo", "Yin (bits)"))
        self.label_49.setText(_translate("DepositionInfo", "TextLabel"))
        self.label_50.setText(_translate("DepositionInfo", "TextLabel"))
        self.label_11.setText(_translate("DepositionInfo", "Iset (nA)"))
        self.label_10.setText(_translate("DepositionInfo", "Bias (V)"))
        self.label_6.setText(_translate("DepositionInfo", "X gain"))
        self.label_7.setText(_translate("DepositionInfo", "Xoffset (bits)"))
        self.label_36.setText(_translate("DepositionInfo", "TextLabel"))
        self.label_48.setText(_translate("DepositionInfo", "TextLabel"))
        self.label_45.setText(_translate("DepositionInfo", "TextLabel"))
        self.label_30.setText(_translate("DepositionInfo", "Feedback"))
        self.label_54.setText(_translate("DepositionInfo", "TextLabel"))
        self.label_21.setText(_translate("DepositionInfo", "Z Dither"))
        self.label_26.setText(_translate("DepositionInfo", "Z gain1"))
        self.label_42.setText(_translate("DepositionInfo", "TextLabel"))
        self.label_22.setText(_translate("DepositionInfo", "Xin (bits)"))
        self.label_43.setText(_translate("DepositionInfo", "TextLabel"))
        self.label_46.setText(_translate("DepositionInfo", "TextLabel"))
        self.label_20.setText(_translate("DepositionInfo", "Bias Dither"))
        self.label_39.setText(_translate("DepositionInfo", "TextLabel"))
        self.label_53.setText(_translate("DepositionInfo", "Bias Range"))
        self.label_9.setText(_translate("DepositionInfo", "Zoffset (bits)"))
        self.label_24.setText(_translate("DepositionInfo", "Zoffset fine (bits)"))
        self.label_47.setText(_translate("DepositionInfo", "TextLabel"))
        self.label_40.setText(_translate("DepositionInfo", "TextLabel"))
        self.label_38.setText(_translate("DepositionInfo", "TextLabel"))
        self.groupBox_2.setTitle(_translate("DepositionInfo", "Date and Time"))
        self.label_4.setText(_translate("DepositionInfo", "Date"))
        self.label_5.setText(_translate("DepositionInfo", "TextLabel"))
        self.label_12.setText(_translate("DepositionInfo", "Time"))
        self.label_14.setText(_translate("DepositionInfo", "TextLabel"))
        self.groupBox_6.setTitle(_translate("DepositionInfo", "Sequence"))
        self.label_56.setText(_translate("DepositionInfo", "TextLabel"))
        self.label_55.setText(_translate("DepositionInfo", "Bias Dither"))
        self.label_58.setText(_translate("DepositionInfo", "Z Dither"))
        self.label_59.setText(_translate("DepositionInfo", "Feedback"))
        self.label_31.setText(_translate("DepositionInfo", "TextLabel"))
        self.label_60.setText(_translate("DepositionInfo", "TextLabel"))
        self.label_13.setText(_translate("DepositionInfo", "Name"))
        self.label_57.setText(_translate("DepositionInfo", "TextLabel"))
        self.groupBox.setTitle(_translate("DepositionInfo", "Read"))
        self.label.setText(_translate("DepositionInfo", "Read Channel"))
        self.label_3.setText(_translate("DepositionInfo", "Average number"))
        self.label_19.setText(_translate("DepositionInfo", "TextLabel"))
        self.label_33.setText(_translate("DepositionInfo", "TextLabel"))
        self.label_17.setText(_translate("DepositionInfo", "TextLabel"))
        self.label_32.setText(_translate("DepositionInfo", "TextLabel"))
        self.label_16.setText(_translate("DepositionInfo", "Sampling Delay (us)"))
        self.label_2.setText(_translate("DepositionInfo", "Read Delay (us)"))
        self.label_15.setText(_translate("DepositionInfo", "Read mode"))
        self.label_18.setText(_translate("DepositionInfo", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DepositionInfo = QtWidgets.QWidget()
    ui = Ui_DepositionInfo()
    ui.setupUi(DepositionInfo)
    DepositionInfo.show()
    sys.exit(app.exec_())
