# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Etest.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ElectronicTest(object):
    def setupUi(self, ElectronicTest):
        ElectronicTest.setObjectName("ElectronicTest")
        ElectronicTest.setEnabled(True)
        ElectronicTest.resize(986, 717)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ElectronicTest.sizePolicy().hasHeightForWidth())
        ElectronicTest.setSizePolicy(sizePolicy)
        ElectronicTest.setMinimumSize(QtCore.QSize(980, 700))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/menuIcon/testiconblack.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ElectronicTest.setWindowIcon(icon)
        self.gridLayout_3 = QtWidgets.QGridLayout(ElectronicTest)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Etest = QtWidgets.QTabWidget(ElectronicTest)
        self.Etest.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Etest.setFont(font)
        self.Etest.setObjectName("Etest")
        self.IO = QtWidgets.QWidget()
        self.IO.setObjectName("IO")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.IO)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.bit20 = QtWidgets.QGroupBox(self.IO)
        self.bit20.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.bit20.setFont(font)
        self.bit20.setObjectName("bit20")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.bit20)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.bit20_val = QtWidgets.QDoubleSpinBox(self.bit20)
        self.bit20_val.setDecimals(8)
        self.bit20_val.setMinimum(-5.0)
        self.bit20_val.setMaximum(5.0)
        self.bit20_val.setSingleStep(0.1)
        self.bit20_val.setObjectName("bit20_val")
        self.gridLayout_24.addWidget(self.bit20_val, 0, 0, 1, 1)
        self.bit20_0 = QtWidgets.QPushButton(self.bit20)
        self.bit20_0.setEnabled(False)
        self.bit20_0.setObjectName("bit20_0")
        self.gridLayout_24.addWidget(self.bit20_0, 0, 1, 1, 1)
        self.bit20_out = QtWidgets.QPushButton(self.bit20)
        self.bit20_out.setEnabled(False)
        self.bit20_out.setObjectName("bit20_out")
        self.gridLayout_24.addWidget(self.bit20_out, 0, 2, 1, 1)
        self.bit20_bit = QtWidgets.QScrollBar(self.bit20)
        self.bit20_bit.setMaximum(1048575)
        self.bit20_bit.setPageStep(10000)
        self.bit20_bit.setOrientation(QtCore.Qt.Horizontal)
        self.bit20_bit.setObjectName("bit20_bit")
        self.gridLayout_24.addWidget(self.bit20_bit, 1, 0, 1, 3)
        self.gridLayout_12.addWidget(self.bit20, 0, 2, 1, 2)
        self.xgain_G = QtWidgets.QGroupBox(self.IO)
        self.xgain_G.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.xgain_G.setFont(font)
        self.xgain_G.setObjectName("xgain_G")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.xgain_G)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.xgain0_1 = QtWidgets.QRadioButton(self.xgain_G)
        self.xgain0_1.setObjectName("xgain0_1")
        self.gridLayout_13.addWidget(self.xgain0_1, 0, 0, 1, 1)
        self.xgain1 = QtWidgets.QRadioButton(self.xgain_G)
        self.xgain1.setObjectName("xgain1")
        self.gridLayout_13.addWidget(self.xgain1, 0, 1, 1, 1)
        self.xgain10 = QtWidgets.QRadioButton(self.xgain_G)
        self.xgain10.setObjectName("xgain10")
        self.gridLayout_13.addWidget(self.xgain10, 0, 2, 1, 1)
        self.gridLayout_12.addWidget(self.xgain_G, 2, 0, 1, 1)
        self.dither0_G = QtWidgets.QGroupBox(self.IO)
        self.dither0_G.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.dither0_G.setFont(font)
        self.dither0_G.setObjectName("dither0_G")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.dither0_G)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.dither0_on = QtWidgets.QRadioButton(self.dither0_G)
        self.dither0_on.setObjectName("dither0_on")
        self.gridLayout_17.addWidget(self.dither0_on, 0, 0, 1, 1)
        self.dither0_off = QtWidgets.QRadioButton(self.dither0_G)
        self.dither0_off.setObjectName("dither0_off")
        self.gridLayout_17.addWidget(self.dither0_off, 0, 1, 1, 1)
        self.gridLayout_12.addWidget(self.dither0_G, 2, 1, 1, 1)
        self.dac_G = QtWidgets.QGroupBox(self.IO)
        self.dac_G.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.dac_G.setFont(font)
        self.dac_G.setObjectName("dac_G")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.dac_G)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.dac_ch = QtWidgets.QComboBox(self.dac_G)
        self.dac_ch.setEnabled(True)
        self.dac_ch.setObjectName("dac_ch")
        self.dac_ch.addItem("")
        self.dac_ch.addItem("")
        self.dac_ch.addItem("")
        self.dac_ch.addItem("")
        self.dac_ch.addItem("")
        self.dac_ch.addItem("")
        self.dac_ch.addItem("")
        self.dac_ch.addItem("")
        self.dac_ch.addItem("")
        self.dac_ch.addItem("")
        self.dac_ch.addItem("")
        self.dac_ch.addItem("")
        self.dac_ch.addItem("")
        self.dac_ch.addItem("")
        self.dac_ch.addItem("")
        self.dac_ch.addItem("")
        self.gridLayout_25.addWidget(self.dac_ch, 0, 0, 1, 6)
        self.dac_val = QtWidgets.QDoubleSpinBox(self.dac_G)
        self.dac_val.setEnabled(True)
        self.dac_val.setDecimals(6)
        self.dac_val.setMinimum(-10.0)
        self.dac_val.setMaximum(10.0)
        self.dac_val.setSingleStep(0.1)
        self.dac_val.setObjectName("dac_val")
        self.gridLayout_25.addWidget(self.dac_val, 1, 0, 1, 3)
        self.dac_0 = QtWidgets.QPushButton(self.dac_G)
        self.dac_0.setEnabled(False)
        self.dac_0.setObjectName("dac_0")
        self.gridLayout_25.addWidget(self.dac_0, 1, 3, 1, 2)
        self.dac_out = QtWidgets.QPushButton(self.dac_G)
        self.dac_out.setEnabled(False)
        self.dac_out.setObjectName("dac_out")
        self.gridLayout_25.addWidget(self.dac_out, 1, 5, 1, 1)
        self.dac_bit = QtWidgets.QScrollBar(self.dac_G)
        self.dac_bit.setEnabled(True)
        self.dac_bit.setMaximum(65535)
        self.dac_bit.setPageStep(1000)
        self.dac_bit.setOrientation(QtCore.Qt.Horizontal)
        self.dac_bit.setObjectName("dac_bit")
        self.gridLayout_25.addWidget(self.dac_bit, 2, 0, 1, 6)
        self.dac_b20 = QtWidgets.QRadioButton(self.dac_G)
        self.dac_b20.setEnabled(False)
        self.dac_b20.setObjectName("dac_b20")
        self.gridLayout_25.addWidget(self.dac_b20, 3, 0, 1, 2)
        self.dac_b10 = QtWidgets.QRadioButton(self.dac_G)
        self.dac_b10.setEnabled(False)
        self.dac_b10.setObjectName("dac_b10")
        self.gridLayout_25.addWidget(self.dac_b10, 3, 2, 1, 3)
        self.dac_b5 = QtWidgets.QRadioButton(self.dac_G)
        self.dac_b5.setEnabled(False)
        self.dac_b5.setObjectName("dac_b5")
        self.gridLayout_25.addWidget(self.dac_b5, 3, 5, 1, 1)
        self.dac_Iset_l = QtWidgets.QLabel(self.dac_G)
        self.dac_Iset_l.setEnabled(True)
        self.dac_Iset_l.setObjectName("dac_Iset_l")
        self.gridLayout_25.addWidget(self.dac_Iset_l, 5, 0, 1, 1)
        self.dac_Iset_val = QtWidgets.QDoubleSpinBox(self.dac_G)
        self.dac_Iset_val.setEnabled(True)
        self.dac_Iset_val.setDecimals(6)
        self.dac_Iset_val.setMinimum(-10.0)
        self.dac_Iset_val.setMaximum(10.0)
        self.dac_Iset_val.setSingleStep(0.01)
        self.dac_Iset_val.setObjectName("dac_Iset_val")
        self.gridLayout_25.addWidget(self.dac_Iset_val, 5, 1, 1, 3)
        self.dac_Iset_unit = QtWidgets.QLabel(self.dac_G)
        self.dac_Iset_unit.setEnabled(True)
        self.dac_Iset_unit.setObjectName("dac_Iset_unit")
        self.gridLayout_25.addWidget(self.dac_Iset_unit, 5, 4, 1, 1)
        self.dac_b10_4 = QtWidgets.QRadioButton(self.dac_G)
        self.dac_b10_4.setEnabled(False)
        self.dac_b10_4.setObjectName("dac_b10_4")
        self.gridLayout_25.addWidget(self.dac_b10_4, 4, 0, 1, 1)
        self.dac_u5 = QtWidgets.QRadioButton(self.dac_G)
        self.dac_u5.setEnabled(False)
        self.dac_u5.setObjectName("dac_u5")
        self.gridLayout_25.addWidget(self.dac_u5, 4, 2, 1, 1)
        self.gridLayout_12.addWidget(self.dac_G, 0, 0, 1, 2)
        self.adc_G = QtWidgets.QGroupBox(self.IO)
        self.adc_G.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.adc_G.setFont(font)
        self.adc_G.setObjectName("adc_G")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.adc_G)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.adc_ch = QtWidgets.QComboBox(self.adc_G)
        self.adc_ch.setObjectName("adc_ch")
        self.adc_ch.addItem("")
        self.adc_ch.addItem("")
        self.adc_ch.addItem("")
        self.adc_ch.addItem("")
        self.adc_ch.addItem("")
        self.adc_ch.addItem("")
        self.adc_ch.addItem("")
        self.adc_ch.addItem("")
        self.gridLayout_23.addWidget(self.adc_ch, 0, 0, 1, 2)
        self.adc_val = QtWidgets.QDoubleSpinBox(self.adc_G)
        self.adc_val.setEnabled(True)
        self.adc_val.setDecimals(6)
        self.adc_val.setMinimum(-10.24)
        self.adc_val.setMaximum(10.24)
        self.adc_val.setSingleStep(0.01)
        self.adc_val.setObjectName("adc_val")
        self.gridLayout_23.addWidget(self.adc_val, 0, 2, 1, 2)
        self.adc_in = QtWidgets.QPushButton(self.adc_G)
        self.adc_in.setEnabled(False)
        self.adc_in.setObjectName("adc_in")
        self.gridLayout_23.addWidget(self.adc_in, 0, 4, 1, 1)
        self.adc_b20 = QtWidgets.QRadioButton(self.adc_G)
        self.adc_b20.setEnabled(False)
        self.adc_b20.setObjectName("adc_b20")
        self.gridLayout_23.addWidget(self.adc_b20, 1, 0, 1, 1)
        self.adc_b10 = QtWidgets.QRadioButton(self.adc_G)
        self.adc_b10.setEnabled(False)
        self.adc_b10.setObjectName("adc_b10")
        self.gridLayout_23.addWidget(self.adc_b10, 1, 1, 1, 2)
        self.adc_b5 = QtWidgets.QRadioButton(self.adc_G)
        self.adc_b5.setEnabled(False)
        self.adc_b5.setObjectName("adc_b5")
        self.gridLayout_23.addWidget(self.adc_b5, 1, 3, 1, 2)
        self.adc_u10 = QtWidgets.QRadioButton(self.adc_G)
        self.adc_u10.setEnabled(False)
        self.adc_u10.setObjectName("adc_u10")
        self.gridLayout_23.addWidget(self.adc_u10, 2, 0, 1, 1)
        self.adc_u5 = QtWidgets.QRadioButton(self.adc_G)
        self.adc_u5.setEnabled(False)
        self.adc_u5.setObjectName("adc_u5")
        self.gridLayout_23.addWidget(self.adc_u5, 2, 1, 1, 2)
        self.gridLayout_12.addWidget(self.adc_G, 1, 0, 1, 2)
        self.ygain_G = QtWidgets.QGroupBox(self.IO)
        self.ygain_G.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ygain_G.setFont(font)
        self.ygain_G.setObjectName("ygain_G")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.ygain_G)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.ygain0_1 = QtWidgets.QRadioButton(self.ygain_G)
        self.ygain0_1.setObjectName("ygain0_1")
        self.gridLayout_14.addWidget(self.ygain0_1, 0, 0, 1, 1)
        self.ygain1 = QtWidgets.QRadioButton(self.ygain_G)
        self.ygain1.setObjectName("ygain1")
        self.gridLayout_14.addWidget(self.ygain1, 0, 1, 1, 1)
        self.ygain10 = QtWidgets.QRadioButton(self.ygain_G)
        self.ygain10.setObjectName("ygain10")
        self.gridLayout_14.addWidget(self.ygain10, 0, 2, 1, 1)
        self.gridLayout_12.addWidget(self.ygain_G, 3, 0, 1, 1)
        self.dither1_G = QtWidgets.QGroupBox(self.IO)
        self.dither1_G.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.dither1_G.setFont(font)
        self.dither1_G.setObjectName("dither1_G")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.dither1_G)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.dither1_on = QtWidgets.QRadioButton(self.dither1_G)
        self.dither1_on.setObjectName("dither1_on")
        self.gridLayout_18.addWidget(self.dither1_on, 0, 0, 1, 1)
        self.dither1_off = QtWidgets.QRadioButton(self.dither1_G)
        self.dither1_off.setObjectName("dither1_off")
        self.gridLayout_18.addWidget(self.dither1_off, 0, 1, 1, 1)
        self.gridLayout_12.addWidget(self.dither1_G, 3, 1, 1, 1)
        self.z1gain_G = QtWidgets.QGroupBox(self.IO)
        self.z1gain_G.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.z1gain_G.setFont(font)
        self.z1gain_G.setObjectName("z1gain_G")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.z1gain_G)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.z1gain1 = QtWidgets.QRadioButton(self.z1gain_G)
        self.z1gain1.setObjectName("z1gain1")
        self.gridLayout_15.addWidget(self.z1gain1, 0, 1, 1, 1)
        self.z1gain10 = QtWidgets.QRadioButton(self.z1gain_G)
        self.z1gain10.setObjectName("z1gain10")
        self.gridLayout_15.addWidget(self.z1gain10, 0, 2, 1, 1)
        self.z1gain0_1 = QtWidgets.QRadioButton(self.z1gain_G)
        self.z1gain0_1.setObjectName("z1gain0_1")
        self.gridLayout_15.addWidget(self.z1gain0_1, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.z1gain_G, 1, 2, 1, 1)
        self.feedback_G = QtWidgets.QGroupBox(self.IO)
        self.feedback_G.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.feedback_G.setFont(font)
        self.feedback_G.setObjectName("feedback_G")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.feedback_G)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.feedback_on = QtWidgets.QRadioButton(self.feedback_G)
        self.feedback_on.setObjectName("feedback_on")
        self.gridLayout_19.addWidget(self.feedback_on, 0, 0, 1, 1)
        self.feedback_off = QtWidgets.QRadioButton(self.feedback_G)
        self.feedback_off.setObjectName("feedback_off")
        self.gridLayout_19.addWidget(self.feedback_off, 0, 1, 1, 1)
        self.gridLayout_12.addWidget(self.feedback_G, 1, 3, 1, 1)
        self.z2gain_G = QtWidgets.QGroupBox(self.IO)
        self.z2gain_G.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.z2gain_G.setFont(font)
        self.z2gain_G.setObjectName("z2gain_G")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.z2gain_G)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.z2gain0_1 = QtWidgets.QRadioButton(self.z2gain_G)
        self.z2gain0_1.setObjectName("z2gain0_1")
        self.gridLayout_16.addWidget(self.z2gain0_1, 0, 0, 1, 1)
        self.z2gain1 = QtWidgets.QRadioButton(self.z2gain_G)
        self.z2gain1.setObjectName("z2gain1")
        self.gridLayout_16.addWidget(self.z2gain1, 0, 1, 1, 1)
        self.z2gain10 = QtWidgets.QRadioButton(self.z2gain_G)
        self.z2gain10.setObjectName("z2gain10")
        self.gridLayout_16.addWidget(self.z2gain10, 0, 2, 1, 1)
        self.gridLayout_12.addWidget(self.z2gain_G, 2, 2, 1, 1)
        self.retract_G = QtWidgets.QGroupBox(self.IO)
        self.retract_G.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.retract_G.setFont(font)
        self.retract_G.setObjectName("retract_G")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.retract_G)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.retract_on = QtWidgets.QRadioButton(self.retract_G)
        self.retract_on.setObjectName("retract_on")
        self.gridLayout_20.addWidget(self.retract_on, 0, 0, 1, 1)
        self.retract_off = QtWidgets.QRadioButton(self.retract_G)
        self.retract_off.setObjectName("retract_off")
        self.gridLayout_20.addWidget(self.retract_off, 0, 1, 1, 1)
        self.gridLayout_12.addWidget(self.retract_G, 2, 3, 1, 1)
        self.coarse_G = QtWidgets.QGroupBox(self.IO)
        self.coarse_G.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.coarse_G.setFont(font)
        self.coarse_G.setObjectName("coarse_G")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.coarse_G)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.fine = QtWidgets.QRadioButton(self.coarse_G)
        self.fine.setObjectName("fine")
        self.gridLayout_21.addWidget(self.fine, 0, 0, 1, 1)
        self.coarse = QtWidgets.QRadioButton(self.coarse_G)
        self.coarse.setObjectName("coarse")
        self.gridLayout_21.addWidget(self.coarse, 0, 1, 1, 1)
        self.gridLayout_12.addWidget(self.coarse_G, 3, 2, 1, 1)
        self.rot_G = QtWidgets.QGroupBox(self.IO)
        self.rot_G.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.rot_G.setFont(font)
        self.rot_G.setObjectName("rot_G")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.rot_G)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.translation = QtWidgets.QRadioButton(self.rot_G)
        self.translation.setObjectName("translation")
        self.gridLayout_22.addWidget(self.translation, 0, 1, 1, 1)
        self.rotation = QtWidgets.QRadioButton(self.rot_G)
        self.rotation.setObjectName("rotation")
        self.gridLayout_22.addWidget(self.rotation, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.rot_G, 3, 3, 1, 1)
        self.Etest.addTab(self.IO, "")
        self.RampTest = QtWidgets.QWidget()
        self.RampTest.setObjectName("RampTest")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.RampTest)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.view_RTest = QtWidgets.QGraphicsView(self.RampTest)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_RTest.sizePolicy().hasHeightForWidth())
        self.view_RTest.setSizePolicy(sizePolicy)
        self.view_RTest.setMinimumSize(QtCore.QSize(580, 580))
        self.view_RTest.setSizeIncrement(QtCore.QSize(0, 0))
        self.view_RTest.setBaseSize(QtCore.QSize(0, 0))
        self.view_RTest.setObjectName("view_RTest")
        self.gridLayout_2.addWidget(self.view_RTest, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.RampTest)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox_OutCh_RTest = QtWidgets.QComboBox(self.widget)
        self.comboBox_OutCh_RTest.setEnabled(True)
        self.comboBox_OutCh_RTest.setObjectName("comboBox_OutCh_RTest")
        self.comboBox_OutCh_RTest.addItem("")
        self.comboBox_OutCh_RTest.addItem("")
        self.comboBox_OutCh_RTest.addItem("")
        self.comboBox_OutCh_RTest.addItem("")
        self.comboBox_OutCh_RTest.addItem("")
        self.comboBox_OutCh_RTest.addItem("")
        self.comboBox_OutCh_RTest.addItem("")
        self.comboBox_OutCh_RTest.addItem("")
        self.comboBox_OutCh_RTest.addItem("")
        self.comboBox_OutCh_RTest.addItem("")
        self.comboBox_OutCh_RTest.addItem("")
        self.comboBox_OutCh_RTest.addItem("")
        self.comboBox_OutCh_RTest.addItem("")
        self.comboBox_OutCh_RTest.addItem("")
        self.comboBox_OutCh_RTest.addItem("")
        self.gridLayout.addWidget(self.comboBox_OutCh_RTest, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox_InCh_RTest = QtWidgets.QComboBox(self.widget)
        self.comboBox_InCh_RTest.setEnabled(True)
        self.comboBox_InCh_RTest.setObjectName("comboBox_InCh_RTest")
        self.comboBox_InCh_RTest.addItem("")
        self.comboBox_InCh_RTest.addItem("")
        self.comboBox_InCh_RTest.addItem("")
        self.comboBox_InCh_RTest.addItem("")
        self.comboBox_InCh_RTest.addItem("")
        self.comboBox_InCh_RTest.addItem("")
        self.comboBox_InCh_RTest.addItem("")
        self.gridLayout.addWidget(self.comboBox_InCh_RTest, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.spinBox_InitVal_RTest = QtWidgets.QSpinBox(self.widget)
        self.spinBox_InitVal_RTest.setEnabled(True)
        self.spinBox_InitVal_RTest.setObjectName("spinBox_InitVal_RTest")
        self.gridLayout.addWidget(self.spinBox_InitVal_RTest, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.spinBox_FinVal_RTest = QtWidgets.QSpinBox(self.widget)
        self.spinBox_FinVal_RTest.setEnabled(True)
        self.spinBox_FinVal_RTest.setObjectName("spinBox_FinVal_RTest")
        self.gridLayout.addWidget(self.spinBox_FinVal_RTest, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.spinBox_StepSize_RTest = QtWidgets.QSpinBox(self.widget)
        self.spinBox_StepSize_RTest.setEnabled(True)
        self.spinBox_StepSize_RTest.setObjectName("spinBox_StepSize_RTest")
        self.gridLayout.addWidget(self.spinBox_StepSize_RTest, 4, 1, 1, 1)
        self.pushButton_RRread_RTest = QtWidgets.QPushButton(self.widget)
        self.pushButton_RRread_RTest.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_RRread_RTest.sizePolicy().hasHeightForWidth())
        self.pushButton_RRread_RTest.setSizePolicy(sizePolicy)
        self.pushButton_RRread_RTest.setMinimumSize(QtCore.QSize(0, 80))
        self.pushButton_RRread_RTest.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_RRread_RTest.setFont(font)
        self.pushButton_RRread_RTest.setAutoDefault(False)
        self.pushButton_RRread_RTest.setDefault(False)
        self.pushButton_RRread_RTest.setFlat(False)
        self.pushButton_RRread_RTest.setObjectName("pushButton_RRread_RTest")
        self.gridLayout.addWidget(self.pushButton_RRread_RTest, 5, 0, 1, 2)
        self.gridLayout_2.addWidget(self.widget, 0, 1, 1, 1)
        self.Etest.addTab(self.RampTest, "")
        self.SquareWave = QtWidgets.QWidget()
        self.SquareWave.setObjectName("SquareWave")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.SquareWave)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.view_SWave = QtWidgets.QGraphicsView(self.SquareWave)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_SWave.sizePolicy().hasHeightForWidth())
        self.view_SWave.setSizePolicy(sizePolicy)
        self.view_SWave.setMinimumSize(QtCore.QSize(580, 580))
        self.view_SWave.setObjectName("view_SWave")
        self.gridLayout_4.addWidget(self.view_SWave, 0, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.SquareWave)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.widget_3.setFont(font)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_5.setVerticalSpacing(10)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 1, 1, 1, 1)
        self.spinBox_V2_SWave = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.spinBox_V2_SWave.setEnabled(True)
        self.spinBox_V2_SWave.setObjectName("spinBox_V2_SWave")
        self.gridLayout_5.addWidget(self.spinBox_V2_SWave, 3, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 2, 1, 1, 1)
        self.spinBox_Delay_SWave = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.spinBox_Delay_SWave.setEnabled(True)
        self.spinBox_Delay_SWave.setObjectName("spinBox_Delay_SWave")
        self.gridLayout_5.addWidget(self.spinBox_Delay_SWave, 1, 2, 1, 1)
        self.spinBox_V1_SWave = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.spinBox_V1_SWave.setEnabled(True)
        self.spinBox_V1_SWave.setObjectName("spinBox_V1_SWave")
        self.gridLayout_5.addWidget(self.spinBox_V1_SWave, 2, 2, 1, 1)
        self.comboBox_Ch_SWave = QtWidgets.QComboBox(self.widget_3)
        self.comboBox_Ch_SWave.setEnabled(True)
        self.comboBox_Ch_SWave.setObjectName("comboBox_Ch_SWave")
        self.comboBox_Ch_SWave.addItem("")
        self.comboBox_Ch_SWave.addItem("")
        self.comboBox_Ch_SWave.addItem("")
        self.comboBox_Ch_SWave.addItem("")
        self.comboBox_Ch_SWave.addItem("")
        self.comboBox_Ch_SWave.addItem("")
        self.comboBox_Ch_SWave.addItem("")
        self.comboBox_Ch_SWave.addItem("")
        self.comboBox_Ch_SWave.addItem("")
        self.comboBox_Ch_SWave.addItem("")
        self.comboBox_Ch_SWave.addItem("")
        self.comboBox_Ch_SWave.addItem("")
        self.comboBox_Ch_SWave.addItem("")
        self.comboBox_Ch_SWave.addItem("")
        self.comboBox_Ch_SWave.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_Ch_SWave, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 1, 1, 1)
        self.pushButton_Start_SWave = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_Start_SWave.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Start_SWave.sizePolicy().hasHeightForWidth())
        self.pushButton_Start_SWave.setSizePolicy(sizePolicy)
        self.pushButton_Start_SWave.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_Start_SWave.setFont(font)
        self.pushButton_Start_SWave.setObjectName("pushButton_Start_SWave")
        self.gridLayout_5.addWidget(self.pushButton_Start_SWave, 4, 1, 1, 2)
        self.gridLayout_4.addWidget(self.widget_3, 0, 1, 1, 1)
        self.Etest.addTab(self.SquareWave, "")
        self.Oscilloscope = QtWidgets.QWidget()
        self.Oscilloscope.setObjectName("Oscilloscope")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.Oscilloscope)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widget_4 = QtWidgets.QWidget(self.Oscilloscope)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_9.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.view_Osci = QtWidgets.QGraphicsView(self.widget_4)
        self.view_Osci.setObjectName("view_Osci")
        self.gridLayout_9.addWidget(self.view_Osci, 0, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.widget_4)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_8.setContentsMargins(3, 3, 3, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.radioButton_Contin_Osci = QtWidgets.QRadioButton(self.widget_5)
        self.radioButton_Contin_Osci.setEnabled(True)
        self.radioButton_Contin_Osci.setObjectName("radioButton_Contin_Osci")
        self.gridLayout_8.addWidget(self.radioButton_Contin_Osci, 2, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget_5)
        self.label_15.setObjectName("label_15")
        self.gridLayout_8.addWidget(self.label_15, 2, 4, 1, 1)
        self.radioButton_NSample_Osci = QtWidgets.QRadioButton(self.widget_5)
        self.radioButton_NSample_Osci.setEnabled(True)
        self.radioButton_NSample_Osci.setObjectName("radioButton_NSample_Osci")
        self.gridLayout_8.addWidget(self.radioButton_NSample_Osci, 1, 0, 1, 1)
        self.pushButton_SorS_Osci = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_SorS_Osci.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SorS_Osci.sizePolicy().hasHeightForWidth())
        self.pushButton_SorS_Osci.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_SorS_Osci.setFont(font)
        self.pushButton_SorS_Osci.setObjectName("pushButton_SorS_Osci")
        self.gridLayout_8.addWidget(self.pushButton_SorS_Osci, 1, 5, 4, 4)
        self.spinBox_Delay_Osci = QtWidgets.QDoubleSpinBox(self.widget_5)
        self.spinBox_Delay_Osci.setEnabled(True)
        self.spinBox_Delay_Osci.setObjectName("spinBox_Delay_Osci")
        self.gridLayout_8.addWidget(self.spinBox_Delay_Osci, 0, 6, 1, 1)
        self.comboBox_InCh_Osci = QtWidgets.QComboBox(self.widget_5)
        self.comboBox_InCh_Osci.setEnabled(True)
        self.comboBox_InCh_Osci.setObjectName("comboBox_InCh_Osci")
        self.comboBox_InCh_Osci.addItem("")
        self.comboBox_InCh_Osci.addItem("")
        self.comboBox_InCh_Osci.addItem("")
        self.comboBox_InCh_Osci.addItem("")
        self.comboBox_InCh_Osci.addItem("")
        self.comboBox_InCh_Osci.addItem("")
        self.comboBox_InCh_Osci.addItem("")
        self.gridLayout_8.addWidget(self.comboBox_InCh_Osci, 0, 1, 1, 3)
        self.spinBox_AvTimes_Osci = QtWidgets.QSpinBox(self.widget_5)
        self.spinBox_AvTimes_Osci.setEnabled(True)
        self.spinBox_AvTimes_Osci.setObjectName("spinBox_AvTimes_Osci")
        self.gridLayout_8.addWidget(self.spinBox_AvTimes_Osci, 2, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget_5)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget_5)
        self.label_13.setObjectName("label_13")
        self.gridLayout_8.addWidget(self.label_13, 1, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget_5)
        self.label_14.setObjectName("label_14")
        self.gridLayout_8.addWidget(self.label_14, 2, 2, 1, 1)
        self.spinBox_Samples_Osci = QtWidgets.QSpinBox(self.widget_5)
        self.spinBox_Samples_Osci.setEnabled(True)
        self.spinBox_Samples_Osci.setObjectName("spinBox_Samples_Osci")
        self.gridLayout_8.addWidget(self.spinBox_Samples_Osci, 1, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget_5)
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 0, 7, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget_5)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 0, 5, 1, 1)
        self.gridLayout_9.addWidget(self.widget_5, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.widget_4, 0, 0, 1, 1)
        self.Etest.addTab(self.Oscilloscope, "")
        self.Echo = QtWidgets.QWidget()
        self.Echo.setObjectName("Echo")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.Echo)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.widget_6 = QtWidgets.QWidget(self.Echo)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.lineEdit_1_Echo = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit_1_Echo.setEnabled(True)
        self.lineEdit_1_Echo.setObjectName("lineEdit_1_Echo")
        self.gridLayout_10.addWidget(self.lineEdit_1_Echo, 0, 0, 1, 1)
        self.pushButton_Query_Echo = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_Query_Echo.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Query_Echo.sizePolicy().hasHeightForWidth())
        self.pushButton_Query_Echo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Query_Echo.setFont(font)
        self.pushButton_Query_Echo.setObjectName("pushButton_Query_Echo")
        self.gridLayout_10.addWidget(self.pushButton_Query_Echo, 0, 1, 2, 1)
        self.lineEdit_2_Echo = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit_2_Echo.setEnabled(True)
        self.lineEdit_2_Echo.setObjectName("lineEdit_2_Echo")
        self.gridLayout_10.addWidget(self.lineEdit_2_Echo, 1, 0, 1, 1)
        self.gridLayout_11.addWidget(self.widget_6, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem1, 0, 1, 1, 1)
        self.Etest.addTab(self.Echo, "")
        self.FeedbackTest = QtWidgets.QWidget()
        self.FeedbackTest.setObjectName("FeedbackTest")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.FeedbackTest)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.widget_2 = QtWidgets.QWidget(self.FeedbackTest)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_26.setHorizontalSpacing(14)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.comboBox_InCh_FTest = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_InCh_FTest.setObjectName("comboBox_InCh_FTest")
        self.comboBox_InCh_FTest.addItem("")
        self.comboBox_InCh_FTest.addItem("")
        self.comboBox_InCh_FTest.addItem("")
        self.comboBox_InCh_FTest.addItem("")
        self.comboBox_InCh_FTest.addItem("")
        self.gridLayout_26.addWidget(self.comboBox_InCh_FTest, 4, 2, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(580, 580))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_26.addWidget(self.graphicsView, 0, 0, 7, 1)
        self.pushButton_Start_FTest = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_Start_FTest.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Start_FTest.sizePolicy().hasHeightForWidth())
        self.pushButton_Start_FTest.setSizePolicy(sizePolicy)
        self.pushButton_Start_FTest.setMinimumSize(QtCore.QSize(0, 80))
        self.pushButton_Start_FTest.setObjectName("pushButton_Start_FTest")
        self.gridLayout_26.addWidget(self.pushButton_Start_FTest, 6, 1, 1, 2)
        self.label_16 = QtWidgets.QLabel(self.widget_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_26.addWidget(self.label_16, 0, 1, 1, 1)
        self.spinBox_Z0Input_FTest = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.spinBox_Z0Input_FTest.setObjectName("spinBox_Z0Input_FTest")
        self.gridLayout_26.addWidget(self.spinBox_Z0Input_FTest, 1, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.widget_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_26.addWidget(self.label_21, 5, 1, 1, 1)
        self.spinBox_DelayInput_FTest = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.spinBox_DelayInput_FTest.setObjectName("spinBox_DelayInput_FTest")
        self.gridLayout_26.addWidget(self.spinBox_DelayInput_FTest, 2, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.widget_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_26.addWidget(self.label_20, 4, 1, 1, 1)
        self.spinBox_IsptInput_FTest = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.spinBox_IsptInput_FTest.setObjectName("spinBox_IsptInput_FTest")
        self.gridLayout_26.addWidget(self.spinBox_IsptInput_FTest, 5, 2, 1, 1)
        self.spinBox_AInput_FTest = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.spinBox_AInput_FTest.setObjectName("spinBox_AInput_FTest")
        self.gridLayout_26.addWidget(self.spinBox_AInput_FTest, 0, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.widget_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_26.addWidget(self.label_19, 3, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.widget_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_26.addWidget(self.label_18, 2, 1, 1, 1)
        self.comboBox_OutCh_FTest = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_OutCh_FTest.setObjectName("comboBox_OutCh_FTest")
        self.comboBox_OutCh_FTest.addItem("")
        self.comboBox_OutCh_FTest.addItem("")
        self.comboBox_OutCh_FTest.addItem("")
        self.comboBox_OutCh_FTest.addItem("")
        self.comboBox_OutCh_FTest.addItem("")
        self.gridLayout_26.addWidget(self.comboBox_OutCh_FTest, 3, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.widget_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_26.addWidget(self.label_17, 1, 1, 1, 1)
        self.gridLayout_6.addWidget(self.widget_2, 0, 0, 1, 1)
        self.Etest.addTab(self.FeedbackTest, "")
        self.gridLayout_3.addWidget(self.Etest, 0, 0, 1, 1)

        self.retranslateUi(ElectronicTest)
        self.Etest.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(ElectronicTest)

    def retranslateUi(self, ElectronicTest):
        _translate = QtCore.QCoreApplication.translate
        ElectronicTest.setWindowTitle(_translate("ElectronicTest", "ELectronic Test"))
        self.bit20.setTitle(_translate("ElectronicTest", "20bit DAC"))
        self.bit20_0.setText(_translate("ElectronicTest", "Zero"))
        self.bit20_out.setText(_translate("ElectronicTest", "20bit output"))
        self.xgain_G.setTitle(_translate("ElectronicTest", "XIN gain"))
        self.xgain0_1.setText(_translate("ElectronicTest", "0.1"))
        self.xgain1.setText(_translate("ElectronicTest", "1.0"))
        self.xgain10.setText(_translate("ElectronicTest", "10"))
        self.dither0_G.setTitle(_translate("ElectronicTest", "Dither0"))
        self.dither0_on.setText(_translate("ElectronicTest", "ON"))
        self.dither0_off.setText(_translate("ElectronicTest", "OFF"))
        self.dac_G.setTitle(_translate("ElectronicTest", "DAC"))
        self.dac_ch.setItemText(0, _translate("ElectronicTest", "DAC0 (XIN)"))
        self.dac_ch.setItemText(1, _translate("ElectronicTest", "DAC1 (X OFFSET)"))
        self.dac_ch.setItemText(2, _translate("ElectronicTest", "DAC2 (Z OFFSET FINE)"))
        self.dac_ch.setItemText(3, _translate("ElectronicTest", "DAC3 (Z OFFSET)"))
        self.dac_ch.setItemText(4, _translate("ElectronicTest", "DAC4 (ISET OFFSET)"))
        self.dac_ch.setItemText(5, _translate("ElectronicTest", "DAC5 (ISET)"))
        self.dac_ch.setItemText(6, _translate("ElectronicTest", "DAC6"))
        self.dac_ch.setItemText(7, _translate("ElectronicTest", "DAC7"))
        self.dac_ch.setItemText(8, _translate("ElectronicTest", "DAC8"))
        self.dac_ch.setItemText(9, _translate("ElectronicTest", "DAC9"))
        self.dac_ch.setItemText(10, _translate("ElectronicTest", "DAC10 (ZOUTER)"))
        self.dac_ch.setItemText(11, _translate("ElectronicTest", "DAC11"))
        self.dac_ch.setItemText(12, _translate("ElectronicTest", "DAC12 (BIAS OFFSET)"))
        self.dac_ch.setItemText(13, _translate("ElectronicTest", "DAC13 (BIAS)"))
        self.dac_ch.setItemText(14, _translate("ElectronicTest", "DAC14 (YOFFSET)"))
        self.dac_ch.setItemText(15, _translate("ElectronicTest", "DAC15 (YIN)"))
        self.dac_0.setText(_translate("ElectronicTest", "Zero"))
        self.dac_out.setText(_translate("ElectronicTest", "Output"))
        self.dac_b20.setText(_translate("ElectronicTest", "+/-10V"))
        self.dac_b10.setText(_translate("ElectronicTest", "+/-5V"))
        self.dac_b5.setText(_translate("ElectronicTest", "+/-2.5V"))
        self.dac_Iset_l.setText(_translate("ElectronicTest", "ISET"))
        self.dac_Iset_unit.setText(_translate("ElectronicTest", "V"))
        self.dac_b10_4.setText(_translate("ElectronicTest", "0V - 10V"))
        self.dac_u5.setText(_translate("ElectronicTest", "0V - 5V"))
        self.adc_G.setTitle(_translate("ElectronicTest", "ADC"))
        self.adc_ch.setItemText(0, _translate("ElectronicTest", "AIN0"))
        self.adc_ch.setItemText(1, _translate("ElectronicTest", "AIN1"))
        self.adc_ch.setItemText(2, _translate("ElectronicTest", "AIN2"))
        self.adc_ch.setItemText(3, _translate("ElectronicTest", "AIN3"))
        self.adc_ch.setItemText(4, _translate("ElectronicTest", "AIN4"))
        self.adc_ch.setItemText(5, _translate("ElectronicTest", "AIN5"))
        self.adc_ch.setItemText(6, _translate("ElectronicTest", "AIN6 (ZOUT)"))
        self.adc_ch.setItemText(7, _translate("ElectronicTest", "AIN7 (PREAMP)"))
        self.adc_in.setText(_translate("ElectronicTest", "Input"))
        self.adc_b20.setText(_translate("ElectronicTest", "+/- 10.24"))
        self.adc_b10.setText(_translate("ElectronicTest", "+/- 5.12"))
        self.adc_b5.setText(_translate("ElectronicTest", "+/- 2.56"))
        self.adc_u10.setText(_translate("ElectronicTest", "0V - 10.24V"))
        self.adc_u5.setText(_translate("ElectronicTest", "0V - 5.12V"))
        self.ygain_G.setTitle(_translate("ElectronicTest", "YIN gain"))
        self.ygain0_1.setText(_translate("ElectronicTest", "0.1"))
        self.ygain1.setText(_translate("ElectronicTest", "1.0"))
        self.ygain10.setText(_translate("ElectronicTest", "10"))
        self.dither1_G.setTitle(_translate("ElectronicTest", "Dither1"))
        self.dither1_on.setText(_translate("ElectronicTest", "ON"))
        self.dither1_off.setText(_translate("ElectronicTest", "OFF"))
        self.z1gain_G.setTitle(_translate("ElectronicTest", "Z1 gain"))
        self.z1gain1.setText(_translate("ElectronicTest", "1.0"))
        self.z1gain10.setText(_translate("ElectronicTest", "10"))
        self.z1gain0_1.setText(_translate("ElectronicTest", "0.1"))
        self.feedback_G.setTitle(_translate("ElectronicTest", "Feedback"))
        self.feedback_on.setText(_translate("ElectronicTest", "ON"))
        self.feedback_off.setText(_translate("ElectronicTest", "OFF"))
        self.z2gain_G.setTitle(_translate("ElectronicTest", "Z2 gain"))
        self.z2gain0_1.setText(_translate("ElectronicTest", "0.1"))
        self.z2gain1.setText(_translate("ElectronicTest", "1.0"))
        self.z2gain10.setText(_translate("ElectronicTest", "10"))
        self.retract_G.setTitle(_translate("ElectronicTest", "Retract"))
        self.retract_on.setText(_translate("ElectronicTest", "ON"))
        self.retract_off.setText(_translate("ElectronicTest", "OFF"))
        self.coarse_G.setTitle(_translate("ElectronicTest", "Coarse"))
        self.fine.setText(_translate("ElectronicTest", "Coarse"))
        self.coarse.setText(_translate("ElectronicTest", "Fine"))
        self.rot_G.setTitle(_translate("ElectronicTest", "ROT"))
        self.translation.setText(_translate("ElectronicTest", "Translation"))
        self.rotation.setText(_translate("ElectronicTest", "Rotation"))
        self.Etest.setTabText(self.Etest.indexOf(self.IO), _translate("ElectronicTest", "I/O"))
        self.label.setText(_translate("ElectronicTest", "Out channel"))
        self.comboBox_OutCh_RTest.setItemText(0, _translate("ElectronicTest", "0 (X IN)"))
        self.comboBox_OutCh_RTest.setItemText(1, _translate("ElectronicTest", "1 (X OFFSET)"))
        self.comboBox_OutCh_RTest.setItemText(2, _translate("ElectronicTest", "2 (Z OFFSET FINE)"))
        self.comboBox_OutCh_RTest.setItemText(3, _translate("ElectronicTest", "3 (Z OFFSET)"))
        self.comboBox_OutCh_RTest.setItemText(4, _translate("ElectronicTest", "5 (ISET)"))
        self.comboBox_OutCh_RTest.setItemText(5, _translate("ElectronicTest", "6 (DAC6)"))
        self.comboBox_OutCh_RTest.setItemText(6, _translate("ElectronicTest", "7 (DAC7)"))
        self.comboBox_OutCh_RTest.setItemText(7, _translate("ElectronicTest", "8 (DAC8)"))
        self.comboBox_OutCh_RTest.setItemText(8, _translate("ElectronicTest", "9 (DAC9)"))
        self.comboBox_OutCh_RTest.setItemText(9, _translate("ElectronicTest", "10 (ZOUTER)"))
        self.comboBox_OutCh_RTest.setItemText(10, _translate("ElectronicTest", "11 (DAC11)"))
        self.comboBox_OutCh_RTest.setItemText(11, _translate("ElectronicTest", "13 (BIAS)"))
        self.comboBox_OutCh_RTest.setItemText(12, _translate("ElectronicTest", "14 (Y OFFSET)"))
        self.comboBox_OutCh_RTest.setItemText(13, _translate("ElectronicTest", "15 (Y IN)"))
        self.comboBox_OutCh_RTest.setItemText(14, _translate("ElectronicTest", "20 (20bitDAC)"))
        self.label_2.setText(_translate("ElectronicTest", "In channel"))
        self.comboBox_InCh_RTest.setItemText(0, _translate("ElectronicTest", "0 (AIN0)"))
        self.comboBox_InCh_RTest.setItemText(1, _translate("ElectronicTest", "1 (AIN1)"))
        self.comboBox_InCh_RTest.setItemText(2, _translate("ElectronicTest", "2 (AIN2)"))
        self.comboBox_InCh_RTest.setItemText(3, _translate("ElectronicTest", "3 (AIN3)"))
        self.comboBox_InCh_RTest.setItemText(4, _translate("ElectronicTest", "4 (AIN4)"))
        self.comboBox_InCh_RTest.setItemText(5, _translate("ElectronicTest", "5 (AIN5)"))
        self.comboBox_InCh_RTest.setItemText(6, _translate("ElectronicTest", "7 (PREAMP)"))
        self.label_3.setText(_translate("ElectronicTest", "Initial value"))
        self.label_4.setText(_translate("ElectronicTest", "Final value"))
        self.label_5.setText(_translate("ElectronicTest", "Step size"))
        self.pushButton_RRread_RTest.setText(_translate("ElectronicTest", "Ramp"))
        self.Etest.setTabText(self.Etest.indexOf(self.RampTest), _translate("ElectronicTest", "Ramp test"))
        self.label_9.setText(_translate("ElectronicTest", "Voltage2"))
        self.label_7.setText(_translate("ElectronicTest", "Delay"))
        self.label_8.setText(_translate("ElectronicTest", "Vlotage1"))
        self.comboBox_Ch_SWave.setItemText(0, _translate("ElectronicTest", "0 (X IN)"))
        self.comboBox_Ch_SWave.setItemText(1, _translate("ElectronicTest", "1 (X OFFSET)"))
        self.comboBox_Ch_SWave.setItemText(2, _translate("ElectronicTest", "2 (Z OFFSET FINE)"))
        self.comboBox_Ch_SWave.setItemText(3, _translate("ElectronicTest", "3 (Z OFFSET)"))
        self.comboBox_Ch_SWave.setItemText(4, _translate("ElectronicTest", "5 (I SET)"))
        self.comboBox_Ch_SWave.setItemText(5, _translate("ElectronicTest", "6 (DAC6)"))
        self.comboBox_Ch_SWave.setItemText(6, _translate("ElectronicTest", "7 (DAC7)"))
        self.comboBox_Ch_SWave.setItemText(7, _translate("ElectronicTest", "8 (DAC8)"))
        self.comboBox_Ch_SWave.setItemText(8, _translate("ElectronicTest", "9 (DAC9)"))
        self.comboBox_Ch_SWave.setItemText(9, _translate("ElectronicTest", "10 (ZOUTER)"))
        self.comboBox_Ch_SWave.setItemText(10, _translate("ElectronicTest", "11 (DAC11)"))
        self.comboBox_Ch_SWave.setItemText(11, _translate("ElectronicTest", "13 (BIAS)"))
        self.comboBox_Ch_SWave.setItemText(12, _translate("ElectronicTest", "14 (Y OFFSET)"))
        self.comboBox_Ch_SWave.setItemText(13, _translate("ElectronicTest", "15 (Y IN)"))
        self.comboBox_Ch_SWave.setItemText(14, _translate("ElectronicTest", "20 (20bitDAC)"))
        self.label_6.setText(_translate("ElectronicTest", "Channel"))
        self.pushButton_Start_SWave.setText(_translate("ElectronicTest", "Start"))
        self.Etest.setTabText(self.Etest.indexOf(self.SquareWave), _translate("ElectronicTest", "Square wave"))
        self.radioButton_Contin_Osci.setText(_translate("ElectronicTest", "Continuous"))
        self.label_15.setText(_translate("ElectronicTest", "times"))
        self.radioButton_NSample_Osci.setText(_translate("ElectronicTest", "N sample"))
        self.pushButton_SorS_Osci.setText(_translate("ElectronicTest", "Start"))
        self.comboBox_InCh_Osci.setItemText(0, _translate("ElectronicTest", "0 (AIN0)"))
        self.comboBox_InCh_Osci.setItemText(1, _translate("ElectronicTest", "1 (AIN1)"))
        self.comboBox_InCh_Osci.setItemText(2, _translate("ElectronicTest", "2 (AIN2)"))
        self.comboBox_InCh_Osci.setItemText(3, _translate("ElectronicTest", "3 (AIN3)"))
        self.comboBox_InCh_Osci.setItemText(4, _translate("ElectronicTest", "4 (AIN4)"))
        self.comboBox_InCh_Osci.setItemText(5, _translate("ElectronicTest", "5 (AIN5)"))
        self.comboBox_InCh_Osci.setItemText(6, _translate("ElectronicTest", "7 (PREAMP)"))
        self.label_10.setText(_translate("ElectronicTest", "Input channel"))
        self.label_13.setText(_translate("ElectronicTest", "# of samples"))
        self.label_14.setText(_translate("ElectronicTest", "Average"))
        self.label_12.setText(_translate("ElectronicTest", "us"))
        self.label_11.setText(_translate("ElectronicTest", "Delay"))
        self.Etest.setTabText(self.Etest.indexOf(self.Oscilloscope), _translate("ElectronicTest", "Oscilloscope"))
        self.pushButton_Query_Echo.setText(_translate("ElectronicTest", "Query"))
        self.Etest.setTabText(self.Etest.indexOf(self.Echo), _translate("ElectronicTest", "Echo"))
        self.comboBox_InCh_FTest.setItemText(0, _translate("ElectronicTest", "0 (AIN0)"))
        self.comboBox_InCh_FTest.setItemText(1, _translate("ElectronicTest", "1 (AIN1)"))
        self.comboBox_InCh_FTest.setItemText(2, _translate("ElectronicTest", "2 (AIN2)"))
        self.comboBox_InCh_FTest.setItemText(3, _translate("ElectronicTest", "3 (AIN3)"))
        self.comboBox_InCh_FTest.setItemText(4, _translate("ElectronicTest", "4 (AIN4)"))
        self.pushButton_Start_FTest.setText(_translate("ElectronicTest", "Start"))
        self.label_16.setText(_translate("ElectronicTest", "A"))
        self.label_21.setText(_translate("ElectronicTest", "I setpoint"))
        self.label_20.setText(_translate("ElectronicTest", "Input"))
        self.label_19.setText(_translate("ElectronicTest", "Output"))
        self.label_18.setText(_translate("ElectronicTest", "Delay"))
        self.comboBox_OutCh_FTest.setItemText(0, _translate("ElectronicTest", "6 (DAC6)"))
        self.comboBox_OutCh_FTest.setItemText(1, _translate("ElectronicTest", "7 (DAC7)"))
        self.comboBox_OutCh_FTest.setItemText(2, _translate("ElectronicTest", "8 (DAC8)"))
        self.comboBox_OutCh_FTest.setItemText(3, _translate("ElectronicTest", "9 (DAC9)"))
        self.comboBox_OutCh_FTest.setItemText(4, _translate("ElectronicTest", "11 (DAC11)"))
        self.label_17.setText(_translate("ElectronicTest", "Z0"))
        self.Etest.setTabText(self.Etest.indexOf(self.FeedbackTest), _translate("ElectronicTest", "Feedback test"))
import logo_rc
