# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainMenu.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HoGroupSTM(object):
    def setupUi(self, HoGroupSTM):
        HoGroupSTM.setObjectName("HoGroupSTM")
        HoGroupSTM.setEnabled(True)
        HoGroupSTM.resize(600, 226)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(HoGroupSTM.sizePolicy().hasHeightForWidth())
        HoGroupSTM.setSizePolicy(sizePolicy)
        HoGroupSTM.setMinimumSize(QtCore.QSize(600, 160))
        font = QtGui.QFont()
        font.setPointSize(9)
        HoGroupSTM.setFont(font)
        HoGroupSTM.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/STMlogo_NiCp2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/logo/STMlogo_blackhole.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/logo/STMlogo_NiCp2.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/logo/STMlogo_blackhole.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/logo/STMlogo_NiCp2.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/logo/STMlogo_blackhole.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        HoGroupSTM.setWindowIcon(icon)
        HoGroupSTM.setWindowOpacity(1.0)
        HoGroupSTM.setAutoFillBackground(True)
        HoGroupSTM.setDockNestingEnabled(False)
        HoGroupSTM.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(HoGroupSTM)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_11.addWidget(self.label_4, 4, 0, 1, 1)
        self.versionLabel = QtWidgets.QLabel(self.widget_3)
        self.versionLabel.setObjectName("versionLabel")
        self.gridLayout_11.addWidget(self.versionLabel, 4, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_11.addWidget(self.label_6, 7, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_11.addWidget(self.label_3, 1, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(40, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem, 5, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem1, 2, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_11.addWidget(self.label_2, 7, 0, 1, 1)
        self.gridLayout_10.addWidget(self.widget_3, 0, 0, 1, 1)
        HoGroupSTM.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(HoGroupSTM)
        self.statusbar.setObjectName("statusbar")
        HoGroupSTM.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(HoGroupSTM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        HoGroupSTM.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar = QtWidgets.QMenuBar(HoGroupSTM)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTip_Approach = QtWidgets.QMenu(self.menubar)
        self.menuTip_Approach.setObjectName("menuTip_Approach")
        self.menuScan = QtWidgets.QMenu(self.menubar)
        self.menuScan.setObjectName("menuScan")
        self.menuControl = QtWidgets.QMenu(self.menubar)
        self.menuControl.setObjectName("menuControl")
        self.menuTest = QtWidgets.QMenu(self.menubar)
        self.menuTest.setSeparatorsCollapsible(False)
        self.menuTest.setToolTipsVisible(False)
        self.menuTest.setObjectName("menuTest")
        self.menuData_Manipulation = QtWidgets.QMenu(self.menubar)
        self.menuData_Manipulation.setObjectName("menuData_Manipulation")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        HoGroupSTM.setMenuBar(self.menubar)
        self.Zcontrol = QtWidgets.QDockWidget(HoGroupSTM)
        self.Zcontrol.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Zcontrol.sizePolicy().hasHeightForWidth())
        self.Zcontrol.setSizePolicy(sizePolicy)
        self.Zcontrol.setMinimumSize(QtCore.QSize(470, 492))
        self.Zcontrol.setFloating(True)
        self.Zcontrol.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.Zcontrol.setAllowedAreas(QtCore.Qt.NoDockWidgetArea)
        self.Zcontrol.setObjectName("Zcontrol")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_Zoffset_Zcontrol = QtWidgets.QGroupBox(self.dockWidgetContents_3)
        self.groupBox_Zoffset_Zcontrol.setFlat(False)
        self.groupBox_Zoffset_Zcontrol.setObjectName("groupBox_Zoffset_Zcontrol")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_Zoffset_Zcontrol)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollBar_Input_Zoffset = QtWidgets.QScrollBar(self.groupBox_Zoffset_Zcontrol)
        self.scrollBar_Input_Zoffset.setMinimum(-32768)
        self.scrollBar_Input_Zoffset.setMaximum(32767)
        self.scrollBar_Input_Zoffset.setProperty("value", -32768)
        self.scrollBar_Input_Zoffset.setOrientation(QtCore.Qt.Horizontal)
        self.scrollBar_Input_Zoffset.setObjectName("scrollBar_Input_Zoffset")
        self.gridLayout_4.addWidget(self.scrollBar_Input_Zoffset, 2, 0, 1, 10)
        self.pushButton_Zauto_Zoffset = QtWidgets.QPushButton(self.groupBox_Zoffset_Zcontrol)
        self.pushButton_Zauto_Zoffset.setEnabled(False)
        self.pushButton_Zauto_Zoffset.setIconSize(QtCore.QSize(16, 9))
        self.pushButton_Zauto_Zoffset.setObjectName("pushButton_Zauto_Zoffset")
        self.gridLayout_4.addWidget(self.pushButton_Zauto_Zoffset, 0, 8, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 1, 6, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 1, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 1, 9, 1, 1)
        self.pushButton_HardRetract_Zoffset = QtWidgets.QPushButton(self.groupBox_Zoffset_Zcontrol)
        self.pushButton_HardRetract_Zoffset.setEnabled(False)
        self.pushButton_HardRetract_Zoffset.setObjectName("pushButton_HardRetract_Zoffset")
        self.gridLayout_4.addWidget(self.pushButton_HardRetract_Zoffset, 0, 9, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 1, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 1, 4, 1, 1)
        self.pushButton_Send_Zoffset = QtWidgets.QPushButton(self.groupBox_Zoffset_Zcontrol)
        self.pushButton_Send_Zoffset.setEnabled(False)
        self.pushButton_Send_Zoffset.setObjectName("pushButton_Send_Zoffset")
        self.gridLayout_4.addWidget(self.pushButton_Send_Zoffset, 2, 10, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem8, 1, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 1, 8, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem10, 1, 7, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem11, 1, 10, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem12, 1, 5, 1, 1)
        self.spinBox_Input_Zoffset = QtWidgets.QSpinBox(self.groupBox_Zoffset_Zcontrol)
        self.spinBox_Input_Zoffset.setMinimum(-32768)
        self.spinBox_Input_Zoffset.setMaximum(32767)
        self.spinBox_Input_Zoffset.setObjectName("spinBox_Input_Zoffset")
        self.gridLayout_4.addWidget(self.spinBox_Input_Zoffset, 0, 0, 1, 4)
        self.spinBox_Indication_Zoffset = QtWidgets.QSpinBox(self.groupBox_Zoffset_Zcontrol)
        self.spinBox_Indication_Zoffset.setEnabled(False)
        self.spinBox_Indication_Zoffset.setMinimum(-32768)
        self.spinBox_Indication_Zoffset.setMaximum(32767)
        self.spinBox_Indication_Zoffset.setObjectName("spinBox_Indication_Zoffset")
        self.gridLayout_4.addWidget(self.spinBox_Indication_Zoffset, 0, 4, 1, 4)
        self.verticalLayout.addWidget(self.groupBox_Zoffset_Zcontrol)
        self.groupBox_Zoffsetfine_Zcontrol = QtWidgets.QGroupBox(self.dockWidgetContents_3)
        self.groupBox_Zoffsetfine_Zcontrol.setFlat(False)
        self.groupBox_Zoffsetfine_Zcontrol.setObjectName("groupBox_Zoffsetfine_Zcontrol")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_Zoffsetfine_Zcontrol)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget = QtWidgets.QWidget(self.groupBox_Zoffsetfine_Zcontrol)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem13 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem13, 3, 11, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem14, 3, 9, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem15, 3, 7, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem16, 3, 10, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem17, 3, 6, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem18, 3, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem19, 3, 13, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem20, 3, 1, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem21, 3, 2, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem22, 3, 3, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem23, 3, 12, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem24, 3, 8, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem25, 3, 5, 1, 1)
        self.pushButton_Advance_Zoffsetfine = QtWidgets.QPushButton(self.widget)
        self.pushButton_Advance_Zoffsetfine.setEnabled(False)
        self.pushButton_Advance_Zoffsetfine.setObjectName("pushButton_Advance_Zoffsetfine")
        self.gridLayout_3.addWidget(self.pushButton_Advance_Zoffsetfine, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 4, 1, 1)
        self.spinBox_AdvInput_Zoffsetfine = QtWidgets.QSpinBox(self.widget)
        self.spinBox_AdvInput_Zoffsetfine.setMinimum(-32768)
        self.spinBox_AdvInput_Zoffsetfine.setMaximum(32767)
        self.spinBox_AdvInput_Zoffsetfine.setObjectName("spinBox_AdvInput_Zoffsetfine")
        self.gridLayout_3.addWidget(self.spinBox_AdvInput_Zoffsetfine, 0, 1, 1, 3)
        self.pushButton_Zero_Zoffsetfine = QtWidgets.QPushButton(self.widget)
        self.pushButton_Zero_Zoffsetfine.setEnabled(False)
        self.pushButton_Zero_Zoffsetfine.setObjectName("pushButton_Zero_Zoffsetfine")
        self.gridLayout_3.addWidget(self.pushButton_Zero_Zoffsetfine, 0, 7, 1, 1)
        self.pushButton_MatchCurrent_Zoffsetfine = QtWidgets.QPushButton(self.widget)
        self.pushButton_MatchCurrent_Zoffsetfine.setEnabled(False)
        self.pushButton_MatchCurrent_Zoffsetfine.setObjectName("pushButton_MatchCurrent_Zoffsetfine")
        self.gridLayout_3.addWidget(self.pushButton_MatchCurrent_Zoffsetfine, 0, 8, 1, 6)
        self.verticalLayout_6.addWidget(self.widget)
        self.gridLayout_14.addLayout(self.verticalLayout_6, 1, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem26 = QtWidgets.QSpacerItem(40, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem26, 1, 2, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(40, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem27, 1, 0, 1, 1)
        self.spinBox_Input_Zoffsetfine = QtWidgets.QSpinBox(self.groupBox_Zoffsetfine_Zcontrol)
        self.spinBox_Input_Zoffsetfine.setEnabled(False)
        self.spinBox_Input_Zoffsetfine.setMinimum(-32768)
        self.spinBox_Input_Zoffsetfine.setMaximum(32767)
        self.spinBox_Input_Zoffsetfine.setObjectName("spinBox_Input_Zoffsetfine")
        self.gridLayout_5.addWidget(self.spinBox_Input_Zoffsetfine, 0, 0, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(40, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem28, 1, 3, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(40, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem29, 1, 1, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(40, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem30, 1, 4, 1, 1)
        self.slider_Input_Zoffsetfine = QtWidgets.QSlider(self.groupBox_Zoffsetfine_Zcontrol)
        self.slider_Input_Zoffsetfine.setEnabled(False)
        self.slider_Input_Zoffsetfine.setMinimum(-32768)
        self.slider_Input_Zoffsetfine.setMaximum(32767)
        self.slider_Input_Zoffsetfine.setOrientation(QtCore.Qt.Horizontal)
        self.slider_Input_Zoffsetfine.setObjectName("slider_Input_Zoffsetfine")
        self.gridLayout_5.addWidget(self.slider_Input_Zoffsetfine, 0, 1, 1, 4)
        self.gridLayout_14.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_Zoffsetfine_Zcontrol)
        self.widget_7 = QtWidgets.QWidget(self.dockWidgetContents_3)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_Feedack_Zcontrol = QtWidgets.QGroupBox(self.widget_7)
        self.groupBox_Feedack_Zcontrol.setEnabled(True)
        self.groupBox_Feedack_Zcontrol.setObjectName("groupBox_Feedack_Zcontrol")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_Feedack_Zcontrol)
        self.verticalLayout_4.setContentsMargins(20, 5, -1, 5)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radioButton_ON_Feedback = QtWidgets.QRadioButton(self.groupBox_Feedack_Zcontrol)
        self.radioButton_ON_Feedback.setChecked(True)
        self.radioButton_ON_Feedback.setObjectName("radioButton_ON_Feedback")
        self.verticalLayout_4.addWidget(self.radioButton_ON_Feedback)
        self.radioButton_OFF_Feedback = QtWidgets.QRadioButton(self.groupBox_Feedack_Zcontrol)
        self.radioButton_OFF_Feedback.setObjectName("radioButton_OFF_Feedback")
        self.verticalLayout_4.addWidget(self.radioButton_OFF_Feedback)
        self.horizontalLayout_2.addWidget(self.groupBox_Feedack_Zcontrol)
        self.groupBox_Retract_Zcontrol = QtWidgets.QGroupBox(self.widget_7)
        self.groupBox_Retract_Zcontrol.setEnabled(True)
        self.groupBox_Retract_Zcontrol.setObjectName("groupBox_Retract_Zcontrol")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_Retract_Zcontrol)
        self.verticalLayout_5.setContentsMargins(20, 5, -1, 5)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.radioButton_ON_Retract = QtWidgets.QRadioButton(self.groupBox_Retract_Zcontrol)
        self.radioButton_ON_Retract.setObjectName("radioButton_ON_Retract")
        self.verticalLayout_5.addWidget(self.radioButton_ON_Retract)
        self.radioButton_OFF_Retract = QtWidgets.QRadioButton(self.groupBox_Retract_Zcontrol)
        self.radioButton_OFF_Retract.setChecked(True)
        self.radioButton_OFF_Retract.setObjectName("radioButton_OFF_Retract")
        self.verticalLayout_5.addWidget(self.radioButton_OFF_Retract)
        self.horizontalLayout_2.addWidget(self.groupBox_Retract_Zcontrol)
        self.groupBox_Dither_Zcontrol = QtWidgets.QGroupBox(self.widget_7)
        self.groupBox_Dither_Zcontrol.setEnabled(True)
        self.groupBox_Dither_Zcontrol.setObjectName("groupBox_Dither_Zcontrol")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_Dither_Zcontrol)
        self.verticalLayout_7.setContentsMargins(20, 5, -1, 5)
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.radioButton_ON_ZDither = QtWidgets.QRadioButton(self.groupBox_Dither_Zcontrol)
        self.radioButton_ON_ZDither.setObjectName("radioButton_ON_ZDither")
        self.verticalLayout_7.addWidget(self.radioButton_ON_ZDither)
        self.radioButton_OFF_ZDither = QtWidgets.QRadioButton(self.groupBox_Dither_Zcontrol)
        self.radioButton_OFF_ZDither.setChecked(True)
        self.radioButton_OFF_ZDither.setObjectName("radioButton_OFF_ZDither")
        self.verticalLayout_7.addWidget(self.radioButton_OFF_ZDither)
        self.horizontalLayout_2.addWidget(self.groupBox_Dither_Zcontrol)
        self.verticalLayout.addWidget(self.widget_7)
        self.groupBox_Gain_Zcontrol = QtWidgets.QGroupBox(self.dockWidgetContents_3)
        self.groupBox_Gain_Zcontrol.setEnabled(True)
        self.groupBox_Gain_Zcontrol.setFlat(False)
        self.groupBox_Gain_Zcontrol.setObjectName("groupBox_Gain_Zcontrol")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_Gain_Zcontrol)
        self.verticalLayout_2.setContentsMargins(9, 5, 9, 9)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_Z1gain_Zcontrol = QtWidgets.QWidget(self.groupBox_Gain_Zcontrol)
        self.widget_Z1gain_Zcontrol.setObjectName("widget_Z1gain_Zcontrol")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_Z1gain_Zcontrol)
        self.horizontalLayout_3.setContentsMargins(11, 0, 11, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_Z1gain_Gain = QtWidgets.QLabel(self.widget_Z1gain_Zcontrol)
        self.label_Z1gain_Gain.setObjectName("label_Z1gain_Gain")
        self.horizontalLayout_3.addWidget(self.label_Z1gain_Gain)
        self.radioButton_Z1gain01_Gain = QtWidgets.QRadioButton(self.widget_Z1gain_Zcontrol)
        self.radioButton_Z1gain01_Gain.setEnabled(True)
        self.radioButton_Z1gain01_Gain.setChecked(True)
        self.radioButton_Z1gain01_Gain.setObjectName("radioButton_Z1gain01_Gain")
        self.horizontalLayout_3.addWidget(self.radioButton_Z1gain01_Gain)
        self.radioButton_Z1gain1_Gain = QtWidgets.QRadioButton(self.widget_Z1gain_Zcontrol)
        self.radioButton_Z1gain1_Gain.setEnabled(True)
        self.radioButton_Z1gain1_Gain.setObjectName("radioButton_Z1gain1_Gain")
        self.horizontalLayout_3.addWidget(self.radioButton_Z1gain1_Gain)
        self.radioButton_Z1gain10_Gain = QtWidgets.QRadioButton(self.widget_Z1gain_Zcontrol)
        self.radioButton_Z1gain10_Gain.setEnabled(True)
        self.radioButton_Z1gain10_Gain.setObjectName("radioButton_Z1gain10_Gain")
        self.horizontalLayout_3.addWidget(self.radioButton_Z1gain10_Gain)
        self.verticalLayout_2.addWidget(self.widget_Z1gain_Zcontrol)
        self.widget_Z2gain_Zcontrol = QtWidgets.QWidget(self.groupBox_Gain_Zcontrol)
        self.widget_Z2gain_Zcontrol.setObjectName("widget_Z2gain_Zcontrol")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_Z2gain_Zcontrol)
        self.horizontalLayout_4.setContentsMargins(11, 0, 11, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_Z2gain_Gain = QtWidgets.QLabel(self.widget_Z2gain_Zcontrol)
        self.label_Z2gain_Gain.setEnabled(True)
        self.label_Z2gain_Gain.setObjectName("label_Z2gain_Gain")
        self.horizontalLayout_4.addWidget(self.label_Z2gain_Gain)
        self.radioButton_Z2gain01_Gain = QtWidgets.QRadioButton(self.widget_Z2gain_Zcontrol)
        self.radioButton_Z2gain01_Gain.setEnabled(True)
        self.radioButton_Z2gain01_Gain.setObjectName("radioButton_Z2gain01_Gain")
        self.horizontalLayout_4.addWidget(self.radioButton_Z2gain01_Gain)
        self.radioButton_Z2gain1_Gain = QtWidgets.QRadioButton(self.widget_Z2gain_Zcontrol)
        self.radioButton_Z2gain1_Gain.setEnabled(True)
        self.radioButton_Z2gain1_Gain.setObjectName("radioButton_Z2gain1_Gain")
        self.horizontalLayout_4.addWidget(self.radioButton_Z2gain1_Gain)
        self.radioButton_Z2gain10_Gain = QtWidgets.QRadioButton(self.widget_Z2gain_Zcontrol)
        self.radioButton_Z2gain10_Gain.setEnabled(True)
        self.radioButton_Z2gain10_Gain.setChecked(True)
        self.radioButton_Z2gain10_Gain.setObjectName("radioButton_Z2gain10_Gain")
        self.horizontalLayout_4.addWidget(self.radioButton_Z2gain10_Gain)
        self.verticalLayout_2.addWidget(self.widget_Z2gain_Zcontrol)
        self.verticalLayout.addWidget(self.groupBox_Gain_Zcontrol)
        self.Zcontrol.setWidget(self.dockWidgetContents_3)
        HoGroupSTM.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.Zcontrol)
        self.Bias = QtWidgets.QDockWidget(HoGroupSTM)
        self.Bias.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bias.sizePolicy().hasHeightForWidth())
        self.Bias.setSizePolicy(sizePolicy)
        self.Bias.setMinimumSize(QtCore.QSize(436, 470))
        self.Bias.setAcceptDrops(False)
        self.Bias.setFloating(True)
        self.Bias.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.Bias.setAllowedAreas(QtCore.Qt.NoDockWidgetArea)
        self.Bias.setObjectName("Bias")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox_Ramp_Bias = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox_Ramp_Bias.setEnabled(True)
        self.groupBox_Ramp_Bias.setObjectName("groupBox_Ramp_Bias")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_Ramp_Bias)
        self.gridLayout.setContentsMargins(-1, 5, -1, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_Rampto7_BiasRamp = QtWidgets.QPushButton(self.groupBox_Ramp_Bias)
        self.pushButton_Rampto7_BiasRamp.setEnabled(False)
        self.pushButton_Rampto7_BiasRamp.setObjectName("pushButton_Rampto7_BiasRamp")
        self.gridLayout.addWidget(self.pushButton_Rampto7_BiasRamp, 3, 5, 1, 1)
        self.spinBox_Input4_BiasRamp = QtWidgets.QDoubleSpinBox(self.groupBox_Ramp_Bias)
        self.spinBox_Input4_BiasRamp.setEnabled(True)
        self.spinBox_Input4_BiasRamp.setDecimals(4)
        self.spinBox_Input4_BiasRamp.setMinimum(-5.0)
        self.spinBox_Input4_BiasRamp.setMaximum(5.0)
        self.spinBox_Input4_BiasRamp.setObjectName("spinBox_Input4_BiasRamp")
        self.gridLayout.addWidget(self.spinBox_Input4_BiasRamp, 4, 1, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem31, 0, 0, 1, 1)
        self.pushButton_Rampto4_BiasRamp = QtWidgets.QPushButton(self.groupBox_Ramp_Bias)
        self.pushButton_Rampto4_BiasRamp.setEnabled(False)
        self.pushButton_Rampto4_BiasRamp.setObjectName("pushButton_Rampto4_BiasRamp")
        self.gridLayout.addWidget(self.pushButton_Rampto4_BiasRamp, 4, 0, 1, 1)
        self.spinBox_Input7_BiasRamp = QtWidgets.QDoubleSpinBox(self.groupBox_Ramp_Bias)
        self.spinBox_Input7_BiasRamp.setDecimals(4)
        self.spinBox_Input7_BiasRamp.setMinimum(-5.0)
        self.spinBox_Input7_BiasRamp.setMaximum(5.0)
        self.spinBox_Input7_BiasRamp.setObjectName("spinBox_Input7_BiasRamp")
        self.gridLayout.addWidget(self.spinBox_Input7_BiasRamp, 3, 6, 1, 1)
        self.pushButton_Rampto2_BiasRamp = QtWidgets.QPushButton(self.groupBox_Ramp_Bias)
        self.pushButton_Rampto2_BiasRamp.setEnabled(False)
        self.pushButton_Rampto2_BiasRamp.setObjectName("pushButton_Rampto2_BiasRamp")
        self.gridLayout.addWidget(self.pushButton_Rampto2_BiasRamp, 2, 0, 1, 1)
        self.spinBox_Input3_BiasRamp = QtWidgets.QDoubleSpinBox(self.groupBox_Ramp_Bias)
        self.spinBox_Input3_BiasRamp.setEnabled(True)
        self.spinBox_Input3_BiasRamp.setDecimals(4)
        self.spinBox_Input3_BiasRamp.setMinimum(-5.0)
        self.spinBox_Input3_BiasRamp.setMaximum(5.0)
        self.spinBox_Input3_BiasRamp.setObjectName("spinBox_Input3_BiasRamp")
        self.gridLayout.addWidget(self.spinBox_Input3_BiasRamp, 3, 1, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem32, 0, 1, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem33, 0, 2, 1, 1)
        self.pushButton_Rampto1_BiasRamp = QtWidgets.QPushButton(self.groupBox_Ramp_Bias)
        self.pushButton_Rampto1_BiasRamp.setEnabled(False)
        self.pushButton_Rampto1_BiasRamp.setObjectName("pushButton_Rampto1_BiasRamp")
        self.gridLayout.addWidget(self.pushButton_Rampto1_BiasRamp, 1, 0, 1, 1)
        self.pushButton_Rampto8_BiasRamp = QtWidgets.QPushButton(self.groupBox_Ramp_Bias)
        self.pushButton_Rampto8_BiasRamp.setEnabled(False)
        self.pushButton_Rampto8_BiasRamp.setObjectName("pushButton_Rampto8_BiasRamp")
        self.gridLayout.addWidget(self.pushButton_Rampto8_BiasRamp, 4, 5, 1, 1)
        spacerItem34 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem34, 0, 6, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_Ramp_Bias)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 5, 6, 1, 1)
        self.spinBox_Input8_BiasRamp = QtWidgets.QDoubleSpinBox(self.groupBox_Ramp_Bias)
        self.spinBox_Input8_BiasRamp.setDecimals(4)
        self.spinBox_Input8_BiasRamp.setMinimum(-5.0)
        self.spinBox_Input8_BiasRamp.setMaximum(5.0)
        self.spinBox_Input8_BiasRamp.setObjectName("spinBox_Input8_BiasRamp")
        self.gridLayout.addWidget(self.spinBox_Input8_BiasRamp, 4, 6, 1, 1)
        self.spinBox_SpeedInput_BiasRamp = QtWidgets.QSpinBox(self.groupBox_Ramp_Bias)
        self.spinBox_SpeedInput_BiasRamp.setObjectName("spinBox_SpeedInput_BiasRamp")
        self.gridLayout.addWidget(self.spinBox_SpeedInput_BiasRamp, 5, 5, 1, 1)
        self.pushButton_Rampto6_BiasRamp = QtWidgets.QPushButton(self.groupBox_Ramp_Bias)
        self.pushButton_Rampto6_BiasRamp.setEnabled(False)
        self.pushButton_Rampto6_BiasRamp.setObjectName("pushButton_Rampto6_BiasRamp")
        self.gridLayout.addWidget(self.pushButton_Rampto6_BiasRamp, 2, 5, 1, 1)
        self.spinBox_Input2_BiasRamp = QtWidgets.QDoubleSpinBox(self.groupBox_Ramp_Bias)
        self.spinBox_Input2_BiasRamp.setEnabled(True)
        self.spinBox_Input2_BiasRamp.setDecimals(4)
        self.spinBox_Input2_BiasRamp.setMinimum(-5.0)
        self.spinBox_Input2_BiasRamp.setMaximum(5.0)
        self.spinBox_Input2_BiasRamp.setObjectName("spinBox_Input2_BiasRamp")
        self.gridLayout.addWidget(self.spinBox_Input2_BiasRamp, 2, 1, 1, 1)
        self.pushButton_StopRamp_BiasRamp = QtWidgets.QPushButton(self.groupBox_Ramp_Bias)
        self.pushButton_StopRamp_BiasRamp.setEnabled(False)
        self.pushButton_StopRamp_BiasRamp.setObjectName("pushButton_StopRamp_BiasRamp")
        self.gridLayout.addWidget(self.pushButton_StopRamp_BiasRamp, 5, 0, 1, 1)
        self.spinBox_Input5_BiasRamp = QtWidgets.QDoubleSpinBox(self.groupBox_Ramp_Bias)
        self.spinBox_Input5_BiasRamp.setDecimals(4)
        self.spinBox_Input5_BiasRamp.setMinimum(-5.0)
        self.spinBox_Input5_BiasRamp.setMaximum(5.0)
        self.spinBox_Input5_BiasRamp.setObjectName("spinBox_Input5_BiasRamp")
        self.gridLayout.addWidget(self.spinBox_Input5_BiasRamp, 1, 6, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem35, 0, 3, 1, 1)
        self.spinBox_Input6_BiasRamp = QtWidgets.QDoubleSpinBox(self.groupBox_Ramp_Bias)
        self.spinBox_Input6_BiasRamp.setDecimals(4)
        self.spinBox_Input6_BiasRamp.setMinimum(-5.0)
        self.spinBox_Input6_BiasRamp.setMaximum(5.0)
        self.spinBox_Input6_BiasRamp.setObjectName("spinBox_Input6_BiasRamp")
        self.gridLayout.addWidget(self.spinBox_Input6_BiasRamp, 2, 6, 1, 1)
        self.spinBox_Input1_BiasRamp = QtWidgets.QDoubleSpinBox(self.groupBox_Ramp_Bias)
        self.spinBox_Input1_BiasRamp.setEnabled(True)
        self.spinBox_Input1_BiasRamp.setDecimals(4)
        self.spinBox_Input1_BiasRamp.setMinimum(-5.0)
        self.spinBox_Input1_BiasRamp.setMaximum(5.0)
        self.spinBox_Input1_BiasRamp.setObjectName("spinBox_Input1_BiasRamp")
        self.gridLayout.addWidget(self.spinBox_Input1_BiasRamp, 1, 1, 1, 1)
        self.pushButton_Rampto5_BiasRamp = QtWidgets.QPushButton(self.groupBox_Ramp_Bias)
        self.pushButton_Rampto5_BiasRamp.setEnabled(False)
        self.pushButton_Rampto5_BiasRamp.setObjectName("pushButton_Rampto5_BiasRamp")
        self.gridLayout.addWidget(self.pushButton_Rampto5_BiasRamp, 1, 5, 1, 1)
        self.pushButton_Rampto3_BiasRamp = QtWidgets.QPushButton(self.groupBox_Ramp_Bias)
        self.pushButton_Rampto3_BiasRamp.setEnabled(False)
        self.pushButton_Rampto3_BiasRamp.setObjectName("pushButton_Rampto3_BiasRamp")
        self.gridLayout.addWidget(self.pushButton_Rampto3_BiasRamp, 3, 0, 1, 1)
        spacerItem36 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem36, 0, 5, 1, 1)
        spacerItem37 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem37, 0, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_Ramp_Bias)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 5, 1, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_Ramp_Bias, 2, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.dockWidgetContents)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_Dither_Bias = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_Dither_Bias.setEnabled(True)
        self.groupBox_Dither_Bias.setObjectName("groupBox_Dither_Bias")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_Dither_Bias)
        self.gridLayout_12.setContentsMargins(20, 5, 20, 5)
        self.gridLayout_12.setVerticalSpacing(6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.radioButton_ON_BiasDither = QtWidgets.QRadioButton(self.groupBox_Dither_Bias)
        self.radioButton_ON_BiasDither.setObjectName("radioButton_ON_BiasDither")
        self.gridLayout_12.addWidget(self.radioButton_ON_BiasDither, 0, 0, 1, 1)
        self.radioButton_OFF_BiasDither = QtWidgets.QRadioButton(self.groupBox_Dither_Bias)
        self.radioButton_OFF_BiasDither.setChecked(True)
        self.radioButton_OFF_BiasDither.setObjectName("radioButton_OFF_BiasDither")
        self.gridLayout_12.addWidget(self.radioButton_OFF_BiasDither, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_Dither_Bias)
        self.groupBox_DAC_Bias = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_DAC_Bias.setObjectName("groupBox_DAC_Bias")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_DAC_Bias)
        self.gridLayout_19.setContentsMargins(20, 5, 20, 5)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.radioButton_20bit_DAC = QtWidgets.QRadioButton(self.groupBox_DAC_Bias)
        self.radioButton_20bit_DAC.setObjectName("radioButton_20bit_DAC")
        self.gridLayout_19.addWidget(self.radioButton_20bit_DAC, 0, 0, 1, 1)
        self.radioButton_16bit_DAC = QtWidgets.QRadioButton(self.groupBox_DAC_Bias)
        self.radioButton_16bit_DAC.setChecked(True)
        self.radioButton_16bit_DAC.setObjectName("radioButton_16bit_DAC")
        self.gridLayout_19.addWidget(self.radioButton_16bit_DAC, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_DAC_Bias)
        self.gridLayout_8.addWidget(self.widget_2, 3, 0, 1, 1)
        self.groupBox_Bias_Bias = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox_Bias_Bias.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Bias_Bias.sizePolicy().hasHeightForWidth())
        self.groupBox_Bias_Bias.setSizePolicy(sizePolicy)
        self.groupBox_Bias_Bias.setObjectName("groupBox_Bias_Bias")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_Bias_Bias)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.scrollBar_Input_Bias = QtWidgets.QScrollBar(self.groupBox_Bias_Bias)
        self.scrollBar_Input_Bias.setEnabled(True)
        self.scrollBar_Input_Bias.setMaximum(1048575)
        self.scrollBar_Input_Bias.setOrientation(QtCore.Qt.Horizontal)
        self.scrollBar_Input_Bias.setObjectName("scrollBar_Input_Bias")
        self.gridLayout_7.addWidget(self.scrollBar_Input_Bias, 0, 1, 1, 1)
        spacerItem38 = QtWidgets.QSpacerItem(40, 9, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem38, 1, 1, 1, 1)
        self.spinBox_Input_Bias = QtWidgets.QDoubleSpinBox(self.groupBox_Bias_Bias)
        self.spinBox_Input_Bias.setEnabled(True)
        self.spinBox_Input_Bias.setDecimals(6)
        self.spinBox_Input_Bias.setMinimum(-5.0)
        self.spinBox_Input_Bias.setMaximum(5.0)
        self.spinBox_Input_Bias.setObjectName("spinBox_Input_Bias")
        self.gridLayout_7.addWidget(self.spinBox_Input_Bias, 0, 0, 1, 1)
        self.pushButton_Filp_Bias = QtWidgets.QPushButton(self.groupBox_Bias_Bias)
        self.pushButton_Filp_Bias.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Filp_Bias.sizePolicy().hasHeightForWidth())
        self.pushButton_Filp_Bias.setSizePolicy(sizePolicy)
        self.pushButton_Filp_Bias.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButton_Filp_Bias.setObjectName("pushButton_Filp_Bias")
        self.gridLayout_7.addWidget(self.pushButton_Filp_Bias, 0, 2, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_Bias_Bias, 0, 0, 1, 1)
        self.groupBox_Range_Bias = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox_Range_Bias.setEnabled(True)
        self.groupBox_Range_Bias.setFlat(False)
        self.groupBox_Range_Bias.setCheckable(False)
        self.groupBox_Range_Bias.setChecked(False)
        self.groupBox_Range_Bias.setObjectName("groupBox_Range_Bias")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox_Range_Bias)
        self.gridLayout_20.setContentsMargins(20, 5, 9, 9)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.radioButton_25_Range = QtWidgets.QRadioButton(self.groupBox_Range_Bias)
        self.radioButton_25_Range.setObjectName("radioButton_25_Range")
        self.gridLayout_20.addWidget(self.radioButton_25_Range, 0, 0, 1, 1)
        self.radioButton_5_Range = QtWidgets.QRadioButton(self.groupBox_Range_Bias)
        self.radioButton_5_Range.setChecked(True)
        self.radioButton_5_Range.setObjectName("radioButton_5_Range")
        self.gridLayout_20.addWidget(self.radioButton_5_Range, 0, 1, 1, 1)
        self.radioButton_10_Range = QtWidgets.QRadioButton(self.groupBox_Range_Bias)
        self.radioButton_10_Range.setObjectName("radioButton_10_Range")
        self.gridLayout_20.addWidget(self.radioButton_10_Range, 0, 2, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_Range_Bias, 10, 0, 1, 1)
        self.Bias.setWidget(self.dockWidgetContents)
        HoGroupSTM.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.Bias)
        self.Current = QtWidgets.QDockWidget(HoGroupSTM)
        self.Current.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Current.sizePolicy().hasHeightForWidth())
        self.Current.setSizePolicy(sizePolicy)
        self.Current.setMinimumSize(QtCore.QSize(442, 360))
        self.Current.setAcceptDrops(False)
        self.Current.setFloating(True)
        self.Current.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.Current.setAllowedAreas(QtCore.Qt.NoDockWidgetArea)
        self.Current.setObjectName("Current")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_Setpoint_Current = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.groupBox_Setpoint_Current.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Setpoint_Current.sizePolicy().hasHeightForWidth())
        self.groupBox_Setpoint_Current.setSizePolicy(sizePolicy)
        self.groupBox_Setpoint_Current.setObjectName("groupBox_Setpoint_Current")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_Setpoint_Current)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label = QtWidgets.QLabel(self.groupBox_Setpoint_Current)
        self.label.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(True)
        self.label.setWordWrap(True)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 1, 1, 1)
        self.spinBox_Input_Setpoint = QtWidgets.QDoubleSpinBox(self.groupBox_Setpoint_Current)
        self.spinBox_Input_Setpoint.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_Input_Setpoint.sizePolicy().hasHeightForWidth())
        self.spinBox_Input_Setpoint.setSizePolicy(sizePolicy)
        self.spinBox_Input_Setpoint.setWrapping(True)
        self.spinBox_Input_Setpoint.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_Input_Setpoint.setProperty("showGroupSeparator", False)
        self.spinBox_Input_Setpoint.setDecimals(5)
        self.spinBox_Input_Setpoint.setMinimum(0.0)
        self.spinBox_Input_Setpoint.setMaximum(100.0)
        self.spinBox_Input_Setpoint.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.spinBox_Input_Setpoint.setObjectName("spinBox_Input_Setpoint")
        self.gridLayout_6.addWidget(self.spinBox_Input_Setpoint, 0, 0, 1, 1)
        self.scrollBar_Input_Setpoint = QtWidgets.QScrollBar(self.groupBox_Setpoint_Current)
        self.scrollBar_Input_Setpoint.setEnabled(True)
        self.scrollBar_Input_Setpoint.setMaximum(65535)
        self.scrollBar_Input_Setpoint.setOrientation(QtCore.Qt.Horizontal)
        self.scrollBar_Input_Setpoint.setObjectName("scrollBar_Input_Setpoint")
        self.gridLayout_6.addWidget(self.scrollBar_Input_Setpoint, 0, 2, 1, 1)
        spacerItem39 = QtWidgets.QSpacerItem(20, 9, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem39, 2, 1, 1, 1)
        spacerItem40 = QtWidgets.QSpacerItem(30, 9, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem40, 2, 0, 1, 1)
        spacerItem41 = QtWidgets.QSpacerItem(40, 9, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem41, 2, 2, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_Setpoint_Current, 1, 0, 1, 1)
        self.groupBox_Gain_Current = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.groupBox_Gain_Current.setEnabled(True)
        self.groupBox_Gain_Current.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.groupBox_Gain_Current.setObjectName("groupBox_Gain_Current")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_Gain_Current)
        self.horizontalLayout_5.setContentsMargins(30, 5, -1, 5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton_8_Gain = QtWidgets.QRadioButton(self.groupBox_Gain_Current)
        self.radioButton_8_Gain.setEnabled(True)
        self.radioButton_8_Gain.setObjectName("radioButton_8_Gain")
        self.horizontalLayout_5.addWidget(self.radioButton_8_Gain)
        self.radioButton_9_Gain = QtWidgets.QRadioButton(self.groupBox_Gain_Current)
        self.radioButton_9_Gain.setEnabled(True)
        self.radioButton_9_Gain.setChecked(True)
        self.radioButton_9_Gain.setObjectName("radioButton_9_Gain")
        self.horizontalLayout_5.addWidget(self.radioButton_9_Gain)
        self.radioButton_10_Gain = QtWidgets.QRadioButton(self.groupBox_Gain_Current)
        self.radioButton_10_Gain.setEnabled(True)
        self.radioButton_10_Gain.setObjectName("radioButton_10_Gain")
        self.horizontalLayout_5.addWidget(self.radioButton_10_Gain)
        self.gridLayout_9.addWidget(self.groupBox_Gain_Current, 0, 0, 1, 1)
        self.groupBox_Ramp_Current = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.groupBox_Ramp_Current.setEnabled(True)
        self.groupBox_Ramp_Current.setObjectName("groupBox_Ramp_Current")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_Ramp_Current)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_Ramp_Current)
        self.label_8.setEnabled(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 4, 1, 1)
        self.pushButton_Rampto4_CurrRamp = QtWidgets.QPushButton(self.groupBox_Ramp_Current)
        self.pushButton_Rampto4_CurrRamp.setEnabled(False)
        self.pushButton_Rampto4_CurrRamp.setObjectName("pushButton_Rampto4_CurrRamp")
        self.gridLayout_2.addWidget(self.pushButton_Rampto4_CurrRamp, 2, 3, 1, 1)
        spacerItem42 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem42, 0, 3, 1, 1)
        self.pushButton_Rampto3_CurrRamp = QtWidgets.QPushButton(self.groupBox_Ramp_Current)
        self.pushButton_Rampto3_CurrRamp.setEnabled(False)
        self.pushButton_Rampto3_CurrRamp.setObjectName("pushButton_Rampto3_CurrRamp")
        self.gridLayout_2.addWidget(self.pushButton_Rampto3_CurrRamp, 1, 3, 1, 1)
        self.pushButton_StopRamp_CurrRamp = QtWidgets.QPushButton(self.groupBox_Ramp_Current)
        self.pushButton_StopRamp_CurrRamp.setEnabled(False)
        self.pushButton_StopRamp_CurrRamp.setObjectName("pushButton_StopRamp_CurrRamp")
        self.gridLayout_2.addWidget(self.pushButton_StopRamp_CurrRamp, 3, 0, 1, 1)
        spacerItem43 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem43, 0, 0, 1, 1)
        self.pushButton_Rampto2_CurrRamp = QtWidgets.QPushButton(self.groupBox_Ramp_Current)
        self.pushButton_Rampto2_CurrRamp.setEnabled(False)
        self.pushButton_Rampto2_CurrRamp.setObjectName("pushButton_Rampto2_CurrRamp")
        self.gridLayout_2.addWidget(self.pushButton_Rampto2_CurrRamp, 2, 0, 1, 1)
        spacerItem44 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem44, 0, 1, 1, 1)
        spacerItem45 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem45, 0, 4, 1, 1)
        self.spinBox_Input3_CurrRamp = QtWidgets.QDoubleSpinBox(self.groupBox_Ramp_Current)
        self.spinBox_Input3_CurrRamp.setEnabled(True)
        self.spinBox_Input3_CurrRamp.setDecimals(4)
        self.spinBox_Input3_CurrRamp.setMinimum(0.0)
        self.spinBox_Input3_CurrRamp.setMaximum(100.0)
        self.spinBox_Input3_CurrRamp.setObjectName("spinBox_Input3_CurrRamp")
        self.gridLayout_2.addWidget(self.spinBox_Input3_CurrRamp, 1, 4, 1, 1)
        self.spinBox_Input2_CurrRamp = QtWidgets.QDoubleSpinBox(self.groupBox_Ramp_Current)
        self.spinBox_Input2_CurrRamp.setEnabled(True)
        self.spinBox_Input2_CurrRamp.setDecimals(4)
        self.spinBox_Input2_CurrRamp.setMinimum(0.0)
        self.spinBox_Input2_CurrRamp.setMaximum(100.0)
        self.spinBox_Input2_CurrRamp.setObjectName("spinBox_Input2_CurrRamp")
        self.gridLayout_2.addWidget(self.spinBox_Input2_CurrRamp, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_Ramp_Current)
        self.label_5.setEnabled(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 1, 1, 1, QtCore.Qt.AlignRight)
        self.pushButton_Rampto1_CurrRamp = QtWidgets.QPushButton(self.groupBox_Ramp_Current)
        self.pushButton_Rampto1_CurrRamp.setEnabled(False)
        self.pushButton_Rampto1_CurrRamp.setCheckable(False)
        self.pushButton_Rampto1_CurrRamp.setObjectName("pushButton_Rampto1_CurrRamp")
        self.gridLayout_2.addWidget(self.pushButton_Rampto1_CurrRamp, 1, 0, 1, 1)
        self.spinBox_Input4_CurrRamp = QtWidgets.QDoubleSpinBox(self.groupBox_Ramp_Current)
        self.spinBox_Input4_CurrRamp.setEnabled(True)
        self.spinBox_Input4_CurrRamp.setDecimals(4)
        self.spinBox_Input4_CurrRamp.setMinimum(0.0)
        self.spinBox_Input4_CurrRamp.setMaximum(100.0)
        self.spinBox_Input4_CurrRamp.setObjectName("spinBox_Input4_CurrRamp")
        self.gridLayout_2.addWidget(self.spinBox_Input4_CurrRamp, 2, 4, 1, 1)
        self.spinBox_Input1_CurrRamp = QtWidgets.QDoubleSpinBox(self.groupBox_Ramp_Current)
        self.spinBox_Input1_CurrRamp.setEnabled(True)
        self.spinBox_Input1_CurrRamp.setDecimals(4)
        self.spinBox_Input1_CurrRamp.setMinimum(0.0)
        self.spinBox_Input1_CurrRamp.setMaximum(100.0)
        self.spinBox_Input1_CurrRamp.setObjectName("spinBox_Input1_CurrRamp")
        self.gridLayout_2.addWidget(self.spinBox_Input1_CurrRamp, 1, 1, 1, 1)
        self.spinBox_SpeedInput_CurrRamp = QtWidgets.QSpinBox(self.groupBox_Ramp_Current)
        self.spinBox_SpeedInput_CurrRamp.setEnabled(True)
        self.spinBox_SpeedInput_CurrRamp.setObjectName("spinBox_SpeedInput_CurrRamp")
        self.gridLayout_2.addWidget(self.spinBox_SpeedInput_CurrRamp, 3, 3, 1, 1)
        spacerItem46 = QtWidgets.QSpacerItem(6, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem46, 0, 2, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_Ramp_Current, 2, 0, 1, 1)
        self.Current.setWidget(self.dockWidgetContents_2)
        HoGroupSTM.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.Current)
        self.actionOpen_O = QtWidgets.QAction(HoGroupSTM)
        self.actionOpen_O.setCheckable(False)
        self.actionOpen_O.setChecked(False)
        self.actionOpen_O.setAutoRepeat(True)
        self.actionOpen_O.setObjectName("actionOpen_O")
        self.actionSave_S = QtWidgets.QAction(HoGroupSTM)
        self.actionSave_S.setObjectName("actionSave_S")
        self.actionBias = QtWidgets.QAction(HoGroupSTM)
        self.actionBias.setObjectName("actionBias")
        self.actionCurrent = QtWidgets.QAction(HoGroupSTM)
        self.actionCurrent.setObjectName("actionCurrent")
        self.actionZ = QtWidgets.QAction(HoGroupSTM)
        self.actionZ.setObjectName("actionZ")
        self.actionScan = QtWidgets.QAction(HoGroupSTM)
        self.actionScan.setObjectName("actionScan")
        self.actionSpectra = QtWidgets.QAction(HoGroupSTM)
        self.actionSpectra.setObjectName("actionSpectra")
        self.actionDeposition = QtWidgets.QAction(HoGroupSTM)
        self.actionDeposition.setObjectName("actionDeposition")
        self.actionTrack = QtWidgets.QAction(HoGroupSTM)
        self.actionTrack.setObjectName("actionTrack")
        self.actionHop = QtWidgets.QAction(HoGroupSTM)
        self.actionHop.setObjectName("actionHop")
        self.actionManipulation = QtWidgets.QAction(HoGroupSTM)
        self.actionManipulation.setObjectName("actionManipulation")
        self.actionShow_All_A = QtWidgets.QAction(HoGroupSTM)
        self.actionShow_All_A.setObjectName("actionShow_All_A")
        self.actionManual_A = QtWidgets.QAction(HoGroupSTM)
        self.actionManual_A.setObjectName("actionManual_A")
        self.actionTipAppr = QtWidgets.QAction(HoGroupSTM)
        self.actionTipAppr.setObjectName("actionTipAppr")
        self.actionEtest = QtWidgets.QAction(HoGroupSTM)
        self.actionEtest.setObjectName("actionEtest")
        self.actionSetting = QtWidgets.QAction(HoGroupSTM)
        self.actionSetting.setObjectName("actionSetting")
        self.Zcontrol.raise_()
        self.Bias.raise_()
        self.Current.raise_()
        self.toolBar.addSeparator()
        self.menuFile.addAction(self.actionOpen_O)
        self.menuFile.addAction(self.actionSave_S)
        self.menuTip_Approach.addAction(self.actionTipAppr)
        self.menuScan.addAction(self.actionScan)
        self.menuScan.addAction(self.actionSpectra)
        self.menuScan.addAction(self.actionDeposition)
        self.menuScan.addAction(self.actionTrack)
        self.menuScan.addAction(self.actionHop)
        self.menuScan.addAction(self.actionManipulation)
        self.menuTest.addAction(self.actionEtest)
        self.menuSetting.addAction(self.actionSetting)
        self.menuHelp.addAction(self.actionManual_A)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuControl.menuAction())
        self.menubar.addAction(self.menuTip_Approach.menuAction())
        self.menubar.addAction(self.menuScan.menuAction())
        self.menubar.addAction(self.menuTest.menuAction())
        self.menubar.addAction(self.menuData_Manipulation.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(HoGroupSTM)
        self.actionBias.triggered['bool'].connect(self.Bias.close)
        self.actionCurrent.triggered['bool'].connect(self.Current.repaint)
        self.actionZ.triggered['bool'].connect(self.Zcontrol.hide)
        self.radioButton_16bit_DAC.clicked['bool'].connect(self.groupBox_Range_Bias.setChecked)
        self.scrollBar_Input_Zoffset.valueChanged['int'].connect(self.spinBox_Input_Zoffset.setValue)
        self.spinBox_Input_Zoffset.valueChanged['int'].connect(self.scrollBar_Input_Zoffset.setValue)
        QtCore.QMetaObject.connectSlotsByName(HoGroupSTM)

    def retranslateUi(self, HoGroupSTM):
        _translate = QtCore.QCoreApplication.translate
        HoGroupSTM.setWindowTitle(_translate("HoGroupSTM", "HoGroupSTM"))
        self.label_4.setText(_translate("HoGroupSTM", "DSP version:"))
        self.versionLabel.setText(_translate("HoGroupSTM", "No DSP found"))
        self.label_6.setText(_translate("HoGroupSTM", "None"))
        self.label_3.setText(_translate("HoGroupSTM", "PyQt5 Ho group STM software by Jiang Yao and Dan Bai"))
        self.label_2.setText(_translate("HoGroupSTM", "Status："))
        self.toolBar.setWindowTitle(_translate("HoGroupSTM", "toolBar"))
        self.menuFile.setTitle(_translate("HoGroupSTM", "File"))
        self.menuTip_Approach.setTitle(_translate("HoGroupSTM", "Tip Approach"))
        self.menuScan.setTitle(_translate("HoGroupSTM", "Scan"))
        self.menuControl.setTitle(_translate("HoGroupSTM", "Control"))
        self.menuTest.setTitle(_translate("HoGroupSTM", "Test"))
        self.menuData_Manipulation.setTitle(_translate("HoGroupSTM", "Data Manipulation"))
        self.menuSetting.setTitle(_translate("HoGroupSTM", "Setting"))
        self.menuHelp.setTitle(_translate("HoGroupSTM", "Help"))
        self.Zcontrol.setWindowTitle(_translate("HoGroupSTM", "Z control"))
        self.groupBox_Zoffset_Zcontrol.setTitle(_translate("HoGroupSTM", "Z offset"))
        self.pushButton_Zauto_Zoffset.setText(_translate("HoGroupSTM", "Z-auto"))
        self.pushButton_HardRetract_Zoffset.setText(_translate("HoGroupSTM", "Hard retract"))
        self.pushButton_Send_Zoffset.setText(_translate("HoGroupSTM", "Send"))
        self.groupBox_Zoffsetfine_Zcontrol.setTitle(_translate("HoGroupSTM", "Z offset(fine)"))
        self.pushButton_Advance_Zoffsetfine.setText(_translate("HoGroupSTM", "Advance"))
        self.label_14.setText(_translate("HoGroupSTM", "bits"))
        self.pushButton_Zero_Zoffsetfine.setText(_translate("HoGroupSTM", "Zero"))
        self.pushButton_MatchCurrent_Zoffsetfine.setText(_translate("HoGroupSTM", "Match current"))
        self.groupBox_Feedack_Zcontrol.setTitle(_translate("HoGroupSTM", "Feedback"))
        self.radioButton_ON_Feedback.setText(_translate("HoGroupSTM", "ON"))
        self.radioButton_OFF_Feedback.setText(_translate("HoGroupSTM", "OFF"))
        self.groupBox_Retract_Zcontrol.setTitle(_translate("HoGroupSTM", "Retract"))
        self.radioButton_ON_Retract.setText(_translate("HoGroupSTM", "ON"))
        self.radioButton_OFF_Retract.setText(_translate("HoGroupSTM", "OFF"))
        self.groupBox_Dither_Zcontrol.setTitle(_translate("HoGroupSTM", "Dither"))
        self.radioButton_ON_ZDither.setText(_translate("HoGroupSTM", "ON"))
        self.radioButton_OFF_ZDither.setText(_translate("HoGroupSTM", "OFF"))
        self.groupBox_Gain_Zcontrol.setTitle(_translate("HoGroupSTM", "Gain"))
        self.label_Z1gain_Gain.setText(_translate("HoGroupSTM", "Z1 Gain"))
        self.radioButton_Z1gain01_Gain.setText(_translate("HoGroupSTM", "0.1"))
        self.radioButton_Z1gain1_Gain.setText(_translate("HoGroupSTM", "1"))
        self.radioButton_Z1gain10_Gain.setText(_translate("HoGroupSTM", "10"))
        self.label_Z2gain_Gain.setText(_translate("HoGroupSTM", "Z2 Gain"))
        self.radioButton_Z2gain01_Gain.setText(_translate("HoGroupSTM", "0.1"))
        self.radioButton_Z2gain1_Gain.setText(_translate("HoGroupSTM", "1"))
        self.radioButton_Z2gain10_Gain.setText(_translate("HoGroupSTM", "10"))
        self.Bias.setWindowTitle(_translate("HoGroupSTM", "Bias"))
        self.groupBox_Ramp_Bias.setTitle(_translate("HoGroupSTM", "Ramp"))
        self.pushButton_Rampto7_BiasRamp.setText(_translate("HoGroupSTM", "Ramp to"))
        self.pushButton_Rampto4_BiasRamp.setText(_translate("HoGroupSTM", "Ramp to"))
        self.pushButton_Rampto2_BiasRamp.setText(_translate("HoGroupSTM", "Ramp to"))
        self.pushButton_Rampto1_BiasRamp.setText(_translate("HoGroupSTM", "Ramp to"))
        self.pushButton_Rampto8_BiasRamp.setText(_translate("HoGroupSTM", "Ramp to"))
        self.label_24.setText(_translate("HoGroupSTM", "bit/ms"))
        self.pushButton_Rampto6_BiasRamp.setText(_translate("HoGroupSTM", "Ramp to"))
        self.pushButton_StopRamp_BiasRamp.setText(_translate("HoGroupSTM", "Stop ramp"))
        self.pushButton_Rampto5_BiasRamp.setText(_translate("HoGroupSTM", "Ramp to"))
        self.pushButton_Rampto3_BiasRamp.setText(_translate("HoGroupSTM", "Ramp to"))
        self.label_12.setText(_translate("HoGroupSTM", "Ramp speed"))
        self.groupBox_Dither_Bias.setTitle(_translate("HoGroupSTM", "Dither"))
        self.radioButton_ON_BiasDither.setText(_translate("HoGroupSTM", "ON"))
        self.radioButton_OFF_BiasDither.setText(_translate("HoGroupSTM", "OFF"))
        self.groupBox_DAC_Bias.setTitle(_translate("HoGroupSTM", "DAC"))
        self.radioButton_20bit_DAC.setText(_translate("HoGroupSTM", "20 bit"))
        self.radioButton_16bit_DAC.setText(_translate("HoGroupSTM", "16 bit"))
        self.groupBox_Bias_Bias.setTitle(_translate("HoGroupSTM", "Bias"))
        self.pushButton_Filp_Bias.setText(_translate("HoGroupSTM", "Flip"))
        self.groupBox_Range_Bias.setTitle(_translate("HoGroupSTM", "Range"))
        self.radioButton_25_Range.setText(_translate("HoGroupSTM", "+/- 2.5"))
        self.radioButton_5_Range.setText(_translate("HoGroupSTM", "+/- 5"))
        self.radioButton_10_Range.setText(_translate("HoGroupSTM", "+/-10"))
        self.Current.setWindowTitle(_translate("HoGroupSTM", "Current"))
        self.groupBox_Setpoint_Current.setTitle(_translate("HoGroupSTM", "Setpoint"))
        self.label.setText(_translate("HoGroupSTM", "nA"))
        self.groupBox_Gain_Current.setTitle(_translate("HoGroupSTM", "Gain"))
        self.radioButton_8_Gain.setText(_translate("HoGroupSTM", "8"))
        self.radioButton_9_Gain.setText(_translate("HoGroupSTM", "9"))
        self.radioButton_10_Gain.setText(_translate("HoGroupSTM", "10"))
        self.groupBox_Ramp_Current.setTitle(_translate("HoGroupSTM", "Ramp"))
        self.label_8.setText(_translate("HoGroupSTM", "bit/ms"))
        self.pushButton_Rampto4_CurrRamp.setText(_translate("HoGroupSTM", "Ramp to"))
        self.pushButton_Rampto3_CurrRamp.setText(_translate("HoGroupSTM", "Ramp to"))
        self.pushButton_StopRamp_CurrRamp.setText(_translate("HoGroupSTM", "Stop ramp"))
        self.pushButton_Rampto2_CurrRamp.setText(_translate("HoGroupSTM", "Ramp to"))
        self.label_5.setText(_translate("HoGroupSTM", "Ramp speed"))
        self.pushButton_Rampto1_CurrRamp.setText(_translate("HoGroupSTM", "Ramp to"))
        self.actionOpen_O.setText(_translate("HoGroupSTM", "Open(&O)"))
        self.actionSave_S.setText(_translate("HoGroupSTM", "Save(&S)"))
        self.actionBias.setText(_translate("HoGroupSTM", "Bias"))
        self.actionCurrent.setText(_translate("HoGroupSTM", "Current"))
        self.actionZ.setText(_translate("HoGroupSTM", "Z"))
        self.actionScan.setText(_translate("HoGroupSTM", "Scan"))
        self.actionSpectra.setText(_translate("HoGroupSTM", "Spectra"))
        self.actionDeposition.setText(_translate("HoGroupSTM", "Deposition"))
        self.actionTrack.setText(_translate("HoGroupSTM", "Track"))
        self.actionHop.setText(_translate("HoGroupSTM", "Hop"))
        self.actionManipulation.setText(_translate("HoGroupSTM", "Manipulation"))
        self.actionShow_All_A.setText(_translate("HoGroupSTM", "Show All(&A)"))
        self.actionManual_A.setText(_translate("HoGroupSTM", "Manual(&M)"))
        self.actionTipAppr.setText(_translate("HoGroupSTM", "Tip Approach"))
        self.actionEtest.setText(_translate("HoGroupSTM", "Electronic Test"))
        self.actionSetting.setText(_translate("HoGroupSTM", "Setting"))
import logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HoGroupSTM = QtWidgets.QMainWindow()
    ui = Ui_HoGroupSTM()
    ui.setupUi(HoGroupSTM)
    HoGroupSTM.show()
    sys.exit(app.exec_())
