# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import serial
import serial.tools.list_ports
from time import sleep
from Setting_ui import Ui_Setting
from TipApproach_ui import Ui_TipApproach
from Etest_ui import Ui_ElectronicTest

# Let the settings subwindow load old configurations and find COM automatically.
class myForm(QtWidgets.QWidget, Ui_Setting):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

        # load settings
        self.settings = QtCore.QSettings("config.ini", QtCore.QSettings.IniFormat)
        # self.com = self.settings.value("SETUP/COM_VALUE")
        self.baud = self.settings.value("SETUP/BAUD_VALUE")#, 0, type=int)

        # init gui
        #self.comboBox_uart.addItem(self.com)
        self.comboBox_baud.setCurrentText(self.baud)
        self.comboBox_baud.currentIndexChanged.connect(self.combox_baud_cb)
        self.saveButton.clicked.connect(self.btn_test_cb)


        def check_valid_uart():
            # com select
            port_values = []

            port_list = list(serial.tools.list_ports.comports())
            length = len(port_list)
            if (0 == len(port_list)):
                print("can't find serial port")
                self.comboBox_uart.setCurrentIndex(-1)
                self.comboBox_uart.clear()
            else:
                for i in range(0, len(port_list)):
                    port_values.append(port_list[i][0])

                for i in range(len(port_list)):
                    index = self.comboBox_uart.findText(port_values[i], QtCore.Qt.MatchFixedString)
                    if (index < 0):
                        current_text = self.comboBox_uart.currentText()
                        self.comboBox_uart.addItem(port_values[i])
                        if ("" == current_text):
                            # print("current text is NULL")
                            sleep(0.04)
                            self.comboBox_uart.setCurrentIndex(-1)
                        else:
                            print("current text is ", current_text)
                # remove eut
                count = self.comboBox_uart.count()
                for i in range(count):
                    data = self.comboBox_uart.itemText(i)
                    is_uart_exist = 0
                    for j in range(length):
                        if (data == port_values[j]):
                            is_uart_exist = 1
                    if (0 == is_uart_exist):
                        # remove1
                        self.comboBox_uart.removeItem(i)
                        current_data = self.comboBox_uart.currentText()
                        if (current_data == data or current_data == ""):
                            self.comboBox_uart.clear()
        # find COM
        check_valid_uart()

    def combox_baud_cb(self):
            self.baud = self.comboBox_baud.currentText()

    def btn_test_cb(self):
            self.settings.setValue("SETUP/BAUD_VALUE", self.baud)
            QtWidgets.QMessageBox.information(self, "Reminder", "QSettings saved successfully!")




class Ui_HoGroupSTM(object):
    def setupUi(self, HoGroupSTM):
        HoGroupSTM.setObjectName("HoGroupSTM")
        HoGroupSTM.setEnabled(True)
        HoGroupSTM.resize(600, 286)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(HoGroupSTM.sizePolicy().hasHeightForWidth())
        HoGroupSTM.setSizePolicy(sizePolicy)
        HoGroupSTM.setMinimumSize(QtCore.QSize(600, 100))
        font = QtGui.QFont()
        font.setPointSize(8)
        HoGroupSTM.setFont(font)
        HoGroupSTM.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/STMlogo_NiCp2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/logo/STMlogo_blackhole.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/logo/STMlogo_NiCp2.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/logo/STMlogo_blackhole.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/logo/STMlogo_NiCp2.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/logo/STMlogo_blackhole.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        HoGroupSTM.setWindowIcon(icon)
        HoGroupSTM.setWindowOpacity(1.0)
        HoGroupSTM.setAutoFillBackground(True)
        HoGroupSTM.setDockNestingEnabled(False)
        HoGroupSTM.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks|QtWidgets.QMainWindow.GroupedDragging)
        HoGroupSTM.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(HoGroupSTM)
        self.centralwidget.setObjectName("centralwidget")
        HoGroupSTM.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(HoGroupSTM)
        self.statusbar.setObjectName("statusbar")
        HoGroupSTM.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(HoGroupSTM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        HoGroupSTM.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar = QtWidgets.QMenuBar(HoGroupSTM)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTip_Approach = QtWidgets.QMenu(self.menubar)
        self.menuTip_Approach.setObjectName("menuTip_Approach")
        self.menuScan = QtWidgets.QMenu(self.menubar)
        self.menuScan.setObjectName("menuScan")
        self.menuControl = QtWidgets.QMenu(self.menubar)
        self.menuControl.setObjectName("menuControl")
        self.menuTest = QtWidgets.QMenu(self.menubar)
        self.menuTest.setSeparatorsCollapsible(False)
        self.menuTest.setToolTipsVisible(False)
        self.menuTest.setObjectName("menuTest")

        self.menuData_Manipulation = QtWidgets.QMenu(self.menubar)
        self.menuData_Manipulation.setObjectName("menuData_Manipulation")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        HoGroupSTM.setMenuBar(self.menubar)
        self.Zcontrol = QtWidgets.QDockWidget(HoGroupSTM)
        self.Zcontrol.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Zcontrol.sizePolicy().hasHeightForWidth())
        self.Zcontrol.setSizePolicy(sizePolicy)
        self.Zcontrol.setMinimumSize(QtCore.QSize(363, 361))
        self.Zcontrol.setFloating(True)
        self.Zcontrol.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.Zcontrol.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.Zcontrol.setObjectName("Zcontrol")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.dockWidgetContents_3)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.groupBox)
        self.horizontalScrollBar.setMinimum(-32768)
        self.horizontalScrollBar.setMaximum(32767)
        self.horizontalScrollBar.setProperty("value", -32768)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.gridLayout_4.addWidget(self.horizontalScrollBar, 2, 0, 1, 10)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setIconSize(QtCore.QSize(16, 9))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 0, 8, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 6, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 1, 9, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_4.addWidget(self.pushButton_2, 0, 9, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 1, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 1, 4, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_4.addWidget(self.pushButton_3, 2, 10, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 1, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 1, 8, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem8, 1, 7, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 1, 10, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem10, 1, 5, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_3.setMinimum(-32768)
        self.spinBox_3.setMaximum(32767)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout_4.addWidget(self.spinBox_3, 0, 0, 1, 4)
        self.spinBox_4 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_4.setEnabled(False)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout_4.addWidget(self.spinBox_4, 0, 4, 1, 4)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(self.dockWidgetContents_3)
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget = QtWidgets.QWidget(self.groupBox_4)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem11 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem11, 3, 11, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem12, 3, 9, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem13, 3, 7, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem14, 3, 10, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem15, 3, 6, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem16, 3, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem17, 3, 13, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem18, 3, 1, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem19, 3, 2, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem20, 3, 3, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem21, 3, 12, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem22, 3, 8, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem23, 3, 5, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.widget)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_3.addWidget(self.pushButton_11, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 4, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.widget)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_3.addWidget(self.spinBox_2, 0, 1, 1, 3)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_3.addWidget(self.pushButton_9, 0, 7, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_3.addWidget(self.pushButton_10, 0, 8, 1, 6)
        self.verticalLayout_6.addWidget(self.widget)
        self.gridLayout_14.addLayout(self.verticalLayout_6, 1, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem24 = QtWidgets.QSpacerItem(40, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem24, 1, 4, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(40, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem25, 1, 2, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_5.addWidget(self.spinBox, 0, 0, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(40, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem26, 1, 3, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(40, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem27, 1, 0, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(40, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem28, 1, 5, 1, 1)
        self.horizontalScrollBar_4 = QtWidgets.QScrollBar(self.groupBox_4)
        self.horizontalScrollBar_4.setMinimum(-32768)
        self.horizontalScrollBar_4.setMaximum(32767)
        self.horizontalScrollBar_4.setProperty("value", -32768)
        self.horizontalScrollBar_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_4.setObjectName("horizontalScrollBar_4")
        self.gridLayout_5.addWidget(self.horizontalScrollBar_4, 0, 1, 1, 5)
        self.gridLayout_14.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.widget_7 = QtWidgets.QWidget(self.dockWidgetContents_3)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_13 = QtWidgets.QGroupBox(self.widget_7)
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_4.setContentsMargins(20, 5, -1, 5)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radioButton_29 = QtWidgets.QRadioButton(self.groupBox_13)
        self.radioButton_29.setObjectName("radioButton_29")
        self.verticalLayout_4.addWidget(self.radioButton_29)
        self.radioButton_30 = QtWidgets.QRadioButton(self.groupBox_13)
        self.radioButton_30.setObjectName("radioButton_30")
        self.verticalLayout_4.addWidget(self.radioButton_30)
        self.horizontalLayout_2.addWidget(self.groupBox_13)
        self.groupBox_12 = QtWidgets.QGroupBox(self.widget_7)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_5.setContentsMargins(20, 5, -1, 5)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.radioButton_25 = QtWidgets.QRadioButton(self.groupBox_12)
        self.radioButton_25.setObjectName("radioButton_25")
        self.verticalLayout_5.addWidget(self.radioButton_25)
        self.radioButton_26 = QtWidgets.QRadioButton(self.groupBox_12)
        self.radioButton_26.setObjectName("radioButton_26")
        self.verticalLayout_5.addWidget(self.radioButton_26)
        self.horizontalLayout_2.addWidget(self.groupBox_12)
        self.groupBox_11 = QtWidgets.QGroupBox(self.widget_7)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_7.setContentsMargins(20, 5, -1, 5)
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.radioButton_28 = QtWidgets.QRadioButton(self.groupBox_11)
        self.radioButton_28.setObjectName("radioButton_28")
        self.verticalLayout_7.addWidget(self.radioButton_28)
        self.radioButton_27 = QtWidgets.QRadioButton(self.groupBox_11)
        self.radioButton_27.setObjectName("radioButton_27")
        self.verticalLayout_7.addWidget(self.radioButton_27)
        self.horizontalLayout_2.addWidget(self.groupBox_11)
        self.verticalLayout.addWidget(self.widget_7)
        self.groupBox_3 = QtWidgets.QGroupBox(self.dockWidgetContents_3)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setContentsMargins(9, 5, 9, 9)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_5 = QtWidgets.QWidget(self.groupBox_3)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_3.setContentsMargins(11, 0, 11, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.widget_5)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.radioButton_7 = QtWidgets.QRadioButton(self.widget_5)
        self.radioButton_7.setObjectName("radioButton_7")
        self.horizontalLayout_3.addWidget(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(self.widget_5)
        self.radioButton_8.setObjectName("radioButton_8")
        self.horizontalLayout_3.addWidget(self.radioButton_8)
        self.radioButton_9 = QtWidgets.QRadioButton(self.widget_5)
        self.radioButton_9.setObjectName("radioButton_9")
        self.horizontalLayout_3.addWidget(self.radioButton_9)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.groupBox_3)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_4.setContentsMargins(11, 0, 11, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.widget_6)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.radioButton_10 = QtWidgets.QRadioButton(self.widget_6)
        self.radioButton_10.setObjectName("radioButton_10")
        self.horizontalLayout_4.addWidget(self.radioButton_10)
        self.radioButton_12 = QtWidgets.QRadioButton(self.widget_6)
        self.radioButton_12.setObjectName("radioButton_12")
        self.horizontalLayout_4.addWidget(self.radioButton_12)
        self.radioButton_11 = QtWidgets.QRadioButton(self.widget_6)
        self.radioButton_11.setObjectName("radioButton_11")
        self.horizontalLayout_4.addWidget(self.radioButton_11)
        self.verticalLayout_2.addWidget(self.widget_6)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.Zcontrol.setWidget(self.dockWidgetContents_3)
        HoGroupSTM.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.Zcontrol)
        self.Bias = QtWidgets.QDockWidget(HoGroupSTM)
        self.Bias.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bias.sizePolicy().hasHeightForWidth())
        self.Bias.setSizePolicy(sizePolicy)
        self.Bias.setMinimumSize(QtCore.QSize(348, 358))
        self.Bias.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.Bias.setAcceptDrops(True)
        self.Bias.setFloating(True)
        self.Bias.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.Bias.setObjectName("Bias")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox_15 = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox_15.setObjectName("groupBox_15")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_15)
        self.gridLayout.setContentsMargins(-1, 5, -1, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_15)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 3, 5, 1, 1)
        self.doubleSpinBox_31 = QtWidgets.QDoubleSpinBox(self.groupBox_15)
        self.doubleSpinBox_31.setDecimals(4)
        self.doubleSpinBox_31.setObjectName("doubleSpinBox_31")
        self.gridLayout.addWidget(self.doubleSpinBox_31, 4, 1, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem29, 0, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_15)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 4, 0, 1, 1)
        self.doubleSpinBox_11 = QtWidgets.QDoubleSpinBox(self.groupBox_15)
        self.doubleSpinBox_11.setDecimals(4)
        self.doubleSpinBox_11.setObjectName("doubleSpinBox_11")
        self.gridLayout.addWidget(self.doubleSpinBox_11, 3, 6, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_15)
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout.addWidget(self.pushButton_22, 2, 0, 1, 1)
        self.doubleSpinBox_15 = QtWidgets.QDoubleSpinBox(self.groupBox_15)
        self.doubleSpinBox_15.setDecimals(4)
        self.doubleSpinBox_15.setObjectName("doubleSpinBox_15")
        self.gridLayout.addWidget(self.doubleSpinBox_15, 3, 1, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem30, 0, 1, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem31, 0, 2, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.groupBox_15)
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout.addWidget(self.pushButton_25, 1, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_15)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 4, 5, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem32, 0, 6, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_15)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 5, 6, 1, 1)
        self.doubleSpinBox_10 = QtWidgets.QDoubleSpinBox(self.groupBox_15)
        self.doubleSpinBox_10.setDecimals(4)
        self.doubleSpinBox_10.setObjectName("doubleSpinBox_10")
        self.gridLayout.addWidget(self.doubleSpinBox_10, 4, 6, 1, 1)
        self.spinBox_5 = QtWidgets.QSpinBox(self.groupBox_15)
        self.spinBox_5.setObjectName("spinBox_5")
        self.gridLayout.addWidget(self.spinBox_5, 5, 5, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.groupBox_15)
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout.addWidget(self.pushButton_24, 2, 5, 1, 1)
        self.doubleSpinBox_21 = QtWidgets.QDoubleSpinBox(self.groupBox_15)
        self.doubleSpinBox_21.setDecimals(4)
        self.doubleSpinBox_21.setObjectName("doubleSpinBox_21")
        self.gridLayout.addWidget(self.doubleSpinBox_21, 2, 1, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_15)
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout.addWidget(self.pushButton_21, 5, 0, 1, 1)
        self.doubleSpinBox_25 = QtWidgets.QDoubleSpinBox(self.groupBox_15)
        self.doubleSpinBox_25.setDecimals(4)
        self.doubleSpinBox_25.setObjectName("doubleSpinBox_25")
        self.gridLayout.addWidget(self.doubleSpinBox_25, 1, 6, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem33, 0, 3, 1, 1)
        self.doubleSpinBox_24 = QtWidgets.QDoubleSpinBox(self.groupBox_15)
        self.doubleSpinBox_24.setDecimals(4)
        self.doubleSpinBox_24.setObjectName("doubleSpinBox_24")
        self.gridLayout.addWidget(self.doubleSpinBox_24, 2, 6, 1, 1)
        self.doubleSpinBox_23 = QtWidgets.QDoubleSpinBox(self.groupBox_15)
        self.doubleSpinBox_23.setDecimals(4)
        self.doubleSpinBox_23.setObjectName("doubleSpinBox_23")
        self.gridLayout.addWidget(self.doubleSpinBox_23, 1, 1, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.groupBox_15)
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout.addWidget(self.pushButton_23, 1, 5, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_15)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 3, 0, 1, 1)
        spacerItem34 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem34, 0, 5, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem35, 0, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_15)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 5, 1, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_15, 2, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.dockWidgetContents)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_8 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_12.setContentsMargins(20, 5, 20, 5)
        self.gridLayout_12.setVerticalSpacing(6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.radioButton_16 = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton_16.setObjectName("radioButton_16")
        self.gridLayout_12.addWidget(self.radioButton_16, 0, 0, 1, 1)
        self.radioButton_17 = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton_17.setObjectName("radioButton_17")
        self.gridLayout_12.addWidget(self.radioButton_17, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_8)
        self.groupBox_9 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_19.setContentsMargins(20, 5, 20, 5)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.radioButton_18 = QtWidgets.QRadioButton(self.groupBox_9)
        self.radioButton_18.setObjectName("radioButton_18")
        self.gridLayout_19.addWidget(self.radioButton_18, 0, 0, 1, 1)
        self.radioButton_19 = QtWidgets.QRadioButton(self.groupBox_9)
        self.radioButton_19.setObjectName("radioButton_19")
        self.gridLayout_19.addWidget(self.radioButton_19, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_9)
        self.gridLayout_8.addWidget(self.widget_2, 3, 0, 1, 1)
        self.groupBox_14 = QtWidgets.QGroupBox(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_14.sizePolicy().hasHeightForWidth())
        self.groupBox_14.setSizePolicy(sizePolicy)
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_10.setContentsMargins(-1, 5, -1, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem36 = QtWidgets.QSpacerItem(40, 9, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem36, 2, 1, 1, 1)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.groupBox_14)
        self.doubleSpinBox_5.setDecimals(6)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.gridLayout_10.addWidget(self.doubleSpinBox_5, 0, 0, 1, 1)
        self.horizontalScrollBar_5 = QtWidgets.QScrollBar(self.groupBox_14)
        self.horizontalScrollBar_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_5.setObjectName("horizontalScrollBar_5")
        self.gridLayout_10.addWidget(self.horizontalScrollBar_5, 0, 1, 1, 2)
        self.gridLayout_8.addWidget(self.groupBox_14, 0, 0, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox_10.setFlat(False)
        self.groupBox_10.setCheckable(False)
        self.groupBox_10.setChecked(False)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_20.setContentsMargins(20, 5, 9, 9)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.radioButton_20 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_20.setObjectName("radioButton_20")
        self.gridLayout_20.addWidget(self.radioButton_20, 0, 0, 1, 1)
        self.radioButton_21 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_21.setObjectName("radioButton_21")
        self.gridLayout_20.addWidget(self.radioButton_21, 0, 1, 1, 1)
        self.radioButton_22 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_22.setObjectName("radioButton_22")
        self.gridLayout_20.addWidget(self.radioButton_22, 0, 2, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_10, 10, 0, 1, 1)
        self.Bias.setWidget(self.dockWidgetContents)
        HoGroupSTM.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.Bias)
        self.Current = QtWidgets.QDockWidget(HoGroupSTM)
        self.Current.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Current.sizePolicy().hasHeightForWidth())
        self.Current.setSizePolicy(sizePolicy)
        self.Current.setMinimumSize(QtCore.QSize(342, 200))
        self.Current.setAcceptDrops(True)
        self.Current.setFloating(True)
        self.Current.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.Current.setObjectName("Current")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_6 = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setContentsMargins(-1, 5, -1, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalScrollBar_3 = QtWidgets.QScrollBar(self.groupBox_6)
        self.horizontalScrollBar_3.setMaximum(65535)
        self.horizontalScrollBar_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_3.setObjectName("horizontalScrollBar_3")
        self.gridLayout_6.addWidget(self.horizontalScrollBar_3, 0, 1, 1, 2)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.doubleSpinBox_4.setDecimals(5)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout_6.addWidget(self.doubleSpinBox_4, 0, 0, 1, 1)
        spacerItem37 = QtWidgets.QSpacerItem(40, 9, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem37, 2, 1, 1, 2)
        self.gridLayout_9.addWidget(self.groupBox_6, 1, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.groupBox_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_5.setContentsMargins(30, 5, -1, 5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton_15 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_15.setObjectName("radioButton_15")
        self.horizontalLayout_5.addWidget(self.radioButton_15)
        self.radioButton_14 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_14.setObjectName("radioButton_14")
        self.horizontalLayout_5.addWidget(self.radioButton_14)
        self.radioButton_13 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_13.setObjectName("radioButton_13")
        self.horizontalLayout_5.addWidget(self.radioButton_13)
        self.gridLayout_9.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_7)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 4, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_2.addWidget(self.pushButton_8, 2, 3, 1, 1)
        spacerItem38 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem38, 0, 3, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_2.addWidget(self.pushButton_7, 1, 3, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 3, 0, 1, 1)
        spacerItem39 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem39, 0, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 2, 0, 1, 1)
        spacerItem40 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem40, 0, 1, 1, 1)
        spacerItem41 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem41, 0, 4, 1, 1)
        self.doubleSpinBox_12 = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.doubleSpinBox_12.setDecimals(4)
        self.doubleSpinBox_12.setObjectName("doubleSpinBox_12")
        self.gridLayout_2.addWidget(self.doubleSpinBox_12, 1, 4, 1, 1)
        self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.doubleSpinBox_9.setDecimals(4)
        self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
        self.gridLayout_2.addWidget(self.doubleSpinBox_9, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_7)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 1, 1, 1, QtCore.Qt.AlignRight)
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_2.addWidget(self.pushButton_12, 1, 0, 1, 1)
        self.doubleSpinBox_13 = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.doubleSpinBox_13.setDecimals(4)
        self.doubleSpinBox_13.setObjectName("doubleSpinBox_13")
        self.gridLayout_2.addWidget(self.doubleSpinBox_13, 2, 4, 1, 1)
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.doubleSpinBox_8.setDecimals(4)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.gridLayout_2.addWidget(self.doubleSpinBox_8, 1, 1, 1, 1)
        self.spinBox_6 = QtWidgets.QSpinBox(self.groupBox_7)
        self.spinBox_6.setObjectName("spinBox_6")
        self.gridLayout_2.addWidget(self.spinBox_6, 3, 3, 1, 1)
        spacerItem42 = QtWidgets.QSpacerItem(6, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem42, 0, 2, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_7, 2, 0, 1, 1)
        self.Current.setWidget(self.dockWidgetContents_2)
        HoGroupSTM.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.Current)
        self.toolBar_2 = QtWidgets.QToolBar(HoGroupSTM)
        self.toolBar_2.setObjectName("toolBar_2")
        HoGroupSTM.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.actionOpen_O = QtWidgets.QAction(HoGroupSTM)
        self.actionOpen_O.setCheckable(False)
        self.actionOpen_O.setChecked(False)
        self.actionOpen_O.setAutoRepeat(True)
        self.actionOpen_O.setObjectName("actionOpen_O")
        self.actionSave_S = QtWidgets.QAction(HoGroupSTM)
        self.actionSave_S.setObjectName("actionSave_S")
        self.actionBias = QtWidgets.QAction(HoGroupSTM)
        self.actionBias.setObjectName("actionBias")
        self.actionCurrent = QtWidgets.QAction(HoGroupSTM)
        self.actionCurrent.setObjectName("actionCurrent")
        self.actionZ = QtWidgets.QAction(HoGroupSTM)
        self.actionZ.setObjectName("actionZ")
        self.actionScan = QtWidgets.QAction(HoGroupSTM)
        self.actionScan.setObjectName("actionScan")
        self.actionSpectra = QtWidgets.QAction(HoGroupSTM)
        self.actionSpectra.setObjectName("actionSpectra")
        self.actionDeposition = QtWidgets.QAction(HoGroupSTM)
        self.actionDeposition.setObjectName("actionDeposition")
        self.actionTrack = QtWidgets.QAction(HoGroupSTM)
        self.actionTrack.setObjectName("actionTrack")
        self.actionHop = QtWidgets.QAction(HoGroupSTM)
        self.actionHop.setObjectName("actionHop")
        self.actionManipulation = QtWidgets.QAction(HoGroupSTM)
        self.actionManipulation.setObjectName("actionManipulation")
        self.actionShow_All_A = QtWidgets.QAction(HoGroupSTM)
        self.actionShow_All_A.setObjectName("actionShow_All_A")
        self.actionManual_A = QtWidgets.QAction(HoGroupSTM)
        self.actionManual_A.setObjectName("actionManual_A")
        self.actionOpen_Dialog = QtWidgets.QAction(HoGroupSTM)
        self.actionOpen_Dialog.setObjectName("actionOpen_Dialog")
        self.actionOpen_tipappr_Dialog = QtWidgets.QAction(HoGroupSTM)
        self.actionOpen_tipappr_Dialog.setObjectName("actionOpen_tipappr_Dialog")
        self.actionElectronic_Test = QtWidgets.QAction(HoGroupSTM)
        self.actionElectronic_Test.setObjectName("actionElectronic_Test")
        self.Bias.raise_()
        self.Current.raise_()
        self.Zcontrol.raise_()
        self.toolBar.addSeparator()
        self.menuFile.addAction(self.actionOpen_O)
        self.menuFile.addAction(self.actionSave_S)
        self.menuScan.addAction(self.actionScan)
        self.menuScan.addAction(self.actionSpectra)
        self.menuScan.addAction(self.actionDeposition)
        self.menuScan.addAction(self.actionTrack)
        self.menuScan.addAction(self.actionHop)
        self.menuScan.addAction(self.actionManipulation)
        self.menuSetting.addAction(self.actionOpen_Dialog)
        self.menuControl.addAction(self.actionBias)
        self.menuControl.addAction(self.actionCurrent)
        self.menuControl.addAction(self.actionZ)
        self.menuControl.addAction(self.actionShow_All_A)
        self.menuTip_Approach.addAction(self.actionOpen_tipappr_Dialog)
        self.menuTest.addAction(self.actionElectronic_Test)
        self.menuHelp.addAction(self.actionManual_A)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuControl.menuAction())
        self.menubar.addAction(self.menuTip_Approach.menuAction())
        self.menubar.addAction(self.menuScan.menuAction())
        self.menubar.addAction(self.menuTest.menuAction())
        self.menubar.addAction(self.menuData_Manipulation.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(HoGroupSTM)
        self.actionOpen_Dialog.triggered['bool'].connect(self.opensettingwin)
        self.actionOpen_tipappr_Dialog.triggered['bool'].connect(self.opentipapprwin)
        self.actionElectronic_Test.triggered['bool'].connect(self.openelectronictest)
        self.actionBias.triggered['bool'].connect(self.Bias.close)
        self.actionCurrent.triggered['bool'].connect(self.Current.repaint)
        self.actionZ.triggered['bool'].connect(self.Zcontrol.hide)
        self.radioButton_19.clicked['bool'].connect(self.groupBox_10.setChecked)
        self.horizontalScrollBar.valueChanged['int'].connect(self.spinBox_3.setValue)
        self.spinBox_3.valueChanged['int'].connect(self.horizontalScrollBar.setValue)
        QtCore.QMetaObject.connectSlotsByName(HoGroupSTM)

        # call out sub windows from menu

        # Setting subwindow
        # self.settingwidget = QtWidgets.QWidget()
        # self.settingwin = Ui_Setting()
        # self.settingwin.setupUi(self.settingwidget)
        self.settingwidget = myForm()
        # Tip approach subwindow
        self.tipapprwidget = QtWidgets.QWidget()
        self.tipapprwin = Ui_TipApproach()
        self.tipapprwin.setupUi(self.tipapprwidget)
        # Electronic test subwindow
        self.electrotestwidget = QtWidgets.QWidget()
        self.electrotestwin = Ui_ElectronicTest()
        self.electrotestwin.setupUi(self.electrotestwidget)



    def retranslateUi(self, HoGroupSTM):
        _translate = QtCore.QCoreApplication.translate
        HoGroupSTM.setWindowTitle(_translate("HoGroupSTM", "HoGroupSTM"))
        self.toolBar.setWindowTitle(_translate("HoGroupSTM", "toolBar"))
        self.menuFile.setTitle(_translate("HoGroupSTM", "File"))
        self.menuTip_Approach.setTitle(_translate("HoGroupSTM", "Tip Approach"))
        self.menuScan.setTitle(_translate("HoGroupSTM", "Scan"))
        self.menuControl.setTitle(_translate("HoGroupSTM", "Control"))
        self.menuTest.setTitle(_translate("HoGroupSTM", "Test"))
        self.menuData_Manipulation.setTitle(_translate("HoGroupSTM", "Data Manipulation"))
        self.menuSetting.setTitle(_translate("HoGroupSTM", "Setting"))
        self.menuHelp.setTitle(_translate("HoGroupSTM", "Help"))
        self.Zcontrol.setWindowTitle(_translate("HoGroupSTM", "Z control"))
        self.groupBox.setTitle(_translate("HoGroupSTM", "Z offset"))
        self.pushButton.setText(_translate("HoGroupSTM", "Z-auto"))
        self.pushButton_2.setText(_translate("HoGroupSTM", "Hard retract"))
        self.pushButton_3.setText(_translate("HoGroupSTM", "Send"))
        self.groupBox_4.setTitle(_translate("HoGroupSTM", "Z offset(fine)"))
        self.pushButton_11.setText(_translate("HoGroupSTM", "Advance"))
        self.label_14.setText(_translate("HoGroupSTM", "bits"))
        self.pushButton_9.setText(_translate("HoGroupSTM", "Zero"))
        self.pushButton_10.setText(_translate("HoGroupSTM", "Match current"))
        self.groupBox_13.setTitle(_translate("HoGroupSTM", "Feedback"))
        self.radioButton_29.setText(_translate("HoGroupSTM", "ON"))
        self.radioButton_30.setText(_translate("HoGroupSTM", "OFF"))
        self.groupBox_12.setTitle(_translate("HoGroupSTM", "Retract"))
        self.radioButton_25.setText(_translate("HoGroupSTM", "ON"))
        self.radioButton_26.setText(_translate("HoGroupSTM", "OFF"))
        self.groupBox_11.setTitle(_translate("HoGroupSTM", "Dither"))
        self.radioButton_28.setText(_translate("HoGroupSTM", "ON"))
        self.radioButton_27.setText(_translate("HoGroupSTM", "OFF"))
        self.groupBox_3.setTitle(_translate("HoGroupSTM", "Gain"))
        self.label_9.setText(_translate("HoGroupSTM", "Z1 Gain"))
        self.radioButton_7.setText(_translate("HoGroupSTM", "0.1"))
        self.radioButton_8.setText(_translate("HoGroupSTM", "1"))
        self.radioButton_9.setText(_translate("HoGroupSTM", "10"))
        self.label_10.setText(_translate("HoGroupSTM", "Z2 Gain"))
        self.radioButton_10.setText(_translate("HoGroupSTM", "0.1"))
        self.radioButton_12.setText(_translate("HoGroupSTM", "1"))
        self.radioButton_11.setText(_translate("HoGroupSTM", "10"))
        self.Bias.setWindowTitle(_translate("HoGroupSTM", "Bias"))
        self.groupBox_15.setTitle(_translate("HoGroupSTM", "Ramp"))
        self.pushButton_16.setText(_translate("HoGroupSTM", "Ramp to"))
        self.pushButton_13.setText(_translate("HoGroupSTM", "Ramp to"))
        self.pushButton_22.setText(_translate("HoGroupSTM", "Ramp to"))
        self.pushButton_25.setText(_translate("HoGroupSTM", "Ramp to"))
        self.pushButton_14.setText(_translate("HoGroupSTM", "Ramp to"))
        self.label_24.setText(_translate("HoGroupSTM", "bit/ms"))
        self.pushButton_24.setText(_translate("HoGroupSTM", "Ramp to"))
        self.pushButton_21.setText(_translate("HoGroupSTM", "Stop ramp"))
        self.pushButton_23.setText(_translate("HoGroupSTM", "Ramp to"))
        self.pushButton_15.setText(_translate("HoGroupSTM", "Ramp to"))
        self.label_12.setText(_translate("HoGroupSTM", "Ramp speed"))
        self.groupBox_8.setTitle(_translate("HoGroupSTM", "Dither"))
        self.radioButton_16.setText(_translate("HoGroupSTM", "ON"))
        self.radioButton_17.setText(_translate("HoGroupSTM", "OFF"))
        self.groupBox_9.setTitle(_translate("HoGroupSTM", "DAC"))
        self.radioButton_18.setText(_translate("HoGroupSTM", "20 bit"))
        self.radioButton_19.setText(_translate("HoGroupSTM", "16 bit"))
        self.groupBox_14.setTitle(_translate("HoGroupSTM", "Setpoint"))
        self.groupBox_10.setTitle(_translate("HoGroupSTM", "Range"))
        self.radioButton_20.setText(_translate("HoGroupSTM", "+/- 2.5"))
        self.radioButton_21.setText(_translate("HoGroupSTM", "+/- 5"))
        self.radioButton_22.setText(_translate("HoGroupSTM", "+/-10"))
        self.Current.setWindowTitle(_translate("HoGroupSTM", "Current"))
        self.groupBox_6.setTitle(_translate("HoGroupSTM", "Setpoint"))
        self.groupBox_5.setTitle(_translate("HoGroupSTM", "Gain"))
        self.radioButton_15.setText(_translate("HoGroupSTM", "8"))
        self.radioButton_14.setText(_translate("HoGroupSTM", "9"))
        self.radioButton_13.setText(_translate("HoGroupSTM", "10"))
        self.groupBox_7.setTitle(_translate("HoGroupSTM", "Ramp"))
        self.label_8.setText(_translate("HoGroupSTM", "bit/ms"))
        self.pushButton_8.setText(_translate("HoGroupSTM", "Ramp to"))
        self.pushButton_7.setText(_translate("HoGroupSTM", "Ramp to"))
        self.pushButton_4.setText(_translate("HoGroupSTM", "Stop ramp"))
        self.pushButton_6.setText(_translate("HoGroupSTM", "Ramp to"))
        self.label_7.setText(_translate("HoGroupSTM", "Ramp speed"))
        self.pushButton_12.setText(_translate("HoGroupSTM", "Ramp to"))
        self.toolBar_2.setWindowTitle(_translate("HoGroupSTM", "toolBar_2"))
        self.actionOpen_O.setText(_translate("HoGroupSTM", "Open(&O)"))
        self.actionSave_S.setText(_translate("HoGroupSTM", "Save(&S)"))
        self.actionBias.setText(_translate("HoGroupSTM", "Bias"))
        self.actionCurrent.setText(_translate("HoGroupSTM", "Current"))
        self.actionZ.setText(_translate("HoGroupSTM", "Z"))
        self.actionScan.setText(_translate("HoGroupSTM", "Scan"))
        self.actionSpectra.setText(_translate("HoGroupSTM", "Spectra"))
        self.actionDeposition.setText(_translate("HoGroupSTM", "Deposition"))
        self.actionTrack.setText(_translate("HoGroupSTM", "Track"))
        self.actionHop.setText(_translate("HoGroupSTM", "Hop"))
        self.actionManipulation.setText(_translate("HoGroupSTM", "Manipulation"))
        self.actionOpen_Dialog.setText(_translate("HoGroupSTM","Open Dialog"))
        self.actionOpen_tipappr_Dialog.setText(_translate("HoGroupSTM", "Open Dialog"))
        self.actionElectronic_Test.setText(_translate("HoGroupSTM", "Electronic Test"))
        self.actionShow_All_A.setText(_translate("HoGroupSTM", "Show All(&A)"))
        self.actionManual_A.setText(_translate("HoGroupSTM", "Manual(&M)"))

    # Open dialog from menubar
    def opensettingwin(self):
        self.settingwidget.show()
    def opentipapprwin(self):
        self.tipapprwidget.show()
    def openelectronictest(self):
        self.electrotestwidget.show()
import logo_rc
