# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Scan.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Scan(object):
    def setupUi(self, Scan):
        Scan.setObjectName("Scan")
        Scan.setWindowModality(QtCore.Qt.NonModal)
        Scan.resize(1029, 549)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Scan.sizePolicy().hasHeightForWidth())
        Scan.setSizePolicy(sizePolicy)
        Scan.setMinimumSize(QtCore.QSize(1029, 549))
        self.gridLayout_10 = QtWidgets.QGridLayout(Scan)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.graph = QtWidgets.QWidget(Scan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph.sizePolicy().hasHeightForWidth())
        self.graph.setSizePolicy(sizePolicy)
        self.graph.setMinimumSize(QtCore.QSize(0, 0))
        self.graph.setObjectName("graph")
        self.gridLayout = QtWidgets.QGridLayout(self.graph)
        self.gridLayout.setContentsMargins(6, 6, 12, 6)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.toolButton = QtWidgets.QWidget(self.graph)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setMinimumSize(QtCore.QSize(484, 0))
        self.toolButton.setMaximumSize(QtCore.QSize(484, 16777215))
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.toolButton)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setHorizontalSpacing(6)
        self.gridLayout_11.setVerticalSpacing(3)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.pushButton_ZoomOut_ViewControl = QtWidgets.QPushButton(self.toolButton)
        self.pushButton_ZoomOut_ViewControl.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/toolbar/data/zoom_out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ZoomOut_ViewControl.setIcon(icon)
        self.pushButton_ZoomOut_ViewControl.setCheckable(True)
        self.pushButton_ZoomOut_ViewControl.setFlat(True)
        self.pushButton_ZoomOut_ViewControl.setObjectName("pushButton_ZoomOut_ViewControl")
        self.gridLayout_11.addWidget(self.pushButton_ZoomOut_ViewControl, 0, 4, 1, 1)
        self.pushButton_Full_ViewControl = QtWidgets.QPushButton(self.toolButton)
        self.pushButton_Full_ViewControl.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/toolbar/data/full_view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Full_ViewControl.setIcon(icon1)
        self.pushButton_Full_ViewControl.setFlat(True)
        self.pushButton_Full_ViewControl.setObjectName("pushButton_Full_ViewControl")
        self.gridLayout_11.addWidget(self.pushButton_Full_ViewControl, 0, 5, 1, 1)
        self.pushButton_Detail_ViewControl = QtWidgets.QPushButton(self.toolButton)
        self.pushButton_Detail_ViewControl.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/toolbar/data/detail_view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Detail_ViewControl.setIcon(icon2)
        self.pushButton_Detail_ViewControl.setFlat(True)
        self.pushButton_Detail_ViewControl.setObjectName("pushButton_Detail_ViewControl")
        self.gridLayout_11.addWidget(self.pushButton_Detail_ViewControl, 0, 6, 1, 1)
        self.pushButton_Move_ViewControl = QtWidgets.QPushButton(self.toolButton)
        self.pushButton_Move_ViewControl.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/toolbar/data/move.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Move_ViewControl.setIcon(icon3)
        self.pushButton_Move_ViewControl.setCheckable(True)
        self.pushButton_Move_ViewControl.setDefault(False)
        self.pushButton_Move_ViewControl.setFlat(True)
        self.pushButton_Move_ViewControl.setObjectName("pushButton_Move_ViewControl")
        self.gridLayout_11.addWidget(self.pushButton_Move_ViewControl, 0, 1, 1, 1)
        self.pushButton_ZoomIn_ViewControl = QtWidgets.QPushButton(self.toolButton)
        self.pushButton_ZoomIn_ViewControl.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/toolbar/data/zoom_in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ZoomIn_ViewControl.setIcon(icon4)
        self.pushButton_ZoomIn_ViewControl.setCheckable(True)
        self.pushButton_ZoomIn_ViewControl.setAutoDefault(False)
        self.pushButton_ZoomIn_ViewControl.setDefault(False)
        self.pushButton_ZoomIn_ViewControl.setFlat(True)
        self.pushButton_ZoomIn_ViewControl.setObjectName("pushButton_ZoomIn_ViewControl")
        self.gridLayout_11.addWidget(self.pushButton_ZoomIn_ViewControl, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.toolButton, 0, 0, 1, 3)
        self.graphicsView_Scan = GraphicsLayoutWidget(self.graph)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.graphicsView_Scan.sizePolicy().hasHeightForWidth())
        self.graphicsView_Scan.setSizePolicy(sizePolicy)
        self.graphicsView_Scan.setMinimumSize(QtCore.QSize(484, 484))
        self.graphicsView_Scan.setMaximumSize(QtCore.QSize(484, 484))
        self.graphicsView_Scan.setObjectName("graphicsView_Scan")
        self.gridLayout.addWidget(self.graphicsView_Scan, 1, 0, 1, 3)
        self.graphicsView_ColorBar_Scan = GraphicsLayoutWidget(self.graph)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_ColorBar_Scan.sizePolicy().hasHeightForWidth())
        self.graphicsView_ColorBar_Scan.setSizePolicy(sizePolicy)
        self.graphicsView_ColorBar_Scan.setMinimumSize(QtCore.QSize(20, 484))
        self.graphicsView_ColorBar_Scan.setMaximumSize(QtCore.QSize(20, 484))
        self.graphicsView_ColorBar_Scan.setObjectName("graphicsView_ColorBar_Scan")
        self.gridLayout.addWidget(self.graphicsView_ColorBar_Scan, 1, 3, 1, 1)
        self.gridLayout_10.addWidget(self.graph, 0, 0, 2, 1)
        self.operation = QtWidgets.QWidget(Scan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operation.sizePolicy().hasHeightForWidth())
        self.operation.setSizePolicy(sizePolicy)
        self.operation.setObjectName("operation")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.operation)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setSpacing(9)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.pallet = QtWidgets.QGroupBox(self.operation)
        self.pallet.setMinimumSize(QtCore.QSize(0, 0))
        self.pallet.setFlat(False)
        self.pallet.setObjectName("pallet")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.pallet)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.radioButton_Gray_Scan = QtWidgets.QRadioButton(self.pallet)
        self.radioButton_Gray_Scan.setChecked(True)
        self.radioButton_Gray_Scan.setObjectName("radioButton_Gray_Scan")
        self.gridLayout_6.addWidget(self.radioButton_Gray_Scan, 0, 0, 1, 1)
        self.radioButton_Color_Scan = QtWidgets.QRadioButton(self.pallet)
        self.radioButton_Color_Scan.setObjectName("radioButton_Color_Scan")
        self.gridLayout_6.addWidget(self.radioButton_Color_Scan, 1, 0, 1, 1)
        self.checkBox_PlaneFit_Scan = QtWidgets.QCheckBox(self.pallet)
        self.checkBox_PlaneFit_Scan.setObjectName("checkBox_PlaneFit_Scan")
        self.gridLayout_6.addWidget(self.checkBox_PlaneFit_Scan, 4, 0, 1, 1)
        self.radioButton_Reverse_Scan = QtWidgets.QRadioButton(self.pallet)
        self.radioButton_Reverse_Scan.setObjectName("radioButton_Reverse_Scan")
        self.gridLayout_6.addWidget(self.radioButton_Reverse_Scan, 2, 0, 1, 1)
        self.checkBox_Illuminated_Scan = QtWidgets.QCheckBox(self.pallet)
        self.checkBox_Illuminated_Scan.setObjectName("checkBox_Illuminated_Scan")
        self.gridLayout_6.addWidget(self.checkBox_Illuminated_Scan, 3, 0, 1, 1)
        self.gridLayout_12.addWidget(self.pallet, 1, 0, 2, 1)
        self.options = QtWidgets.QWidget(self.operation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.options.sizePolicy().hasHeightForWidth())
        self.options.setSizePolicy(sizePolicy)
        self.options.setMinimumSize(QtCore.QSize(0, 50))
        self.options.setObjectName("options")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.options)
        self.gridLayout_8.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_8.setHorizontalSpacing(12)
        self.gridLayout_8.setVerticalSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButton_SendOptions_Scan = QtWidgets.QPushButton(self.options)
        self.pushButton_SendOptions_Scan.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_SendOptions_Scan.setObjectName("pushButton_SendOptions_Scan")
        self.gridLayout_8.addWidget(self.pushButton_SendOptions_Scan, 0, 0, 1, 1)
        self.pushButton_ScanOptions_Scan = QtWidgets.QPushButton(self.options)
        self.pushButton_ScanOptions_Scan.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_ScanOptions_Scan.setObjectName("pushButton_ScanOptions_Scan")
        self.gridLayout_8.addWidget(self.pushButton_ScanOptions_Scan, 0, 1, 1, 1)
        self.gridLayout_12.addWidget(self.options, 1, 1, 1, 1)
        self.ScanControl = QtWidgets.QFrame(self.operation)
        self.ScanControl.setMinimumSize(QtCore.QSize(0, 180))
        self.ScanControl.setFrameShape(QtWidgets.QFrame.Box)
        self.ScanControl.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ScanControl.setObjectName("ScanControl")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.ScanControl)
        self.gridLayout_7.setVerticalSpacing(9)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_15 = QtWidgets.QLabel(self.ScanControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.ScanControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.ScanControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName("label_18")
        self.gridLayout_7.addWidget(self.label_18, 2, 0, 1, 1)
        self.pushButton_SeqList_ScanControl = QtWidgets.QPushButton(self.ScanControl)
        self.pushButton_SeqList_ScanControl.setMinimumSize(QtCore.QSize(0, 26))
        self.pushButton_SeqList_ScanControl.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButton_SeqList_ScanControl.setObjectName("pushButton_SeqList_ScanControl")
        self.gridLayout_7.addWidget(self.pushButton_SeqList_ScanControl, 2, 3, 1, 1)
        self.label_Seq_ScanControl = QtWidgets.QLabel(self.ScanControl)
        self.label_Seq_ScanControl.setMinimumSize(QtCore.QSize(60, 26))
        self.label_Seq_ScanControl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_Seq_ScanControl.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_Seq_ScanControl.setText("")
        self.label_Seq_ScanControl.setObjectName("label_Seq_ScanControl")
        self.gridLayout_7.addWidget(self.label_Seq_ScanControl, 2, 1, 1, 1)
        self.scrollBar_StepSize_ScanControl = QtWidgets.QScrollBar(self.ScanControl)
        self.scrollBar_StepSize_ScanControl.setMinimumSize(QtCore.QSize(200, 0))
        self.scrollBar_StepSize_ScanControl.setMinimum(1)
        self.scrollBar_StepSize_ScanControl.setMaximum(65535)
        self.scrollBar_StepSize_ScanControl.setSingleStep(10)
        self.scrollBar_StepSize_ScanControl.setPageStep(100)
        self.scrollBar_StepSize_ScanControl.setProperty("value", 512)
        self.scrollBar_StepSize_ScanControl.setOrientation(QtCore.Qt.Horizontal)
        self.scrollBar_StepSize_ScanControl.setObjectName("scrollBar_StepSize_ScanControl")
        self.gridLayout_7.addWidget(self.scrollBar_StepSize_ScanControl, 1, 3, 1, 1)
        self.scrollBar_ScanSize_ScanControl = QtWidgets.QScrollBar(self.ScanControl)
        self.scrollBar_ScanSize_ScanControl.setMinimumSize(QtCore.QSize(200, 0))
        self.scrollBar_ScanSize_ScanControl.setMinimum(1)
        self.scrollBar_ScanSize_ScanControl.setMaximum(1024)
        self.scrollBar_ScanSize_ScanControl.setProperty("value", 128)
        self.scrollBar_ScanSize_ScanControl.setOrientation(QtCore.Qt.Horizontal)
        self.scrollBar_ScanSize_ScanControl.setObjectName("scrollBar_ScanSize_ScanControl")
        self.gridLayout_7.addWidget(self.scrollBar_ScanSize_ScanControl, 0, 3, 1, 1)
        self.spinBox_StepSize_ScanControl = QtWidgets.QSpinBox(self.ScanControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_StepSize_ScanControl.sizePolicy().hasHeightForWidth())
        self.spinBox_StepSize_ScanControl.setSizePolicy(sizePolicy)
        self.spinBox_StepSize_ScanControl.setMinimumSize(QtCore.QSize(0, 26))
        self.spinBox_StepSize_ScanControl.setMaximumSize(QtCore.QSize(16777215, 28))
        self.spinBox_StepSize_ScanControl.setMinimum(1)
        self.spinBox_StepSize_ScanControl.setMaximum(65535)
        self.spinBox_StepSize_ScanControl.setSingleStep(1)
        self.spinBox_StepSize_ScanControl.setProperty("value", 512)
        self.spinBox_StepSize_ScanControl.setObjectName("spinBox_StepSize_ScanControl")
        self.gridLayout_7.addWidget(self.spinBox_StepSize_ScanControl, 1, 1, 1, 1)
        self.spinBox_ScanSize_ScanControl = QtWidgets.QSpinBox(self.ScanControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_ScanSize_ScanControl.sizePolicy().hasHeightForWidth())
        self.spinBox_ScanSize_ScanControl.setSizePolicy(sizePolicy)
        self.spinBox_ScanSize_ScanControl.setMinimumSize(QtCore.QSize(0, 26))
        self.spinBox_ScanSize_ScanControl.setMaximumSize(QtCore.QSize(16777215, 28))
        self.spinBox_ScanSize_ScanControl.setMinimum(1)
        self.spinBox_ScanSize_ScanControl.setMaximum(1024)
        self.spinBox_ScanSize_ScanControl.setProperty("value", 128)
        self.spinBox_ScanSize_ScanControl.setObjectName("spinBox_ScanSize_ScanControl")
        self.gridLayout_7.addWidget(self.spinBox_ScanSize_ScanControl, 0, 1, 1, 1)
        self.gridLayout_12.addWidget(self.ScanControl, 2, 1, 1, 1)
        self.Buttons = QtWidgets.QWidget(self.operation)
        self.Buttons.setMinimumSize(QtCore.QSize(0, 63))
        self.Buttons.setObjectName("Buttons")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.Buttons)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.pushButton_Info_Scan = QtWidgets.QPushButton(self.Buttons)
        self.pushButton_Info_Scan.setMinimumSize(QtCore.QSize(0, 42))
        self.pushButton_Info_Scan.setObjectName("pushButton_Info_Scan")
        self.gridLayout_9.addWidget(self.pushButton_Info_Scan, 0, 0, 1, 1)
        self.pushButton_Load_Scan = QtWidgets.QPushButton(self.Buttons)
        self.pushButton_Load_Scan.setMinimumSize(QtCore.QSize(0, 42))
        self.pushButton_Load_Scan.setObjectName("pushButton_Load_Scan")
        self.gridLayout_9.addWidget(self.pushButton_Load_Scan, 0, 1, 1, 1)
        self.pushButton_SaveAll_Scan = QtWidgets.QPushButton(self.Buttons)
        self.pushButton_SaveAll_Scan.setMinimumSize(QtCore.QSize(0, 42))
        self.pushButton_SaveAll_Scan.setObjectName("pushButton_SaveAll_Scan")
        self.gridLayout_9.addWidget(self.pushButton_SaveAll_Scan, 0, 2, 1, 1)
        self.pushButton_Start_Scan = QtWidgets.QPushButton(self.Buttons)
        self.pushButton_Start_Scan.setEnabled(False)
        self.pushButton_Start_Scan.setMinimumSize(QtCore.QSize(140, 42))
        self.pushButton_Start_Scan.setObjectName("pushButton_Start_Scan")
        self.gridLayout_9.addWidget(self.pushButton_Start_Scan, 0, 3, 1, 1)
        self.gridLayout_12.addWidget(self.Buttons, 3, 0, 1, 2)
        self.XY = QtWidgets.QFrame(self.operation)
        self.XY.setMinimumSize(QtCore.QSize(0, 212))
        self.XY.setFrameShape(QtWidgets.QFrame.Box)
        self.XY.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.XY.setMidLineWidth(0)
        self.XY.setObjectName("XY")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.XY)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.XY_in = QtWidgets.QWidget(self.XY)
        self.XY_in.setMinimumSize(QtCore.QSize(0, 140))
        self.XY_in.setObjectName("XY_in")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.XY_in)
        self.gridLayout_3.setSpacing(9)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(self.XY_in)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 1, 1, 1)
        self.scrollBar_Xin_XY = QtWidgets.QScrollBar(self.XY_in)
        self.scrollBar_Xin_XY.setMaximum(65535)
        self.scrollBar_Xin_XY.setSliderPosition(32768)
        self.scrollBar_Xin_XY.setOrientation(QtCore.Qt.Horizontal)
        self.scrollBar_Xin_XY.setObjectName("scrollBar_Xin_XY")
        self.gridLayout_3.addWidget(self.scrollBar_Xin_XY, 3, 0, 1, 2)
        self.spinBox_XinInput_XY = QtWidgets.QSpinBox(self.XY_in)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_XinInput_XY.sizePolicy().hasHeightForWidth())
        self.spinBox_XinInput_XY.setSizePolicy(sizePolicy)
        self.spinBox_XinInput_XY.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_XinInput_XY.setMaximumSize(QtCore.QSize(16777215, 26))
        self.spinBox_XinInput_XY.setMinimum(-32768)
        self.spinBox_XinInput_XY.setMaximum(32767)
        self.spinBox_XinInput_XY.setObjectName("spinBox_XinInput_XY")
        self.gridLayout_3.addWidget(self.spinBox_XinInput_XY, 1, 0, 1, 1)
        self.spinBox_XinIndication_XY = QtWidgets.QSpinBox(self.XY_in)
        self.spinBox_XinIndication_XY.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_XinIndication_XY.sizePolicy().hasHeightForWidth())
        self.spinBox_XinIndication_XY.setSizePolicy(sizePolicy)
        self.spinBox_XinIndication_XY.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_XinIndication_XY.setMaximumSize(QtCore.QSize(16777215, 26))
        self.spinBox_XinIndication_XY.setMinimum(-32768)
        self.spinBox_XinIndication_XY.setMaximum(32767)
        self.spinBox_XinIndication_XY.setObjectName("spinBox_XinIndication_XY")
        self.gridLayout_3.addWidget(self.spinBox_XinIndication_XY, 2, 0, 1, 1)
        self.spinBox_YinIndication_XY = QtWidgets.QSpinBox(self.XY_in)
        self.spinBox_YinIndication_XY.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_YinIndication_XY.sizePolicy().hasHeightForWidth())
        self.spinBox_YinIndication_XY.setSizePolicy(sizePolicy)
        self.spinBox_YinIndication_XY.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_YinIndication_XY.setMaximumSize(QtCore.QSize(16777215, 26))
        self.spinBox_YinIndication_XY.setMinimum(-32768)
        self.spinBox_YinIndication_XY.setMaximum(32767)
        self.spinBox_YinIndication_XY.setObjectName("spinBox_YinIndication_XY")
        self.gridLayout_3.addWidget(self.spinBox_YinIndication_XY, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.XY_in)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.spinBox_YinInput_XY = QtWidgets.QSpinBox(self.XY_in)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_YinInput_XY.sizePolicy().hasHeightForWidth())
        self.spinBox_YinInput_XY.setSizePolicy(sizePolicy)
        self.spinBox_YinInput_XY.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_YinInput_XY.setMaximumSize(QtCore.QSize(16777215, 26))
        self.spinBox_YinInput_XY.setMinimum(-32768)
        self.spinBox_YinInput_XY.setMaximum(32767)
        self.spinBox_YinInput_XY.setObjectName("spinBox_YinInput_XY")
        self.gridLayout_3.addWidget(self.spinBox_YinInput_XY, 1, 1, 1, 1)
        self.scrollBar_Yin_XY = QtWidgets.QScrollBar(self.XY_in)
        self.scrollBar_Yin_XY.setMaximum(65535)
        self.scrollBar_Yin_XY.setSliderPosition(32768)
        self.scrollBar_Yin_XY.setTracking(True)
        self.scrollBar_Yin_XY.setOrientation(QtCore.Qt.Vertical)
        self.scrollBar_Yin_XY.setInvertedAppearance(True)
        self.scrollBar_Yin_XY.setInvertedControls(True)
        self.scrollBar_Yin_XY.setObjectName("scrollBar_Yin_XY")
        self.gridLayout_3.addWidget(self.scrollBar_Yin_XY, 0, 2, 4, 1)
        self.gridLayout_5.addWidget(self.XY_in, 0, 1, 1, 1)
        self.XY_gain = QtWidgets.QWidget(self.XY)
        self.XY_gain.setMinimumSize(QtCore.QSize(0, 40))
        self.XY_gain.setObjectName("XY_gain")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.XY_gain)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_13 = QtWidgets.QLabel(self.XY_gain)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 0, 0, 1, 1)
        self.radioButton_Gain0_1_XY = QtWidgets.QRadioButton(self.XY_gain)
        self.radioButton_Gain0_1_XY.setEnabled(False)
        self.radioButton_Gain0_1_XY.setObjectName("radioButton_Gain0_1_XY")
        self.gridLayout_4.addWidget(self.radioButton_Gain0_1_XY, 0, 1, 1, 1)
        self.radioButton_Gain1_XY = QtWidgets.QRadioButton(self.XY_gain)
        self.radioButton_Gain1_XY.setEnabled(False)
        self.radioButton_Gain1_XY.setChecked(True)
        self.radioButton_Gain1_XY.setObjectName("radioButton_Gain1_XY")
        self.gridLayout_4.addWidget(self.radioButton_Gain1_XY, 0, 2, 1, 1)
        self.radioButton_Gain10_XY = QtWidgets.QRadioButton(self.XY_gain)
        self.radioButton_Gain10_XY.setEnabled(False)
        self.radioButton_Gain10_XY.setObjectName("radioButton_Gain10_XY")
        self.gridLayout_4.addWidget(self.radioButton_Gain10_XY, 0, 3, 1, 1)
        self.pushButton_Zero_XY = QtWidgets.QPushButton(self.XY_gain)
        self.pushButton_Zero_XY.setEnabled(False)
        self.pushButton_Zero_XY.setMinimumSize(QtCore.QSize(90, 30))
        self.pushButton_Zero_XY.setObjectName("pushButton_Zero_XY")
        self.gridLayout_4.addWidget(self.pushButton_Zero_XY, 0, 4, 1, 1)
        self.pushButton_Send_XY = QtWidgets.QPushButton(self.XY_gain)
        self.pushButton_Send_XY.setEnabled(False)
        self.pushButton_Send_XY.setMinimumSize(QtCore.QSize(90, 30))
        self.pushButton_Send_XY.setObjectName("pushButton_Send_XY")
        self.gridLayout_4.addWidget(self.pushButton_Send_XY, 0, 5, 1, 1)
        self.gridLayout_5.addWidget(self.XY_gain, 1, 0, 1, 2)
        self.XY_offset = QtWidgets.QWidget(self.XY)
        self.XY_offset.setMinimumSize(QtCore.QSize(0, 140))
        self.XY_offset.setObjectName("XY_offset")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.XY_offset)
        self.gridLayout_2.setSpacing(9)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollBar_Yoffset_XY = QtWidgets.QScrollBar(self.XY_offset)
        self.scrollBar_Yoffset_XY.setMaximum(65535)
        self.scrollBar_Yoffset_XY.setSliderPosition(32768)
        self.scrollBar_Yoffset_XY.setTracking(True)
        self.scrollBar_Yoffset_XY.setInvertedAppearance(True)
        self.scrollBar_Yoffset_XY.setInvertedControls(True)
        self.scrollBar_Yoffset_XY.setObjectName("scrollBar_Yoffset_XY")
        self.gridLayout_2.addWidget(self.scrollBar_Yoffset_XY, 0, 2, 4, 1)
        self.spinBox_YoffsetIndication_XY = QtWidgets.QSpinBox(self.XY_offset)
        self.spinBox_YoffsetIndication_XY.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_YoffsetIndication_XY.sizePolicy().hasHeightForWidth())
        self.spinBox_YoffsetIndication_XY.setSizePolicy(sizePolicy)
        self.spinBox_YoffsetIndication_XY.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_YoffsetIndication_XY.setMaximumSize(QtCore.QSize(16777215, 26))
        self.spinBox_YoffsetIndication_XY.setMinimum(-32768)
        self.spinBox_YoffsetIndication_XY.setMaximum(32767)
        self.spinBox_YoffsetIndication_XY.setObjectName("spinBox_YoffsetIndication_XY")
        self.gridLayout_2.addWidget(self.spinBox_YoffsetIndication_XY, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.XY_offset)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.scrollBar_Xoffset_XY = QtWidgets.QScrollBar(self.XY_offset)
        self.scrollBar_Xoffset_XY.setMaximum(65535)
        self.scrollBar_Xoffset_XY.setSliderPosition(32768)
        self.scrollBar_Xoffset_XY.setOrientation(QtCore.Qt.Horizontal)
        self.scrollBar_Xoffset_XY.setObjectName("scrollBar_Xoffset_XY")
        self.gridLayout_2.addWidget(self.scrollBar_Xoffset_XY, 3, 0, 1, 2)
        self.spinBox_YoffsetInput_XY = QtWidgets.QSpinBox(self.XY_offset)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_YoffsetInput_XY.sizePolicy().hasHeightForWidth())
        self.spinBox_YoffsetInput_XY.setSizePolicy(sizePolicy)
        self.spinBox_YoffsetInput_XY.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_YoffsetInput_XY.setMaximumSize(QtCore.QSize(16777215, 26))
        self.spinBox_YoffsetInput_XY.setMinimum(-32768)
        self.spinBox_YoffsetInput_XY.setMaximum(32767)
        self.spinBox_YoffsetInput_XY.setObjectName("spinBox_YoffsetInput_XY")
        self.gridLayout_2.addWidget(self.spinBox_YoffsetInput_XY, 1, 1, 1, 1)
        self.spinBox_XoffsetInput_XY = QtWidgets.QSpinBox(self.XY_offset)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_XoffsetInput_XY.sizePolicy().hasHeightForWidth())
        self.spinBox_XoffsetInput_XY.setSizePolicy(sizePolicy)
        self.spinBox_XoffsetInput_XY.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_XoffsetInput_XY.setMaximumSize(QtCore.QSize(16777215, 26))
        self.spinBox_XoffsetInput_XY.setMinimum(-32768)
        self.spinBox_XoffsetInput_XY.setMaximum(32767)
        self.spinBox_XoffsetInput_XY.setObjectName("spinBox_XoffsetInput_XY")
        self.gridLayout_2.addWidget(self.spinBox_XoffsetInput_XY, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.XY_offset)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox_XoffsetIndication_XY = QtWidgets.QSpinBox(self.XY_offset)
        self.spinBox_XoffsetIndication_XY.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_XoffsetIndication_XY.sizePolicy().hasHeightForWidth())
        self.spinBox_XoffsetIndication_XY.setSizePolicy(sizePolicy)
        self.spinBox_XoffsetIndication_XY.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_XoffsetIndication_XY.setMaximumSize(QtCore.QSize(16777215, 26))
        self.spinBox_XoffsetIndication_XY.setMinimum(-32768)
        self.spinBox_XoffsetIndication_XY.setMaximum(32767)
        self.spinBox_XoffsetIndication_XY.setObjectName("spinBox_XoffsetIndication_XY")
        self.gridLayout_2.addWidget(self.spinBox_XoffsetIndication_XY, 2, 0, 1, 1)
        self.gridLayout_5.addWidget(self.XY_offset, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.XY, 0, 0, 1, 2)
        self.gridLayout_10.addWidget(self.operation, 0, 1, 2, 1)

        self.retranslateUi(Scan)
        QtCore.QMetaObject.connectSlotsByName(Scan)

    def retranslateUi(self, Scan):
        _translate = QtCore.QCoreApplication.translate
        Scan.setWindowTitle(_translate("Scan", "Scan"))
        self.pallet.setTitle(_translate("Scan", "Pallet"))
        self.radioButton_Gray_Scan.setText(_translate("Scan", "Gray"))
        self.radioButton_Color_Scan.setText(_translate("Scan", "Color"))
        self.checkBox_PlaneFit_Scan.setText(_translate("Scan", "Plane fit"))
        self.radioButton_Reverse_Scan.setText(_translate("Scan", "Reverse"))
        self.checkBox_Illuminated_Scan.setText(_translate("Scan", "Illuminated "))
        self.pushButton_SendOptions_Scan.setText(_translate("Scan", "Send options"))
        self.pushButton_ScanOptions_Scan.setText(_translate("Scan", "Scan options"))
        self.label_15.setText(_translate("Scan", "Step size"))
        self.label_14.setText(_translate("Scan", "Scan size"))
        self.label_18.setText(_translate("Scan", "Sequence"))
        self.pushButton_SeqList_ScanControl.setText(_translate("Scan", "Sequence List"))
        self.pushButton_Info_Scan.setText(_translate("Scan", "Info"))
        self.pushButton_Load_Scan.setText(_translate("Scan", "Load"))
        self.pushButton_SaveAll_Scan.setText(_translate("Scan", "Save All"))
        self.pushButton_Start_Scan.setText(_translate("Scan", "Start"))
        self.label_8.setText(_translate("Scan", "Y in"))
        self.label_7.setText(_translate("Scan", "X in"))
        self.label_13.setText(_translate("Scan", "X/Y gain"))
        self.radioButton_Gain0_1_XY.setText(_translate("Scan", "0.1"))
        self.radioButton_Gain1_XY.setText(_translate("Scan", "1"))
        self.radioButton_Gain10_XY.setText(_translate("Scan", "10"))
        self.pushButton_Zero_XY.setText(_translate("Scan", "Zero"))
        self.pushButton_Send_XY.setText(_translate("Scan", "Send"))
        self.label_2.setText(_translate("Scan", "Y offset"))
        self.label.setText(_translate("Scan", "X offset"))
from pyqtgraph import GraphicsLayoutWidget
import logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Scan = QtWidgets.QWidget()
    ui = Ui_Scan()
    ui.setupUi(Scan)
    Scan.show()
    sys.exit(app.exec_())
