# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SequenceEditor.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SequenceEditor(object):
    def setupUi(self, SequenceEditor):
        SequenceEditor.setObjectName("SequenceEditor")
        SequenceEditor.setWindowModality(QtCore.Qt.ApplicationModal)
        SequenceEditor.resize(1069, 441)
        self.gridLayout_6 = QtWidgets.QGridLayout(SequenceEditor)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.Mode = QtWidgets.QGroupBox(SequenceEditor)
        self.Mode.setObjectName("Mode")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Mode)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioButton_Deposition_Mode = QtWidgets.QRadioButton(self.Mode)
        self.radioButton_Deposition_Mode.setObjectName("radioButton_Deposition_Mode")
        self.gridLayout_2.addWidget(self.radioButton_Deposition_Mode, 0, 0, 1, 1)
        self.radioButton_ReadSeq_Mode = QtWidgets.QRadioButton(self.Mode)
        self.radioButton_ReadSeq_Mode.setObjectName("radioButton_ReadSeq_Mode")
        self.gridLayout_2.addWidget(self.radioButton_ReadSeq_Mode, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.Mode, 0, 1, 1, 1)
        self.Bias = QtWidgets.QGroupBox(SequenceEditor)
        self.Bias.setObjectName("Bias")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Bias)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.radioButton_16bit_Bias = QtWidgets.QRadioButton(self.Bias)
        self.radioButton_16bit_Bias.setObjectName("radioButton_16bit_Bias")
        self.gridLayout_3.addWidget(self.radioButton_16bit_Bias, 0, 0, 1, 1)
        self.radioButton_20bit_Bias = QtWidgets.QRadioButton(self.Bias)
        self.radioButton_20bit_Bias.setObjectName("radioButton_20bit_Bias")
        self.gridLayout_3.addWidget(self.radioButton_20bit_Bias, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.Bias, 0, 2, 1, 1)
        self.Edit = QtWidgets.QWidget(SequenceEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Edit.sizePolicy().hasHeightForWidth())
        self.Edit.setSizePolicy(sizePolicy)
        self.Edit.setMinimumSize(QtCore.QSize(0, 0))
        self.Edit.setObjectName("Edit")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Edit)
        self.gridLayout_4.setVerticalSpacing(14)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_Simulation_Edit = QtWidgets.QPushButton(self.Edit)
        self.pushButton_Simulation_Edit.setMinimumSize(QtCore.QSize(120, 36))
        self.pushButton_Simulation_Edit.setObjectName("pushButton_Simulation_Edit")
        self.gridLayout_4.addWidget(self.pushButton_Simulation_Edit, 3, 1, 1, 1)
        self.pushButton_Save_Edit = QtWidgets.QPushButton(self.Edit)
        self.pushButton_Save_Edit.setMinimumSize(QtCore.QSize(120, 36))
        self.pushButton_Save_Edit.setObjectName("pushButton_Save_Edit")
        self.gridLayout_4.addWidget(self.pushButton_Save_Edit, 2, 0, 1, 1)
        self.pushButton_Remove_Edit = QtWidgets.QPushButton(self.Edit)
        self.pushButton_Remove_Edit.setMinimumSize(QtCore.QSize(120, 36))
        self.pushButton_Remove_Edit.setObjectName("pushButton_Remove_Edit")
        self.gridLayout_4.addWidget(self.pushButton_Remove_Edit, 0, 1, 1, 1)
        self.pushButton_Insert_Edit = QtWidgets.QPushButton(self.Edit)
        self.pushButton_Insert_Edit.setMinimumSize(QtCore.QSize(120, 36))
        self.pushButton_Insert_Edit.setObjectName("pushButton_Insert_Edit")
        self.gridLayout_4.addWidget(self.pushButton_Insert_Edit, 1, 0, 1, 1)
        self.pushButton_Validate_Edit = QtWidgets.QPushButton(self.Edit)
        self.pushButton_Validate_Edit.setMinimumSize(QtCore.QSize(120, 36))
        self.pushButton_Validate_Edit.setObjectName("pushButton_Validate_Edit")
        self.gridLayout_4.addWidget(self.pushButton_Validate_Edit, 3, 0, 1, 1)
        self.pushButton_AddStep_Edit = QtWidgets.QPushButton(self.Edit)
        self.pushButton_AddStep_Edit.setMinimumSize(QtCore.QSize(120, 36))
        self.pushButton_AddStep_Edit.setObjectName("pushButton_AddStep_Edit")
        self.gridLayout_4.addWidget(self.pushButton_AddStep_Edit, 0, 0, 1, 1)
        self.pushButton_AddtoList_Edit = QtWidgets.QPushButton(self.Edit)
        self.pushButton_AddtoList_Edit.setMinimumSize(QtCore.QSize(120, 36))
        self.pushButton_AddtoList_Edit.setObjectName("pushButton_AddtoList_Edit")
        self.gridLayout_4.addWidget(self.pushButton_AddtoList_Edit, 4, 0, 1, 1)
        self.pushButton_Cancel_Edit = QtWidgets.QPushButton(self.Edit)
        self.pushButton_Cancel_Edit.setMinimumSize(QtCore.QSize(120, 36))
        self.pushButton_Cancel_Edit.setObjectName("pushButton_Cancel_Edit")
        self.gridLayout_4.addWidget(self.pushButton_Cancel_Edit, 4, 1, 1, 1)
        self.pushButton_Clear_Edit = QtWidgets.QPushButton(self.Edit)
        self.pushButton_Clear_Edit.setMinimumSize(QtCore.QSize(120, 36))
        self.pushButton_Clear_Edit.setObjectName("pushButton_Clear_Edit")
        self.gridLayout_4.addWidget(self.pushButton_Clear_Edit, 1, 1, 1, 1)
        self.pushButton_SaveAs_Edit = QtWidgets.QPushButton(self.Edit)
        self.pushButton_SaveAs_Edit.setMinimumSize(QtCore.QSize(120, 36))
        self.pushButton_SaveAs_Edit.setObjectName("pushButton_SaveAs_Edit")
        self.gridLayout_4.addWidget(self.pushButton_SaveAs_Edit, 2, 1, 1, 1)
        self.gridLayout_6.addWidget(self.Edit, 2, 1, 1, 2)
        self.Preamp = QtWidgets.QGroupBox(SequenceEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Preamp.sizePolicy().hasHeightForWidth())
        self.Preamp.setSizePolicy(sizePolicy)
        self.Preamp.setMinimumSize(QtCore.QSize(0, 60))
        self.Preamp.setObjectName("Preamp")
        self.gridLayout = QtWidgets.QGridLayout(self.Preamp)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_Gain8_Preamp = QtWidgets.QRadioButton(self.Preamp)
        self.radioButton_Gain8_Preamp.setObjectName("radioButton_Gain8_Preamp")
        self.gridLayout.addWidget(self.radioButton_Gain8_Preamp, 0, 0, 1, 1)
        self.radioButton_Gain9_Preamp = QtWidgets.QRadioButton(self.Preamp)
        self.radioButton_Gain9_Preamp.setObjectName("radioButton_Gain9_Preamp")
        self.gridLayout.addWidget(self.radioButton_Gain9_Preamp, 0, 1, 1, 1)
        self.radioButton_Gain10_Preamp = QtWidgets.QRadioButton(self.Preamp)
        self.radioButton_Gain10_Preamp.setObjectName("radioButton_Gain10_Preamp")
        self.gridLayout.addWidget(self.radioButton_Gain10_Preamp, 0, 2, 1, 1)
        self.gridLayout_6.addWidget(self.Preamp, 1, 1, 1, 2)
        self.Table = QtWidgets.QWidget(SequenceEditor)
        self.Table.setMinimumSize(QtCore.QSize(360, 0))
        self.Table.setObjectName("Table")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.Table)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.table_Content_SeqEditor = QtWidgets.QTableWidget(self.Table)
        self.table_Content_SeqEditor.setColumnCount(7)
        self.table_Content_SeqEditor.setObjectName("table_Content_SeqEditor")
        self.table_Content_SeqEditor.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.table_Content_SeqEditor.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_Content_SeqEditor.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_Content_SeqEditor.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_Content_SeqEditor.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_Content_SeqEditor.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_Content_SeqEditor.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Content_SeqEditor.setHorizontalHeaderItem(6, item)
        self.gridLayout_5.addWidget(self.table_Content_SeqEditor, 1, 0, 1, 6)
        self.label = QtWidgets.QLabel(self.Table)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 2, 1, 1)
        self.checkBox_DitherB__SeqEditor = QtWidgets.QCheckBox(self.Table)
        self.checkBox_DitherB__SeqEditor.setMinimumSize(QtCore.QSize(100, 0))
        self.checkBox_DitherB__SeqEditor.setObjectName("checkBox_DitherB__SeqEditor")
        self.gridLayout_5.addWidget(self.checkBox_DitherB__SeqEditor, 0, 3, 1, 1)
        self.lineEdit_Name_SeqEditor = QtWidgets.QLineEdit(self.Table)
        self.lineEdit_Name_SeqEditor.setObjectName("lineEdit_Name_SeqEditor")
        self.gridLayout_5.addWidget(self.lineEdit_Name_SeqEditor, 0, 1, 1, 1)
        self.checkBox_FeedbackON__SeqEditor = QtWidgets.QCheckBox(self.Table)
        self.checkBox_FeedbackON__SeqEditor.setMinimumSize(QtCore.QSize(100, 0))
        self.checkBox_FeedbackON__SeqEditor.setObjectName("checkBox_FeedbackON__SeqEditor")
        self.gridLayout_5.addWidget(self.checkBox_FeedbackON__SeqEditor, 0, 5, 1, 1)
        self.checkBox_DitherZ__SeqEditor = QtWidgets.QCheckBox(self.Table)
        self.checkBox_DitherZ__SeqEditor.setMinimumSize(QtCore.QSize(100, 0))
        self.checkBox_DitherZ__SeqEditor.setObjectName("checkBox_DitherZ__SeqEditor")
        self.gridLayout_5.addWidget(self.checkBox_DitherZ__SeqEditor, 0, 4, 1, 1)
        self.gridLayout_6.addWidget(self.Table, 0, 0, 3, 1)

        self.retranslateUi(SequenceEditor)
        QtCore.QMetaObject.connectSlotsByName(SequenceEditor)

    def retranslateUi(self, SequenceEditor):
        _translate = QtCore.QCoreApplication.translate
        SequenceEditor.setWindowTitle(_translate("SequenceEditor", "Sequence Editor"))
        self.Mode.setTitle(_translate("SequenceEditor", "Mode"))
        self.radioButton_Deposition_Mode.setText(_translate("SequenceEditor", "Deposition"))
        self.radioButton_ReadSeq_Mode.setText(_translate("SequenceEditor", "Read Sequence"))
        self.Bias.setTitle(_translate("SequenceEditor", "Bias bit"))
        self.radioButton_16bit_Bias.setText(_translate("SequenceEditor", "16 bit"))
        self.radioButton_20bit_Bias.setText(_translate("SequenceEditor", "20 bit"))
        self.pushButton_Simulation_Edit.setText(_translate("SequenceEditor", "Run Simulation"))
        self.pushButton_Save_Edit.setText(_translate("SequenceEditor", "Save"))
        self.pushButton_Remove_Edit.setText(_translate("SequenceEditor", "Remove selected"))
        self.pushButton_Insert_Edit.setText(_translate("SequenceEditor", "Insert Above"))
        self.pushButton_Validate_Edit.setText(_translate("SequenceEditor", "Validate"))
        self.pushButton_AddStep_Edit.setText(_translate("SequenceEditor", "Add Step"))
        self.pushButton_AddtoList_Edit.setText(_translate("SequenceEditor", "Add to list"))
        self.pushButton_Cancel_Edit.setText(_translate("SequenceEditor", "Cancel"))
        self.pushButton_Clear_Edit.setText(_translate("SequenceEditor", "Clear"))
        self.pushButton_SaveAs_Edit.setText(_translate("SequenceEditor", "Save as"))
        self.Preamp.setTitle(_translate("SequenceEditor", "Preamp gain"))
        self.radioButton_Gain8_Preamp.setText(_translate("SequenceEditor", "8"))
        self.radioButton_Gain9_Preamp.setText(_translate("SequenceEditor", "9"))
        self.radioButton_Gain10_Preamp.setText(_translate("SequenceEditor", "10"))
        item = self.table_Content_SeqEditor.horizontalHeaderItem(0)
        item.setText(_translate("SequenceEditor", "Command"))
        item = self.table_Content_SeqEditor.horizontalHeaderItem(1)
        item.setText(_translate("SequenceEditor", "Channel"))
        item = self.table_Content_SeqEditor.horizontalHeaderItem(2)
        item.setText(_translate("SequenceEditor", "Option 1"))
        item = self.table_Content_SeqEditor.horizontalHeaderItem(3)
        item.setText(_translate("SequenceEditor", "Option 2"))
        item = self.table_Content_SeqEditor.horizontalHeaderItem(4)
        item.setText(_translate("SequenceEditor", "data"))
        item = self.table_Content_SeqEditor.horizontalHeaderItem(5)
        item.setText(_translate("SequenceEditor", "units"))
        self.label.setText(_translate("SequenceEditor", "Name"))
        self.checkBox_DitherB__SeqEditor.setText(_translate("SequenceEditor", "DitherB"))
        self.checkBox_FeedbackON__SeqEditor.setText(_translate("SequenceEditor", "Feedback"))
        self.checkBox_DitherZ__SeqEditor.setText(_translate("SequenceEditor", "DitherZ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SequenceEditor = QtWidgets.QWidget()
    ui = Ui_SequenceEditor()
    ui.setupUi(SequenceEditor)
    SequenceEditor.show()
    sys.exit(app.exec_())
