# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Setting.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Setting(object):
    def setupUi(self, Setting):
        Setting.setObjectName("Setting")
        Setting.setWindowModality(QtCore.Qt.ApplicationModal)
        Setting.resize(360, 348)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Setting.sizePolicy().hasHeightForWidth())
        Setting.setSizePolicy(sizePolicy)
        Setting.setMinimumSize(QtCore.QSize(360, 220))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/menuIcon/settingiconblack.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Setting.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Setting)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_5 = QtWidgets.QWidget(Setting)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.widget_5)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_5.setContentsMargins(-1, 3, -1, 3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.saveButton = QtWidgets.QPushButton(self.widget_3)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout_5.addWidget(self.saveButton, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget_3, 3, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.widget_5)
        self.widget.setObjectName("widget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_6.setContentsMargins(-1, 3, -1, 3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setIndent(0)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 3, 1, 1)
        self.comboBox_baud = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_baud.sizePolicy().hasHeightForWidth())
        self.comboBox_baud.setSizePolicy(sizePolicy)
        self.comboBox_baud.setObjectName("comboBox_baud")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_baud, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox_uart = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_uart.sizePolicy().hasHeightForWidth())
        self.comboBox_uart.setSizePolicy(sizePolicy)
        self.comboBox_uart.setObjectName("comboBox_uart")
        self.gridLayout_6.addWidget(self.comboBox_uart, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.widget_5)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_3.setContentsMargins(-1, 3, -1, 3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.initButton = QtWidgets.QPushButton(self.widget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.initButton.setFont(font)
        self.initButton.setObjectName("initButton")
        self.gridLayout_3.addWidget(self.initButton, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget_4, 1, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_4.setContentsMargins(-1, 3, -1, 3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(132, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.spinBox_Biasoffset25_Setting = QtWidgets.QDoubleSpinBox(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_Biasoffset25_Setting.sizePolicy().hasHeightForWidth())
        self.spinBox_Biasoffset25_Setting.setSizePolicy(sizePolicy)
        self.spinBox_Biasoffset25_Setting.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spinBox_Biasoffset25_Setting.setFont(font)
        self.spinBox_Biasoffset25_Setting.setObjectName("spinBox_Biasoffset25_Setting")
        self.gridLayout_4.addWidget(self.spinBox_Biasoffset25_Setting, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(132, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 1)
        self.spinBox_Biasoffset5_Setting = QtWidgets.QDoubleSpinBox(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_Biasoffset5_Setting.sizePolicy().hasHeightForWidth())
        self.spinBox_Biasoffset5_Setting.setSizePolicy(sizePolicy)
        self.spinBox_Biasoffset5_Setting.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spinBox_Biasoffset5_Setting.setFont(font)
        self.spinBox_Biasoffset5_Setting.setObjectName("spinBox_Biasoffset5_Setting")
        self.gridLayout_4.addWidget(self.spinBox_Biasoffset5_Setting, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(132, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 2, 0, 1, 1)
        self.spinBox_Biasoffset10_Setting = QtWidgets.QDoubleSpinBox(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_Biasoffset10_Setting.sizePolicy().hasHeightForWidth())
        self.spinBox_Biasoffset10_Setting.setSizePolicy(sizePolicy)
        self.spinBox_Biasoffset10_Setting.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spinBox_Biasoffset10_Setting.setFont(font)
        self.spinBox_Biasoffset10_Setting.setObjectName("spinBox_Biasoffset10_Setting")
        self.gridLayout_4.addWidget(self.spinBox_Biasoffset10_Setting, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(132, 0))
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 3, 0, 1, 1)
        self.spinBox_Isetoff_Setting = QtWidgets.QDoubleSpinBox(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_Isetoff_Setting.sizePolicy().hasHeightForWidth())
        self.spinBox_Isetoff_Setting.setSizePolicy(sizePolicy)
        self.spinBox_Isetoff_Setting.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spinBox_Isetoff_Setting.setFont(font)
        self.spinBox_Isetoff_Setting.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_Isetoff_Setting.setObjectName("spinBox_Isetoff_Setting")
        self.gridLayout_4.addWidget(self.spinBox_Isetoff_Setting, 3, 1, 1, 1)
        self.gridLayout_2.addWidget(self.widget_6, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_5, 4, 0, 1, 1)

        self.retranslateUi(Setting)
        QtCore.QMetaObject.connectSlotsByName(Setting)

    def retranslateUi(self, Setting):
        _translate = QtCore.QCoreApplication.translate
        Setting.setWindowTitle(_translate("Setting", "Setting"))
        self.saveButton.setText(_translate("Setting", "Save settings"))
        self.label_2.setText(_translate("Setting", "Baudrate"))
        self.comboBox_baud.setItemText(0, _translate("Setting", "9600"))
        self.comboBox_baud.setItemText(1, _translate("Setting", "38400"))
        self.label.setText(_translate("Setting", "COM"))
        self.initButton.setText(_translate("Setting", "Initailize"))
        self.label_3.setText(_translate("Setting", "Bias offset（+/-2.5V）"))
        self.label_4.setText(_translate("Setting", "Bias offset (+/-5V)"))
        self.label_5.setText(_translate("Setting", "Bias offset(+/-10V)"))
        self.label_6.setText(_translate("Setting", "Iset offset"))
import logo_rc
