# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Spectroscopy.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Spectroscopy(object):
    def setupUi(self, Spectroscopy):
        Spectroscopy.setObjectName("Spectroscopy")
        Spectroscopy.resize(665, 662)
        self.gridLayout = QtWidgets.QGridLayout(Spectroscopy)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_Save = QtWidgets.QPushButton(Spectroscopy)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Save.sizePolicy().hasHeightForWidth())
        self.pushButton_Save.setSizePolicy(sizePolicy)
        self.pushButton_Save.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.gridLayout.addWidget(self.pushButton_Save, 2, 1, 1, 1)
        self.pushButton_Info = QtWidgets.QPushButton(Spectroscopy)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Info.sizePolicy().hasHeightForWidth())
        self.pushButton_Info.setSizePolicy(sizePolicy)
        self.pushButton_Info.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_Info.setObjectName("pushButton_Info")
        self.gridLayout.addWidget(self.pushButton_Info, 3, 1, 1, 1)
        self.Graph = QtWidgets.QGroupBox(Spectroscopy)
        self.Graph.setObjectName("Graph")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Graph)
        self.gridLayout_3.setSpacing(9)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollBar_Pointer2_Graph = QtWidgets.QScrollBar(self.Graph)
        self.scrollBar_Pointer2_Graph.setMinimumSize(QtCore.QSize(120, 0))
        self.scrollBar_Pointer2_Graph.setMaximum(65535)
        self.scrollBar_Pointer2_Graph.setOrientation(QtCore.Qt.Horizontal)
        self.scrollBar_Pointer2_Graph.setObjectName("scrollBar_Pointer2_Graph")
        self.gridLayout_3.addWidget(self.scrollBar_Pointer2_Graph, 1, 2, 1, 2)
        self.label = QtWidgets.QLabel(self.Graph)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_YAuto_Graph = QtWidgets.QPushButton(self.Graph)
        self.pushButton_YAuto_Graph.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_YAuto_Graph.setObjectName("pushButton_YAuto_Graph")
        self.gridLayout_3.addWidget(self.pushButton_YAuto_Graph, 4, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.Graph)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.Graph)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 5, 0, 1, 1)
        self.scrollBar_Pointer1_Graph = QtWidgets.QScrollBar(self.Graph)
        self.scrollBar_Pointer1_Graph.setMinimumSize(QtCore.QSize(120, 0))
        self.scrollBar_Pointer1_Graph.setMaximum(65535)
        self.scrollBar_Pointer1_Graph.setOrientation(QtCore.Qt.Horizontal)
        self.scrollBar_Pointer1_Graph.setObjectName("scrollBar_Pointer1_Graph")
        self.gridLayout_3.addWidget(self.scrollBar_Pointer1_Graph, 0, 2, 1, 2)
        self.pushButton_XAuto_Graph = QtWidgets.QPushButton(self.Graph)
        self.pushButton_XAuto_Graph.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_XAuto_Graph.setObjectName("pushButton_XAuto_Graph")
        self.gridLayout_3.addWidget(self.pushButton_XAuto_Graph, 2, 3, 1, 1)
        self.label_Channel_Graph = QtWidgets.QLabel(self.Graph)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Channel_Graph.sizePolicy().hasHeightForWidth())
        self.label_Channel_Graph.setSizePolicy(sizePolicy)
        self.label_Channel_Graph.setMinimumSize(QtCore.QSize(0, 20))
        self.label_Channel_Graph.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_Channel_Graph.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_Channel_Graph.setText("")
        self.label_Channel_Graph.setObjectName("label_Channel_Graph")
        self.gridLayout_3.addWidget(self.label_Channel_Graph, 5, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.Graph)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.Graph)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.scrollBar_XScale_Graph = QtWidgets.QScrollBar(self.Graph)
        self.scrollBar_XScale_Graph.setMinimumSize(QtCore.QSize(120, 0))
        self.scrollBar_XScale_Graph.setMinimum(1)
        self.scrollBar_XScale_Graph.setMaximum(100)
        self.scrollBar_XScale_Graph.setOrientation(QtCore.Qt.Horizontal)
        self.scrollBar_XScale_Graph.setObjectName("scrollBar_XScale_Graph")
        self.gridLayout_3.addWidget(self.scrollBar_XScale_Graph, 2, 1, 1, 2)
        self.scrollBar_YScale_Graph = QtWidgets.QScrollBar(self.Graph)
        self.scrollBar_YScale_Graph.setMinimumSize(QtCore.QSize(120, 0))
        self.scrollBar_YScale_Graph.setMinimum(1)
        self.scrollBar_YScale_Graph.setMaximum(100)
        self.scrollBar_YScale_Graph.setOrientation(QtCore.Qt.Horizontal)
        self.scrollBar_YScale_Graph.setObjectName("scrollBar_YScale_Graph")
        self.gridLayout_3.addWidget(self.scrollBar_YScale_Graph, 4, 1, 1, 2)
        self.scrollBar_Channel_Graph = QtWidgets.QScrollBar(self.Graph)
        self.scrollBar_Channel_Graph.setMinimumSize(QtCore.QSize(120, 0))
        self.scrollBar_Channel_Graph.setMaximum(99)
        self.scrollBar_Channel_Graph.setOrientation(QtCore.Qt.Horizontal)
        self.scrollBar_Channel_Graph.setObjectName("scrollBar_Channel_Graph")
        self.gridLayout_3.addWidget(self.scrollBar_Channel_Graph, 5, 1, 1, 2)
        self.spinBox_Pointer1_Graph = QtWidgets.QDoubleSpinBox(self.Graph)
        self.spinBox_Pointer1_Graph.setDecimals(7)
        self.spinBox_Pointer1_Graph.setMinimum(-10.24)
        self.spinBox_Pointer1_Graph.setMaximum(10.24)
        self.spinBox_Pointer1_Graph.setObjectName("spinBox_Pointer1_Graph")
        self.gridLayout_3.addWidget(self.spinBox_Pointer1_Graph, 0, 1, 1, 1)
        self.spinBox_Pointer2_Graph = QtWidgets.QDoubleSpinBox(self.Graph)
        self.spinBox_Pointer2_Graph.setDecimals(7)
        self.spinBox_Pointer2_Graph.setMinimum(-10.24)
        self.spinBox_Pointer2_Graph.setMaximum(10.24)
        self.spinBox_Pointer2_Graph.setObjectName("spinBox_Pointer2_Graph")
        self.gridLayout_3.addWidget(self.spinBox_Pointer2_Graph, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.Graph, 0, 1, 1, 2)
        self.widget = QtWidgets.QWidget(Spectroscopy)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView_2_Spectro = QtWidgets.QGraphicsView(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_2_Spectro.sizePolicy().hasHeightForWidth())
        self.graphicsView_2_Spectro.setSizePolicy(sizePolicy)
        self.graphicsView_2_Spectro.setMinimumSize(QtCore.QSize(280, 280))
        self.graphicsView_2_Spectro.setObjectName("graphicsView_2_Spectro")
        self.verticalLayout.addWidget(self.graphicsView_2_Spectro)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout.addWidget(self.widget_2)
        self.graphicsView_1_Spectro = QtWidgets.QGraphicsView(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_1_Spectro.sizePolicy().hasHeightForWidth())
        self.graphicsView_1_Spectro.setSizePolicy(sizePolicy)
        self.graphicsView_1_Spectro.setMinimumSize(QtCore.QSize(280, 280))
        self.graphicsView_1_Spectro.setObjectName("graphicsView_1_Spectro")
        self.verticalLayout.addWidget(self.graphicsView_1_Spectro)
        self.gridLayout.addWidget(self.widget, 0, 0, 4, 1)
        self.General = QtWidgets.QGroupBox(Spectroscopy)
        self.General.setObjectName("General")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.General)
        self.gridLayout_5.setSpacing(9)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_LockIn_General = QtWidgets.QPushButton(self.General)
        self.pushButton_LockIn_General.setObjectName("pushButton_LockIn_General")
        self.gridLayout_5.addWidget(self.pushButton_LockIn_General, 8, 2, 1, 2)
        self.spinBox_Pass_General = QtWidgets.QSpinBox(self.General)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_Pass_General.sizePolicy().hasHeightForWidth())
        self.spinBox_Pass_General.setSizePolicy(sizePolicy)
        self.spinBox_Pass_General.setMinimumSize(QtCore.QSize(60, 20))
        self.spinBox_Pass_General.setMinimum(1)
        self.spinBox_Pass_General.setMaximum(1024)
        self.spinBox_Pass_General.setObjectName("spinBox_Pass_General")
        self.gridLayout_5.addWidget(self.spinBox_Pass_General, 4, 1, 1, 1)
        self.scrollBar_StepSize_General = QtWidgets.QScrollBar(self.General)
        self.scrollBar_StepSize_General.setMinimumSize(QtCore.QSize(120, 0))
        self.scrollBar_StepSize_General.setMinimum(1)
        self.scrollBar_StepSize_General.setMaximum(8192)
        self.scrollBar_StepSize_General.setOrientation(QtCore.Qt.Horizontal)
        self.scrollBar_StepSize_General.setObjectName("scrollBar_StepSize_General")
        self.gridLayout_5.addWidget(self.scrollBar_StepSize_General, 2, 2, 1, 2)
        self.spiBox_StepSize_General = QtWidgets.QDoubleSpinBox(self.General)
        self.spiBox_StepSize_General.setDecimals(7)
        self.spiBox_StepSize_General.setMaximum(10.0)
        self.spiBox_StepSize_General.setObjectName("spiBox_StepSize_General")
        self.gridLayout_5.addWidget(self.spiBox_StepSize_General, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.General)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 1)
        self.pushButton_EditPoints = QtWidgets.QPushButton(self.General)
        self.pushButton_EditPoints.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_EditPoints.setObjectName("pushButton_EditPoints")
        self.gridLayout_5.addWidget(self.pushButton_EditPoints, 6, 2, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.General)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 3, 0, 1, 2)
        self.comboBox_RampCh_General = QtWidgets.QComboBox(self.General)
        self.comboBox_RampCh_General.setObjectName("comboBox_RampCh_General")
        self.comboBox_RampCh_General.addItem("")
        self.comboBox_RampCh_General.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_RampCh_General, 4, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.General)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.General)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(0, 25))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 3, 2, 1, 2)
        self.scrollBar_Max_General = QtWidgets.QScrollBar(self.General)
        self.scrollBar_Max_General.setMinimumSize(QtCore.QSize(120, 0))
        self.scrollBar_Max_General.setMaximum(65535)
        self.scrollBar_Max_General.setOrientation(QtCore.Qt.Horizontal)
        self.scrollBar_Max_General.setObjectName("scrollBar_Max_General")
        self.gridLayout_5.addWidget(self.scrollBar_Max_General, 1, 2, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.General)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 1, 0, 1, 1)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.General)
        self.doubleSpinBox_3.setDecimals(7)
        self.doubleSpinBox_3.setMinimum(-10.0)
        self.doubleSpinBox_3.setMaximum(10.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.gridLayout_5.addWidget(self.doubleSpinBox_3, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.General)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 4, 2, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.General)
        self.doubleSpinBox_2.setDecimals(7)
        self.doubleSpinBox_2.setMinimum(-10.0)
        self.doubleSpinBox_2.setMaximum(10.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout_5.addWidget(self.doubleSpinBox_2, 0, 1, 1, 1)
        self.scrollBar_Min_General = QtWidgets.QScrollBar(self.General)
        self.scrollBar_Min_General.setMinimumSize(QtCore.QSize(120, 0))
        self.scrollBar_Min_General.setMaximum(65535)
        self.scrollBar_Min_General.setOrientation(QtCore.Qt.Horizontal)
        self.scrollBar_Min_General.setObjectName("scrollBar_Min_General")
        self.gridLayout_5.addWidget(self.scrollBar_Min_General, 0, 2, 1, 2)
        self.pushButton_Advance = QtWidgets.QPushButton(self.General)
        self.pushButton_Advance.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_Advance.setObjectName("pushButton_Advance")
        self.gridLayout_5.addWidget(self.pushButton_Advance, 7, 2, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.General)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 2, 0, 1, 1)
        self.groupBox_Delta_General = QtWidgets.QGroupBox(self.General)
        self.groupBox_Delta_General.setCheckable(True)
        self.groupBox_Delta_General.setObjectName("groupBox_Delta_General")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_Delta_General)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_11 = QtWidgets.QLabel(self.groupBox_Delta_General)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 0, 1, 1)
        self.scrollBar_Z_Delta = QtWidgets.QScrollBar(self.groupBox_Delta_General)
        self.scrollBar_Z_Delta.setMinimum(-32768)
        self.scrollBar_Z_Delta.setMaximum(32767)
        self.scrollBar_Z_Delta.setOrientation(QtCore.Qt.Horizontal)
        self.scrollBar_Z_Delta.setObjectName("scrollBar_Z_Delta")
        self.gridLayout_4.addWidget(self.scrollBar_Z_Delta, 1, 0, 1, 2)
        self.spinBox_Bias_Delta = QtWidgets.QDoubleSpinBox(self.groupBox_Delta_General)
        self.spinBox_Bias_Delta.setDecimals(7)
        self.spinBox_Bias_Delta.setObjectName("spinBox_Bias_Delta")
        self.gridLayout_4.addWidget(self.spinBox_Bias_Delta, 2, 1, 1, 1)
        self.spinBox_Delta_Z = QtWidgets.QSpinBox(self.groupBox_Delta_General)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_Delta_Z.sizePolicy().hasHeightForWidth())
        self.spinBox_Delta_Z.setSizePolicy(sizePolicy)
        self.spinBox_Delta_Z.setMinimumSize(QtCore.QSize(60, 20))
        self.spinBox_Delta_Z.setMinimum(-32768)
        self.spinBox_Delta_Z.setMaximum(32767)
        self.spinBox_Delta_Z.setObjectName("spinBox_Delta_Z")
        self.gridLayout_4.addWidget(self.spinBox_Delta_Z, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_Delta_General)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 2, 0, 1, 1)
        self.scrollBar_Bias_Delta = QtWidgets.QScrollBar(self.groupBox_Delta_General)
        self.scrollBar_Bias_Delta.setMinimum(0)
        self.scrollBar_Bias_Delta.setMaximum(65535)
        self.scrollBar_Bias_Delta.setProperty("value", 32768)
        self.scrollBar_Bias_Delta.setOrientation(QtCore.Qt.Horizontal)
        self.scrollBar_Bias_Delta.setObjectName("scrollBar_Bias_Delta")
        self.gridLayout_4.addWidget(self.scrollBar_Bias_Delta, 3, 0, 1, 2)
        self.gridLayout_5.addWidget(self.groupBox_Delta_General, 6, 0, 3, 2)
        self.gridLayout.addWidget(self.General, 1, 1, 1, 2)
        self.pushButton_Scan = QtWidgets.QPushButton(Spectroscopy)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Scan.sizePolicy().hasHeightForWidth())
        self.pushButton_Scan.setSizePolicy(sizePolicy)
        self.pushButton_Scan.setMaximumSize(QtCore.QSize(250, 16777215))
        self.pushButton_Scan.setObjectName("pushButton_Scan")
        self.gridLayout.addWidget(self.pushButton_Scan, 2, 2, 2, 1)

        self.retranslateUi(Spectroscopy)
        QtCore.QMetaObject.connectSlotsByName(Spectroscopy)

    def retranslateUi(self, Spectroscopy):
        _translate = QtCore.QCoreApplication.translate
        Spectroscopy.setWindowTitle(_translate("Spectroscopy", "Spectroscopy"))
        self.pushButton_Save.setText(_translate("Spectroscopy", "Save"))
        self.pushButton_Info.setText(_translate("Spectroscopy", "Info"))
        self.Graph.setTitle(_translate("Spectroscopy", "Graph"))
        self.label.setText(_translate("Spectroscopy", "Pointer 1"))
        self.pushButton_YAuto_Graph.setText(_translate("Spectroscopy", "Auto"))
        self.label_2.setText(_translate("Spectroscopy", "Pointer 2"))
        self.label_5.setText(_translate("Spectroscopy", "Channel"))
        self.pushButton_XAuto_Graph.setText(_translate("Spectroscopy", "Auto"))
        self.label_4.setText(_translate("Spectroscopy", "Y scale"))
        self.label_3.setText(_translate("Spectroscopy", "X scale"))
        self.General.setTitle(_translate("Spectroscopy", "General options"))
        self.pushButton_LockIn_General.setText(_translate("Spectroscopy", "Lock-in paramenters"))
        self.label_6.setText(_translate("Spectroscopy", "Min"))
        self.pushButton_EditPoints.setText(_translate("Spectroscopy", "Edit points"))
        self.label_13.setText(_translate("Spectroscopy", "Number of data points"))
        self.comboBox_RampCh_General.setItemText(0, _translate("Spectroscopy", "Bias"))
        self.comboBox_RampCh_General.setItemText(1, _translate("Spectroscopy", "Z fine"))
        self.label_9.setText(_translate("Spectroscopy", "Pass #"))
        self.label_7.setText(_translate("Spectroscopy", "Max"))
        self.label_10.setText(_translate("Spectroscopy", "Ramp Ch"))
        self.pushButton_Advance.setText(_translate("Spectroscopy", " Advance option"))
        self.label_8.setText(_translate("Spectroscopy", "Step size"))
        self.groupBox_Delta_General.setTitle(_translate("Spectroscopy", "Delta Z and Bias"))
        self.label_11.setText(_translate("Spectroscopy", "Z (bit)"))
        self.label_12.setText(_translate("Spectroscopy", "Bias (V)"))
        self.pushButton_Scan.setText(_translate("Spectroscopy", "Scan"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Spectroscopy = QtWidgets.QWidget()
    ui = Ui_Spectroscopy()
    ui.setupUi(Spectroscopy)
    Spectroscopy.show()
    sys.exit(app.exec_())
