# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SpectroscopyInfo.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SpectroscopyInfo(object):
    def setupUi(self, SpectroscopyInfo):
        SpectroscopyInfo.setObjectName("SpectroscopyInfo")
        SpectroscopyInfo.setWindowModality(QtCore.Qt.ApplicationModal)
        SpectroscopyInfo.resize(659, 824)
        self.gridLayout = QtWidgets.QGridLayout(SpectroscopyInfo)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(SpectroscopyInfo)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_28 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setMinimumSize(QtCore.QSize(0, 25))
        self.label_28.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 0, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setMinimumSize(QtCore.QSize(0, 25))
        self.label_38.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_38.setObjectName("label_38")
        self.gridLayout_5.addWidget(self.label_38, 10, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_47.sizePolicy().hasHeightForWidth())
        self.label_47.setSizePolicy(sizePolicy)
        self.label_47.setMinimumSize(QtCore.QSize(0, 25))
        self.label_47.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_47.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_47.setObjectName("label_47")
        self.gridLayout_5.addWidget(self.label_47, 7, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(0, 25))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 5, 2, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_42.sizePolicy().hasHeightForWidth())
        self.label_42.setSizePolicy(sizePolicy)
        self.label_42.setMinimumSize(QtCore.QSize(0, 25))
        self.label_42.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_42.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_42.setObjectName("label_42")
        self.gridLayout_5.addWidget(self.label_42, 3, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.groupBox_4)
        self.label_53.setObjectName("label_53")
        self.gridLayout_5.addWidget(self.label_53, 10, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(0, 25))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 1, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMinimumSize(QtCore.QSize(0, 25))
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 6, 2, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_49.sizePolicy().hasHeightForWidth())
        self.label_49.setSizePolicy(sizePolicy)
        self.label_49.setMinimumSize(QtCore.QSize(0, 25))
        self.label_49.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_49.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_49.setObjectName("label_49")
        self.gridLayout_5.addWidget(self.label_49, 5, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(0, 25))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        self.label_43.setMinimumSize(QtCore.QSize(0, 25))
        self.label_43.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_43.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_43.setObjectName("label_43")
        self.gridLayout_5.addWidget(self.label_43, 1, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setMinimumSize(QtCore.QSize(0, 25))
        self.label_36.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_36.setObjectName("label_36")
        self.gridLayout_5.addWidget(self.label_36, 9, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(0, 25))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 6, 0, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_52.sizePolicy().hasHeightForWidth())
        self.label_52.setSizePolicy(sizePolicy)
        self.label_52.setMinimumSize(QtCore.QSize(0, 25))
        self.label_52.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_52.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_52.setObjectName("label_52")
        self.gridLayout_5.addWidget(self.label_52, 0, 3, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_50.sizePolicy().hasHeightForWidth())
        self.label_50.setSizePolicy(sizePolicy)
        self.label_50.setMinimumSize(QtCore.QSize(0, 25))
        self.label_50.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_50.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_50.setObjectName("label_50")
        self.gridLayout_5.addWidget(self.label_50, 3, 3, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_48.sizePolicy().hasHeightForWidth())
        self.label_48.setSizePolicy(sizePolicy)
        self.label_48.setMinimumSize(QtCore.QSize(0, 25))
        self.label_48.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_48.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_48.setObjectName("label_48")
        self.gridLayout_5.addWidget(self.label_48, 6, 3, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMinimumSize(QtCore.QSize(0, 25))
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 7, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setMinimumSize(QtCore.QSize(0, 25))
        self.label_30.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 10, 0, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.groupBox_4)
        self.label_54.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_54.setObjectName("label_54")
        self.gridLayout_5.addWidget(self.label_54, 10, 3, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_46.sizePolicy().hasHeightForWidth())
        self.label_46.setSizePolicy(sizePolicy)
        self.label_46.setMinimumSize(QtCore.QSize(0, 25))
        self.label_46.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_46.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_46.setObjectName("label_46")
        self.gridLayout_5.addWidget(self.label_46, 8, 3, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_40.sizePolicy().hasHeightForWidth())
        self.label_40.setSizePolicy(sizePolicy)
        self.label_40.setMinimumSize(QtCore.QSize(0, 25))
        self.label_40.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_40.setObjectName("label_40")
        self.gridLayout_5.addWidget(self.label_40, 6, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(0, 25))
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 3, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(0, 25))
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 3, 2, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setMinimumSize(QtCore.QSize(0, 25))
        self.label_37.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_37.setObjectName("label_37")
        self.gridLayout_5.addWidget(self.label_37, 8, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        self.label_44.setMinimumSize(QtCore.QSize(0, 25))
        self.label_44.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_44.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_44.setObjectName("label_44")
        self.gridLayout_5.addWidget(self.label_44, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(0, 25))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 8, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMinimumSize(QtCore.QSize(0, 25))
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 8, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(0, 25))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_39.sizePolicy().hasHeightForWidth())
        self.label_39.setSizePolicy(sizePolicy)
        self.label_39.setMinimumSize(QtCore.QSize(0, 25))
        self.label_39.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_39.setObjectName("label_39")
        self.gridLayout_5.addWidget(self.label_39, 7, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        self.label_41.setMinimumSize(QtCore.QSize(0, 25))
        self.label_41.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_41.setObjectName("label_41")
        self.gridLayout_5.addWidget(self.label_41, 5, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMinimumSize(QtCore.QSize(0, 25))
        self.label_27.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 9, 2, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_51.sizePolicy().hasHeightForWidth())
        self.label_51.setSizePolicy(sizePolicy)
        self.label_51.setMinimumSize(QtCore.QSize(0, 25))
        self.label_51.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_51.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_51.setObjectName("label_51")
        self.gridLayout_5.addWidget(self.label_51, 1, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(0, 25))
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 7, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setMinimumSize(QtCore.QSize(0, 25))
        self.label_29.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 0, 2, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_45.sizePolicy().hasHeightForWidth())
        self.label_45.setSizePolicy(sizePolicy)
        self.label_45.setMinimumSize(QtCore.QSize(0, 25))
        self.label_45.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_45.setObjectName("label_45")
        self.gridLayout_5.addWidget(self.label_45, 9, 3, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QtCore.QSize(0, 25))
        self.label_26.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 9, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 5, 0, 3, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(SpectroscopyInfo)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_88 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_88.sizePolicy().hasHeightForWidth())
        self.label_88.setSizePolicy(sizePolicy)
        self.label_88.setMinimumSize(QtCore.QSize(0, 25))
        self.label_88.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_88.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_88.setObjectName("label_88")
        self.gridLayout_3.addWidget(self.label_88, 2, 1, 1, 1)
        self.label_87 = QtWidgets.QLabel(self.groupBox_2)
        self.label_87.setObjectName("label_87")
        self.gridLayout_3.addWidget(self.label_87, 2, 0, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.groupBox_2)
        self.label_67.setObjectName("label_67")
        self.gridLayout_3.addWidget(self.label_67, 2, 2, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.groupBox_2)
        self.label_69.setObjectName("label_69")
        self.gridLayout_3.addWidget(self.label_69, 3, 0, 1, 1)
        self.label_86 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_86.sizePolicy().hasHeightForWidth())
        self.label_86.setSizePolicy(sizePolicy)
        self.label_86.setMinimumSize(QtCore.QSize(0, 25))
        self.label_86.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_86.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_86.setObjectName("label_86")
        self.gridLayout_3.addWidget(self.label_86, 0, 5, 1, 1)
        self.label_85 = QtWidgets.QLabel(self.groupBox_2)
        self.label_85.setObjectName("label_85")
        self.gridLayout_3.addWidget(self.label_85, 0, 4, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_76.sizePolicy().hasHeightForWidth())
        self.label_76.setSizePolicy(sizePolicy)
        self.label_76.setMinimumSize(QtCore.QSize(0, 25))
        self.label_76.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_76.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_76.setObjectName("label_76")
        self.gridLayout_3.addWidget(self.label_76, 0, 3, 1, 1)
        self.label_79 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_79.sizePolicy().hasHeightForWidth())
        self.label_79.setSizePolicy(sizePolicy)
        self.label_79.setMinimumSize(QtCore.QSize(0, 25))
        self.label_79.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_79.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_79.setObjectName("label_79")
        self.gridLayout_3.addWidget(self.label_79, 4, 1, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_77.sizePolicy().hasHeightForWidth())
        self.label_77.setSizePolicy(sizePolicy)
        self.label_77.setMinimumSize(QtCore.QSize(0, 25))
        self.label_77.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_77.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_77.setObjectName("label_77")
        self.gridLayout_3.addWidget(self.label_77, 2, 3, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_82.sizePolicy().hasHeightForWidth())
        self.label_82.setSizePolicy(sizePolicy)
        self.label_82.setMinimumSize(QtCore.QSize(0, 25))
        self.label_82.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_82.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_82.setObjectName("label_82")
        self.gridLayout_3.addWidget(self.label_82, 3, 3, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.groupBox_2)
        self.label_72.setObjectName("label_72")
        self.gridLayout_3.addWidget(self.label_72, 4, 2, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_81.sizePolicy().hasHeightForWidth())
        self.label_81.setSizePolicy(sizePolicy)
        self.label_81.setMinimumSize(QtCore.QSize(0, 25))
        self.label_81.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_81.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_81.setObjectName("label_81")
        self.gridLayout_3.addWidget(self.label_81, 2, 5, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_83.sizePolicy().hasHeightForWidth())
        self.label_83.setSizePolicy(sizePolicy)
        self.label_83.setMinimumSize(QtCore.QSize(0, 25))
        self.label_83.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_83.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_83.setObjectName("label_83")
        self.gridLayout_3.addWidget(self.label_83, 4, 3, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.groupBox_2)
        self.label_65.setObjectName("label_65")
        self.gridLayout_3.addWidget(self.label_65, 0, 0, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.groupBox_2)
        self.label_68.setObjectName("label_68")
        self.gridLayout_3.addWidget(self.label_68, 2, 4, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_78.sizePolicy().hasHeightForWidth())
        self.label_78.setSizePolicy(sizePolicy)
        self.label_78.setMinimumSize(QtCore.QSize(0, 25))
        self.label_78.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_78.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_78.setObjectName("label_78")
        self.gridLayout_3.addWidget(self.label_78, 3, 1, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_75.sizePolicy().hasHeightForWidth())
        self.label_75.setSizePolicy(sizePolicy)
        self.label_75.setMinimumSize(QtCore.QSize(0, 25))
        self.label_75.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_75.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_75.setObjectName("label_75")
        self.gridLayout_3.addWidget(self.label_75, 0, 1, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.groupBox_2)
        self.label_66.setObjectName("label_66")
        self.gridLayout_3.addWidget(self.label_66, 0, 2, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.groupBox_2)
        self.label_71.setObjectName("label_71")
        self.gridLayout_3.addWidget(self.label_71, 3, 2, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.groupBox_2)
        self.label_70.setObjectName("label_70")
        self.gridLayout_3.addWidget(self.label_70, 4, 0, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.groupBox_2)
        self.label_73.setObjectName("label_73")
        self.gridLayout_3.addWidget(self.label_73, 3, 4, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_80.sizePolicy().hasHeightForWidth())
        self.label_80.setSizePolicy(sizePolicy)
        self.label_80.setMinimumSize(QtCore.QSize(0, 25))
        self.label_80.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_80.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_80.setObjectName("label_80")
        self.gridLayout_3.addWidget(self.label_80, 3, 5, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.groupBox_2)
        self.label_74.setObjectName("label_74")
        self.gridLayout_3.addWidget(self.label_74, 4, 4, 1, 1)
        self.label_84 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_84.sizePolicy().hasHeightForWidth())
        self.label_84.setSizePolicy(sizePolicy)
        self.label_84.setMinimumSize(QtCore.QSize(0, 25))
        self.label_84.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_84.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_84.setObjectName("label_84")
        self.gridLayout_3.addWidget(self.label_84, 4, 5, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 8, 0, 1, 2)
        self.groupBox_6 = QtWidgets.QGroupBox(SpectroscopyInfo)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_59 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_59.sizePolicy().hasHeightForWidth())
        self.label_59.setSizePolicy(sizePolicy)
        self.label_59.setMinimumSize(QtCore.QSize(0, 25))
        self.label_59.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_59.setObjectName("label_59")
        self.gridLayout_7.addWidget(self.label_59, 0, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setMinimumSize(QtCore.QSize(0, 25))
        self.label_31.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_31.setObjectName("label_31")
        self.gridLayout_7.addWidget(self.label_31, 0, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_56.sizePolicy().hasHeightForWidth())
        self.label_56.setSizePolicy(sizePolicy)
        self.label_56.setMinimumSize(QtCore.QSize(0, 25))
        self.label_56.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_56.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_56.setObjectName("label_56")
        self.gridLayout_7.addWidget(self.label_56, 1, 1, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_55.sizePolicy().hasHeightForWidth())
        self.label_55.setSizePolicy(sizePolicy)
        self.label_55.setMinimumSize(QtCore.QSize(0, 25))
        self.label_55.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_55.setObjectName("label_55")
        self.gridLayout_7.addWidget(self.label_55, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(0, 25))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_60.sizePolicy().hasHeightForWidth())
        self.label_60.setSizePolicy(sizePolicy)
        self.label_60.setMinimumSize(QtCore.QSize(0, 25))
        self.label_60.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_60.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_60.setObjectName("label_60")
        self.gridLayout_7.addWidget(self.label_60, 0, 3, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_58.sizePolicy().hasHeightForWidth())
        self.label_58.setSizePolicy(sizePolicy)
        self.label_58.setMinimumSize(QtCore.QSize(0, 25))
        self.label_58.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_58.setObjectName("label_58")
        self.gridLayout_7.addWidget(self.label_58, 1, 2, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_57.sizePolicy().hasHeightForWidth())
        self.label_57.setSizePolicy(sizePolicy)
        self.label_57.setMinimumSize(QtCore.QSize(0, 25))
        self.label_57.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_57.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_57.setObjectName("label_57")
        self.gridLayout_7.addWidget(self.label_57, 1, 3, 1, 1)
        self.listWidget_2 = QtWidgets.QListWidget(self.groupBox_6)
        self.listWidget_2.setObjectName("listWidget_2")
        self.gridLayout_7.addWidget(self.listWidget_2, 3, 0, 1, 4)
        self.gridLayout.addWidget(self.groupBox_6, 6, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(SpectroscopyInfo)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.gridLayout_4.addWidget(self.tableWidget, 2, 6, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 7, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(SpectroscopyInfo)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_94 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_94.sizePolicy().hasHeightForWidth())
        self.label_94.setSizePolicy(sizePolicy)
        self.label_94.setMinimumSize(QtCore.QSize(0, 25))
        self.label_94.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_94.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_94.setObjectName("label_94")
        self.gridLayout_6.addWidget(self.label_94, 1, 1, 1, 1)
        self.label_99 = QtWidgets.QLabel(self.groupBox_5)
        self.label_99.setObjectName("label_99")
        self.gridLayout_6.addWidget(self.label_99, 0, 0, 1, 1)
        self.label_103 = QtWidgets.QLabel(self.groupBox_5)
        self.label_103.setObjectName("label_103")
        self.gridLayout_6.addWidget(self.label_103, 1, 2, 1, 1)
        self.label_102 = QtWidgets.QLabel(self.groupBox_5)
        self.label_102.setObjectName("label_102")
        self.gridLayout_6.addWidget(self.label_102, 2, 2, 1, 1)
        self.label_100 = QtWidgets.QLabel(self.groupBox_5)
        self.label_100.setObjectName("label_100")
        self.gridLayout_6.addWidget(self.label_100, 1, 0, 1, 1)
        self.label_104 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_104.sizePolicy().hasHeightForWidth())
        self.label_104.setSizePolicy(sizePolicy)
        self.label_104.setMinimumSize(QtCore.QSize(0, 25))
        self.label_104.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_104.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_104.setObjectName("label_104")
        self.gridLayout_6.addWidget(self.label_104, 2, 1, 1, 1)
        self.label_101 = QtWidgets.QLabel(self.groupBox_5)
        self.label_101.setObjectName("label_101")
        self.gridLayout_6.addWidget(self.label_101, 2, 0, 1, 1)
        self.label_105 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_105.sizePolicy().hasHeightForWidth())
        self.label_105.setSizePolicy(sizePolicy)
        self.label_105.setMinimumSize(QtCore.QSize(0, 25))
        self.label_105.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_105.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_105.setObjectName("label_105")
        self.gridLayout_6.addWidget(self.label_105, 1, 3, 1, 1)
        self.label_106 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_106.sizePolicy().hasHeightForWidth())
        self.label_106.setSizePolicy(sizePolicy)
        self.label_106.setMinimumSize(QtCore.QSize(0, 25))
        self.label_106.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_106.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_106.setObjectName("label_106")
        self.gridLayout_6.addWidget(self.label_106, 2, 3, 1, 1)
        self.label_93 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_93.sizePolicy().hasHeightForWidth())
        self.label_93.setSizePolicy(sizePolicy)
        self.label_93.setMinimumSize(QtCore.QSize(0, 25))
        self.label_93.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_93.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_93.setObjectName("label_93")
        self.gridLayout_6.addWidget(self.label_93, 0, 1, 1, 3)
        self.gridLayout.addWidget(self.groupBox_5, 3, 1, 2, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(SpectroscopyInfo)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_110 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_110.sizePolicy().hasHeightForWidth())
        self.label_110.setSizePolicy(sizePolicy)
        self.label_110.setMinimumSize(QtCore.QSize(0, 25))
        self.label_110.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_110.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_110.setObjectName("label_110")
        self.gridLayout_9.addWidget(self.label_110, 0, 3, 1, 1)
        self.label_109 = QtWidgets.QLabel(self.groupBox_7)
        self.label_109.setObjectName("label_109")
        self.gridLayout_9.addWidget(self.label_109, 0, 0, 1, 1)
        self.label_107 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_107.sizePolicy().hasHeightForWidth())
        self.label_107.setSizePolicy(sizePolicy)
        self.label_107.setMinimumSize(QtCore.QSize(0, 25))
        self.label_107.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_107.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_107.setObjectName("label_107")
        self.gridLayout_9.addWidget(self.label_107, 0, 1, 1, 1)
        self.label_108 = QtWidgets.QLabel(self.groupBox_7)
        self.label_108.setObjectName("label_108")
        self.gridLayout_9.addWidget(self.label_108, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.groupBox_ZDrift_BetPasses = QtWidgets.QGroupBox(SpectroscopyInfo)
        self.groupBox_ZDrift_BetPasses.setCheckable(False)
        self.groupBox_ZDrift_BetPasses.setObjectName("groupBox_ZDrift_BetPasses")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_ZDrift_BetPasses)
        self.gridLayout_8.setSpacing(9)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_91 = QtWidgets.QLabel(self.groupBox_ZDrift_BetPasses)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_91.sizePolicy().hasHeightForWidth())
        self.label_91.setSizePolicy(sizePolicy)
        self.label_91.setMinimumSize(QtCore.QSize(0, 25))
        self.label_91.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_91.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_91.setObjectName("label_91")
        self.gridLayout_8.addWidget(self.label_91, 1, 2, 1, 1)
        self.label_92 = QtWidgets.QLabel(self.groupBox_ZDrift_BetPasses)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_92.sizePolicy().hasHeightForWidth())
        self.label_92.setSizePolicy(sizePolicy)
        self.label_92.setMinimumSize(QtCore.QSize(0, 25))
        self.label_92.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_92.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_92.setObjectName("label_92")
        self.gridLayout_8.addWidget(self.label_92, 3, 2, 1, 1)
        self.label_95 = QtWidgets.QLabel(self.groupBox_ZDrift_BetPasses)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_95.sizePolicy().hasHeightForWidth())
        self.label_95.setSizePolicy(sizePolicy)
        self.label_95.setMinimumSize(QtCore.QSize(120, 0))
        self.label_95.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_95.setObjectName("label_95")
        self.gridLayout_8.addWidget(self.label_95, 2, 0, 1, 1)
        self.label_97 = QtWidgets.QLabel(self.groupBox_ZDrift_BetPasses)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_97.sizePolicy().hasHeightForWidth())
        self.label_97.setSizePolicy(sizePolicy)
        self.label_97.setMinimumSize(QtCore.QSize(0, 25))
        self.label_97.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_97.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_97.setObjectName("label_97")
        self.gridLayout_8.addWidget(self.label_97, 2, 2, 1, 1)
        self.label_98 = QtWidgets.QLabel(self.groupBox_ZDrift_BetPasses)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_98.sizePolicy().hasHeightForWidth())
        self.label_98.setSizePolicy(sizePolicy)
        self.label_98.setMinimumSize(QtCore.QSize(120, 0))
        self.label_98.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_98.setObjectName("label_98")
        self.gridLayout_8.addWidget(self.label_98, 3, 0, 1, 1)
        self.label_96 = QtWidgets.QLabel(self.groupBox_ZDrift_BetPasses)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_96.sizePolicy().hasHeightForWidth())
        self.label_96.setSizePolicy(sizePolicy)
        self.label_96.setMinimumSize(QtCore.QSize(120, 0))
        self.label_96.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_96.setObjectName("label_96")
        self.gridLayout_8.addWidget(self.label_96, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_ZDrift_BetPasses, 0, 1, 3, 1)
        self.groupBox = QtWidgets.QGroupBox(SpectroscopyInfo)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(0, 25))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 3, 2, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        self.label_35.setMinimumSize(QtCore.QSize(0, 25))
        self.label_35.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_35.setObjectName("label_35")
        self.gridLayout_2.addWidget(self.label_35, 1, 1, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_61.sizePolicy().hasHeightForWidth())
        self.label_61.setSizePolicy(sizePolicy)
        self.label_61.setMinimumSize(QtCore.QSize(0, 25))
        self.label_61.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_61.setObjectName("label_61")
        self.gridLayout_2.addWidget(self.label_61, 1, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(0, 25))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 2, 3, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_64.sizePolicy().hasHeightForWidth())
        self.label_64.setSizePolicy(sizePolicy)
        self.label_64.setMinimumSize(QtCore.QSize(0, 25))
        self.label_64.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_64.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_64.setObjectName("label_64")
        self.gridLayout_2.addWidget(self.label_64, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 25))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(0, 25))
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 2, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setMinimumSize(QtCore.QSize(0, 25))
        self.label_34.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_34.setObjectName("label_34")
        self.gridLayout_2.addWidget(self.label_34, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(0, 25))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 3, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 25))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 2, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_62.sizePolicy().hasHeightForWidth())
        self.label_62.setSizePolicy(sizePolicy)
        self.label_62.setMinimumSize(QtCore.QSize(0, 25))
        self.label_62.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_62.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_62.setObjectName("label_62")
        self.gridLayout_2.addWidget(self.label_62, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 25))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_63.sizePolicy().hasHeightForWidth())
        self.label_63.setSizePolicy(sizePolicy)
        self.label_63.setMinimumSize(QtCore.QSize(0, 25))
        self.label_63.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_63.setObjectName("label_63")
        self.gridLayout_2.addWidget(self.label_63, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 25))
        self.label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 25))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(0, 25))
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 4, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(0, 25))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 0, 3, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setMinimumSize(QtCore.QSize(0, 25))
        self.label_32.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_32.setObjectName("label_32")
        self.gridLayout_2.addWidget(self.label_32, 5, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setMinimumSize(QtCore.QSize(0, 25))
        self.label_33.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_33.setObjectName("label_33")
        self.gridLayout_2.addWidget(self.label_33, 5, 1, 1, 1)
        self.label_89 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_89.sizePolicy().hasHeightForWidth())
        self.label_89.setSizePolicy(sizePolicy)
        self.label_89.setMinimumSize(QtCore.QSize(0, 25))
        self.label_89.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_89.setObjectName("label_89")
        self.gridLayout_2.addWidget(self.label_89, 5, 2, 1, 1)
        self.label_90 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_90.sizePolicy().hasHeightForWidth())
        self.label_90.setSizePolicy(sizePolicy)
        self.label_90.setMinimumSize(QtCore.QSize(0, 25))
        self.label_90.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_90.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_90.setObjectName("label_90")
        self.gridLayout_2.addWidget(self.label_90, 5, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(0, 25))
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 4, 1, 1, 3)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 4, 1)

        self.retranslateUi(SpectroscopyInfo)
        QtCore.QMetaObject.connectSlotsByName(SpectroscopyInfo)

    def retranslateUi(self, SpectroscopyInfo):
        _translate = QtCore.QCoreApplication.translate
        SpectroscopyInfo.setWindowTitle(_translate("SpectroscopyInfo", "Spectroscopy Data Info"))
        self.groupBox_4.setTitle(_translate("SpectroscopyInfo", "Status"))
        self.label_28.setText(_translate("SpectroscopyInfo", "Bias DAC"))
        self.label_38.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_47.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_8.setText(_translate("SpectroscopyInfo", "Yoffset (bits)"))
        self.label_42.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_53.setText(_translate("SpectroscopyInfo", "Bias Range"))
        self.label_11.setText(_translate("SpectroscopyInfo", "Iset (nA)"))
        self.label_24.setText(_translate("SpectroscopyInfo", "Zoffset fine (bits)"))
        self.label_49.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_10.setText(_translate("SpectroscopyInfo", "Bias (V)"))
        self.label_43.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_36.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_9.setText(_translate("SpectroscopyInfo", "Zoffset (bits)"))
        self.label_52.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_50.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_48.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_23.setText(_translate("SpectroscopyInfo", "Yin (bits)"))
        self.label_30.setText(_translate("SpectroscopyInfo", "Feedback"))
        self.label_54.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_46.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_40.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_20.setText(_translate("SpectroscopyInfo", "Bias Dither"))
        self.label_21.setText(_translate("SpectroscopyInfo", "Z Dither"))
        self.label_37.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_44.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_6.setText(_translate("SpectroscopyInfo", "X gain"))
        self.label_25.setText(_translate("SpectroscopyInfo", "Y gain"))
        self.label_7.setText(_translate("SpectroscopyInfo", "Xoffset (bits)"))
        self.label_39.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_41.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_27.setText(_translate("SpectroscopyInfo", "Z gain2"))
        self.label_51.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_22.setText(_translate("SpectroscopyInfo", "Xin (bits)"))
        self.label_29.setText(_translate("SpectroscopyInfo", "Pream gain"))
        self.label_45.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_26.setText(_translate("SpectroscopyInfo", "Z gain1"))
        self.groupBox_2.setTitle(_translate("SpectroscopyInfo", "Lock in paramenter"))
        self.label_88.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_87.setText(_translate("SpectroscopyInfo", "Lock-in frequency (Hz)"))
        self.label_67.setText(_translate("SpectroscopyInfo", "Phase 1"))
        self.label_69.setText(_translate("SpectroscopyInfo", "Sensivity 1 (mV)"))
        self.label_86.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_85.setText(_translate("SpectroscopyInfo", "Modulation type"))
        self.label_76.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_79.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_77.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_82.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_72.setText(_translate("SpectroscopyInfo", "Offset 2 (%)"))
        self.label_81.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_83.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_65.setText(_translate("SpectroscopyInfo", "OSC amplitude (mVrms)"))
        self.label_68.setText(_translate("SpectroscopyInfo", "Phase 2"))
        self.label_78.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_75.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_66.setText(_translate("SpectroscopyInfo", "OSC frequency (kHz)"))
        self.label_71.setText(_translate("SpectroscopyInfo", "Offset 1 (%)"))
        self.label_70.setText(_translate("SpectroscopyInfo", "Sensivity 2 (mV)"))
        self.label_73.setText(_translate("SpectroscopyInfo", "Time constant 1 (ms)"))
        self.label_80.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_74.setText(_translate("SpectroscopyInfo", "Time constant 2 (ms)"))
        self.label_84.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.groupBox_6.setTitle(_translate("SpectroscopyInfo", "Sequence"))
        self.label_59.setText(_translate("SpectroscopyInfo", "Feedback"))
        self.label_31.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_56.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_55.setText(_translate("SpectroscopyInfo", "Bias Dither"))
        self.label_13.setText(_translate("SpectroscopyInfo", "Name"))
        self.label_60.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_58.setText(_translate("SpectroscopyInfo", "Z Dither"))
        self.label_57.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.groupBox_3.setTitle(_translate("SpectroscopyInfo", "Points"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("SpectroscopyInfo", "X"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("SpectroscopyInfo", "Y"))
        self.groupBox_5.setTitle(_translate("SpectroscopyInfo", "Scan"))
        self.label_94.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_99.setText(_translate("SpectroscopyInfo", "Pre-scan"))
        self.label_103.setText(_translate("SpectroscopyInfo", "Pattern size"))
        self.label_102.setText(_translate("SpectroscopyInfo", "Pattern center Y"))
        self.label_100.setText(_translate("SpectroscopyInfo", "Re-scan"))
        self.label_104.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_101.setText(_translate("SpectroscopyInfo", "Pattern center X"))
        self.label_105.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_106.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_93.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.groupBox_7.setTitle(_translate("SpectroscopyInfo", "Date and time"))
        self.label_110.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_109.setText(_translate("SpectroscopyInfo", "Date"))
        self.label_107.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_108.setText(_translate("SpectroscopyInfo", "Time"))
        self.groupBox_ZDrift_BetPasses.setTitle(_translate("SpectroscopyInfo", "Correction"))
        self.label_91.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_92.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_95.setText(_translate("SpectroscopyInfo", "Match current"))
        self.label_97.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_98.setText(_translate("SpectroscopyInfo", "Feedback on delay (ms)"))
        self.label_96.setText(_translate("SpectroscopyInfo", "Z correction"))
        self.groupBox.setTitle(_translate("SpectroscopyInfo", "Options"))
        self.label_12.setText(_translate("SpectroscopyInfo", "Start bias"))
        self.label_35.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_61.setText(_translate("SpectroscopyInfo", "# of passes"))
        self.label_18.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_64.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_4.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_17.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_34.setText(_translate("SpectroscopyInfo", "# of data points"))
        self.label_14.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_2.setText(_translate("SpectroscopyInfo", "Read Dealy"))
        self.label_62.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_3.setText(_translate("SpectroscopyInfo", "Min"))
        self.label_63.setText(_translate("SpectroscopyInfo", "Delta Z"))
        self.label.setText(_translate("SpectroscopyInfo", "Move Delay"))
        self.label_5.setText(_translate("SpectroscopyInfo", "Max"))
        self.label_15.setText(_translate("SpectroscopyInfo", "Scan Direction"))
        self.label_19.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_32.setText(_translate("SpectroscopyInfo", "Ramp channel"))
        self.label_33.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_89.setText(_translate("SpectroscopyInfo", "# of spectra"))
        self.label_90.setText(_translate("SpectroscopyInfo", "TextLabel"))
        self.label_16.setText(_translate("SpectroscopyInfo", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SpectroscopyInfo = QtWidgets.QWidget()
    ui = Ui_SpectroscopyInfo()
    ui.setupUi(SpectroscopyInfo)
    SpectroscopyInfo.show()
    sys.exit(app.exec_())
