# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TipApproach.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TipApproach(object):
    def setupUi(self, TipApproach):
        TipApproach.setObjectName("TipApproach")
        TipApproach.setEnabled(True)
        TipApproach.resize(1024, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TipApproach.sizePolicy().hasHeightForWidth())
        TipApproach.setSizePolicy(sizePolicy)
        TipApproach.setMinimumSize(QtCore.QSize(1024, 600))
        font = QtGui.QFont()
        font.setPointSize(9)
        TipApproach.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/menuIcon/tipappriconblack.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TipApproach.setWindowIcon(icon)
        self.gridLayout_5 = QtWidgets.QGridLayout(TipApproach)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget_Status_TipAppr = QtWidgets.QWidget(TipApproach)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_Status_TipAppr.sizePolicy().hasHeightForWidth())
        self.widget_Status_TipAppr.setSizePolicy(sizePolicy)
        self.widget_Status_TipAppr.setMinimumSize(QtCore.QSize(0, 18))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.widget_Status_TipAppr.setFont(font)
        self.widget_Status_TipAppr.setObjectName("widget_Status_TipAppr")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget_Status_TipAppr)
        self.gridLayout_10.setContentsMargins(-1, 0, -1, 6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_14 = QtWidgets.QLabel(self.widget_Status_TipAppr)
        self.label_14.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_14.setObjectName("label_14")
        self.gridLayout_10.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_Status_Status = QtWidgets.QLabel(self.widget_Status_TipAppr)
        self.label_Status_Status.setText("")
        self.label_Status_Status.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_Status_Status.setObjectName("label_Status_Status")
        self.gridLayout_10.addWidget(self.label_Status_Status, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget_Status_TipAppr)
        self.label_15.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_15.setObjectName("label_15")
        self.gridLayout_10.addWidget(self.label_15, 0, 2, 1, 1)
        self.label_Pass_Status = QtWidgets.QLabel(self.widget_Status_TipAppr)
        self.label_Pass_Status.setText("")
        self.label_Pass_Status.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_Pass_Status.setObjectName("label_Pass_Status")
        self.gridLayout_10.addWidget(self.label_Pass_Status, 0, 3, 1, 1)
        self.gridLayout_5.addWidget(self.widget_Status_TipAppr, 2, 0, 1, 1)
        self.widget_7 = QtWidgets.QWidget(TipApproach)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_Steps_TipAppr = QtWidgets.QGroupBox(self.widget_7)
        self.groupBox_Steps_TipAppr.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Steps_TipAppr.sizePolicy().hasHeightForWidth())
        self.groupBox_Steps_TipAppr.setSizePolicy(sizePolicy)
        self.groupBox_Steps_TipAppr.setObjectName("groupBox_Steps_TipAppr")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_Steps_TipAppr)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_6 = QtWidgets.QWidget(self.groupBox_Steps_TipAppr)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pushButton_TipAppr_Steps = QtWidgets.QPushButton(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_TipAppr_Steps.sizePolicy().hasHeightForWidth())
        self.pushButton_TipAppr_Steps.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_TipAppr_Steps.setFont(font)
        self.pushButton_TipAppr_Steps.setObjectName("pushButton_TipAppr_Steps")
        self.verticalLayout_9.addWidget(self.pushButton_TipAppr_Steps)
        self.gridLayout_2.addWidget(self.widget_6, 0, 2, 1, 1)
        self.widget = QtWidgets.QWidget(self.groupBox_Steps_TipAppr)
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.spinBox_NumInput_Steps = QtWidgets.QSpinBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_NumInput_Steps.setFont(font)
        self.spinBox_NumInput_Steps.setObjectName("spinBox_NumInput_Steps")
        self.horizontalLayout_7.addWidget(self.spinBox_NumInput_Steps)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.scrollBar_NumInput_Steps = QtWidgets.QScrollBar(self.widget)
        self.scrollBar_NumInput_Steps.setOrientation(QtCore.Qt.Horizontal)
        self.scrollBar_NumInput_Steps.setObjectName("scrollBar_NumInput_Steps")
        self.verticalLayout_4.addWidget(self.scrollBar_NumInput_Steps)
        spacerItem = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.groupBox_Steps_TipAppr)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_Up_Steps = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Up_Steps.sizePolicy().hasHeightForWidth())
        self.pushButton_Up_Steps.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_Up_Steps.setFont(font)
        self.pushButton_Up_Steps.setObjectName("pushButton_Up_Steps")
        self.verticalLayout_6.addWidget(self.pushButton_Up_Steps)
        self.pushButton_Down_Steps = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Down_Steps.sizePolicy().hasHeightForWidth())
        self.pushButton_Down_Steps.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_Down_Steps.setFont(font)
        self.pushButton_Down_Steps.setObjectName("pushButton_Down_Steps")
        self.verticalLayout_6.addWidget(self.pushButton_Down_Steps)
        spacerItem1 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem1)
        self.gridLayout_2.addWidget(self.widget_2, 0, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_Steps_TipAppr, 2, 0, 1, 3)
        self.groupBox_ApprPar_TipAppr = QtWidgets.QGroupBox(self.widget_7)
        self.groupBox_ApprPar_TipAppr.setEnabled(False)
        self.groupBox_ApprPar_TipAppr.setObjectName("groupBox_ApprPar_TipAppr")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_ApprPar_TipAppr)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollBar_BstepInput_ApprPar = QtWidgets.QScrollBar(self.groupBox_ApprPar_TipAppr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollBar_BstepInput_ApprPar.sizePolicy().hasHeightForWidth())
        self.scrollBar_BstepInput_ApprPar.setSizePolicy(sizePolicy)
        self.scrollBar_BstepInput_ApprPar.setMinimumSize(QtCore.QSize(120, 0))
        self.scrollBar_BstepInput_ApprPar.setOrientation(QtCore.Qt.Horizontal)
        self.scrollBar_BstepInput_ApprPar.setObjectName("scrollBar_BstepInput_ApprPar")
        self.gridLayout_4.addWidget(self.scrollBar_BstepInput_ApprPar, 3, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_ApprPar_TipAppr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 0, 1, 1)
        self.spinBox_GstepInput_ApprPar = QtWidgets.QSpinBox(self.groupBox_ApprPar_TipAppr)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_GstepInput_ApprPar.setFont(font)
        self.spinBox_GstepInput_ApprPar.setObjectName("spinBox_GstepInput_ApprPar")
        self.gridLayout_4.addWidget(self.spinBox_GstepInput_ApprPar, 3, 1, 1, 1)
        self.spinBox_BstepInput_ApprPar = QtWidgets.QSpinBox(self.groupBox_ApprPar_TipAppr)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_BstepInput_ApprPar.setFont(font)
        self.spinBox_BstepInput_ApprPar.setObjectName("spinBox_BstepInput_ApprPar")
        self.gridLayout_4.addWidget(self.spinBox_BstepInput_ApprPar, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_ApprPar_TipAppr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 3, 0, 1, 1)
        self.scrollBar_GstepInput_ApprPar = QtWidgets.QScrollBar(self.groupBox_ApprPar_TipAppr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollBar_GstepInput_ApprPar.sizePolicy().hasHeightForWidth())
        self.scrollBar_GstepInput_ApprPar.setSizePolicy(sizePolicy)
        self.scrollBar_GstepInput_ApprPar.setMinimumSize(QtCore.QSize(120, 0))
        self.scrollBar_GstepInput_ApprPar.setOrientation(QtCore.Qt.Horizontal)
        self.scrollBar_GstepInput_ApprPar.setObjectName("scrollBar_GstepInput_ApprPar")
        self.gridLayout_4.addWidget(self.scrollBar_GstepInput_ApprPar, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 4, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_ApprPar_TipAppr, 1, 0, 1, 1)
        self.groupBox_WaveForm_TipAppr = QtWidgets.QGroupBox(self.widget_7)
        self.groupBox_WaveForm_TipAppr.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_WaveForm_TipAppr.sizePolicy().hasHeightForWidth())
        self.groupBox_WaveForm_TipAppr.setSizePolicy(sizePolicy)
        self.groupBox_WaveForm_TipAppr.setObjectName("groupBox_WaveForm_TipAppr")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_WaveForm_TipAppr)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.widget_4 = QtWidgets.QWidget(self.groupBox_WaveForm_TipAppr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_8.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalScrollBar_2 = QtWidgets.QScrollBar(self.widget_4)
        self.horizontalScrollBar_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_2.setObjectName("horizontalScrollBar_2")
        self.gridLayout_8.addWidget(self.horizontalScrollBar_2, 3, 0, 1, 5)
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.widget_4)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.gridLayout_8.addWidget(self.horizontalScrollBar, 1, 0, 1, 5)
        self.label_2 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 2, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777209))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox_DelayInput_WaveForm = QtWidgets.QDoubleSpinBox(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_DelayInput_WaveForm.setFont(font)
        self.spinBox_DelayInput_WaveForm.setObjectName("spinBox_DelayInput_WaveForm")
        self.gridLayout_8.addWidget(self.spinBox_DelayInput_WaveForm, 0, 2, 1, 1)
        self.spinBox_AcceInput_WaveForm = QtWidgets.QDoubleSpinBox(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_AcceInput_WaveForm.setFont(font)
        self.spinBox_AcceInput_WaveForm.setObjectName("spinBox_AcceInput_WaveForm")
        self.gridLayout_8.addWidget(self.spinBox_AcceInput_WaveForm, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_8.addWidget(self.label_4, 2, 3, 1, 1)
        self.gridLayout_9.addWidget(self.widget_4, 0, 0, 1, 1)
        self.widget_8 = QtWidgets.QWidget(self.groupBox_WaveForm_TipAppr)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout_7.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_8 = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 2, 5, 1, 1)
        self.scrollBar_XstepInput_WaveForm = QtWidgets.QScrollBar(self.widget_8)
        self.scrollBar_XstepInput_WaveForm.setMaximum(65535)
        self.scrollBar_XstepInput_WaveForm.setOrientation(QtCore.Qt.Horizontal)
        self.scrollBar_XstepInput_WaveForm.setObjectName("scrollBar_XstepInput_WaveForm")
        self.gridLayout_7.addWidget(self.scrollBar_XstepInput_WaveForm, 1, 0, 1, 6)
        self.label_5 = QtWidgets.QLabel(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 2, 0, 1, 2)
        self.scrollBar_ZstepInput_WaveForm = QtWidgets.QScrollBar(self.widget_8)
        self.scrollBar_ZstepInput_WaveForm.setMaximum(65535)
        self.scrollBar_ZstepInput_WaveForm.setOrientation(QtCore.Qt.Horizontal)
        self.scrollBar_ZstepInput_WaveForm.setObjectName("scrollBar_ZstepInput_WaveForm")
        self.gridLayout_7.addWidget(self.scrollBar_ZstepInput_WaveForm, 3, 0, 1, 6)
        self.label_6 = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 0, 5, 1, 1)
        self.spinBox_ZouterInput_WaveForm = QtWidgets.QDoubleSpinBox(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_ZouterInput_WaveForm.setFont(font)
        self.spinBox_ZouterInput_WaveForm.setObjectName("spinBox_ZouterInput_WaveForm")
        self.gridLayout_7.addWidget(self.spinBox_ZouterInput_WaveForm, 2, 4, 1, 1)
        self.spinBox_XstepInput_WaveForm = QtWidgets.QDoubleSpinBox(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_XstepInput_WaveForm.setFont(font)
        self.spinBox_XstepInput_WaveForm.setObjectName("spinBox_XstepInput_WaveForm")
        self.gridLayout_7.addWidget(self.spinBox_XstepInput_WaveForm, 0, 4, 1, 1)
        self.gridLayout_9.addWidget(self.widget_8, 0, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_WaveForm_TipAppr, 0, 0, 1, 3)
        self.groupBox_MInCurr_TipAppr = QtWidgets.QGroupBox(self.widget_7)
        self.groupBox_MInCurr_TipAppr.setEnabled(False)
        self.groupBox_MInCurr_TipAppr.setObjectName("groupBox_MInCurr_TipAppr")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_MInCurr_TipAppr)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.spinBox_Input_MInCurr = QtWidgets.QDoubleSpinBox(self.groupBox_MInCurr_TipAppr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_Input_MInCurr.sizePolicy().hasHeightForWidth())
        self.spinBox_Input_MInCurr.setSizePolicy(sizePolicy)
        self.spinBox_Input_MInCurr.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.spinBox_Input_MInCurr.setFont(font)
        self.spinBox_Input_MInCurr.setObjectName("spinBox_Input_MInCurr")
        self.gridLayout_11.addWidget(self.spinBox_Input_MInCurr, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_MInCurr_TipAppr)
        self.label_13.setObjectName("label_13")
        self.gridLayout_11.addWidget(self.label_13, 0, 1, 1, 1)
        self.scrollBar_Input_MInCurr = QtWidgets.QScrollBar(self.groupBox_MInCurr_TipAppr)
        self.scrollBar_Input_MInCurr.setMinimumSize(QtCore.QSize(160, 0))
        self.scrollBar_Input_MInCurr.setOrientation(QtCore.Qt.Horizontal)
        self.scrollBar_Input_MInCurr.setObjectName("scrollBar_Input_MInCurr")
        self.gridLayout_11.addWidget(self.scrollBar_Input_MInCurr, 1, 0, 1, 2)
        self.gridLayout_6.addWidget(self.groupBox_MInCurr_TipAppr, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.widget_7, 0, 0, 2, 1)
        self.groupBox_Trans_TipAppro = QtWidgets.QGroupBox(TipApproach)
        self.groupBox_Trans_TipAppro.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Trans_TipAppro.sizePolicy().hasHeightForWidth())
        self.groupBox_Trans_TipAppro.setSizePolicy(sizePolicy)
        self.groupBox_Trans_TipAppro.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_Trans_TipAppro.setCheckable(True)
        self.groupBox_Trans_TipAppro.setChecked(False)
        self.groupBox_Trans_TipAppro.setObjectName("groupBox_Trans_TipAppro")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_Trans_TipAppro)
        self.gridLayout.setContentsMargins(9, 9, 9, 9)
        self.gridLayout.setObjectName("gridLayout")
        self.Display_Trans = QtWidgets.QTextBrowser(self.groupBox_Trans_TipAppro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Display_Trans.sizePolicy().hasHeightForWidth())
        self.Display_Trans.setSizePolicy(sizePolicy)
        self.Display_Trans.setMinimumSize(QtCore.QSize(340, 340))
        self.Display_Trans.setObjectName("Display_Trans")
        self.gridLayout.addWidget(self.Display_Trans, 2, 0, 1, 2)
        self.pushButton_Xfwd_Trans = QtWidgets.QPushButton(self.groupBox_Trans_TipAppro)
        self.pushButton_Xfwd_Trans.setObjectName("pushButton_Xfwd_Trans")
        self.gridLayout.addWidget(self.pushButton_Xfwd_Trans, 0, 1, 1, 1)
        self.pushButton_Ybkwd_Trans = QtWidgets.QPushButton(self.groupBox_Trans_TipAppro)
        self.pushButton_Ybkwd_Trans.setObjectName("pushButton_Ybkwd_Trans")
        self.gridLayout.addWidget(self.pushButton_Ybkwd_Trans, 3, 1, 1, 1)
        self.pushButton_Xbkwd_Trans = QtWidgets.QPushButton(self.groupBox_Trans_TipAppro)
        self.pushButton_Xbkwd_Trans.setObjectName("pushButton_Xbkwd_Trans")
        self.gridLayout.addWidget(self.pushButton_Xbkwd_Trans, 3, 0, 1, 1)
        self.pushButton_Yfwd_Trans = QtWidgets.QPushButton(self.groupBox_Trans_TipAppro)
        self.pushButton_Yfwd_Trans.setObjectName("pushButton_Yfwd_Trans")
        self.gridLayout.addWidget(self.pushButton_Yfwd_Trans, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_Trans_TipAppro, 0, 1, 1, 1)
        self.pushButton_STOP_Steps = QtWidgets.QPushButton(TipApproach)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_STOP_Steps.sizePolicy().hasHeightForWidth())
        self.pushButton_STOP_Steps.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_STOP_Steps.setFont(font)
        self.pushButton_STOP_Steps.setObjectName("pushButton_STOP_Steps")
        self.gridLayout_5.addWidget(self.pushButton_STOP_Steps, 1, 1, 1, 1)

        self.retranslateUi(TipApproach)
        QtCore.QMetaObject.connectSlotsByName(TipApproach)

    def retranslateUi(self, TipApproach):
        _translate = QtCore.QCoreApplication.translate
        TipApproach.setWindowTitle(_translate("TipApproach", "Tip Approach"))
        self.label_14.setText(_translate("TipApproach", "Status:"))
        self.label_15.setText(_translate("TipApproach", "Pass #:"))
        self.groupBox_Steps_TipAppr.setTitle(_translate("TipApproach", "Steps"))
        self.pushButton_TipAppr_Steps.setText(_translate("TipApproach", "Tip approach"))
        self.label_11.setText(_translate("TipApproach", "Number of steps"))
        self.pushButton_Up_Steps.setText(_translate("TipApproach", "Step up"))
        self.pushButton_Down_Steps.setText(_translate("TipApproach", "Step down"))
        self.groupBox_ApprPar_TipAppr.setTitle(_translate("TipApproach", "Approach parameters"))
        self.label_9.setText(_translate("TipApproach", "# of Giant steps"))
        self.label_10.setText(_translate("TipApproach", "Baby step size"))
        self.groupBox_WaveForm_TipAppr.setTitle(_translate("TipApproach", "Wave form control"))
        self.label_2.setText(_translate("TipApproach", "ms"))
        self.label_3.setText(_translate("TipApproach", "Acceleration"))
        self.label.setText(_translate("TipApproach", "Delay"))
        self.label_4.setText(_translate("TipApproach", "% of g"))
        self.label_8.setText(_translate("TipApproach", "V"))
        self.label_5.setText(_translate("TipApproach", "Xin step size"))
        self.label_7.setText(_translate("TipApproach", "Zouter step size"))
        self.label_6.setText(_translate("TipApproach", "V"))
        self.groupBox_MInCurr_TipAppr.setTitle(_translate("TipApproach", "Min tunneling current"))
        self.label_13.setText(_translate("TipApproach", "V"))
        self.groupBox_Trans_TipAppro.setTitle(_translate("TipApproach", "Translate"))
        self.pushButton_Xfwd_Trans.setText(_translate("TipApproach", "+X"))
        self.pushButton_Ybkwd_Trans.setText(_translate("TipApproach", "-Y"))
        self.pushButton_Xbkwd_Trans.setText(_translate("TipApproach", "-X"))
        self.pushButton_Yfwd_Trans.setText(_translate("TipApproach", "+Y"))
        self.pushButton_STOP_Steps.setText(_translate("TipApproach", "STOP"))
import logo_rc
