#
#   Makefile definitions for ideal
#
OBJ   = lowpass.o highpass.o bandpass.o bandstop.o window.o butterworth.o \
	exponential.o lowpassIdeal.o
PROG  = lowpass highpass bandpass bandstop window butterworth exponential \
	lowpassIdeal
MANP  = lowpass.m window.m xfilter.m
CINCL = ideal.i
XPROG = xfilter

xprog:  $(XPROG)
include:cincl
object: cobj
lib:    clib
program:cprog xprog
doc:    manpage

