

/*C*

________________________________________________________________

        ideal_L
        $Id: ideal_L.h,v 1.3 1997/03/24 09:32:03 svein Exp $
        Copyright 1994, Blab, UiO
        Image processing lab, Department of Informatics
        University of Oslo
        E-mail: blab@ifi.uio.no
________________________________________________________________
  
  Permission to use, copy, modify and distribute this software and its
  documentation for any purpose and without fee is hereby granted, 
  provided that this copyright notice appear in all copies and that 
  both that copyright notice and this permission notice appear in supporting
  documentation and that the name of B-lab, Department of Informatics or
  University of Oslo not be used in advertising or publicity pertaining 
  to distribution of the software without specific, written prior permission.

  B-LAB DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING ALL
  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT SHALL B-LAB
  BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION
  OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN 
  CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 

*/

#ifndef _IDEAL_L_H_
#define _IDEAL_L_H_

_XITE_CPLUSPLUS_BEGIN

/* Error handling. */

#define E_NONE       0
#define E_PIXTYP     1
#define E_WINDOW     2
#define E_FILTERSIZE 3
#define E_FFT        4
#define E_MALLOC     5
#define E_ARG        6

static char *e_s[] = {
  "OK",
  "Bad pixeltype",
  "Unknown window type",
  "Filtersize larger than bandsize",
  "Error in fft2d",
  "Malloc failed",
  "Bad number of arguments",
};

_XITE_CPLUSPLUS_END

#endif /* _IDEAL_L_H_ */
