#define DEP_PULSE_PERCENT_CHANGE_MIN 1
#define DEP_PULSE_PERCENT_CHANGE_MAX 200

#define DEP_IMAGE_CHANNEL       3

#define DEP_NUM_DEFAULTS        4
#define DEP_DEF_OTHER           0
#define DEP_DEF_CRASH           1
#define DEP_DEF_HIGH_V          2
#define DEP_DEF_LOW_V           3

#define DEP_PULSE_END_EVENT     0
#define DEP_PULSE_I_ONCE_EVENT  1
#define DEP_PULSE_Z_EVENT       2
#define DEP_PULSE_I_EVENT       3
#define DEP_PULSE_FEEDBACK_EVENT 4

#define DEP_TIME_PER_SAMPLE 20
#define DEP_PULSE_I_SAMPLES 10

#define DEP_PULSE_MEASURE_I_WAIT_MIN 8
#define DEP_PULSE_FEEDBACK_WAIT_MIN 8

#define DEP_OSCILL_X_MIN 1
#define DEP_OSCILL_X_MAX 256
#define DEP_OSCILL_Y_MIN 1
#define DEP_OSCILL_Y_MAX 256

#define DEP_VERT_MAX      0xFFFF
#define DEP_VERT_MIN      0
#define DEP_VERT_DELT     0xFFFF/200
#define DEP_VERT_DDELT    0xFFFF/20

#define DEP_PULSE_Z_OFFSET_MIN (-200)
#define DEP_PULSE_Z_OFFSET_MAX 200
#define DEP_PULSE_Z_OFFSET_DELT 1
#define DEP_PULSE_Z_OFFSET_DDELT 50


#define DEP_PULSE_NUMBER_MAX 10000
#define DEP_PULSE_NUMBER_MIN 1
#define DEP_PULSE_NUMBER_DELT 1
#define DEP_PULSE_NUMBER_DDELT 10

#define DEP_PULSE_BIAS_SPEED_MIN 0.01
#define DEP_PULSE_BIAS_SPEED_MAX 100
#define DEP_PULSE_BIAS_SPEED_DELT 0.1
#define DEP_PULSE_BIAS_SPEED_DDELT 1.0


#define DEP_PULSE_DURATION_MIN 8
#define DEP_PULSE_DURATION_MAX 100000000
#define DEP_PULSE_DURATION_DELT 1
#define DEP_PULSE_DURATION_DDELT 1000

#define DEP_CURRENT_BIT_TIME 50

//#define DEP_TIME_MIN 25
//#define DEP_TIME_MAX 32000
//#define DEP_TIME_DELT 10
#define DEP_TIME_MIN 0
#define DEP_TIME_MAX 187000
#define DEP_TIME_DELT 10

#define DEP_TIME_DDELT 100
#define DEP_BIAS_MIN 0
#define DEP_BIAS_MAX MAX
#define DEP_BIAS_DELT  1
#define DEP_BIAS_DDELT 50

#define ADC_CONV_TIME 26.32


