//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Stm32.rc
//
#define ENTER                           1
#define FILE_LOAD                       2
#define FILE_SAVE_AS                    4
#define FILE_EXIT                       5
#define TIP                             6
#define FINE                            14
#define COARSE                          15
#define INPUT                           16
#define INPUT_CLOSE                     17
#define OUTPUT                          18
#define SCAN                            19
#define HEATER                          20
#define IDS_FILTERSTRING                50
#define PAL_FILTERSTRING                51
#define MAS_FILTERSTRING                52
#define GIF_FILTERSTRING                53
#define SPC_FILTERSTRING                54
#define DEP_FILTERSTRING                55
#define GRD_FILTERSTRING                56
#define FIG_FILTERSTRING                57
#define DATA_STM_FILTERSTRING           58
#define DATA_DEP_FILTERSTRING           59
#define DATA_SPC_FILTERSTRING           60
#define DATA_MAS_FILTERSTRING           61
#define DATA_CUT_FILTERSTRING           62
#define DATA_CNT_FILTERSTRING           63
#define CNT_FILTERSTRING                64
#define EXP_FILTERSTRING                65
#define STP_FILTERSTRING                66
#define DATA_STP_FILTERSTRING           67
#define PS_FILTERSTRING                 68
#define HOP_FILTERSTRING                69
#define TXT_FILTERSTRING                70
#define MAP_FILTERSTRING                71
#define CXP_FILTERSTRING                72
#define COARSE_WAVE_GROUP               101
#define DEP_READ_CLOCK_TIME             101
#define LOGPAL_NEW_IMAGE                101
#define TEST_SIX                        101
#define COARSE_STEP_GROUP               102
#define MENU_SCANNING_DEPOSITION        102
#define COARSE_PERIOD_GROUP             103
#define STM_ETEST                       103
#define COARSE_EDIT_ENABLE              104
#define MENU_DATA_MANIPULATION          104
#define COARSE_PERIOD_GROUP2            104
#define FILE_EXPORT                     105
#define SCAN_Z_BITS_EDIT                106
#define MENU_SPEC                       106
#define SCAN_Z_VOLTS_EDIT               107
#define MENU_MODE_STM                   107
#define SCAN_Z_ANGS_EDIT                108
#define EXPORTDIRDLG                    108
#define MENU_MODE_DATAPRO               108
#define SCAN_Z_ZERO                     109
#define SCAN_START                      110
#define SCAN_SIZE_BITS_EDIT             111
#define SCAN_SIZE_STEPS_EDIT            112
#define SCAN_SIZE_VOLTS_EDIT            113
#define SCAN_SIZE_ANGS_EDIT             114
#define SCAN_STEP_SCROLL                115
#define SCAN_SIZE_128                   116
#define SCAN_Y_BITS_EDIT                117
#define SCAN_Y_VOLTS_EDIT               118
#define IDD_DIALOG1                     118
#define SCAN_Y_ANGS_EDIT                119
#define IDD_DIALOG2                     119
#define SCAN_STEP_BITS_EDIT             120
#define IDD_DIALOG3                     120
#define SCAN_STEP_VOLTS_EDIT            121
#define SCAN_TRIGGER_CH                 122
#define SCAN_Y_ZERO                     123
#define SCAN_X_BITS_EDIT                124
#define SCAN_Z_SCROLL                   125
#define SCAN_Y_GAIN_TENTH               126
#define SCAN_X_VOLTS_EDIT               127
#define SCAN_SIZE_256                   128
#define SCAN_SIZE_512                   129
#define SCAN_SIZE_64                    130
#define SCAN_SIZE_SCROLL                131
#define SCAN_X_ANGS_EDIT                132
#define SCAN_X_ZERO                     133
#define SCAN_EXIT                       134
#define SCAN_Y_SCROLL                   135
#define SCAN_X_SCROLL                   136
#define SCAN_STEP_ANGS_EDIT             137
#define SCAN_Y_GAIN_ONE                 138
#define SCAN_Y_GAIN_TEN                 139
#define SCAN_X_GAIN_TENTH               140
#define SCAN_X_GAIN_ONE                 141
#define SCAN_X_GAIN_TEN                 142
#define SCAN_SCALE_001                  143
#define SCAN_SCALE_01                   144
#define SCAN_SCALE_1                    145
#define SCAN_CENTER                     146
#define SCAN_DETAIL_VIEW                147
#define SCAN_FREQ_1                     148
#define SCAN_FREQ_10                    149
#define SCAN_FREQ_100                   150
#define SCAN_FULL_VIEW                  151
#define COMMENT_EDIT                    152
#define SCAN_NUM_EDIT                   154
#define PRESCAN_RS_NUM                  154
#define SCAN_NUM_SCROLL                 155
#define RAMPBIAS_VOLTS_EDIT             155
#define PRESCAN_RS_VOLTS                155
#define SCAN_LOAD                       156
#define SCAN_SAVE                       157
#define SCAN_ZOOM_IN                    160
#define SCAN_ZOOM_OUT                   161
#define COMMENT_EXIT                    162
#define PRESCAN_TEMP                    163
#define TIP_CURRENT                     164
#define TIP_CURRENT_AMPS_EDIT           165
#define TIP_CURRENT_SCROLL              166
#define SAMPLE_BIAS_VOLTS               167
#define PRESCAN_EXIT                    169
#define SCAN_FINE                       170
#define SCAN_PLANE_FIT                  172
#define DEP_IMAGE_MANIPULATION          173
#define DEP_SAVE                        174
#define DEP_LOAD                        175
#define DEP_INFO                        176
#define DEP_COMMENT                     177
#define IMAGE_LOAD_PREV                 179
#define IMAGE_AUTO_ILLUMINATE           180
#define DEP_PULSE_CRASH                 182
#define DEP_PULSE_LOW_V                 184
#define DEP_PULSE_HIGH_V                185
#define DEP_PULSE_OTHER                 186
#define VSCALE_EXIT                     187
#define VSCALE_MAX                      188
#define VSCALE_MIN                      189
#define VSCALE_MAX_SC                   190
#define VSCALE_MIN_SC                   191
#define VSCALE_SET_MAX                  192
#define VSCALE_SET_MIN                  193
#define VSCALE_SET_CENTER               194
#define IMAGE_VSCALE                    196
#define IM_NEW_VSCALE                   197
#define VSCALE_NEW_IMAGE                198
#define OSCILLOSCOPE                    200
#define I_CH0                           201
#define I_CH1                           202
#define I_CH2                           203
#define I_CH3                           204
#define I_DATA0                         205
#define I_DATA1                         206
#define I_DATA2                         207
#define I_DATA3                         208
#define I_BITS0                         209
#define I_BITS1                         210
#define I_BITS2                         211
#define I_BITS3                         212
#define I_VOLTS0                        213
#define I_VOLTS1                        214
#define I_VOLTS2                        215
#define I_VOLTS3                        216
#define I_UPDATE                        217
#define PRESCAN_BUTTON                  218
#define SAMPLE_BIAS_SCROLL              220
#define TIP_CURRENT_GAIN_8              221
#define TIP_CURRENT_GAIN_9              222
#define TIP_CURRENT_GAIN_10             223
#define RAMPBIAS_SCROLL                 224
#define PRESCAN_RS_SCROLL               224
#define TIP_CURRENT_GAIN_11             225
#define TIP_ACCEL_EDIT                  226
#define TIP_ACCEL_SCROLL                227
#define SCAN_COMMENT                    231
#define TIP_CURRENT_BITS_EDIT           232
#define TIP_STEP_DOWN                   233
#define TIP_STEP_UP                     234
#define SAMPLE_BIAS_BITS_EDIT           235
#define SAMPLE_BIAS_VOLTS_EDIT          236
#define PRESCAN_SCAN_START              238
#define TIP_CURRENT_RANGE_TEXT          240
#define IMAGE_MANIPULATION              242
#define TEST_BUTTON                     243
#define FEEDBACK_OFF                    244
#define X_FIRST                         245
#define Y_FIRST                         246
#define READ_FORWARD                    247
#define READ_BACKWARD                   248
#define TIP_NUMBER_SCROLL               249
#define BIAS_SQUARE_WAVE                250
#define TIP_NUMBER_EDIT                 251
#define READ_BOTH_WAY                   252
#define FEEDBACK_ON                     254
#define SEND_X_Y_OFFSETS                257
#define LINEARIZE                       259
#define TIP_X_STEP_VOLTS_EDIT           260
#define TIP_DELAY_EDIT                  261
#define TIP_X_STEP_BITS_EDIT            262
#define TAKE_LOG                        263
#define TIP_X_STEP_SCROLL               264
#define FIT_PLANE                       265
#define TIP_ZO_STEP_BITS_EDIT           266
#define TIP_ZO_EDIT                     267
#define TIP_ZO_STEP_SCROLL              268
#define DELAY_FREQ_DEP                  269
#define TIP_DELAY_SCROLL                270
#define DELAY_LOAD                      270
#define DELAY_FIXED                     271
#define TIP_UNRETRACT                   272
#define DELAY_SAVE                      272
#define TIP_RETRACT                     273
#define DELAY_LOAD2                     273
#define SMOOTH00                        274
#define TIP_ZO_STEP_VOLTS_EDIT          275
#define DELAY_FREQ_DEP2                 275
#define SMOOTH10                        278
#define SMOOTH01                        280
#define SMOOTH_11                       281
#define SMOOTH_1_1                      284
#define SMOOTH0_1                       285
#define SMOOTH1_1                       286
#define SMOOTH_10                       287
#define SMOOTH                          288
#define NORMALIZE                       289
#define DELAY_FIXED_VALUE               294
#define SCAN_Y_SCROLL_                  295
#define SCAN_Y_SCROLL_2                 296
#define AVG_1                           297
#define SCAN_Y_SCROLL_3                 297
#define SMOOTH_SMALL                    299
#define AVG_3                           300
#define RANGE                           301
#define FIVE_RANGE                      302
#define TEN_RANGE                       303
#define O_CH_SCROLL                     304
#define O_CH_EDIT                       305
#define O_DATA_SCROLL                   306
#define O_DATA_EDIT                     307
#define O_BITS_EDIT                     308
#define O_VOLTS_EDIT                    309
#define O_CH_EDIT2                      310
#define SET_RANGE                       311
#define SEND_OUTPUT                     312
#define OUTPUT_EXIT                     313
#define O_CH_SCROLL2                    313
#define AVG_4                           314
#define SUB_1                           315
#define SUB_2                           316
#define SUB_3                           317
#define SUB_4                           318
#define SMOOTH_LARGE                    319
#define AVG_2                           320
#define IMAGE_Y_SCROLL                  321
#define PROJECT3D                       322
#define INTER_STEP_SCROLL               323
#define INTER_STEP_DELAY_VALUE          328
#define BRIGHTEN                        329
#define DARKEN                          330
#define GAMMA                           331
#define ANIMATE_DELAY                   332
#define STEP_VELOCITY                   333
#define IMAGE_X_SCROLL                  334
#define GAMMA_VALUE                     335
#define CONTRAST_INC                    336
#define CONTRAST_DEC                    337
#define READ_1_IMAGE                    338
#define SAVE_GIF                        339
#define LOAD_IMAGE                      341
#define SAVE_IMAGE                      342
#define LOAD_PAL                        344
#define SAVE_PAL                        345
#define IMAGE_EXIT                      347
#define COPY_1                          348
#define COPY_2                          349
#define COPY_3                          350
#define SEND_Z_OFFSET                   351
#define COPY_4                          352
#define DRIFT_A_VALUE                   353
#define DRIFT_B_VALUE                   354
#define READ_2_IMAGES                   355
#define DRIFT_COMP                      356
#define TEST_EXIT                       357
#define DRIFT_C_VALUE                   358
#define INTER_LINE_DELAY_VALUE          359
#define X_DERIV                         361
#define Y_DERIV                         363
#define TAKE_DERIV                      364
#define SCAN_TIME                       365
#define GRAD                            366
#define CLIP                            367
#define INVERT                          368
#define INTER_LINE_SCROLL               370
#define IMAGE_INFO                      371
#define SAMPLE_TYPE_TEXT                372
#define FEEDBACK_ON_CURRENT             374
#define WAIT_FOR_CURRENT                375
#define TIP_SPACING                     376
#define TIP_SPACING_SCROLL              378
#define PAL_EXIT                        379
#define PAL_FCNS                        380
#define CONTROLS                        381
#define IMAGE_LOGPAL                    381
#define IO_X                            382
#define IO_Y                            383
#define IO_Z                            384
#define TIP_CONTROLS                    385
#define Y_RANGE_5                       386
#define IO_POS_CH                       387
#define Y_RANGE_10                      388
#define IO_POS_RANGE_10                 391
#define IO_POS_RANGE_5                  392
#define IO_POS_BITS                     393
#define IO_POS_VOLTS                    394
#define IO_POS_SCROLL                   395
#define Z_RANGE_5                       396
#define IO_X_OFFSET                     397
#define IO_Y_OFFSET                     398
#define IO_Z_OFFSET                     399
#define Z_RANGE_10                      400
#define COARSE_TRANS_X                  401
#define IO_BIAS_RANGE_5                 401
#define COARSE_TRANS_Y                  402
#define IO_BIAS_RANGE_10                402
#define X_OFFSET_RANGE_5                403
#define COARSE_PARACUT                  404
#define IO_OFFSET_CH                    405
#define COARSE_SAWTOOTH                 406
#define X_OFFSET_RANGE_10               407
#define COARSE_STEPS_EDIT               408
#define COARSE_ANGS_EDIT                409
#define COARSE_STEPS_SCROLL             410
#define COARSE_LSTEP                    411
#define COARSE_RSTEP                    412
#define COARSE_NUM_STEPS_EDIT           413
#define COARSE_NUM_STEPS_SCROLL         414
#define COARSE_LGO                      415
#define IO_OFFSET_RANGE_5               416
#define COARSE_RGO                      417
#define COARSE_X_EDIT                   418
#define COARSE_Y_EDIT                   419
#define COARSE_X_RESET                  421
#define COARSE_Y_RESET                  422
#define IO_OFFSET_RANGE_10              423
#define COARSE_EXIT                     424
#define COARSE_PERIOD_EDIT              425
#define COARSE_FREQ_EDIT                426
#define COARSE_PERIOD_SCROLL            427
#define COARSE_TIME_EDIT                428
#define COARSE_DISTANCE_EDIT            429
#define IO_OFFSET_BITS                  431
#define IO_OFFSET_SCROLL                432
#define Y_OFFSET_RANGE_5                433
#define IO_OFFSET_VOLTS                 434
#define Y_OFFSET_RANGE_10               435
#define IO_Z_01                         436
#define IO_Z_1                          437
#define IO_Z_10                         438
#define IO_Z2_01                        439
#define IO_Z2_1                         440
#define IO_Z2_10                        441
#define Z_OFFSET_RANGE_5                442
#define IO_X_01                         443
#define IO_X_1                          444
#define IO_X_10                         445
#define IO_Y_01                         446
#define IO_Y_1                          447
#define IO_Y_10                         448
#define IO_POS_SEND                     449
#define Z_OFFSET_RANGE_10               450
#define IO_FEEDBACK_ON                  451
#define IO_FEEDBACK_OFF                 452
#define O_BOX                           453
#define IO_RETRACT_ON                   454
#define IO_RETRACT_OFF                  455
#define O_CH_1                          456
#define O_CH_2                          457
#define IO_TRANSLATE                    458
#define IO_ROTATE                       459
#define IO_COARSE                       460
#define IO_FINE                         461
#define TIP_TRANSLATE_NE                461
#define O_CH_3                          462
#define TIP_TRANSLATE_SW                462
#define IO_DITHER0_OFF                  463
#define IO_OFFSET_SEND                  464
#define IO_POS_ANGS                     465
#define X_RANGE_5                       466
#define IO_DITHER0_ON                   466
#define X_RANGE_10                      467
#define PRE_SCAN_CONTROLS               468
#define IO_EXIT                         471
#define IO_OFFSET_ANGS                  472
#define O_CH_0                          473
#define IO_DITHER1_OFF                  473
#define SAMPLE_RATE                     474
#define IO_DITHER1_ON                   474
#define TIME_PER_DIVISION               485
#define TIME_PER_DIVISION_SCROLL        486
#define O_START                         487
#define O_STOP                          488
#define TIP_APPROACH                    501
#define TIP_EXIT                        503
#define IO_DEFAULTS                     504
#define O_EXIT                          505
#define O_READING                       506
#define O_SCREEN_SCROLL                 507
#define TIP_OSCILLOSCOPE                508
#define O_LOWER_V_0                     509
#define PRE_SCAN_OSCILLOSCOPE           510
#define O_LOWER_V_1                     511
#define UNCLIP                          512
#define O_HIGHER_V_1                    513
#define O_HIGHER_SCROLL_1               514
#define EQUALIZE                        515
#define O_LOWER_SCROLL_1                516
#define O_LOWER_SCROLL_0                517
#define ANIMATE                         518
#define O_LOWER_V_2                     519
#define HISTOGRAM                       520
#define O_HIGHER_V_2                    521
#define O_HIGHER_SCROLL_2               522
#define CLIP_TO_HIST                    523
#define O_LOWER_SCROLL_2                524
#define O_HIGHER_V_0                    525
#define UNEQUALIZE                      526
#define O_LOWER_V_3                     527
#define RANDPAL                         528
#define O_HIGHER_V_3                    529
#define O_HIGHER_SCROLL_3               530
#define FILTER_LIST                     531
#define O_LOWER_SCROLL_3                532
#define O_HIGHER_SCROLL_0               533
#define IO_REINIT                       534
#define O_OFFSET_1                      535
#define O_OFFSET_0_SCROLL               536
#define M_SCREEN_SCROLL                 537
#define O_OFFSET_2                      538
#define O_OFFSET_1_SCROLL               539
#define M_PRINT                         540
#define O_OFFSET_2_SCROLL               541
#define O_OFFSET_3_SCROLL               542
#define M_5V                            543
#define O_OFFSET_3                      544
#define O_TRIG_CH_0                     545
#define O_OFFSET_0                      546
#define O_TRIG_CH_1                     547
#define O_TRIG_CH_2                     548
#define O_TRIGGER                       549
#define O_TRIGGER_VALUE                 550
#define O_TRIGGER_SCROLL                551
#define O_TRIG_CH_3                     552
#define M_10V                           553
#define M_MIN_RANGE                     554
#define SCAN_FREQ_LOW                   555
#define IO_SQUARE_DELAY                 556
#define M_MINSCROLL                     557
#define SCAN_FREQ_LOW2                  557
#define M_MAX_RANGE                     558
#define IO_SQUARE_DELAY2                558
#define SCAN_FREQ_MED                   559
#define M_MAX_SCROLL                    560
#define SCAN_FREQ_MED2                  560
#define SCAN_FREQ_HIGH                  561
#define M_SPEED                         562
#define IO_SQUARE_DELAY3                562
#define TIP_UP_DEFAULTS                 563
#define M_AMU_SCROLL                    564
#define TIP_UP_DEFAULTS2                564
#define M_ZOOM                          565
#define TIP_UP_DEFAULTS3                565
#define TIP_DOWN_DEFAULTS               566
#define M_INPUT_CH                      567
#define TIP_UP_DEFAULTS4                567
#define M_OUPUT_CH                      568
#define TIP_UP_DEFAULTS5                568
#define SEL_FCNS                        569
#define SCAN_FREQ_MED3                  569
#define IM_X_SCROLL                     570
#define M_SCAN                          571
#define CRASH_TOLERANCE                 572
#define M_P1_MASS                       573
#define M_P1_PRESS                      574
#define TIP_NUM_GIANT                   575
#define TIP_BABY_SIZE                   576
#define TIP_GIANT_SCROLL                577
#define M_P2_MASS                       578
#define M_P2_PRESS                      579
#define TIP_BABY_SCROLL                 580
#define HEATER_TARGET_CURRENT           581
#define TIP_STATUS                      582
#define M_INTEGRAL                      583
#define M_SAVE                          584
#define M_LOAD                          585
#define M_MIN_SCROLL                    586
#define M_P1_SCROLL                     587
#define M_P2_SCROLL                     588
#define M_OUTPUT_CH                     589
#define M_ZOOM_IN                       590
#define M_ZOOM_OUT                      591
#define IM_BIG_SMALL                    592
#define TIP_TUNNEL_BITS                 593
#define M_P1_CALIB                      594
#define M_P2_PEAK                       595
#define M_P2_CALIB                      596
#define M_P1_PEAK                       597
#define M_CALIBRATE                     598
#define M_ZOOM_PEAK                     599
#define FINE_X_BITS_EDIT                600
#define FINE_X_VOLTS_EDIT               601
#define FINE_X_DISTANCE_EDIT            602
#define FINE_X_RAMP                     603
#define FINE_X_JUMP                     604
#define FINE_X_ZERO                     605
#define FINE_Y_BITS_EDIT                606
#define FINE_Y_VOLTS_EDIT               607
#define FINE_Y_DISTANCE_EDIT            608
#define FINE_Y_RAMP                     609
#define FINE_Y_JUMP                     610
#define FINE_Y_ZERO                     611
#define FINE_AUTO_RAMP                  612
#define FINE_EXIT                       613
#define FINE_X_SCROLL                   614
#define FINE_Y_SCROLL                   615
#define TIP_TUNNEL_SCROLL               616
#define M_V_SCALE                       617
#define M_V_SCALE_SCROLL                618
#define M_COMMENT                       619
#define CRASH_DO_NOTHING                620
#define TIP_TUNNEL_VOLTS                621
#define M_SPEC_SCALE                    622
#define CRASH_STOP                      623
#define TIP_STOP                        624
#define CRASH_AUTO_Z                    625
#define TIP_PASS_NUM                    626
#define HEATER_TARGET_SCROLL            627
#define M_SLOPE                         628
#define M_INTERCEPT                     629
#define CRASH_MINMAX_Z                  630
#define HEATER_INIT_RAMP                631
#define M_BACKGROUND                    632
#define M_BACK_FIND                     633
#define M_LOAD_CALIB                    634
#define DIGITAL_ABORT                   635
#define HEATER_INIT_RAMP_SCROLL         636
#define IM_Y_SCROLL                     637
#define IM_ZOOM_IN                      638
#define HEATER_SAVE                     639
#define IM_ZOOM_OUT                     640
#define HEATER_LOAD                     641
#define DIGITAL_MAX_TRY                 642
#define RANDOM_1                        643
#define HEATER_COOL_RAMP                644
#define Z_OFFSET_CRASH                  645
#define HEATER_COOL_RAMP_SCROLL         646
#define Z_OFFSET_AUTO_ABOVE             647
#define HEATER_STATUS                   648
#define HEATER_TIME                     649
#define HEATER_TIME_SCROLL              650
#define HEATER_EXIT                     651
#define HEATER_START_STOP               652
#define Z_OFFSET_AUTO_BELOW             653
#define HEATER_CHECK                    654
#define DEP_BOX                         655
#define HEATER_CHECK_SCROLL             656
#define HEATER_COMMENT                  657
#define SEL_POINTS                      658
#define SEL_LINE                        659
#define HEATER_VOLTAGE_CH               660
#define SEL_SQUARE                      661
#define HEATER_TEMP_CH                  662
#define SEL_CIRCLE                      663
#define HEATER_CURRENT_CH               664
#define DEPOSITION                      665
#define SCAN_PRESCAN2                   666
#define SEL_EXIT                        667
#define SCAN_TRACK                      667
#define SEL_P1_HSCROLL                  668
#define SCAN_LATMAN                     668
#define SEL_P1_VSCROLL                  669
#define SEL_P1_X_INT                    670
#define SEL_P1_X_VOLTS                  671
#define ANL_EXIT                        672
#define SEL_P1_Y_INT                    674
#define SEL_P1_Y_VOLTS                  675
#define SEL_P1_Z_FLOAT                  677
#define SEL_P1_Z_VOLTS                  678
#define IMAGE_GRID                      679
#define DEP_WRI_TIME                    680
#define SEL_P2_HSCROLL                  681
#define SEL_P2_VSCROLL                  682
#define SEL_P2_X_INT                    683
#define SEL_P2_X_VOLTS                  684
#define SEL_P2_Y_INT                    687
#define SEL_P2_Y_VOLTS                  688
#define ANL_AVG_Z2                      689
#define SEL_P2_Z_FLOAT                  690
#define SEL_P2_Z_VOLTS                  691
#define ANL_AVG_Z2_VOLTS                692
#define SEL_LOCK                        693
#define ANL_DEL1_X_INT                  694
#define ANL_DEL1_X_VOLTS                695
#define DEP_MOV_BIAS                    696
#define DEP_WRI_BIAS                    697
#define ANL_DEL1_Y_INT                  698
#define ANL_DEL1_Y_VOLTS                699
#define MASSPEC                         700
#define M_EXIT                          701
#define SUB_EXIT                        702
#define ANL_DEL1_Z_FLOAT                703
#define ANL_DEL1_Z_VOLTS                704
#define DEP_WRI_TIME_SC                 705
#define ANL_DEL1_DIST_FLOAT             705
#define SEL_INVERT                      706
#define ANL_DEL1_DIST_VOLTS             706
#define SEL_CROP                        707
#define ANL_DEL2_DIST_FLOAT             707
#define SEL_REPAINT_P1                  708
#define ANL_DEL2_DIST_VOLTS             708
#define SEL_REPAINT_P2                  709
#define SEL_MAX                         710
#define IM_SEL_REDRAW                   711
#define SEL_MIN                         712
#define IM_SEL_EXIT                     713
#define ANL_AVG_Z1                      714
#define ANL_AVG_Z1_VOLTS                715
#define DEP_MOV_BIAS_SC                 716
#define SEL_1_2                         717
#define SEL_REPAINT_L1                  718
#define SEL_REPAINT_L2                  719
#define DEP_WRI_BIAS_SC                 720
#define DEP_EXIT                        721
#define SEL_CONSTRAIN                   722
#define DEP_STATUS                      723
#define SEL_CUR_SEL                     724
#define DEP_STATUS1                     724
#define SEL_COPY                        725
#define DEP_STATUS2                     725
#define PRESCAN_SHARPEN                 726
#define DEP_STATUS4                     726
#define ANL_DEL2_X_INT                  727
#define DEP_STATUS3                     727
#define ANL_DEL2_X_VOLTS                728
#define SEL_SEL_CHANGED                 730
#define IMAGE_ILLUMINATE                731
#define SHARP_CYCLES                    732
#define ANL_DEL2_Y_INT                  733
#define ANL_DEL2_Y_VOLTS                734
#define ANL_DEL2_Z_VOLTS                736
#define SHARP_CYCLES_SCROLL             737
#define ANL_DEL2_Z_FLOAT                738
#define ANL_X1_ANGS                     739
#define IMAGE_LOAD_NEXT                 740
#define ANL_Y1_ANGS                     741
#define ANL_Z1_ANGS                     742
#define ANL_X2_ANGS                     743
#define SHARP_LINES                     744
#define ANL_DIST1_ANGS                  744
#define ANL_Y2_ANGS                     745
#define ANL_Z2_ANGS                     746
#define ANL_AVG_Z1_FLOAT                747
#define SHARP_LINES_SCROLL              748
#define ANL_DIST2_ANGS                  748
#define ANL_AVG_Z1_ANGS                 749
#define ANL_AVG_Z2_FLOAT                750
#define IMAGE_SUBTRACT                  751
#define ANL_AVG_Z2_ANGS                 752
#define IMAGE_FFT                       753
#define SHARP_BIAS1                     754
#define SHARP_BIAS2                     756
#define SHARP_BIAS2_SCROLL              757
#define SHARP_BIAS1_SCROLL              758
#define SHARP_EXIT                      759
#define IMAGE_IFFT                      760
#define IMAGE_ENHANCE                   761
#define PRESCAN_BIAS_FLIP               762
#define DEP_PULSE_EXIT                  763
#define PRESCAN_DOSED_WITH              764
#define PRESCAN_SAMPLE_LIST             765
#define PRESCAN_DOSED_LIST              766
#define SCAN_STATUS                     767
#define PRESCAN_CONSEQ                  768
#define READ_2_POLAR_IMAGES             769
#define PRESCAN_CONSEQ_SCROLL           770
#define SCAN_SWITCH_1_2                 771
#define SP_SKIP                         772
#define SP_SKIP_SCROLL                  773
#define INFO_WIDTH_PIXELS               774
#define SCAN_SPEC                       775
#define PRESCAN_OVER_WAIT1              776
#define DEP_MOV_CURRENT                 777
#define INFO_WIDTH_ANGS                 778
#define PRESCAN_OVER_WAIT2              779
#define DEP_WRI_CURRENT                 780
#define PRESCAN_OVER_FAST               781
#define PRESCAN_OVER_SLOW               782
#define PRESCAN_OVER_PERCENT            783
#define PRESCAN_DOSED_LANG              784
#define DEP_MOV_CURRENT_SCROLL          785
#define DEP_WRI_CURRENT_SCROLL          786
#define DEP_DOIT                        787
#define DEP_BOX_MODE                    788
#define DEP_LINES_MODE                  789
#define DEP_POLY_MODE                   790
#define DEP_STOP                        790
#define DEP_NUM_LINES                   791
#define SP_P2_VOLTS                     792
#define SP_P2_CURR                      793
#define PRESCAN_BIAS_SEND               794
#define DEP_MAX_BIAS                    795
#define DEP_MAX_BIAS_SCROLL             796
#define DEP_MAX_I                       797
#define DEP_MAX_I_SCROLL                798
#define DEP_PULSE_OPTIONS               799
#define DEP_POLY_SELECT                 800
#define DEP_MAX_I_SCROLL2               800
#define SCAN_SHARPEN                    801
#define DEP_PULSE_OPTIONS2              801
#define SCAN_SHARPENB                   802
#define DEP_MAX_I_SCROLL3               802
#define DEP_POLY_ADD                    803
#define DEP_PULSE_OPTIONS3              803
#define DEP_MAX_WRI_TIME                804
#define DEP_MAX_WRI_TIME_SC             805
#define SP_MIN_SCROLL                   806
#define SP_MAX_SCROLL                   807
#define SP_AMU_SCROLL                   808
#define SP_Z_OFFSET_BIAS_SCROLL         808
#define GRID_COPY_1                     809
#define SP_MIN_SCROLL2                  809
#define SP_P1_SCROLL                    810
#define SP_MAX_SCROLL2                  810
#define INFO_SAMPLE_TYPE                811
#define SP_TRIGGER_HIGH_SCROLL          811
#define SP_P2_SCROLL                    812
#define SP_TRIGGER_LOW_SCROLL           812
#define INFO_DOSED_WITH                 813
#define SP_MIN_RANGE                    814
#define INFO_COMMENT                    815
#define SP_Z_OFFSET_BIAS                815
#define INFO_WIDTH_VOLTS                816
#define SP_MIN_RANGE2                   816
#define SP_MAX_RANGE                    817
#define SP_SPEED                        818
#define INFO_DOSED_LANG                 819
#define SP_SPEED2                       819
#define SP_MAX_RANGE2                   819
#define SP_INPUT_CH                     820
#define SP_START_DELAY                  820
#define INFO_FILENAME                   821
#define SP_SPEED3                       821
#define SP_TRIGGER_TIME                 821
#define INFO_VERSION                    822
#define SP_TRIGGER_HIGH                 822
#define INFO_STEP_SIZE                  823
#define SP_TRIGGER_LOW                  823
#define INFO_X_GAIN                     824
#define SP_FINAL_DELAY                  824
#define SCAN_TRIGGER_PULSE              824
#define INFO_Y_GAIN                     825
#define SP_FB_DELAY                     825
#define INFO_Z_GAIN                     826
#define INFO_Z_FREQ                     827
#define GRID_COPY_2                     828
#define INFO_X_OFFSET                   829
#define INFO_Y_OFFSET                   830
#define INFO_Z_OFFSET                   831
#define INFO_Z_CRASH_PROT               832
#define INFO_SCAN_ORDER                 833
#define INFO_AMP_GAIN                   834
#define INFO_CURRENT                    835
#define INFO_BIAS                       836
#define INFO_INTER_STEP_DELAY           837
#define INFO_STEP_DELAY                 838
#define INFO_INTER_LINE_DELAY           839
#define INFO_DIGITAL_FEEDBACK           840
#define INFO_TIP_SPACING                841
#define INFO_SCAN_MODE                  842
#define INFO_SAMPLES                    843
#define INFO_OVERSHOT_BY                844
#define INFO_OVERSHOT_WAITS             845
#define INFO_EXIT                       846
#define SP_OUTPUT_CH                    847
#define GRID_COPY_3                     848
#define GRID_COPY_4                     849
#define SP_SCREEN_SCROLL                850
#define SP_ZOOM_IN                      851
#define SP_ZOOM_OUT                     852
#define SP_COMMENT                      853
#define SP_SCAN                         854
#define SP_SAVE_ALL                     855
#define SP_SAVE                         856
#define SP_LOAD                         857
#define SP_EXIT                         858
#define SP_P1_VOLTS                     859
#define SP_P1_PEAK                      860
#define SP_P1_CURR                      861
#define SP_P2_PEAK                      862
#define SP_PREAMP_SCALE                 863
#define SP_INTEGRAL                     864
#define SP_INFO                         864
#define SP_BACKGROUND                   865
#define SP_BACK_FIND                    866
#define DEP_PULSE_MODE                  868
#define SP_STOP_CRASHING                869
#define SP_CRASH_CURR                   870
#define GRID_SAVE                       871
#define SP_CRASH_CURR_SC                872
#define SP_CRASH_CURR_SCROLL            873
#define SP_NUM_SAMPLES                  874
#define SP_NUM_SAMPLES_SCROLL           875
#define DEP_PULSE_DURATION              876
#define DEP_PULSE_DURATION_SCROLL       877
#define SP_OUTPUT_CH_NAME               877
#define SP_STATUS                       878
#define SP_BIAS                         879
#define DEP_PULSE_FEEDBACK              880
#define DEP_PULSE_DURATION2             880
#define GRID_LOAD                       881
#define SP_NUM_PASSES                   881
#define DEP_PULSE_DURATION3             881
#define DEP_1_4_IMAGES                  882
#define SP_NUM_PASSES_SCROLL            882
#define SP_DELTA_X                      882
#define GRID_ANGLE_1                    883
#define SP_CURRENT                      883
#define SP_TRIGGER_CH                   883
#define GRID_ANGLE_0_SC                 884
#define SP_TRIGGER_CH_SCROLL            884
#define COMMENT2_EXIT                   885
#define DEP_PULSE_DURATION_FIXED        886
#define SP_DELTA_Y                      886
#define SP_GRAPH_IV                     887
#define SP_GRAPH_DIDV                   888
#define GRID_ANGLE_1_SC                 889
#define SP_CURRENT_SCROLL               889
#define SP_PRESCAN                      890
#define SP_DELTAZ_BITS                  891
#define DEP_PULSE_DURATION_Z            892
#define DEP_PULSE_DURATION_I            893
#define SP_DELTAZ_VOLTS                 894
#define SP_DELTAZ_SCROLL                895
#define DEP_PULSE_MEASURE               896
#define SP_CRASH_IN_RANGE               897
#define SP_CRASH_DO_NOTHING             898
#define SP_SCAN_TIME                    899
#define DEP_PULSE_MEASURE4              899
#define DEP_PULSE_MEASURE_SCROLL        900
#define DEP_OSCILL_I_MIN                902
#define DEP_PULSE_MEASURE2              902
#define DEP_OSCILL_I_MAX                903
#define DEP_PULSE_MEASURE3              903
#define DEP_OSCILL_I_MIN_SCROLL         904
#define DEP_PULSE_MEASURE5              904
#define DEP_OSCILL_I_MAX_SCROLL         905
#define DEP_PULSE_BIAS_SPEED            906
#define DEP_PULSE_BIAS_SPEED_SCROLL     907
#define SP_MEASURE_I                    908
#define DEP_PULSE_I_SPEED               909
#define DEP_PULSE_I_SPEED_SCROLL        910
#define DEP_PULSE_BIAS_STEP             911
#define DEP_PULSE_DURATION_MICRO        912
#define DEP_PULSE_DURATION_MILLI        913
#define SP_MEASURE_Z                    914
#define DEP_PULSE_Z_SCROLL              915
#define DEP_PULSE_Z_BITS                916
#define DEP_PULSE_Z_VOLTS               917
#define DEP_PULSE_Z_ANGS                918
#define GRID_ANGLE_2                    919
#define DEP_OSCILL_Z_MIN                920
#define DEP_PULSE_NUMBER                921
#define DEP_PULSE_NUMBER_SCROLL         922
#define DEP_OSCILL_Z_MAX                923
#define DEP_PULSE_BETWEEN_DELAY         924
#define DEP_INTER_PULSE_DELAY           924
#define DEP_OSCILL_Z_MIN_SCROLL         925
#define DEP_PULSE_MEASURE_I_ONCE        926
#define DEP_OSCILL_Z_MAX_SCROLL         928
#define DEP_PULSE_Z_SPEED               929
#define DEP_PULSE_Z_SPEED_SCROLL        930
#define DEP_PULSE_Z_CRASH               931
#define GRID_ANGLE_2_SC                 932
#define INFO_TEMPERATURE                933
#define DEP_PULSE_MEASURE_I_WAIT        934
#define GRID_DIST_0                     935
#define DEP_PULSE_AVG_I                 936
#define DEP_PULSE_FEEDBACK_ON           937
#define DEP_PULSE_FEEDBACK_OFF          938
#define DEP_PULSE_FEEDBACK_AFTER        939
#define GRID_DIST_0_SC                  940
#define DEP_PULSE_FREQ_1                941
#define DEP_PULSE_FREQ_10               942
#define DEP_PULSE_FREQ_100              943
#define DEP_PULSE_FREQ_LOW              944
#define DEP_PULSE_FREQ_MED              945
#define DEP_PULSE_FREQ_HIGH             946
#define DEP_PULSE_FEEDBACK_WAIT         947
#define GRID_DIST_1                     948
#define GRID_DIST_1_SC                  949
#define DEP_PULSE_USE_MOVE_BIAS         950
#define GRID_DIST_2                     951
#define GRID_DIST_2_SC                  952
#define DEP_PULSE_CHANGE_TIME           953
#define GRID_YINT_0                     954
#define GRID_YINT_0_SC                  955
#define GRID_YINT_1                     956
#define GRID_YINT_1_SC                  957
#define GRID_YINT_2                     958
#define GRID_YINT_2_SC                  959
#define COMMENT2_EDIT                   960
#define GRID_GET_0                      961
#define GRID_HIDE_0                     962
#define GRID_LOCK_0                     963
#define GRID_GET_1                      964
#define GRID_HIDE_1                     965
#define GRID_LOCK_1                     966
#define GRID_GET_2                      967
#define GRID_HIDE_2                     968
#define GRID_LOCK_2                     969
#define GRID_ANGLE_0                    970
#define IM_REDRAW_IMAGE                 971
#define GRID_GET_LINE                   971
#define GRID_NEW_IMAGE                  972
#define GRID_NUM_LINES_0                973
#define GRID_NUM_LINES_1                974
#define GRID_NUM_LINES_2                975
#define GRID_MATCH_3                    976
#define GRID_VERT_SC                    977
#define GRID_HORIZ_SC                   978
#define GRID_TOGGLE                     980
#define INFO_DEP_FILENAME               981
#define IMAGE_COMMENTS                  982
#define DEP_PULSE_AVG_STOP_PTS          983
#define IMAGE_AUTO_INFO                 984
#define IMAGE_PRINT                     985
#define DEP_PULSE_AFTER_TIME            986
#define PRINT_EXIT                      987
#define DEP_PULSE_PERCENT_CHANGE        989
#define DEP_PULSE_AVG_PTS               991
#define DEP_PULSE_IGNORE_INITIAL        994
#define COMMENT2_NEW_IMAGE              995
#define SUB_X                           996
#define SUB_Y                           997
#define SUB_GET                         998
#define PRINT_BW                        999
#define PRINT_EPS_X                     1002
#define PRINT_EPS_Y                     1003
#define PRINT_EPS_SCALE                 1004
#define PRINT_TEXT_JUST_C               1005
#define GRID_EXIT                       1006
#define PRINT_TEXT_JUST_L               1006
#define PRINT_GREY                      1007
#define PRINT_COLOR                     1008
#define PRINT_IMAGE_SIZE                1010
#define PRINT_FILENAME                  1012
#define PRINT_TEXT_JUST_R               1012
#define PRINT_IMAGE_FILENAME            1013
#define PRINT_GRID                      1014
#define PRINT_TEXT_ANGLE                1014
#define PRINT_GRID_FILENAME             1015
#define PRINT_PALETTE                   1016
#define PRINT_PALETTE_FILENAME          1017
#define PRINT_GRID_R                    1019
#define SMOOTH11                        1020
#define PRINT_TEXT_X                    1020
#define PRINT_GRID_G                    1021
#define PRINT_GRID_B                    1022
#define PRINT_IMAGE_X                   1028
#define DEP_MOV_TIME_SC                 1030
#define PRINT_TEXT_Y                    1030
#define PRINT_IMAGE_Y                   1031
#define PRINT_DEVICE_FILENAME           1034
#define PRINT_DEVICE_RES                1036
#define PRINT_PRINT                     1038
#define DEP_MOV_TIME                    1040
#define PRINT_ARROW_X1                  1040
#define PRINT_ADD_1                     1041
#define PRINT_ADD_2                     1042
#define PRINT_ADD_3                     1043
#define PRINT_ADD_4                     1044
#define PRINT_LINK_1                    1048
#define PRINT_LINK_2                    1049
#define ANL_FNCS                        1050
#define PRINT_ARROW_Y1                  1050
#define PRINT_LINK_3                    1051
#define PRINT_LINK_4                    1052
#define PRINT_DEVICE_GAMMA              1054
#define PRINT_LOAD                      1055
#define PRINT_SAVE                      1056
#define PRINT_OBJECT_SELECT             1058
#define PRINT_OBJECT_MOVE               1059
#define PRINT_OBJECT_ADD                1060
#define PRINT_ARROW_X2                  1060
#define PRINT_ADD_ARROW                 1061
#define PRINT_ADD_TEXT                  1062
#define PRINT_DELETE_SELECTED           1063
#define PRINT_STATUS                    1066
#define PRINT_TEXT                      1068
#define PRINT_TEXT_R                    1070
#define PRINT_TEXT_G                    1071
#define PRINT_TEXT_B                    1072
#define PRINT_TEXT_FONT                 1076
#define PRINT_TEXT_SIZE                 1077
#define PRINT_TEXT_FONT_NAME            1079
#define PRINT_ADD_EPS                   1080
#define PRINT_ARROW_Y2                  1081
#define PRINT_ARROW_R                   1083
#define PRINT_ARROW_G                   1084
#define PRINT_ARROW_B                   1085
#define PRINT_ARROW_WIDTH               1089
#define DEP_PULSE_MEASURE_Z             1090
#define PRINT_ARROW_HEAD                1090
#define DEP_PULSE_MEASURE_2             1091
#define GRID_CLIP_TO_LINE               1092
#define DEP_PULSE_MEASURE_Z3            1092
#define DEP_PULSE_MEASURE_3             1092
#define GRID_LINE_X1                    1093
#define GRID_LINE_Y1                    1094
#define GRID_LINE_X2                    1095
#define GRID_LINE_Y2                    1096
#define GRID_CLIP_Y_LESS                1099
#define SP_V_SCALE_MIN                  1100
#define IMAGE_USE_CURRENT               1100
#define LOGPAL_EXIT                     1101
#define LOGPAL_CREATE                   1102
#define LOGPAL_CURRENT_INDEX            1103
#define LOGPAL_R                        1104
#define LOGPAL_G                        1105
#define LOGPAL_B                        1106
#define LOGPAL_REMOVE                   1107
#define LOGPAL_EQUALIZED                1108
#define TRACK_AUTO_AUTO                 1108
#define PRINT_SAVE_LINKS_AS_ADDED       1108
#define SP_FORWARD                      1108
#define LOGPAL_GAMMA                    1109
#define SP_USE_Z_OFFSET_BIAS            1109
#define SP_V_SCALE_MIN_SCROLL           1110
#define LOGPAL_ADD_POINT                1110
#define LOGPAL_ADD_INDEX                1111
#define LOGPAL_NEXT                     1112
#define PRINT_COMPOUND                  1112
#define LOGPAL_PREV                     1113
#define PRINT_EXPLODE                   1113
#define LOGPAL_DESTROY                  1114
#define PRINT_ARROW_TYPE                1114
#define LOGPAL_VISUALIZE                1115
#define PRINT_GET_LINE                  1115
#define LOGPAL_REPAINT                  1116
#define TRACK_EXIT                      1116
#define TRACK_STOP                      1117
#define TRACK_START                     1118
#define TRACK_MAX_BITS                  1119
#define SP_ZOOM_TO_MIN                  1120
#define TRACK_CUR_LIMIT_Y_MIN           1120
#define TRACK_CUR_LIMIT_X_MIN           1121
#define TRACK_CUR_LIMIT_X_MAX           1122
#define TRACK_CUR_LIMIT_Y_MAX           1123
#define TRACK_CUR_POS_Y                 1124
#define TRACK_CUR_POS_X                 1125
#define SCAN_REPAINT_CURSOR             1126
#define TRACK_AVG_DATA_PTS              1126
#define TRACK_OFFSET_X                  1128
#define TRACK_OFFSET_Y                  1129
#define SP_MAX_CENTER                   1130
#define TRACK_SAMPLE_EVERY              1130
#define TRACK_MAX                       1131
#define TRACK_MIN                       1132
#define TRACK_START_AGAIN               1133
#define SP_TRACK_SAMPLE_EVERY           1133
#define TRACK_MAX_BITS_SCROLL           1134
#define IMAGE_DX                        1135
#define TRACK_PLANE_A                   1135
#define IM_3D2TEXT                      1136
#define TRACK_PLANE_B                   1136
#define INFODEP_FILENAME                1137
#define INFODEP_VERSION                 1138
#define INFODEP_Z_FREQ                  1139
#define INFODEP_TEMPERATURE             1140
#define INFODEP_Z_OFFSET                1141
#define INFODEP_Z_CRASH_PROT            1142
#define INFODEP_AMP_GAIN                1143
#define INFODEP_CURRENT                 1144
#define INFODEP_BIAS                    1145
#define INFODEP_MOVE_TIME               1146
#define INFODEP_WRITE_TIME              1147
#define INFODEP_SAMPLES                 1148
#define INFODEP_SAMPLE_TYPE             1149
#define SP_V_SCALE_SCROLL               1150
#define INFODEP_DOSED_WITH              1150
#define INFODEP_DOSED_LANG              1151
#define INFODEP_COMMENT                 1152
#define INFODEP_EXIT                    1153
#define INFODEP_MOVE_BIAS               1154
#define INFODEP_WRITE_BIAS              1155
#define INFODEP_MOVE_CURRENT            1156
#define INFODEP_WRITE_CURRENT           1157
#define INFODEP_PULSE_DURATION          1159
#define SP_V_SCALE                      1160
#define INFODEP_BIAS_SPEED              1160
#define INFODEP_CURRENT_SPEED           1161
#define INFODEP_Z_OFFSET_SPEED          1162
#define INFODEP_FEEDBACK                1163
#define INFODEP_Z_OFFSET_MOVEMENT_BIAS  1164
#define INFODEP_MEASURED                1165
#define TRACE_EXIT                      1166
#define TRACE_HIGH                      1167
#define TRACE_LOW                       1168
#define TRACE_FROM                      1169
#define TRACE_TO                        1170
#define TRACE_ANALYZE                   1171
#define TRACE_STATE_TOTAL               1172
#define TRACE_TOTAL                     1173
#define TRACE_NUM                       1174
#define TRACE_AVG_MS                    1175
#define TRACE_AVG_V                     1176
#define TRACE_AVG_MS2                   1177
#define TRACE_AVG_V2                    1178
#define TRACE_NUM2                      1179
#define TRACE_START_HIGH                1180
#define TRACE_START_LOW                 1181
#define TRACE_START_UNDEFINED           1182
#define TRACE_STATE_TOTAL2              1183
#define TRACE_NUM_SUM                   1184
#define TRACE_AVG_MS_SUM                1185
#define TRACE_AVG_V_SUM                 1186
#define TRACE_AVG_MS2_SUM               1187
#define TRACE_AVG_V2_SUM                1188
#define TRACE_NUM2_SUM                  1189
#define TRACE_ADD                       1190
#define TRACE_CLEAR                     1191
#define DEP_PULSE_Z_AFTER_NONE          1191
#define DEP_PULSE_Z_AFTER_AUTO          1192
#define DEP_PULSE_Z_AFTER_BACK          1193
#define DEP_PULSE_Z_AFTER_NONE2         1194
#define DEP_TRIGGER_STEP                1194
#define SP_MEASURE_2                    1195
#define DEP_PULSE_Z_AFTER_NONE3         1195
#define DEP_TRIGGER_PULSE               1195
#define SP_MEASURE_3                    1196
#define DEP_PULSE_Z_AFTER_NONE4         1196
#define DEP_TRIGGER_NONE                1196
#define SP_V_SPEED                      1197
#define SP_BACKWARD                     1199
#define SP_AVG_BOTH                     1200
#define COUNT_EXIT                      1201
#define SP_TRACK_MAX_BITS               1201
#define SP_TRACK_MAX_BITS_SCROLL        1202
#define COUNT_EXPORT                    1202
#define SP_TRACK_AVG_DATA_PTS           1203
#define SP_TRACK_MAX                    1204
#define SP_TRACK_MIN                    1205
#define SP_TRACK_EVERY                  1206
#define SP_TRACK_ITERATIONS             1207
#define SP_TRACK_OFFSET_Y               1208
#define SP_TRACK_OFFSET_X               1209
#define SP_BITS_PER_STEP                1210
#define SP_DITHER0_ON                   1211
#define SP_DITHER0_OFF                  1212
#define SP_DITHER1_ON                   1213
#define SP_DITHER1_OFF                  1214
#define SP_FEEDBACK_ON                  1215
#define SP_FEEDBACK_OFF                 1216
#define IO_EMERGENCY_EXIT               1216
#define SP_DITHER_WAIT                  1217
#define SP_CLEAR                        1218
#define SP_TRACK_PLANE_B                1218
#define SP_CLEAR_ALL                    1219
#define SP_TRACK_PLANE_A                1219
#define SP_FEEDBACK_EVERY               1220
#define SP_MOVE_DELAY                   1221
#define SP_FEEDBACK_ON_EVERY            1222
#define SP_FEEDBACK_WAIT                1223
#define INFOSPC_BITS_PER_STEP           1223
#define SP_TRACK_CURRENT_X              1224
#define INFOSPC_FILENAME                1224
#define SP_TRACK_CURRENT_Y              1225
#define INFOSPC_VERSION                 1225
#define INFOSPC_TEMPERATURE             1226
#define INFOSPC_FEEDBACK                1227
#define INFOSPC_SAMPLE_BIAS             1227
#define INFOSPC_FEEDBACK_EVERY          1228
#define INFOSPC_SEN1                    1228
#define INFOSPC_MEASURED                1229
#define INFOSPC_FEEDBACK_WAIT           1230
#define INFOSPC_I_SETPOINT              1230
#define INFOSPC_NUM_PASSES              1231
#define INFOSPC_SEN2                    1231
#define INFOSPC_SAMPLES                 1232
#define INFOSPC_W                       1232
#define INFOSPC_Z_OFFSET                1233
#define INFOSPc_Z_CRASH_PROT            1234
#define INFOSPC_OSC                     1234
#define INFOSPC_Z_OFFSET_BIAS           1235
#define INFOSPC_TC                      1235
#define INFOSPC_AMP_GAIN                1236
#define INFOSPC_OUT                     1236
#define INFOSPC_CURRENT                 1237
#define INFOSPC_N1                      1237
#define INFOSPC_BIAS                    1238
#define INFOSPC_PHA1                    1238
#define INFOSPC_MOVE_TIME               1239
#define INFOSPC_READ_TIME               1240
#define INFOSPC_BIAS_FROM               1241
#define INFOSPC_PHA2                    1241
#define INFOSPC_BIAS_TO                 1242
#define INFOSPC_SAMPLE_TYPE             1243
#define INFOSPC_DOSED_WITH              1244
#define INFOSPC_DOSED_LANG              1245
#define INFOSPC_COMMENT                 1246
#define INFOSPC_EXIT                    1247
#define INFOSPC_DITHER0                 1248
#define INFOSPC_DITHER1                 1249
#define INFOSPC_DITHER_WAIT             1250
#define INFOSPC_TRACK_MAX_BITS          1251
#define INFOSPC_TRACK_OFFSET_X          1252
#define INFOSPC_TRACK_OFFSET_Y          1253
#define INFOSPC_TRACK_AVG_DATA_PTS      1254
#define INFOSPC_TRACK_SAMPLE_EVERY      1255
#define INFOSPC_TRACK_ITERATIONS        1256
#define INFOSPC_TRACK_EVERY             1257
#define INFOSPC_TRACK_MAX               1258
#define INFOSPC_TRACK_MIN               1259
#define SP_SETTINGS_1                   1260
#define SP_SETTINGS_2                   1261
#define SP_SETTINGS_3                   1262
#define SP_SETTINGS_4                   1263
#define PRESCAN_FEEDBACK_READ_ON        1263
#define PRESCAN_FEEDBACK_READ_OFF       1264
#define PRESCAN_FEEDBACK_MOVE_ON        1265
#define PRESCAN_FEEDBACK_MOVE_OFF       1266
#define PRESCAN_FEEDBACK_END_ON         1266
#define PRESCAN_CHANNEL_0               1267
#define PRESCAN_RETRACT_END_ON          1267
#define PRESCAN_CHANNEL_1               1268
#define PRESCAN_TIPAUTO_END_ON          1268
#define PRESCAN_CHANNEL_2               1269
#define PRESCAN_FEEDBACK_END_ON4        1269
#define PRESCAN_CHANNEL_3               1270
#define PRESCAN_FEEDBACK_END_ON5        1270
#define PRESCAN_DITHER0_READ_ON         1271
#define PRESCAN_DITHER0_READ_OFF        1272
#define PRESCAN_DITHER0_MOVE_ON         1273
#define PRESCAN_DITHER0_MOVE_OFF        1274
#define PRESCAN_DITHER_WAIT             1275
#define PRINT_COPY                      1276
#define PRINT_PASTE                     1277
#define TIP_REINIT                      1278
#define PRESCAN_DITHER1_READ_ON         1279
#define TIP_BIAS                        1279
#define PRESCAN_DITHER1_READ_OFF        1280
#define SUB_Z                           1280
#define PRESCAN_DITHER1_MOVE_ON         1281
#define SUB_SUBTRACT                    1281
#define PRESCAN_DITHER1_MOVE_OFF        1282
#define SUB_AVERAGE                     1282
#define SUB_DIVIDE                      1283
#define ETEST_EXIT                      1284
#define ETEST_ON1                       1285
#define ETEST_ON2                       1286
#define ETEST_ON3                       1287
#define ETEST_ON4                       1288
#define ETEST_ON5                       1289
#define ETEST_ON6                       1290
#define ETEST_ON7                       1291
#define ETEST_ON8                       1292
#define ETEST_ON9                       1293
#define ETEST_ON10                      1294
#define ETEST_ON11                      1295
#define ETEST_ON12                      1296
#define ETEST_DIGITAL_OUTPUT            1297
#define ETEST_RAMP_FROM_V               1298
#define ETEST_RAMP_FROM_BITS            1298
#define ETEST_RAMP_TO_V                 1299
#define ETEST_RAMP_TO_BITS              1299
#define ETEST_RAMP_OUTPUT_CH            1300
#define ETEST_RAMP_INPUT_CH             1301
#define ETEST_RAMP_DO_IT                1302
#define COUNT_LOAD                      1302
#define ETEST_BIT_TEST_OUTPUT_CH        1303
#define ETEST_BIT_TEST_INPUT_CH         1304
#define ETEST_TEST_INPUT                1305
#define ETEST_TEST_OUTPUT               1306
#define ETEST_CALIBRATION               1307
#define COUNT_ADD                       1308
#define COUNT_ERASE                     1309
#define COUNT_RED                       1310
#define COUNT_CLEAR_ALL                 1311
#define COUNT_GREEN                     1312
#define COUNT_SYMBOL_SIZE               1313
#define IM_COUNTING                     1314
#define COUNT_SAVE                      1315
#define SUB_DIDV                        1316
#define SPOPT_EXIT                      1317
#define SP_OPTIONS                      1318
#define SP_ZOOM_PEAK                    1320
#define SP_MODE_ABSOLUTE                1320
#define SP_MODE_RELATIVE                1321
#define SP_TRACK_STEP_DELAY             1322
#define SP_X                            1323
#define SP_Y                            1324
#define SP_IMAGE_NAME                   1325
#define TRACK_STEP_DELAY                1326
#define COUNT_COMMENT                   1327
#define COUNT_HIDE                      1328
#define COUNT_BLUE                      1329
#define COUNT_CYAN                      1330
#define TRACE_REJECT                    1331
#define TRACE_REJECT_TIME               1332
#define TRACE_REJECT_THAT               1333
#define LOCKIN_EXIT                     1333
#define TRACE_REJECT_THAT_TIME          1334
#define LOCKIN_SEN1                     1334
#define LOCKIN_SEN2                     1335
#define LOCKIN_W                        1336
#define LOCKIN_OSC                      1337
#define LOCKIN_TC                       1338
#define LOCKIN_N1                       1339
#define LOCKIN_PHA1                     1340
#define LOCKIN_PHA2                     1341
#define SP_LOCKIN                       1342
#define SUB_SMOOTH                      1343
#define PRINT_OBJECT_COLOR              1344
#define PRINT_OBJECT                    1345
#define PRINT_MOVE_POS                  1346
#define PRINT_MOVE_X                    1347
#define PRINT_MOVE_Y                    1348
#define PRINT_SCALE_POS                 1349
#define DEP_PULSE_MEASURE_I             1350
#define PRINT_SCALE_FACTOR              1350
#define PRINT_ZOOM_IN                   1351
#define PRINT_ZOOM_OUT                  1352
#define PRINT_COUNTING_OPTIONS          1353
#define PRINT_X_SCROLL                  1354
#define PRINT_Y_SCROLL                  1355
#define TRACE_BIN_WIDTH                 1356
#define TRACE_SAVE_BIN                  1357
#define COUNT_R_1                       1358
#define COUNT_G_1                       1359
#define COUNT_B_1                       1360
#define COUNT_R_2                       1361
#define COUNT_G_2                       1362
#define COUNT_B_2                       1363
#define COUNT_R_3                       1364
#define COUNT_G_3                       1365
#define COUNT_B_3                       1366
#define COUNT_R_4                       1367
#define COUNT_G_4                       1368
#define COUNT_B_4                       1369
#define COUNT_CONVERT                   1370
#define PRESCAN_RECORD_CH               1371
#define PRESCAN_READ_CH                 1372
#define PRESCAN_RS_INCH                 1372
#define PRESCAN_ADD                     1373
#define PRESCAN_DEL                     1374
#define PRESCAN_INSERT                  1375
#define PRESCAN_SUMMARY                 1376
#define PRESCAN_SAVE_SEQUENCE           1377
#define PRESCAN_NEXT                    1378
#define PRESCAN_PREVIOUS                1379
#define PRESCAN_SAVE_SEQUENCE2          1380
#define PRESCAN_LOAD_SEQUENCE           1380
#define PRESCAN_SEQUENCE_NUMBER         1381
#define PRESCAN_WAIT_1                  1382
#define PRESCAN_RS_OUTCH                1382
#define PRESCAN_WAIT_2                  1383
#define SCAN_1                          1383
#define PRESCAN_RS_BITS                 1383
#define PRESCAN_WAIT_3                  1384
#define SCAN_2                          1384
#define PRESCAN_RS_WAIT                 1384
#define SCAN_3                          1385
#define PRESCAN_WAIT_4                  1385
#define SCAN_4                          1386
#define SCAN_CURRENT_DATA_SCROLL        1387
#define SCAN_CURRENT_DATA               1388
#define SCAN_SAVE_PARAMETERS            1389
#define SCAN_LOAD_PARAMETERS            1390
#define INFO_SEQ_SUMMARY                1391
#define INFO_INPUT_CH                   1392
#define INFO_DITHER_0                   1393
#define INFO_DITHER_1                   1394
#define INFO_FEEDBACK                   1395
#define INFO_SEQUENCE                   1396
#define SCAN_SAVE_ALL                   1397
#define COUNT_SLOPPY_ERASE              1398
#define COUNT_HORIZ_SCROLL              1399
#define COUNT_VERT_SCROLL               1400
#define SUB_SCALE                       1401
#define SUB_PARAM1                      1402
#define SUB_PARAM2                      1403
#define SUB_PARAM3                      1404
#define SUB_INTEGRATE                   1405
#define IMAGE_ROTATE                    1406
#define FOURIER_FFT                     1409
#define FOURIER_IFFT                    1410
#define FOURIER_FHT                     1411
#define FOURIER_IFHT                    1412
#define FOURIER_LOW                     1413
#define FOURIER_HIGH                    1414
#define FOURIER_BAND_PASS               1415
#define FOURIER_BAND_STOP               1416
#define FOURIER_RECTANGLE               1417
#define FOURIER_TRIANGLE                1418
#define FOURIER_HANNING                 1419
#define FOURIER_HAMMING                 1420
#define FOURIER_BARTLETT                1421
#define FOURIER_LOW_CUTOFF              1422
#define FOURIER_HIGH_CUTOFF             1423
#define FOURIER_ORDER                   1424
#define FOURIER_FILTER                  1425
#define FOURIER_EXIT                    1426
#define HOP_STEP_DELAY                  1431
#define HOP_INTERSTEP_DELAY             1432
#define HOP_RADIUS                      1433
#define HOP_EVERY                       1434
#define HOP_EXPONENT                    1435
#define HOP_FREQUENCY                   1436
#define HOP_AVG_DATA_PTS                1437
#define HOP_A                           1438
#define HOP_MIN                         1439
#define HOP_MAX                         1440
#define HOP_START_TRACKING              1441
#define HOP_STOP_TRACKING               1442
#define HOP_SAVE                        1443
#define HOP_EXIT                        1444
#define SCAN_HOP                        1445
#define TRACE_TIME_BIN                  1446
#define HOP_B                           1448
#define EXP_DIR_OK                      1449
#define EXP_DIR_CANCEL                  1450
#define EXPORT_SRC_DIR                  1452
#define EXPORT_DEST_DIR                 1453
#define SP_TRACK_AT_MIN                 1453
#define SP_FEEDBACK_AT_MIN              1454
#define SP_OFFSET_HOLD_ON               1455
#define IO_ZOFFSET_1                    1456
#define SP_TRIGGER_ON                   1456
#define IO_ZOFFSET_7                    1457
#define PRESCAN_READ_RAMPBIAS           1457
#define SP_START_DELAY_ON               1457
#define IO_BIAS_CH0                     1458
#define SP_FINAL_DELAY_ON               1458
#define IO_BIAS_CH10                    1459
#define SP_FB_DELAY_ON                  1459
#define PRINT_IMAGE_RES_RAW             1460
#define SP_STEP_DELAY_ON                1460
#define PRINT_IMAGE_RES_SMOOTH          1461
#define SP_VIB_MAP                      1461
#define SP_STEPTRIGGER_ON               1461
#define SP_CHOOSE_MAP                   1462
#define VM_REF_X                        1465
#define VM_REF_Y                        1466
#define VM_POINT_NUM                    1467
#define VM_OFF_X                        1468
#define VM_OFF_Y                        1469
#define VM_NEXT                         1470
#define VM_PREV                         1471
#define VM_CLEAR                        1472
#define VM_ADD                          1473
#define VM_INSERT                       1474
#define VM_DELETE                       1475
#define VM_LOAD                         1476
#define VM_SAVE                         1477
#define SPC_VM_POINT_LABEL              1477
#define VM_SAVE_AS_CNT                  1478
#define SPC_VM_POINT                    1478
#define TIP_SAMPLE_LIST                 1478
#define VM_EXIT                         1479
#define SPC_VM_XOFF_LABEL               1479
#define TIP_DOSED_LIST                  1479
#define VM_DOT_R                        1480
#define SPC_VM_YOFF_LABEL               1480
#define TIP_SAMPLE_TYPE_TEXT            1480
#define VM_DOT_G                        1481
#define SPC_VM_XOFF                     1481
#define TIP_DOSED_WITH                  1481
#define VM_DOT_B                        1482
#define SPC_VM_YOFF                     1482
#define HOP_ESC_MESSAGE                 1482
#define VM_DOT_SIZE                     1483
#define STATIC_TEXT                     1483
#define STATIC_TEXT_2                   1484
#define VM_LINE_PTS                     1484
#define STATIC_TEXT_3                   1485
#define VM_NUM_LINES                    1485
#define DEP_V_SCALE_MAX                 1486
#define VM_TRANS_X                      1486
#define DEP_V_SCALE_MAX_SCROLL          1487
#define VM_TRANS_Y                      1487
#define DEP_V_SCALE_MIN                 1488
#define VM_IMPORT_REF                   1488
#define DEP_V_SCALE_MIN_SCROLL          1489
#define DEP_ZOOM_MAX                    1490
#define DEP_ZOOM_CENTER                 1491
#define DEP_ZOOM_MIN                    1492
#define LM_INITIAL_X                    1493
#define LM_INITIAL_Y                    1494
#define LM_FINAL_X                      1495
#define LM_FINAL_Y                      1496
#define LM_SWITCH                       1497
#define LM_INTERSTEP_DELAY              1498
#define LM_READ_DELAY                   1499
#define LM_MEASURE_EVERY                1500
#define LM_IMAGE_BIAS_BITS              1501
#define LM_IMAGE_BIAS_V                 1502
#define LM_IMAGE_BIAS_SCROLL            1503
#define LM_IMPORT_IMAGE_BIAS            1504
#define LM_IMPORT                       1504
#define LM_MANIP_BIAS_BITS              1505
#define LM_MANIP_BIAS_SCROLL            1506
#define LM_MANIP_BIAS_V                 1507
#define LM_EXIT                         1508
#define LM_STOP                         1509
#define PRESCAN_A_PER_V                 1509
#define LM_START                        1510
#define PRESCAN_Z_A_PER_V               1510
#define LOCKIN_USED                     1510
#define LM_COMMENT                      1511
#define LOCKIN_NOT_USED                 1511
#define LM_INFO                         1512
#define LM_LOAD                         1513
#define LM_SAVE                         1514
#define INFOSPC_PASSES                  1514
#define INFOSPC_FEEDBACK_DESC           1515
#define LM_IMAGE_I_BITS                 1515
#define INFOSPC_TRACK_DESC              1516
#define LM_IMAGE_I_SCROLL               1516
#define INFOSPC_SETTINGS_RECORDED       1517
#define LM_IMAGE_I_NA                   1517
#define LM_MANIP_I_BITS                 1518
#define LM_MANIP_I_SCROLL               1519
#define LM_MANIP_I_NA                   1520
#define LM_V_SCALE_MIN_SCROLL           1521
#define LM_V_SCALE_MAX_SCROLL           1522
#define LM_V_SCALE_MAX                  1523
#define LM_V_SCALE_MIN                  1524
#define LM_ZOOM_PEAK                    1525
#define LM_ZOOM_TO_MAX                  1525
#define LM_MAX_CENTER                   1526
#define LM_CENTER                       1526
#define LM_ZOOM_TO_MIN                  1527
#define LM_DO_READ_Z                    1528
#define LM_COLOR_R                      1529
#define LM_COLOR_G                      1530
#define LM_COLOR_G2                     1531
#define LM_COLOR_B                      1531
#define LM_READ_N_TIMES                 1532
#define LM_STATUS                       1533
#define LM_RAMP_DELAY                   1534
#define LM_Z_SLOPE                      1535
#define LM_FBACK_OFF                    1536
#define LM_CALC_SLOPE                   1537
#define PRESCAN_RS_TYPE                 1542
#define PRESCAN_RS_ON                   1543
#define PRESCAN_RS_OFF                  1544
#define VM_PATTERN_LINE                 1545
#define PRESCAN_RS_ON2                  1545
#define VM_PATTERN_MESH                 1546
#define PRESCAN_RS_OFF2                 1546
#define VM_PATTERN_WHEEL                1547
#define SAVE_AS_TOP                     1548
#define LM_CONST_I                      1549
#define LM_CONST_Z                      1550
#define SP_USE_READSQ                   1551
#define SP_RS_TYPE                      1552
#define SP_RS_ON                        1553
#define SP_RS_OFF                       1554
#define SP_RS_WAIT                      1555
#define SP_RS_INCH                      1556
#define SP_RS_NUM                       1557
#define SP_RS_OUTCH                     1558
#define SP_RS_BITS                      1559
#define SP_RS_VOLTS                     1560
#define SP_RS_SCROLL                    1561
#define SP_ADD                          1562
#define SP_DEL                          1563
#define SP_INSERT                       1564
#define SP_NEXT                         1565
#define SP_PREVIOUS                     1566
#define SP_SUMMARY                      1567
#define SCAN_R                          1568
#define SCAN_F                          1569
#define SCAN_G                          1570
#define SP_RAMP_DELAY                   1571
#define IDC_PROGRESS1                   1572
#define Current_RampTo_Btn              1573
#define IDC_OPENSERIAL                  1574
#define Current_RampTo_Edit             1574
#define IDC_CLOSESERIAL                 1575
#define Current_RampTo_Stop             1575
#define IDC_SPIN1                       1576
#define Current_RampTo_Btn2             1576
#define SP_STEP_DELAY                   1577
#define Current_RampToSpeed_Edit        1577
#define TIP_TRANSLATE_CRASH             1578
#define Current_RampTo_Edit2            1578
#define Bias_RampTo_Btn                 1579
#define SCAN_OFFSET_AUTO_BELOW          1579
#define Bias_RampTo_Edit                1580
#define DEP_OFFSET_AUTO_BELOW           1580
#define Bias_RampTo_Stop                1581
#define SPE_OFFSET_AUTO_BELOW           1581
#define DEP_TRACK_MAX_BITS              1582
#define Current_RampTo_Edit5            1582
#define Bias_RampToSpeed_Edit           1583
#define DEP_TRACK_MAX_BITS_SCROLL       1583
#define Current_RampToSpeed_Edit2       1584
#define DEP_TRACK_AVG_DATA_PTS          1584
#define Current_RampTo_Btn3             1585
#define DEP_TRACK_MAX                   1585
#define Current_RampTo_Edit3            1586
#define DEP_TRACK_MIN                   1586
#define DEP_TRACK_SAMPLE_EVERY          1587
#define Current_RampToSpeed_Edit3       1588
#define DEP_TRACK_ITERATIONS            1588
#define TIP_TRANSLATE_SAMPLE_CHECK      1589
#define Current_RampTo_Btn4             1589
#define DEP_TRACK_EVERY                 1589
#define Current_RampTo_Edit4            1590
#define DEP_TRACK_OFFSET_X              1590
#define DEP_TRACK_CURRENT_X             1591
#define Current_RampToSpeed_Edit4       1592
#define DEP_TRACK_CURRENT_Y             1592
#define Bias_RampTo_Btn2                1593
#define DEP_TRACK_OFFSET_Y              1593
#define Bias_RampTo_Edit2               1594
#define DEP_TRACK_STEP_DELAY            1594
#define DEP_TRACK_PLANE_A               1595
#define Bias_RampTo_Edit5               1595
#define Bias_RampToSpeed_Edit2          1596
#define DEP_TRACK_PLANE_B               1596
#define Bias_RampTo_Btn3                1597
#define DEP_TRACK_AT_MIN                1597
#define Bias_RampTo_Edit3               1598
#define DEP_OFFSET_HOLD_ON              1598
#define SCAN_TRIGGER_HIGH               1599
#define Bias_RampToSpeed_Edit3          1600
#define SCAN_TRIGGER_LOW                1600
#define Bias_RampTo_Btn4                1601
#define DEP_TRIGGER_START               1601
#define Bias_RampTo_Edit4               1602
#define DEP_TRIGGER_END                 1602
#define DEP_TRIGGER_UP                  1603
#define Bias_RampToSpeed_Edit4          1604
#define DEP_TRIGGER_DOWN                1604
#define DEP_TRIGGER_CH                  1606
#define DEP_TRIGGER_CH_SCROLL           1607
#define DEP_TRIGGER_HIGH                1608
#define DEP_TRIGGER_LOW                 1609
#define DEP_TRIGGER_HIGH_SCROLL         1610
#define DEP_TRIGGER_LOW_SCROLL          1611
#define DEP_TRIGGER_TIME                1612
#define DEP_TRIGGER_TOHIGH              1613
#define DEP_TRIGGER_TOLOW               1614
#define MOH_TEST                        2560
#define TEST_ONE                        2560
#define IOCTRL                          2561
#define TIME_TEST                       2562
#define TEST_TWO                        2562
#define AD_TEST                         2563
#define TEST_THREE                      2563
#define INPUT_SWITCH_TEST               2564
#define HOP_C                           2564
#define TEST_FOUR                       2564
#define ONE_INPUT_TEST                  2565
#define TEST_FIVE                       2565
#define PRESCAN2_EXIT                   2566
#define SCAN_REPAINT_STATUS             2600
#define SCAN_REPAINT_FINE_POS           2601
#define SCAN_REPAINT_TRACK_LIMITS       2602
#define SCAN_TRACKING_START             2603
#define SCAN_TRACKING_STOP              2604
#define IMAGE_TRACE                     2605
#define IMAGE_REPAINT_TRACE_LIMITS      2610
#define COUNT_NEW_IMAGE                 2620
#define FOURIER_NEW_IMAGE               2625
#define LOGPAL_EXIT2                    2630
#define SCAN_REPAINT_SIZES              4321
#define TIP_TRANSLATE_SAMPLE            5001
#define TIP_TRANSLATE_SAMPLE_NW         5003
#define TIP_TRANSLATE_SAMPLE_NE         5004
#define TIP_TRANSLATE_SAMPLE_SE         5005
#define TIP_TRANSLATE_SAMPLE_SW         5006
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        124
#define _APS_NEXT_COMMAND_VALUE         109
#define _APS_NEXT_CONTROL_VALUE         1615
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
