# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'electronictest.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ElectronicTest(object):
    def setupUi(self, ElectronicTest):
        ElectronicTest.setObjectName("ElectronicTest")
        ElectronicTest.resize(455, 250)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ElectronicTest.sizePolicy().hasHeightForWidth())
        ElectronicTest.setSizePolicy(sizePolicy)
        ElectronicTest.setMinimumSize(QtCore.QSize(455, 250))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/menuIcon/testiconblack.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ElectronicTest.setWindowIcon(icon)
        self.gridLayout_3 = QtWidgets.QGridLayout(ElectronicTest)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.RampTest = QtWidgets.QTabWidget(ElectronicTest)
        self.RampTest.setObjectName("RampTest")
        self.IO = QtWidgets.QWidget()
        self.IO.setObjectName("IO")
        self.RampTest.addTab(self.IO, "")
        self.RampTest1 = QtWidgets.QWidget()
        self.RampTest1.setObjectName("RampTest1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.RampTest1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_2 = QtWidgets.QWidget(self.RampTest1)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(160, 160))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_2.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.widget)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.widget)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout.addWidget(self.spinBox_2, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.widget)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout.addWidget(self.spinBox_3, 4, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 5, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 5, 1, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.widget_2, 0, 0, 1, 1)
        self.RampTest.addTab(self.RampTest1, "")
        self.SquareWave = QtWidgets.QWidget()
        self.SquareWave.setObjectName("SquareWave")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.SquareWave)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 0, 1, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.SquareWave)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 1, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.widget_3)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_3, 0, 2, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_5.addWidget(self.doubleSpinBox, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 1, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout_5.addWidget(self.doubleSpinBox_2, 2, 2, 1, 1)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.gridLayout_5.addWidget(self.doubleSpinBox_3, 3, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 2, 1, 1, 1)
        self.gridLayout_6.addWidget(self.widget_3, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem1, 1, 0, 1, 1)
        self.RampTest.addTab(self.SquareWave, "")
        self.Oscilloscope = QtWidgets.QWidget()
        self.Oscilloscope.setObjectName("Oscilloscope")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.Oscilloscope)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widget_4 = QtWidgets.QWidget(self.Oscilloscope)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_9.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.widget_4)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.gridLayout_9.addWidget(self.graphicsView_2, 0, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.widget_4)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_8.setContentsMargins(3, 3, 3, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.comboBox_4 = QtWidgets.QComboBox(self.widget_5)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_8.addWidget(self.comboBox_4, 0, 1, 1, 3)
        self.label_10 = QtWidgets.QLabel(self.widget_5)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem2, 0, 4, 1, 1)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.widget_5)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout_8.addWidget(self.doubleSpinBox_4, 0, 7, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.widget_5)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_8.addWidget(self.radioButton, 1, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget_5)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_8.addWidget(self.radioButton_2, 2, 0, 1, 1)
        self.spinBox_5 = QtWidgets.QSpinBox(self.widget_5)
        self.spinBox_5.setObjectName("spinBox_5")
        self.gridLayout_8.addWidget(self.spinBox_5, 2, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget_5)
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 0, 8, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem3, 2, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget_5)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 0, 5, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget_5)
        self.label_13.setObjectName("label_13")
        self.gridLayout_8.addWidget(self.label_13, 1, 2, 1, 1)
        self.spinBox_4 = QtWidgets.QSpinBox(self.widget_5)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout_8.addWidget(self.spinBox_4, 1, 3, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_8.addWidget(self.pushButton_3, 1, 7, 4, 1)
        self.label_14 = QtWidgets.QLabel(self.widget_5)
        self.label_14.setObjectName("label_14")
        self.gridLayout_8.addWidget(self.label_14, 2, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget_5)
        self.label_15.setObjectName("label_15")
        self.gridLayout_8.addWidget(self.label_15, 1, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem4, 1, 5, 1, 1)
        self.gridLayout_9.addWidget(self.widget_5, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.widget_4, 0, 0, 1, 1)
        self.RampTest.addTab(self.Oscilloscope, "")
        self.Echo = QtWidgets.QWidget()
        self.Echo.setObjectName("Echo")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.Echo)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.widget_6 = QtWidgets.QWidget(self.Echo)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_10.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_10.addWidget(self.pushButton_4, 0, 1, 2, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_10.addWidget(self.lineEdit_2, 1, 0, 1, 1)
        self.gridLayout_11.addWidget(self.widget_6, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem5, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem6, 0, 1, 1, 1)
        self.RampTest.addTab(self.Echo, "")
        self.gridLayout_3.addWidget(self.RampTest, 0, 0, 1, 1)

        self.retranslateUi(ElectronicTest)
        self.RampTest.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(ElectronicTest)

    def retranslateUi(self, ElectronicTest):
        _translate = QtCore.QCoreApplication.translate
        ElectronicTest.setWindowTitle(_translate("ElectronicTest", "ELectronic Test"))
        self.RampTest.setTabText(self.RampTest.indexOf(self.IO), _translate("ElectronicTest", "I/O"))
        self.label.setText(_translate("ElectronicTest", "Out channel"))
        self.comboBox.setItemText(0, _translate("ElectronicTest", "0 (X IN)"))
        self.comboBox.setItemText(1, _translate("ElectronicTest", "1 (X OFFSET)"))
        self.comboBox.setItemText(2, _translate("ElectronicTest", "2 (Z OFFSET FINE)"))
        self.comboBox.setItemText(3, _translate("ElectronicTest", "3 (Z OFFSET)"))
        self.comboBox.setItemText(4, _translate("ElectronicTest", "5 (ISET)"))
        self.comboBox.setItemText(5, _translate("ElectronicTest", "6 (DAC6)"))
        self.comboBox.setItemText(6, _translate("ElectronicTest", "7 (DAC7)"))
        self.comboBox.setItemText(7, _translate("ElectronicTest", "8 (DAC8)"))
        self.comboBox.setItemText(8, _translate("ElectronicTest", "9 (DAC9)"))
        self.comboBox.setItemText(9, _translate("ElectronicTest", "10 (ZOUTER)"))
        self.comboBox.setItemText(10, _translate("ElectronicTest", "11 (DAC11)"))
        self.comboBox.setItemText(11, _translate("ElectronicTest", "13 (BIAS)"))
        self.comboBox.setItemText(12, _translate("ElectronicTest", "14 (Y OFFSET)"))
        self.comboBox.setItemText(13, _translate("ElectronicTest", "15 (Y IN)"))
        self.comboBox.setItemText(14, _translate("ElectronicTest", "20 (20bitDAC)"))
        self.label_2.setText(_translate("ElectronicTest", "In channel"))
        self.comboBox_2.setItemText(0, _translate("ElectronicTest", "0 (AIN0)"))
        self.comboBox_2.setItemText(1, _translate("ElectronicTest", "1 (AIN1)"))
        self.comboBox_2.setItemText(2, _translate("ElectronicTest", "2 (AIN2)"))
        self.comboBox_2.setItemText(3, _translate("ElectronicTest", "3 (AIN3)"))
        self.comboBox_2.setItemText(4, _translate("ElectronicTest", "4 (AIN4)"))
        self.comboBox_2.setItemText(5, _translate("ElectronicTest", "5 (AIN5)"))
        self.comboBox_2.setItemText(6, _translate("ElectronicTest", "7 (PREAMP)"))
        self.label_3.setText(_translate("ElectronicTest", "Initial value"))
        self.label_4.setText(_translate("ElectronicTest", "Final value"))
        self.label_5.setText(_translate("ElectronicTest", "Step size"))
        self.pushButton.setText(_translate("ElectronicTest", "Ramp"))
        self.pushButton_2.setText(_translate("ElectronicTest", "Ramp read"))
        self.RampTest.setTabText(self.RampTest.indexOf(self.RampTest1), _translate("ElectronicTest", "Ramp test"))
        self.label_9.setText(_translate("ElectronicTest", "Voltage2"))
        self.label_7.setText(_translate("ElectronicTest", "Delay"))
        self.comboBox_3.setItemText(0, _translate("ElectronicTest", "0 (X IN)"))
        self.comboBox_3.setItemText(1, _translate("ElectronicTest", "1 (X OFFSET)"))
        self.comboBox_3.setItemText(2, _translate("ElectronicTest", "2 (Z OFFSET FINE)"))
        self.comboBox_3.setItemText(3, _translate("ElectronicTest", "3 (Z OFFSET)"))
        self.comboBox_3.setItemText(4, _translate("ElectronicTest", "5 (I SET)"))
        self.comboBox_3.setItemText(5, _translate("ElectronicTest", "6 (DAC6)"))
        self.comboBox_3.setItemText(6, _translate("ElectronicTest", "7 (DAC7)"))
        self.comboBox_3.setItemText(7, _translate("ElectronicTest", "8 (DAC8)"))
        self.comboBox_3.setItemText(8, _translate("ElectronicTest", "9 (DAC9)"))
        self.comboBox_3.setItemText(9, _translate("ElectronicTest", "10 (ZOUTER)"))
        self.comboBox_3.setItemText(10, _translate("ElectronicTest", "11 (DAC11)"))
        self.comboBox_3.setItemText(11, _translate("ElectronicTest", "13 (BIAS)"))
        self.comboBox_3.setItemText(12, _translate("ElectronicTest", "14 (Y OFFSET)"))
        self.comboBox_3.setItemText(13, _translate("ElectronicTest", "15 (Y IN)"))
        self.comboBox_3.setItemText(14, _translate("ElectronicTest", "20 (20bitDAC)"))
        self.label_6.setText(_translate("ElectronicTest", "Channel"))
        self.label_8.setText(_translate("ElectronicTest", "Vlotage1"))
        self.RampTest.setTabText(self.RampTest.indexOf(self.SquareWave), _translate("ElectronicTest", "Square wave"))
        self.comboBox_4.setItemText(0, _translate("ElectronicTest", "0 (AIN0)"))
        self.comboBox_4.setItemText(1, _translate("ElectronicTest", "1 (AIN1)"))
        self.comboBox_4.setItemText(2, _translate("ElectronicTest", "2 (AIN2)"))
        self.comboBox_4.setItemText(3, _translate("ElectronicTest", "3 (AIN3)"))
        self.comboBox_4.setItemText(4, _translate("ElectronicTest", "4 (AIN4)"))
        self.comboBox_4.setItemText(5, _translate("ElectronicTest", "5 (AIN5)"))
        self.comboBox_4.setItemText(6, _translate("ElectronicTest", "7 (PREAMP)"))
        self.label_10.setText(_translate("ElectronicTest", "Input channel"))
        self.radioButton.setText(_translate("ElectronicTest", "N sample"))
        self.radioButton_2.setText(_translate("ElectronicTest", "Continuous"))
        self.label_12.setText(_translate("ElectronicTest", "us"))
        self.label_11.setText(_translate("ElectronicTest", "Delay"))
        self.label_13.setText(_translate("ElectronicTest", "# of samples"))
        self.pushButton_3.setText(_translate("ElectronicTest", "Start/Stop"))
        self.label_14.setText(_translate("ElectronicTest", "Average"))
        self.label_15.setText(_translate("ElectronicTest", "times"))
        self.RampTest.setTabText(self.RampTest.indexOf(self.Oscilloscope), _translate("ElectronicTest", "Oscilloscope"))
        self.pushButton_4.setText(_translate("ElectronicTest", "Query"))
        self.RampTest.setTabText(self.RampTest.indexOf(self.Echo), _translate("ElectronicTest", "Echo"))
import logo_rc
