# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HoGroupSTM(object):
    def setupUi(self, HoGroupSTM):
        HoGroupSTM.setObjectName("HoGroupSTM")
        HoGroupSTM.setEnabled(True)
        HoGroupSTM.resize(600, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(HoGroupSTM.sizePolicy().hasHeightForWidth())
        HoGroupSTM.setSizePolicy(sizePolicy)
        HoGroupSTM.setMinimumSize(QtCore.QSize(600, 100))
        font = QtGui.QFont()
        font.setPointSize(8)
        HoGroupSTM.setFont(font)
        HoGroupSTM.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/STMlogo_NiCp2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/logo/STMlogo_blackhole.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/logo/STMlogo_NiCp2.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/logo/STMlogo_blackhole.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/logo/STMlogo_NiCp2.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/logo/STMlogo_blackhole.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        HoGroupSTM.setWindowIcon(icon)
        HoGroupSTM.setWindowOpacity(1.0)
        HoGroupSTM.setAutoFillBackground(True)
        HoGroupSTM.setDockNestingEnabled(False)
        HoGroupSTM.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks|QtWidgets.QMainWindow.GroupedDragging)
        HoGroupSTM.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(HoGroupSTM)
        self.centralwidget.setObjectName("centralwidget")
        HoGroupSTM.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(HoGroupSTM)
        self.statusbar.setObjectName("statusbar")
        HoGroupSTM.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(HoGroupSTM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        HoGroupSTM.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar = QtWidgets.QMenuBar(HoGroupSTM)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTip_Approach = QtWidgets.QMenu(self.menubar)
        self.menuTip_Approach.setObjectName("menuTip_Approach")
        self.menuScan = QtWidgets.QMenu(self.menubar)
        self.menuScan.setObjectName("menuScan")
        self.menuControl = QtWidgets.QMenu(self.menubar)
        self.menuControl.setObjectName("menuControl")
        self.menuTest = QtWidgets.QMenu(self.menubar)
        self.menuTest.setSeparatorsCollapsible(False)
        self.menuTest.setToolTipsVisible(False)
        self.menuTest.setObjectName("menuTest")
        self.menuData_Manipulation = QtWidgets.QMenu(self.menubar)
        self.menuData_Manipulation.setObjectName("menuData_Manipulation")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        HoGroupSTM.setMenuBar(self.menubar)
        self.Zcontrol = QtWidgets.QDockWidget(HoGroupSTM)
        self.Zcontrol.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Zcontrol.sizePolicy().hasHeightForWidth())
        self.Zcontrol.setSizePolicy(sizePolicy)
        self.Zcontrol.setFloating(True)
        self.Zcontrol.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.Zcontrol.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.Zcontrol.setObjectName("Zcontrol")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.dockWidgetContents_3)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.page_5)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_8.addWidget(self.label_12)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lcdNumber = QtWidgets.QLCDNumber(self.page_5)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout_2.addWidget(self.lcdNumber)
        self.widget_2 = QtWidgets.QWidget(self.page_5)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.page_5)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.widget = QtWidgets.QWidget(self.page_5)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.horizontalLayout.addWidget(self.doubleSpinBox_3)
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.label_14)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_9 = QtWidgets.QPushButton(self.widget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_7.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_7.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.widget)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_7.addWidget(self.pushButton_11)
        self.gridLayout_3.addLayout(self.verticalLayout_7, 0, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.widget)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.gridLayout_6.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.page_6)
        self.label_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_11.setMidLineWidth(0)
        self.label_11.setTextFormat(QtCore.Qt.PlainText)
        self.label_11.setScaledContents(True)
        self.label_11.setWordWrap(False)
        self.label_11.setIndent(-2)
        self.label_11.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11)
        self.frame_4 = QtWidgets.QFrame(self.page_6)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_9.setContentsMargins(20, -1, 20, 20)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_9.addWidget(self.label_9, 2, 0, 1, 1)
        self.radioButton_7 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_7.setObjectName("radioButton_7")
        self.gridLayout_9.addWidget(self.radioButton_7, 3, 0, 1, 1)
        self.radioButton_8 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_8.setObjectName("radioButton_8")
        self.gridLayout_9.addWidget(self.radioButton_8, 3, 1, 1, 1)
        self.radioButton_9 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_9.setObjectName("radioButton_9")
        self.gridLayout_9.addWidget(self.radioButton_9, 3, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.page_6)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_10.setContentsMargins(20, -1, 20, 20)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_10 = QtWidgets.QLabel(self.frame_5)
        self.label_10.setObjectName("label_10")
        self.gridLayout_10.addWidget(self.label_10, 0, 0, 1, 1)
        self.radioButton_12 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_12.setObjectName("radioButton_12")
        self.gridLayout_10.addWidget(self.radioButton_12, 1, 0, 1, 1)
        self.radioButton_11 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_11.setObjectName("radioButton_11")
        self.gridLayout_10.addWidget(self.radioButton_11, 1, 1, 1, 1)
        self.radioButton_10 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_10.setObjectName("radioButton_10")
        self.gridLayout_10.addWidget(self.radioButton_10, 1, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_5)
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = QtWidgets.QFrame(self.page_7)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.frame)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.gridLayout_4.addWidget(self.frame, 4, 0, 1, 2)
        self.frame_2 = QtWidgets.QFrame(self.page_7)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_2.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_2.addWidget(self.radioButton_4)
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_2.addWidget(self.checkBox_2)
        self.gridLayout_4.addWidget(self.frame_2, 4, 2, 1, 2)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.page_7)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout_4.addWidget(self.doubleSpinBox_2, 1, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_4.addWidget(self.pushButton_3, 2, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_4.addWidget(self.pushButton_2, 3, 1, 1, 2)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.page_7)
        self.doubleSpinBox.setWrapping(True)
        self.doubleSpinBox.setReadOnly(True)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_4.addWidget(self.doubleSpinBox, 1, 1, 1, 2)
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.page_7)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.gridLayout_4.addWidget(self.horizontalScrollBar, 2, 0, 1, 3)
        self.pushButton = QtWidgets.QPushButton(self.page_7)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 3, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.page_7)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButton_5 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_3.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_3.addWidget(self.radioButton_6)
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_3.addWidget(self.checkBox_3)
        self.gridLayout_4.addWidget(self.frame_3, 4, 4, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.page_7)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_7)
        self.gridLayout_5.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.Zcontrol.setWidget(self.dockWidgetContents_3)
        HoGroupSTM.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.Zcontrol)
        self.Bias = QtWidgets.QDockWidget(HoGroupSTM)
        self.Bias.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(38)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bias.sizePolicy().hasHeightForWidth())
        self.Bias.setSizePolicy(sizePolicy)
        self.Bias.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.Bias.setAcceptDrops(True)
        self.Bias.setFloating(True)
        self.Bias.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.Bias.setObjectName("Bias")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.biastab1 = QtWidgets.QWidget()
        self.biastab1.setObjectName("biastab1")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.biastab1)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.frame_9 = QtWidgets.QFrame(self.biastab1)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.frame_9)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.verticalLayout_10.addWidget(self.lcdNumber_2)
        self.horizontalSlider = QtWidgets.QSlider(self.frame_9)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_10.addWidget(self.horizontalSlider)
        self.gridLayout_16.addLayout(self.verticalLayout_10, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_29 = QtWidgets.QLabel(self.frame_9)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_3.addWidget(self.label_29)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.frame_9)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout_16.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.gridLayout_15.addWidget(self.frame_9, 0, 0, 1, 1)
        self.tabWidget.addTab(self.biastab1, "")
        self.biastab2 = QtWidgets.QWidget()
        self.biastab2.setObjectName("biastab2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.biastab2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.doubleSpinBox_17 = QtWidgets.QDoubleSpinBox(self.biastab2)
        self.doubleSpinBox_17.setObjectName("doubleSpinBox_17")
        self.gridLayout_11.addWidget(self.doubleSpinBox_17, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.biastab2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_11.addWidget(self.label_19, 0, 1, 1, 1)
        self.doubleSpinBox_15 = QtWidgets.QDoubleSpinBox(self.biastab2)
        self.doubleSpinBox_15.setObjectName("doubleSpinBox_15")
        self.gridLayout_11.addWidget(self.doubleSpinBox_15, 0, 2, 1, 1)
        self.doubleSpinBox_22 = QtWidgets.QDoubleSpinBox(self.biastab2)
        self.doubleSpinBox_22.setObjectName("doubleSpinBox_22")
        self.gridLayout_11.addWidget(self.doubleSpinBox_22, 1, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.biastab2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_11.addWidget(self.label_16, 1, 1, 1, 1)
        self.doubleSpinBox_16 = QtWidgets.QDoubleSpinBox(self.biastab2)
        self.doubleSpinBox_16.setObjectName("doubleSpinBox_16")
        self.gridLayout_11.addWidget(self.doubleSpinBox_16, 1, 2, 1, 1)
        self.doubleSpinBox_21 = QtWidgets.QDoubleSpinBox(self.biastab2)
        self.doubleSpinBox_21.setObjectName("doubleSpinBox_21")
        self.gridLayout_11.addWidget(self.doubleSpinBox_21, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.biastab2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_11.addWidget(self.label_17, 2, 1, 1, 1)
        self.doubleSpinBox_19 = QtWidgets.QDoubleSpinBox(self.biastab2)
        self.doubleSpinBox_19.setObjectName("doubleSpinBox_19")
        self.gridLayout_11.addWidget(self.doubleSpinBox_19, 2, 2, 1, 1)
        self.doubleSpinBox_18 = QtWidgets.QDoubleSpinBox(self.biastab2)
        self.doubleSpinBox_18.setObjectName("doubleSpinBox_18")
        self.gridLayout_11.addWidget(self.doubleSpinBox_18, 3, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.biastab2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_11.addWidget(self.label_18, 3, 1, 1, 1)
        self.doubleSpinBox_20 = QtWidgets.QDoubleSpinBox(self.biastab2)
        self.doubleSpinBox_20.setObjectName("doubleSpinBox_20")
        self.gridLayout_11.addWidget(self.doubleSpinBox_20, 3, 2, 1, 1)
        self.doubleSpinBox_24 = QtWidgets.QDoubleSpinBox(self.biastab2)
        self.doubleSpinBox_24.setObjectName("doubleSpinBox_24")
        self.gridLayout_11.addWidget(self.doubleSpinBox_24, 4, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.biastab2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_11.addWidget(self.label_21, 4, 1, 1, 1)
        self.doubleSpinBox_27 = QtWidgets.QDoubleSpinBox(self.biastab2)
        self.doubleSpinBox_27.setObjectName("doubleSpinBox_27")
        self.gridLayout_11.addWidget(self.doubleSpinBox_27, 4, 2, 1, 1)
        self.doubleSpinBox_30 = QtWidgets.QDoubleSpinBox(self.biastab2)
        self.doubleSpinBox_30.setObjectName("doubleSpinBox_30")
        self.gridLayout_11.addWidget(self.doubleSpinBox_30, 5, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.biastab2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_11.addWidget(self.label_22, 5, 1, 1, 1)
        self.doubleSpinBox_29 = QtWidgets.QDoubleSpinBox(self.biastab2)
        self.doubleSpinBox_29.setObjectName("doubleSpinBox_29")
        self.gridLayout_11.addWidget(self.doubleSpinBox_29, 5, 2, 1, 1)
        self.doubleSpinBox_28 = QtWidgets.QDoubleSpinBox(self.biastab2)
        self.doubleSpinBox_28.setObjectName("doubleSpinBox_28")
        self.gridLayout_11.addWidget(self.doubleSpinBox_28, 6, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.biastab2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_11.addWidget(self.label_23, 6, 1, 1, 1)
        self.doubleSpinBox_26 = QtWidgets.QDoubleSpinBox(self.biastab2)
        self.doubleSpinBox_26.setObjectName("doubleSpinBox_26")
        self.gridLayout_11.addWidget(self.doubleSpinBox_26, 6, 2, 1, 1)
        self.doubleSpinBox_25 = QtWidgets.QDoubleSpinBox(self.biastab2)
        self.doubleSpinBox_25.setObjectName("doubleSpinBox_25")
        self.gridLayout_11.addWidget(self.doubleSpinBox_25, 7, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.biastab2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_11.addWidget(self.label_20, 7, 1, 1, 1)
        self.doubleSpinBox_23 = QtWidgets.QDoubleSpinBox(self.biastab2)
        self.doubleSpinBox_23.setObjectName("doubleSpinBox_23")
        self.gridLayout_11.addWidget(self.doubleSpinBox_23, 7, 2, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.biastab2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_11.addWidget(self.pushButton_5, 8, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.biastab2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_11.addWidget(self.label_25, 8, 1, 1, 1)
        self.doubleSpinBox_31 = QtWidgets.QDoubleSpinBox(self.biastab2)
        self.doubleSpinBox_31.setObjectName("doubleSpinBox_31")
        self.gridLayout_11.addWidget(self.doubleSpinBox_31, 8, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.biastab2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_11.addWidget(self.label_24, 8, 3, 1, 1)
        self.tabWidget.addTab(self.biastab2, "")
        self.biastab4 = QtWidgets.QWidget()
        self.biastab4.setObjectName("biastab4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.biastab4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_6 = QtWidgets.QFrame(self.biastab4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_12.setContentsMargins(-1, -1, -1, 20)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_26 = QtWidgets.QLabel(self.frame_6)
        self.label_26.setObjectName("label_26")
        self.gridLayout_12.addWidget(self.label_26, 0, 0, 1, 1)
        self.radioButton_16 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_16.setObjectName("radioButton_16")
        self.gridLayout_12.addWidget(self.radioButton_16, 1, 0, 1, 1)
        self.radioButton_17 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_17.setObjectName("radioButton_17")
        self.gridLayout_12.addWidget(self.radioButton_17, 1, 1, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.biastab4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_13.setContentsMargins(-1, -1, -1, 20)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_27 = QtWidgets.QLabel(self.frame_7)
        self.label_27.setObjectName("label_27")
        self.gridLayout_13.addWidget(self.label_27, 0, 0, 1, 1)
        self.radioButton_18 = QtWidgets.QRadioButton(self.frame_7)
        self.radioButton_18.setObjectName("radioButton_18")
        self.gridLayout_13.addWidget(self.radioButton_18, 1, 0, 1, 1)
        self.radioButton_19 = QtWidgets.QRadioButton(self.frame_7)
        self.radioButton_19.setObjectName("radioButton_19")
        self.gridLayout_13.addWidget(self.radioButton_19, 1, 1, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.biastab4)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_14.setContentsMargins(-1, -1, -1, 20)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_28 = QtWidgets.QLabel(self.frame_8)
        self.label_28.setObjectName("label_28")
        self.gridLayout_14.addWidget(self.label_28, 0, 0, 1, 2)
        self.radioButton_20 = QtWidgets.QRadioButton(self.frame_8)
        self.radioButton_20.setObjectName("radioButton_20")
        self.gridLayout_14.addWidget(self.radioButton_20, 1, 0, 1, 1)
        self.radioButton_21 = QtWidgets.QRadioButton(self.frame_8)
        self.radioButton_21.setObjectName("radioButton_21")
        self.gridLayout_14.addWidget(self.radioButton_21, 1, 1, 1, 1)
        self.radioButton_22 = QtWidgets.QRadioButton(self.frame_8)
        self.radioButton_22.setObjectName("radioButton_22")
        self.gridLayout_14.addWidget(self.radioButton_22, 1, 2, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_8)
        self.tabWidget.addTab(self.biastab4, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        self.Bias.setWidget(self.dockWidgetContents)
        HoGroupSTM.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.Bias)
        self.Current = QtWidgets.QDockWidget(HoGroupSTM)
        self.Current.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Current.sizePolicy().hasHeightForWidth())
        self.Current.setSizePolicy(sizePolicy)
        self.Current.setAcceptDrops(True)
        self.Current.setFloating(True)
        self.Current.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.Current.setObjectName("Current")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.splitter = QtWidgets.QSplitter(self.dockWidgetContents_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.frame1 = QtWidgets.QFrame(self.splitter)
        self.frame1.setFrameShape(QtWidgets.QFrame.Box)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame1.setObjectName("frame1")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.radioButton_15 = QtWidgets.QRadioButton(self.frame1)
        self.radioButton_15.setObjectName("radioButton_15")
        self.gridLayout_8.addWidget(self.radioButton_15, 1, 0, 1, 1)
        self.radioButton_14 = QtWidgets.QRadioButton(self.frame1)
        self.radioButton_14.setObjectName("radioButton_14")
        self.gridLayout_8.addWidget(self.radioButton_14, 1, 1, 1, 1)
        self.radioButton_13 = QtWidgets.QRadioButton(self.frame1)
        self.radioButton_13.setObjectName("radioButton_13")
        self.gridLayout_8.addWidget(self.radioButton_13, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.frame1)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 0, 0, 1, 1)
        self.frame_21 = QtWidgets.QFrame(self.splitter)
        self.frame_21.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_21)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.frame_21)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.verticalLayout_4.addWidget(self.doubleSpinBox_5)
        self.horizontalScrollBar_3 = QtWidgets.QScrollBar(self.frame_21)
        self.horizontalScrollBar_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_3.setObjectName("horizontalScrollBar_3")
        self.verticalLayout_4.addWidget(self.horizontalScrollBar_3)
        self.frame_31 = QtWidgets.QFrame(self.splitter)
        self.frame_31.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_31.setObjectName("frame_31")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_31)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.frame_31)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.gridLayout_2.addWidget(self.doubleSpinBox_8, 0, 2, 1, 1)
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.frame_31)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.gridLayout_2.addWidget(self.doubleSpinBox_7, 1, 0, 1, 1)
        self.doubleSpinBox_13 = QtWidgets.QDoubleSpinBox(self.frame_31)
        self.doubleSpinBox_13.setObjectName("doubleSpinBox_13")
        self.gridLayout_2.addWidget(self.doubleSpinBox_13, 3, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_31)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(self.frame_31)
        self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
        self.gridLayout_2.addWidget(self.doubleSpinBox_9, 1, 2, 1, 1)
        self.doubleSpinBox_12 = QtWidgets.QDoubleSpinBox(self.frame_31)
        self.doubleSpinBox_12.setObjectName("doubleSpinBox_12")
        self.gridLayout_2.addWidget(self.doubleSpinBox_12, 2, 2, 1, 1)
        self.doubleSpinBox_11 = QtWidgets.QDoubleSpinBox(self.frame_31)
        self.doubleSpinBox_11.setObjectName("doubleSpinBox_11")
        self.gridLayout_2.addWidget(self.doubleSpinBox_11, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_31)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_31)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 1, 1, 1)
        self.doubleSpinBox_10 = QtWidgets.QDoubleSpinBox(self.frame_31)
        self.doubleSpinBox_10.setObjectName("doubleSpinBox_10")
        self.gridLayout_2.addWidget(self.doubleSpinBox_10, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_31)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 4, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_31)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 4, 0, 1, 1)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.frame_31)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.gridLayout_2.addWidget(self.doubleSpinBox_6, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_31)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 1, 1, 1)
        self.doubleSpinBox_14 = QtWidgets.QDoubleSpinBox(self.frame_31)
        self.doubleSpinBox_14.setObjectName("doubleSpinBox_14")
        self.gridLayout_2.addWidget(self.doubleSpinBox_14, 4, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_31)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 4, 3, 1, 1)
        self.gridLayout_7.addWidget(self.splitter, 0, 0, 1, 1)
        self.Current.setWidget(self.dockWidgetContents_2)
        HoGroupSTM.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.Current)
        self.toolBar_2 = QtWidgets.QToolBar(HoGroupSTM)
        self.toolBar_2.setObjectName("toolBar_2")
        HoGroupSTM.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.actionOpen_O = QtWidgets.QAction(HoGroupSTM)
        self.actionOpen_O.setCheckable(False)
        self.actionOpen_O.setChecked(False)
        self.actionOpen_O.setAutoRepeat(True)
        self.actionOpen_O.setObjectName("actionOpen_O")
        self.actionSave_S = QtWidgets.QAction(HoGroupSTM)
        self.actionSave_S.setObjectName("actionSave_S")
        self.actionBias = QtWidgets.QAction(HoGroupSTM)
        self.actionBias.setObjectName("actionBias")
        self.actionCurrent = QtWidgets.QAction(HoGroupSTM)
        self.actionCurrent.setObjectName("actionCurrent")
        self.actionZ = QtWidgets.QAction(HoGroupSTM)
        self.actionZ.setObjectName("actionZ")
        self.actionScan = QtWidgets.QAction(HoGroupSTM)
        self.actionScan.setObjectName("actionScan")
        self.actionSpectra = QtWidgets.QAction(HoGroupSTM)
        self.actionSpectra.setObjectName("actionSpectra")
        self.actionDeposition = QtWidgets.QAction(HoGroupSTM)
        self.actionDeposition.setObjectName("actionDeposition")
        self.actionTrack = QtWidgets.QAction(HoGroupSTM)
        self.actionTrack.setObjectName("actionTrack")
        self.actionHop = QtWidgets.QAction(HoGroupSTM)
        self.actionHop.setObjectName("actionHop")
        self.actionManipulation = QtWidgets.QAction(HoGroupSTM)
        self.actionManipulation.setObjectName("actionManipulation")
        self.actionShow_All_A = QtWidgets.QAction(HoGroupSTM)
        self.actionShow_All_A.setObjectName("actionShow_All_A")
        self.actionManual_A = QtWidgets.QAction(HoGroupSTM)
        self.actionManual_A.setObjectName("actionManual_A")
        self.toolBar.addSeparator()
        self.menuFile.addAction(self.actionOpen_O)
        self.menuFile.addAction(self.actionSave_S)
        self.menuScan.addAction(self.actionScan)
        self.menuScan.addAction(self.actionSpectra)
        self.menuScan.addAction(self.actionDeposition)
        self.menuScan.addAction(self.actionTrack)
        self.menuScan.addAction(self.actionHop)
        self.menuScan.addAction(self.actionManipulation)
        self.menuControl.addAction(self.actionBias)
        self.menuControl.addAction(self.actionCurrent)
        self.menuControl.addAction(self.actionZ)
        self.menuControl.addAction(self.actionShow_All_A)
        self.menuHelp.addAction(self.actionManual_A)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuControl.menuAction())
        self.menubar.addAction(self.menuTip_Approach.menuAction())
        self.menubar.addAction(self.menuScan.menuAction())
        self.menubar.addAction(self.menuTest.menuAction())
        self.menubar.addAction(self.menuData_Manipulation.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(HoGroupSTM)
        self.stackedWidget.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(2)
        self.actionBias.triggered['bool'].connect(self.Bias.close)
        self.actionCurrent.triggered['bool'].connect(self.Current.repaint)
        self.actionZ.triggered['bool'].connect(self.Zcontrol.hide)
        QtCore.QMetaObject.connectSlotsByName(HoGroupSTM)

    def retranslateUi(self, HoGroupSTM):
        _translate = QtCore.QCoreApplication.translate
        HoGroupSTM.setWindowTitle(_translate("HoGroupSTM", "HoGroupSTM"))
        self.toolBar.setWindowTitle(_translate("HoGroupSTM", "toolBar"))
        self.menuFile.setTitle(_translate("HoGroupSTM", "File"))
        self.menuTip_Approach.setTitle(_translate("HoGroupSTM", "Tip Approach"))
        self.menuScan.setTitle(_translate("HoGroupSTM", "Scan"))
        self.menuControl.setTitle(_translate("HoGroupSTM", "Control"))
        self.menuTest.setTitle(_translate("HoGroupSTM", "menu"))
        self.menuData_Manipulation.setTitle(_translate("HoGroupSTM", "Data Manipulation"))
        self.menuSetting.setTitle(_translate("HoGroupSTM", "Setting"))
        self.menuHelp.setTitle(_translate("HoGroupSTM", "Help"))
        self.Zcontrol.setWindowTitle(_translate("HoGroupSTM", "Z control"))
        self.label_12.setText(_translate("HoGroupSTM", "Z offset(fine)"))
        self.label_13.setText(_translate("HoGroupSTM", "Advance"))
        self.label_14.setText(_translate("HoGroupSTM", "bits"))
        self.pushButton_9.setText(_translate("HoGroupSTM", "Zero"))
        self.pushButton_10.setText(_translate("HoGroupSTM", "Match current"))
        self.pushButton_11.setText(_translate("HoGroupSTM", "advance"))
        self.label_11.setText(_translate("HoGroupSTM", "ZGain Control"))
        self.label_9.setText(_translate("HoGroupSTM", "Z1 Gain"))
        self.radioButton_7.setText(_translate("HoGroupSTM", "0.1"))
        self.radioButton_8.setText(_translate("HoGroupSTM", "1"))
        self.radioButton_9.setText(_translate("HoGroupSTM", "10"))
        self.label_10.setText(_translate("HoGroupSTM", "Z2 Gain"))
        self.radioButton_12.setText(_translate("HoGroupSTM", "0.1"))
        self.radioButton_11.setText(_translate("HoGroupSTM", "1"))
        self.radioButton_10.setText(_translate("HoGroupSTM", "10"))
        self.radioButton.setText(_translate("HoGroupSTM", "Dither ON"))
        self.radioButton_2.setText(_translate("HoGroupSTM", "Dither OFF"))
        self.checkBox.setText(_translate("HoGroupSTM", "Dither"))
        self.radioButton_3.setText(_translate("HoGroupSTM", "Retract ON"))
        self.radioButton_4.setText(_translate("HoGroupSTM", "Retract OFF"))
        self.checkBox_2.setText(_translate("HoGroupSTM", "Retract"))
        self.pushButton_3.setText(_translate("HoGroupSTM", "Send"))
        self.pushButton_2.setText(_translate("HoGroupSTM", "Hard retract"))
        self.pushButton.setText(_translate("HoGroupSTM", "Z-auto"))
        self.radioButton_5.setText(_translate("HoGroupSTM", "Feedback ON"))
        self.radioButton_6.setText(_translate("HoGroupSTM", "Feedback OFF"))
        self.checkBox_3.setText(_translate("HoGroupSTM", "Feedback"))
        self.label_15.setText(_translate("HoGroupSTM", "Z offset"))
        self.Bias.setWindowTitle(_translate("HoGroupSTM", "Bias"))
        self.label_29.setText(_translate("HoGroupSTM", "Range:+/-"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.biastab1), _translate("HoGroupSTM", "Control"))
        self.label_19.setText(_translate("HoGroupSTM", "Ramp to"))
        self.label_16.setText(_translate("HoGroupSTM", "Ramp to"))
        self.label_17.setText(_translate("HoGroupSTM", "Ramp to"))
        self.label_18.setText(_translate("HoGroupSTM", "Ramp to"))
        self.label_21.setText(_translate("HoGroupSTM", "Ramp to"))
        self.label_22.setText(_translate("HoGroupSTM", "Ramp to"))
        self.label_23.setText(_translate("HoGroupSTM", "Ramp to"))
        self.label_20.setText(_translate("HoGroupSTM", "Ramp to"))
        self.pushButton_5.setText(_translate("HoGroupSTM", "Stop ramp"))
        self.label_25.setText(_translate("HoGroupSTM", "Ramp Speed"))
        self.label_24.setText(_translate("HoGroupSTM", "Bit/ms"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.biastab2), _translate("HoGroupSTM", "Ramp"))
        self.label_26.setText(_translate("HoGroupSTM", "Dither"))
        self.radioButton_16.setText(_translate("HoGroupSTM", "Dither ON"))
        self.radioButton_17.setText(_translate("HoGroupSTM", "Dither OFF"))
        self.label_27.setText(_translate("HoGroupSTM", "DAC"))
        self.radioButton_18.setText(_translate("HoGroupSTM", "20 bit"))
        self.radioButton_19.setText(_translate("HoGroupSTM", "16 bit"))
        self.label_28.setText(_translate("HoGroupSTM", "Range"))
        self.radioButton_20.setText(_translate("HoGroupSTM", "+/- 2.5"))
        self.radioButton_21.setText(_translate("HoGroupSTM", "+/- 5"))
        self.radioButton_22.setText(_translate("HoGroupSTM", "+/-10"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.biastab4), _translate("HoGroupSTM", "Electro"))
        self.Current.setWindowTitle(_translate("HoGroupSTM", "Current"))
        self.radioButton_15.setText(_translate("HoGroupSTM", "10"))
        self.radioButton_14.setText(_translate("HoGroupSTM", "9"))
        self.radioButton_13.setText(_translate("HoGroupSTM", "8"))
        self.label.setText(_translate("HoGroupSTM", "Gain"))
        self.label_2.setText(_translate("HoGroupSTM", "Control"))
        self.label_3.setText(_translate("HoGroupSTM", "Ramp to"))
        self.label_5.setText(_translate("HoGroupSTM", "Ramp to"))
        self.label_6.setText(_translate("HoGroupSTM", "Ramp to"))
        self.label_7.setText(_translate("HoGroupSTM", "Ramp speed"))
        self.pushButton_4.setText(_translate("HoGroupSTM", "Stop ramp"))
        self.label_4.setText(_translate("HoGroupSTM", "Ramp to"))
        self.label_8.setText(_translate("HoGroupSTM", "Bit/ms"))
        self.toolBar_2.setWindowTitle(_translate("HoGroupSTM", "toolBar_2"))
        self.actionOpen_O.setText(_translate("HoGroupSTM", "Open(&O)"))
        self.actionSave_S.setText(_translate("HoGroupSTM", "Save(&S)"))
        self.actionBias.setText(_translate("HoGroupSTM", "Bias"))
        self.actionCurrent.setText(_translate("HoGroupSTM", "Current"))
        self.actionZ.setText(_translate("HoGroupSTM", "Z"))
        self.actionScan.setText(_translate("HoGroupSTM", "Scan"))
        self.actionSpectra.setText(_translate("HoGroupSTM", "Spectra"))
        self.actionDeposition.setText(_translate("HoGroupSTM", "Deposition"))
        self.actionTrack.setText(_translate("HoGroupSTM", "Track"))
        self.actionHop.setText(_translate("HoGroupSTM", "Hop"))
        self.actionManipulation.setText(_translate("HoGroupSTM", "Manipulation"))
        self.actionShow_All_A.setText(_translate("HoGroupSTM", "Show All(&A)"))
        self.actionManual_A.setText(_translate("HoGroupSTM", "Manual(&M)"))
import logo_rc
